### ISSUE TITLE
swarm advector bug

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#1]
from lmondy:

I've attached a log and notebook for a crash I'm getting. Seems to be related to the advector - whenever it kicks in, UW crashes.

The error seems to be:
StgDomain/Mesh/src/IGraph.c:911: failed assertion `fromEl < Sync_GetNumDomains( ((IGraph*)self)->remotes[fromDim] )'

[pyLMR.ipynb.txt](https://github.com/underworldcode/underworld2/files/4181/pyLMR.ipynb.txt)
[crash.log.txt](https://github.com/underworldcode/underworld2/files/4182/crash.log.txt)

Which is occurring after:
Time Integration
               EP:        SwarmAdvector_AdvectionSetup -    0.0000 [min] /    0.0000 [max] (secs)
        1st order:                 HNCG0JZU__integrand -    0.0637 [min] /    0.0637 [max] (secs)
               EP:       SwarmAdvector_AdvectionFinish -    0.0261 (secs)
               EP:                 GeneralSwarm_Update -    0.0000 (secs)
Time Integration - 0.0899301 [min] / 0.0899301 [max] (secs)

This occurs with or without the advDiff stuff.

Cheers,

Luke

**Comment by julesghub** [comment]
not sure if this is still an issue. Luke please reopen if you still encounter this issue
