### ISSUE TITLE
Need help to configurate multigrid in 3D problem

### ISSUE THREAD

**Issue by QwZhang** [underworldcode/underworld2#101]
Hi, all,
I find it's computationally expensive to run Underworld if one use the usual solver instead of multigrid. For instance, when I try to rerun a 2D subduction model after extending it into a 3D one (I tried 125x70x18 elements to get required resolution of 20x10x40 km for subduction with 20 particles per element), it became extremely slow (I used 100 CPU cores and it spent almost two days to finish 100 steps). I have been followed the configuration involving using of the **Stokes_SLE_UzawaSolver** as demonstrated in **InputFiles-1.7.0\InputFiles\SlabSubduction.xml**:
```
      <struct name="uzawa" mergeType="replace">
         <param name="Type">Stokes_SLE_UzawaSolver</param>
         <param name="Preconditioner">preconditioner</param>
         <param name="tolerance">1.0e-5</param>
         <param name="maxIterations">5000</param>
         <!-- must be in slab models as DaveStegman has tuned this simulation.
         but this is dangerous and we must calculate a better param selection
         for uzawa to reasonably converge 
         JulianGiordani 24Jul07
         -->
         <param name="useAbsoluteTolerance">true</param>
      </struct>
```
Here is what the **FrequentOutput.dat** recorded for this particular run:
```
#       Timestep            Time            Vrms        CPU_Time
               0               0     4.01962e-10         6789.97
               1     1.70796e+12     4.37561e-10         8856.23
               2     3.23728e+12     4.66809e-10         10874.4
               3     4.70818e+12     4.90486e-10         12451.9
               4     6.10714e+12     5.14847e-10         13966.6
               5     7.47714e+12     5.45636e-10         16178.5
              ...
              98      8.1864e+13     2.53321e-09          158105
              99     8.23665e+13     2.55131e-09          158905
             100     8.28681e+13     2.56969e-09          159887
```
It seems that the wall time is too much for this 3D model even taking into consideration of increase of computation after transferring a 2D model to 3D one. 
So I want to try multigrid to get fast convergence rate. This is crucial if I want to run similar model at current or even higher resolution with more CPU cores. 
In doing so, I get very limited information in the user manual (v.1.5.2 and v.1.7.1) about how to setup Underworld with multigrid:
```
<include>StgFEM/MultigridForRegular.xml</include>
<param name="mgLevels">3</param> <!-- The number of MG levels. -->
```
And I am still confused about:

1. How can I setup Underworld with multigrid capability? Does it to necessary to remove all the configuration about the Uzawa solver listed above if one wish to activate multigrid-related solver by including the **StgFEM/MultigridForRegular.xml** and set a appropriate multigrid levels (**mgLevels**)?
2. How can I control the max number (if needed) of iterations and tolerance for the multigrid solver?
3. According to the user manual (v.1.7.1) and how prof. Moresi describes about the usage of multigrid in Underworld in his [Moresi2007](http://www.nature.com/nature/journal/v508/n7495/full/nature13033.html#supplementary-information) nature paper, which is about 3D subduction:

> In a model domain we use a resolution of 256x96x96 elements with a uniform grid spacing in each coordinate direction. This gives a grid resolution of 8.3 km in the vertical direction, and a horizontal resolution of 30 km. We initially seed this grid with 15 material points randomly located in each element onto which the distribution of distinct materials from the original configuration of distinct material domains is mapped when each run is initialized. We verified the model outputs using a lower resolution grid of 192x64x64. **Note that the number of elements is constrained by our use of a simple geometrical-multigrid solver which dictates the resolution in each coordinate direction to be N 5 m32n elements, where m is a small integer (typically 2, 3, 5) and n is the number of levels in the multigrid mesh hierarchy.**

It seems that the multigrid levels and number of elements in certain direction (e.g., x direction) cannot be arbitrary. For example, if multigrid level = 3, the number of elements in x, y, z direction should at least be able to be divided exactly by 2 for 3 times?

Any help or hints will be appreciated!

Best,
Qw

**Comment by jmansour** [comment]
Hi Qw

I believe you only need to include StgFEM/MultigridForRegular.xml to setup multigrid.  Then to set the tolerance & iteration count, just modify your `uzawa` block as usual.

Note that multigrid runs as default in UW2, and the interface to solver options is significantly improved.

**Comment by QwZhang** [comment]
Thank you for your reply.
