### ISSUE TITLE
valueRange Parameter not working for swarm variables

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#104]
I'm working on the FluxTerm branch, but assuming this may be a problem for all branches. When I try to set the colourbar limits for a swarm variable, it seems to just return the value zero on all points (irrespective of the actual swarm variable values):

    fig1 = glucifer.Figure( figsize=(800,400) )
    fig1.append( glucifer.objects.Points(swarm, viscosityMapFn,  pointSize=2.0, valueRange=[0.0,10.]) )
    fig1.show()

**Comment by OKaluza** [comment]
Fixed in development 42337dc927ca29db717ae8ffe736f2ad92d7dee9
