### ISSUE TITLE
How to clone the underworld code from the development branch?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#106]
How can I get the code from development branch via git clone? I found the HTTPS used for clone are the same for the three branches and it always clone the master branch when use "git clone https://github.com/underworldcode/underworld2.git".

**Comment by julesghub** [comment]
I don't know how to do it from git clone. I always change branch after I
have downloaded the whole repo.

To see the available branches
   > git branch -a

To update to our `development` branch
   > git checkout development

cheers,
J

**Comment by wkillers** [comment]
Thanks
