### ISSUE TITLE
How to setup passive tracers?

### ISSUE THREAD

**Issue by QwZhang** [underworldcode/underworld2#109]
Hi,
Passive tracers are very crucial to record prescribed parameters like position, stress, etc. and configuration of them is easy in the old `Underworld` ( in the `*.xml` inputfile). 
Having not dug deep into `Underworld2` with python interface, how can I use them? It seems that there is no documentation about this capability of `Underworld2` so far.

To be specific, how can I:
1. lays out the particles?
2. output the value of the specified field(s) on these particles to a file? 

Thanks a lot.
Regards,
Qw

**Comment by jmansour** [comment]
All the documentation is in the `docs` directory.  Most of it is in Jupyter Notebooks format. 

As with many things in UW2, we don't provide the explicit functionality for passive tracers, but do provide the means to create them easily.  Basically you just need to do the following:
1. create swarm
2. create numpy array with coordinate of particles (ie the passive tracers) you wish to add to the swarm.
3. use the `swarmSubMesh.add_particles_with_coordinates` method to add the particles

The swarms section of the user guide has some examples where particles are added to the swarm
https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/04_Swarms.ipynb

Also the Stokes sinker example uses passive tracers:
https://github.com/underworldcode/underworld2/blob/master/docs/examples/1_05_StokesSinker.ipynb

To write field values on the tracers, add a variable for each value you wish to write.  Something like this:

```
# create the variable. this will add space for data on each particle
vel_variable = swarm.add_variable( datatype='double', count=2 ) # for 2d data
# now write the data into the variable.  
vel_variable.data[:] = velocityField.evaluate(swarm.particleCoordinates.data)
```
Note that we are writing directly into the variables data using the 'data' handle.  Also, we use the 'evaluate' method to evaluate the velocityField at the particle coordinates. 

Now that you have the data stored on your passive tracers, you can write it to a file any way you wish.  In UW2 we don't provide functionality for this kind of IO operation, as you can implement this very easily directly using python (though there are a few caveats for parallel usage). 

Give it a shot and let us know how you get along.

**Comment by jmansour** [comment]
i'll close this for now, but feel free to report back here your progress, or reopen if still having difficulties.
