### ISSUE TITLE
Viscosity function takes a long time to evaluate

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#11]
I have quite a complicated viscosity function now, and when I try to evaluate it, it takes more than 5 minutes. Adding extra functions on top (such as the visc_limited_Fn) seems to make the time required to increase non-linearly (is my guess, but I haven't actually timed the difference).

A full notebook example is here: https://github.com/OlympusMonds/lithospheric_modelling_recipe/blob/pyLMR/pyLMR.ipynb

Do you have any tips for speeding this up?

**Comment by jmansour** [comment]
Hi Luke 

Functions can of course be made arbitrarily complex, so there's always going to be a point where the complexity begins to bite. I have a few ideas on how to improve the efficiency of functions, but some of these are not going to happen for a little while. There are also a few potentially low hanging fruit that should speed things up somewhat, though I can't say for sure if they'll make a dramatic difference.  

That notebook you've posted is pretty big.  Perhaps if you can get it down to the essential ingredients where you're finding function evaluation gets crazy, then I can have a more focused look and see if potentially there's a bug, or perhaps some other solution.  

You should also make sure you've simplified your function definition as much as possible.  For example, this:

fn = 1./temperatureField + 5./temperatureField - 10./temperatureField

will take much longer than this

fn = -4./temperatureField

**Comment by OlympusMonds** [comment]
OK! With some tweaks, I've significantly reduced the time. Particularly bad statements were things like this:
```python
visc_limited_Fn = fn.branching.conditional([ (visc_law_Fn <= min_visc, min_visc),
                                             (visc_law_Fn >  min_visc, visc_law_Fn) ]) 
```
I had two of these guys nested, and it was not happy.

The *much* faster equivalent is:
```python
visc_limited_Fn_v2 = fn.misc.max(visc_law_Fn_v2, min_visc)
```
Which now seems obvious (I looked in fn.math for a min/max function, but it's in fn.misc!).

**Comment by jmansour** [comment]
Luke, note that in your previous version, visc_law_Fn will be evaluated up to 3 times per point evaluation.  This is equivalent and results in max 2 evaluations

```
visc_limited_Fn = fn.branching.conditional([ (visc_law_Fn <= min_visc, min_visc),
                                             (True, visc_law_Fn) ]) 
```
Perhaps there's some way to cache the results to avoid this.

**Comment by OlympusMonds** [comment]
I did some tests, and made a nice graph to show the differences. Scroll down to the bottom of this notebook:
https://github.com/OlympusMonds/lithospheric_modelling_recipe/blob/pyLMR/pyLMR-Visc_Fn_tester.ipynb
It also shows how the different viscosity functions chain together, for better or worse.

I think caching would be good, because without it, even the official stress limiter rheology is calling the viscosity function more than once (assuming that the stress function it has been passed is essentially 2*visc*strainrate).

**Comment by jmansour** [comment]
Cheers for that Luke! The numbers seem to be what I would expect. Yep,
caching would improve things quiet considerably in this case.

I'll reopen this issue, and report back results for some changes I'll be
making.

**Comment by julesghub** [comment]
refer to #44
