### ISSUE TITLE
ValueError when using matplotlib?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#110]
In Mac OSX EI 10.11.4, when I import the matplotlib module in python as in example "05_StokesSinker.ipynb", an error appears like below:
`$%matplotlib inline`
`$ValueError: unknown locale: UTF-8.`

I have searched on the internet as some other suggested to add some export in the ~/.bash_profile as:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

```
But this doesn't works.

**Comment by jmansour** [comment]
I've never come across this.  Had a quick search and found this:

https://github.com/matplotlib/matplotlib/issues/5420/

Not sure if you've seen that.  In general, I recommend using virtualenv for python on OS X

https://hackercodex.com/guide/python-development-environment-on-mac-osx/
