### ISSUE TITLE
Where to find the visco-elasto-plastic related modules in UW2?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#114]
Where can I find these modules to learn about what kind of rheology discriptions contains in UW2, i.e., how to setup a visco-elasto-plastic viscosity?

**Comment by jmansour** [comment]
Which rheologies in particular are you after?  

As with other aspects in UW2, we provide the mechanisms for users to define their own rheologies, but do not currently provide any specific rheology implementations.  For example, to create an Arrhenius type rheology, you might do something like this:

```python
import underworld as uw
import underworld.function as fn

mesh = uw.mesh.FeMesh_Cartesian()
tempField = uw.mesh.MeshVariable(mesh,1)

eta0 = 1.
E    = 1.
V_d  = 1.
T_0  = 1.

eta = eta0*fn.math.exp( (E + V_d) / (tempField + T_0) )
```

for 

\eta = \eta_0 \exp \left( \frac {E + V d} {T + T_0} \right)

We will be adding an example for viscoelastic type behaviour shortly.  Likewise, it is not explicit elasticity functionality, but using the provided uw2 fundamental objects you can implement elastic behaviour.

**Comment by wkillers** [comment]
Hi @jmansour , thanks. I think I should creat my own rheologies manually.
