### ISSUE TITLE
swarm unaware of deformed mesh

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#12]
If a swarm is tied to a mesh, and the mesh is then deformed, the particle cell table will be incorrect (requiring update particle owners)  and the particles may no longer be inside the domain. 

There are a few options here. A decent default behaviour would be to use the local particle coordinates to remap the particles to the new mesh configuration. Alternatively, particles owners are updated, and particles outside the local domain are culled or moved to another proc. 

At the very least we should prevent the mesh being deformed if swarm is tied to it to force users to do all deformations before the swarm is attached.

**Comment by julesghub** [comment]
refer to #64
