### ISSUE TITLE
Building error with the latest development branch

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#120]
After configuring, I run the 'compile.py' script to build the code and some errors appears:
```
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading Conscript files.
scons: Building targets ...
SymLink(["build/lib/libFunction_swig.so"], ["build/lib/libFunction_swig.dylib"])
scons: *** [build/lib/libFunction_swig.so] File exists
scons: building terminated because of errors.
```
This error also arise when do the ./scons.py manually.

**Comment by jmansour** [comment]
not sure why it's doing this on your system.  just remove your build directory and try again.  or use the dockers.

**Comment by wkillers** [comment]
yeah, this works after remove the build directory and rebuild. I have no idea why the problem comes out as before, but anyway, it works.
