### ISSUE TITLE
evaluate_global() method?

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#125]
So it would basically allow users to evaluate the function at any location irrespective of whether query location is local or not.  It would then gather results to all processors. 

Do we want to provide this?  Naturally we would need to include sufficient warning of potential efficiency issues.

**Comment by garethkennedy** [comment]
Yes vote right here.

**Comment by lmoresi** [comment]
This seems like an important thing to be able to do - I would guess that there is an efficient way to handle this for vectors of positions. 

Something similar for swarms ? Being able to provide a global ID and query the value of a particle no matter which proc it calls home.

L

**Comment by garethkennedy** [comment]
Prototype version in there now for testing by developers. 
Access as you would for evaluate but called "_evaluate_global". For example:
meshVar._evaluate_global( (0.5, 0.5) )
Post any issues that people find here.

**Comment by lmoresi** [comment]
Next we should allow this to evaluate at a swarm, mesh or index set

**Comment by julesghub** [comment]
agreed! Batch mode could make this very quick and very useful.
