### ISSUE TITLE
test runner parallel operation

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#126]
Need to be able to run our tests in parallel.  I'd suggest we add options so that we can do something like this:
```
run_tests.py --processes=4 --mpirun=mpiexec
```
Notebooks should be ignored for parallel tests.

**Comment by julesghub** [comment]
this functionality has been done in commit 094b9a7a4a65343054926bb912176639cc32ca32

In parallel the notebooks are being converted to .py and then tested. I figure I'd leave it like this for a bit until we fold all this into jenkins.
closing ticket for now
