### ISSUE TITLE
git hook to automatically convert ipynb to py 

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#127]
Notice that we're getting some python versions of the notebook files, which is great, but I can see us running into issues of them going out of sync with each other, which is not great. 

Perhaps we should simply have a git hook which automatically generates py files for all notebooks at commit time?  Perhaps initially we can simply have a script which automates the process for all files in a particular directory.  This command does the job:

```
jupyter nbconvert --to python some_model.ipynb
```

**Comment by lmoresi** [comment]
That's probably my fault and unintentional - I check the validity by doing that conversion and then an mpirun -np 4 ...

Sometimes the GitHub client is a bit over keen to commit new files.


Sent from my iPhone

On 4 May 2016, at 08:39, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Notice that we're getting some python versions of the notebook files, which is great, but I can see us running into issues of them going out of sync with each other, which is not great.

Perhaps we should simply have a git hook which automatically generates py files for all notebooks at commit time? Perhaps initially we can simply have a script which automates the process for all files in a particular directory. This command does the job:

jupyter nbconvert --to python some_model.ipynb

**Comment by julesghub** [comment]
in the script we'll also need to strip the magic commands. ie
get_ipython().magic(u'matplotlib inline')

**Comment by lmoresi** [comment]
I suggest that we discourage magic in general. The only case where it is useful is that inline command and I have been doing this:


try :
    if(__IPYTHON__) :
        get_ipython().magic(u'matplotlib inline')
except NameError :
    pass




On 4 May 2016 at 3:49:17 PM, julesghub (notifications@github.com<mailto:notifications@github.com>) wrote:

in the script we'll also need to strip the magic commands. ie
get_ipython().magic(u'matplotlib inline')
---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Perhaps we should create a 'convenience' module which captures these little tidbids to avoid cluttering our example modules with this uglyness. 

inside underworld.convenience:
```
def matplotlib_inline()
    try :
        if(__IPYTHON__) :
            get_ipython().magic(u'matplotlib inline')
    except NameError :
        pass
```

```
import underworld as uw
uw.convenience.matplotlib_inline()
```

I'm starting to think it might be worthwhile to do this for directory & file creation to avoid MPI uglyness in beginner level examples.

**Comment by julesghub** [comment]
I agree. This line is quite confronting.
A convenience wrapper - well documented - sounds good.

**Comment by lmoresi** [comment]
John, Julian,

I agree … wrapping is a good idea.

convenience is a bit of an odd choice, but if we put you on the spot you can come up with something of great genius.

L




On 5 May 2016 at 10:18:24 AM, julesghub (notifications@github.com<mailto:notifications@github.com>) wrote:

I agree. This line is quite confronting.
A convenience wrapper - well documented - sounds good.

On 5 May 2016 at 08:57, jmansour <notifications@github.com> wrote:

> Perhaps we should create a 'convenience' module which captures these
> little tidbids to avoid cluttering our example modules with this uglyness.
>
> inside underworld.convenience:
>
> def matplotlib_inline()
> try :
> if(__IPYTHON__) :
> get_ipython().magic(u'matplotlib inline')
> except NameError :
> pass
>
> import underworld as uw
> uw.convenience.matplotlib_inline()
>
> I'm starting to think it might be worthwhile to do this for directory &
> file creation to avoid MPI uglyness in beginner level examples.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/127#issuecomment-217028583>
>

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/127#issuecomment-217045278>

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
I'm still waiting on alternate name suggestions for UW functions! 😄

**Comment by lmoresi** [comment]
We could do the conversion at build time - are we assuming Jupyter is a dependency ?

Sent from my iPhone

On 5 May 2016, at 10:26, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm still waiting on alternate name suggestions for UW functions! 😄

**Comment by jmansour** [comment]
No jupyter isn't a dependency.  

I've added a little _script_ to do this in utils. 7bb19546c8838eccbb7919a7409db945af9cc6ae

**Comment by jmansour** [comment]
I don't think the automatic generation is currently warranted.
