### ISSUE TITLE
Issues installing on Mac OS 10.11

### ISSUE THREAD

**Issue by VinceUW** [underworldcode/underworld2#128]
Hello guys,
I have installed Underworld II using the last blog post "Dependency setup for Mac OSx - El Capitan MARCH 02, 2016". However, when trying the following command in python:

_import underworld as uw_

the shell returns:

_Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "underworld/__init__.py", line 44, in <module>
    import libUnderworld
  File "libUnderworld/__init__.py", line 1, in <module>
    from libUnderworldPy import *
  File "libUnderworld/libUnderworldPy/__init__.py", line 2, in <module>
    import StGermain
ImportError: No module named StGermain_

Any idea what I should do? With OS 10.11 do you think it is better to install using the dockers? If yes, then I need to uninstall the current version of Underworld II, how can I uninstall properly?

Cheers,

Vincent

**Comment by julesghub** [comment]
Hi Vincent,

From the error msg it appears that the python modules were not compiled
properly.
Did you complete the installation here
https://github.com/underworldcode/underworld2/blob/development/README.md#compilation
?

In any case we recommend using dockers - they are much easier to get setup.

To uninstall the version of Underworld from git you can just remove the
directory where you downloaded the repository - we don't install anything
outside of that directory.

cheers,
Jules

**Comment by VinceUW** [comment]
Hi Julian,

Thanks for the quick response. I didn't complete the installation, my bad! However, when I run

> ./configure.py

I get an error message concerning the libXML2 package. I attach here the shell message and the config.log file as a text file.

Cheers,
Vincent

> Submodule 'libUnderworld/gLucifer/Viewer' (https://github.com/OKaluza/LavaVu.git) registered for path 'libUnderworld/gLucifer/Viewer'
> Submodule 'libUnderworld/h5py' (https://github.com/h5py/h5py) registered for path 'libUnderworld/h5py_ext'
> Cloning into 'libUnderworld/gLucifer/Viewer'...
> remote: Counting objects: 3372, done.
> remote: Compressing objects: 100% (253/253), done.
> remote: Total 3372 (delta 174), reused 0 (delta 0), pack-reused 3119
> Receiving objects: 100% (3372/3372), 9.06 MiB | 2.55 MiB/s, done.
> Resolving deltas: 100% (2582/2582), done.
> Checking connectivity... done.
> Submodule path 'libUnderworld/gLucifer/Viewer': checked out 'c4899fed94fc659a84015ba8f019a61de3c90c23'
> Cloning into 'libUnderworld/h5py_ext'...
> remote: Counting objects: 8699, done.
> remote: Total 8699 (delta 0), reused 0 (delta 0), pack-reused 8699
> Receiving objects: 100% (8699/8699), 4.04 MiB | 1.56 MiB/s, done.
> Resolving deltas: 100% (5349/5349), done.
> Checking connectivity... done.
> Submodule path 'libUnderworld/h5py_ext': checked out '9d491fe2ac635236b05a01da1c5a669edcaf3eaa'
> scons: Reading SConscript files ...
> Checking whether the C compiler works yes
> Checking for Solvers... yes
> Checking for package libm... yes
> Checking for package libXML2... no
> 
> ****  ERROR ****
> Failed to locate required package libXML2.
> Details in 'config.log'


[config.txt](https://github.com/underworldcode/underworld2/files/258680/config.txt)

**Comment by jmansour** [comment]
have you installed the xcode command line tools?

$ xcode-select --install

**Comment by VinceUW** [comment]
Thanks John for following up!

I just did and it solved the issue. It seems working now... I will go through the tutorials and let you know if I need further help.

Cheers!
Vincent
