### ISSUE TITLE
create an arbitrary FeMesh_IndexSet / fix velocity on a point

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#132]
The example from the FeMesh_IndexSet docstring isn't working for me:

    amesh = uw.mesh.FeMesh_Cartesian( elementType='Q1/dQ0', elementRes=(4,4), minCoord=(0.,0.), maxCoord=(1.,1.) )
    iset = uw.libUnderworld.StgDomain.RegularMeshUtils_CreateGlobalMaxISet( amesh._mesh )
    uw.mesh.FeMesh_IndexSet( amesh, topologicalIndex=0, size=amesh.nodesGlobal, fromObject=iset )
    uw.mesh.FeMesh_IndexSet([ 4,  9, 14, 19, 24])

All I want to do is set a zero velocity on an arbitrary point, so I was playing around with trying to create an FeMesh_IndexSet. Is this the way to go about it?

**Comment by garethkennedy** [comment]
Easier to add the list of indices to the boundary condition. 
For example;
allFixed = mesh.specialSets["Empty"]
for index in range(iWantTheseFixed):
        i = someArray(index) # might look like (4, 9, 14, 19, 24) as above
        allFixed.add(i)
        velocityField.data[i] = (0., 0.)
freeslipBC = uw.conditions.DirichletCondition( variable        = velocityField, 
                                               indexSetsPerDof = (allFixed, allFixed) )

**Comment by jmansour** [comment]
You can't really set a zero velocity at an arbitrary point.. well at least not trivially.  You would have to introduce a new constraint to the matrix.  

Alternatively, you can move the closes mesh vertex to the point, and then set it's velocity to zero via the Dirichlet condition.  Or if you fix all the nodes of associated element to zero if you are happy with a fuzzier zero.  So the process will be this:
1. Find the required vertices.  sorry, no fancy tools for this yet.  walk the mesh.
2. flag these as dirichlet via the DirichletCondition class.
3. Set these to zero on the MeshVariable.

**Comment by dansand** [comment]
Thanks. 

Yes, I meant a node / vertex, not a point. So I was trying to set the indexSet the wrong way, i.e. like:

`mesh.specialSets[np.array([5, 16, 33])]`

rather than:

    Fixed = mesh.specialSets["Empty"]
    for index in [5, 16, 33]:
        Fixed.add(index)
 
Thanks
