### ISSUE TITLE
multiple conditions, fn.branching.conditional

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#133]
Can we supply multiple conditions to the fn.branching.conditional, i.e using AND / OR expressions?
I need something like the following:

    materialV = 1 # viscoplastic
    materialA = 0 # accommodation layer a.k.a. Sticky Air
    materialU = 2 # Under layer 
    materialVariable.data[:] = materialA

    conditions = [ (       coord[1] > 0.8 , materialA ),
               (       materialVariable == materialA and coord[1] < 0.1 , materialU ),
               (       True ,           materialV ) ]

But this doesn't seem to work because materialVariable == materialA evaluates to False. So I guess this boils down to making this a valid comparison...

**Comment by jmansour** [comment]
equality comparison is not currently supported.  something like this might work:

```
conditions = [ (       coord[1] > 0.8 , materialA ),
           (       (materialVariable > (materialA-0.5)) and (materialVariable < (materialA+0.5)) and coord[1] < 0.1 , materialU ),
           (       True ,           materialV ) ]
```
