### ISSUE TITLE
How to define a viscosity that is both temperature dependent and compositional dependent?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#134]
If I want to define a viscosity law that is both temperature and compositional dependent, i.e., the temperature-dependence of viscosity is related to the temperature on mesh point, while the compositional-dependence of viscosity is related to the particle types (defined from swarm variables), how to realise such kind of rheology?

**Comment by jmansour** [comment]
Yep, this is certainly possible.  

Basically, you want to use the `underworld.function.branching.map` class to create a function which maps to different functions according to key provided by your *material* swarm variable.  Check the `1_05_StokesSinker` example or the `1_06_RayleighTaylor` example.   Note that in both these examples, the functions map to constant values, but actually you can actually pass in any other function instead.  

For example, to have only one material being temperature dependent, you might do this:

```
tempDependentIndex = 0
nontempDependentIndex = 1
# some routine to set materialVariable as necessary... it should only take values `0`  or `1`
.....
#
viscosityMap = { tempDependentIndex : fn.math.exp(1./temperatureField),
                       nontempDependentIndex:10. }
fn_viscosity  = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap )
```

If instead you want to have all materials being temp dependent, but with different coefficients, you might do this:

```
material0 = 0
material1 = 1
# some routine to set materialVariable as necessary... it should only take values `0`  or `1`
.....
#
coeffMap = { material0 : 10.,
                     material1 : 100. }
fn_coeff = fn.branching.map( fn_key = materialVariable, mapping = coeffMap )
fn_viscosity  = fn.math.exp( 1./ ( fn_coeff * temperatueField ) )

```

**Comment by wkillers** [comment]
Thank you very much!

**Comment by jmansour** [comment]
No probs!

**Comment by wkillers** [comment]
Hi @jmansour ,

I constructed a viscosity structure as you have suggested, but it seems to be a little strange when I run it in a test. When I use temp-dependent for all materials the solver goes well, but when I use a mapped viscosity for different materials, it seems to be stucked somewhere. I upload my script and could you help me to check it to find what's the problem?
```
[input_test.txt](https://github.com/underworldcode/underworld2/files/283304/input_test.txt)
[input_test.txt](https://github.com/underworldcode/underworld2/files/283306/input_test.txt)
[Uploading input_test.txt…]()


SHANs-iMac:underworld2-case apple$ python input_test.py 
	Global element size: 128x64
	Local offset of rank 0: 0x0
	Local range of rank 0: 128x64
In func WeightsCalculator_CalculateAll(): for swarm "VLGSHJ9G__swarm"
	done 33% (2731 cells)...
	done 67% (5462 cells)...
	done 100% (8192 cells)...
WeightsCalculator_CalculateAll(): finished update of weights for swarm "VLGSHJ9G__swarm"
In func WeightsCalculator_CalculateAll(): for swarm "VLGSHJ9G__swarm"
	done 33% (2731 cells)...
	done 67% (5462 cells)...
	done 100% (8192 cells)...
WeightsCalculator_CalculateAll(): finished update of weights for swarm "VLGSHJ9G__swarm"
Linear solver (63GY8UA2__system-execute) 

BSSCR -- Block Stokes Schur Compliment Reduction Solver 
AUGMENTED LAGRANGIAN K2 METHOD - Penalty = 0.000000

SROpGenerator_SimpleFinestLevel: time = 3.49400e-02 
  [5] SROpGenerator_SimpleCoarserLevel: time = 1.17221e-02 
  [4] SROpGenerator_SimpleCoarserLevel: time = 2.94995e-03 
  [3] SROpGenerator_SimpleCoarserLevel: time = 8.28028e-04 
  [2] SROpGenerator_SimpleCoarserLevel: time = 2.88010e-04 
  [1] SROpGenerator_SimpleCoarserLevel: time = 1.49012e-04 
```
Thank you.

Tips: the material variables are defined in line 128-139. The viscosity is defined in line 144-163.

**Comment by jmansour** [comment]
Perhaps you should visualise your viscosity first to see it's all in order.  It could well be that you have a negative viscosity somewhere which is causing havoc with the solvers.  Also, you can evaluate your velocity on the swarm to get the actual numbers out:
```
viscosity_fn.evaluate(gswarm)
```

**Comment by wkillers** [comment]
I have checked the viscosity and I think it is correct as I wished. I output all the swarm viscosities at initial time and check it, there is no negative viscosity.
```
gmtinfo ~/Desktop/underworld/my_underworld2/underworld2-case/test/InitialSwarmsViscosity.txt 
/Users/apple/Desktop/underworld/my_underworld2/underworld2-case/test/InitialSwarmsViscosity.txt: N = 81920	<0.01/1000000>
```
I also plot the viscosity in lucifer and it seems good.
![initialviscosity](https://cloud.githubusercontent.com/assets/18066578/15561722/5d512140-232b-11e6-8b54-45bde82dea47.png)

**Comment by jmansour** [comment]
Isn't the colourbar range from -2 to 6?

**Comment by wkillers** [comment]
Yes, but the colourbar is the logarithmic form of viscosity.

**Comment by wkillers** [comment]
Is it possible because I use serial calculation that the slover for such mapping viscosity is to slow? But I am not sure if just a different rheology can cause such big difference in solver speed.

**Comment by jmansour** [comment]
So did you actually pass in the log of the viscosity to glucifer?  If not,
the scale should still show the actually viscosity values.

Otherwise, you have 8 orders of magnitude in your viscosity which is
probably why the solver is having difficulties.  I suggest dropping the
viscosity contrast down somewhat and seeing if it solves.  You might also
want to take a look at the user guide (StokesSolver section) for some info
on tweaking the solver.

**Comment by wkillers** [comment]
Oops, I think the solver is not stocked but just too slow. I use three constant values instead of temp-dependent viscosity for all three materials and mapping them, the solver goes well but is slow. It is even slower than with temp-dependent viscosity for all materials without using mapping function. So perhaps there is something about the mapping function that slow down the solver speed.

**Comment by wkillers** [comment]
Yes, the orders of magnitude in viscosity is also a factor, I reduce it to about 4 and the solver is much faster. 

Thanks a lot for the discussion.

**Comment by jmansour** [comment]
How long does this take? 

```
viscosity_fn.evaluate(gswarm)
```

This should be almost identical to the amount of time it takes the solver to actually evaluate your viscosity function (mapping or otherwise).  

Are you running in parallel or serial?

**Comment by wkillers** [comment]
The "viscosity_fn.evaluate(gswarm)" does not take two much time. I run in serial.

**Comment by wkillers** [comment]
@jmansour , I may need to further look into the info about solver in tweaking the parameters. Anyway, thank you very much for the discussions.
