### ISSUE TITLE
Number of processors

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#135]
Hi,

I'm using the Stokes problem to do a compression plate problem. I know the solver is BSSCR, but I would like to know the number of cores or the number of processors that underworld2 uses to do the iterations, and how can I change this number? Is it done via python using something like?:

uw.system.solver ("property"=number of processors?)

or do I have to change the bsscr.py script?

Thanks for this repository! Is very usefull.

**Comment by jmansour** [comment]
You will have to do this using the `mpirun` command.  Note that parallel simulation is not available within Jupyter notebooks.. or at least it's not a trivial affair.  If you are using notebooks, you are better of boiling your notebook down to a regular python script (using the 'Download as' option in the menu).  Then from the command line, you will need to run something like this 

```
mpirun -np 4 python YourModel.py
```

to utilise 8 processors.  If you are using dockers, you will need to do this within a docker-notebook terminal, or from your native command line doing something like this

```
docker run -v $PWD:/workspace underworldcode/underworld2 mpirun -np 4 YourModel.py
```

Also, if you are running on OSX with docker, note that you will have to permit the docker container access to multiple cores through VirtualBox preferences.

**Comment by AngelValverdePerez** [comment]
I've downloaded the ipyparallel. It seems to be working via jupyter notebook.

But your solution it would be helpfull if I want to run .py files
