### ISSUE TITLE
webgl viewer possibly broken 

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#137]
See #87 for details.

**Comment by jmansour** [comment]
I've committed a hack fix here on the 2.0.0b branch: 7131891e92c1324e54dab300e7ea92aab2fc811b

This should reproduce the bug:
`
import underworld as uw
import glucifer
mesh = uw.mesh.FeMesh_Cartesian()
fig = glucifer.Figure()
fig.append(glucifer.objects.Mesh( mesh ))
fig.show(type='webgl')
`

Basically, if you do `fig.show(type='webgl')` *after* you do `fig.show()`, it works fine, but if you just try and use the webgl viewer straight up, kaboom.   In the following, the `view` object is null. 
`
Process 89596 stopped
* thread #1: tid = 0x59f89b, 0x000000010a1bb593 libLavaVu.dylib`Geometry::drawable(this=0x0000000101866b20, idx=0) + 739 at Geometry.cpp:703, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2)
    frame #0: 0x000000010a1bb593 libLavaVu.dylib`Geometry::drawable(this=0x0000000101866b20, idx=0) + 739 at Geometry.cpp:703
   700 	  if (idx < geom.size() && geom[idx]->count > 0 && !hidden[idx])
   701 	  {
   702 	    //Not filtered by viewport?
-> 703 	    if (!view->filtered) return true;
   704 	
   705 	    //Search viewport object set
   706 	    if (view->hasObject(geom[idx]->draw))
(lldb) p view
(View *) $0 = 0x0000000000000000
(lldb) bt
* thread #1: tid = 0x59f89b, 0x000000010a1bb593 libLavaVu.dylib`Geometry::drawable(this=0x0000000101866b20, idx=0) + 739 at Geometry.cpp:703, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x2)
  * frame #0: 0x000000010a1bb593 libLavaVu.dylib`Geometry::drawable(this=0x0000000101866b20, idx=0) + 739 at Geometry.cpp:703
    frame #1: 0x000000010a1ba6ed libLavaVu.dylib`Geometry::jsonExportAll(this=0x0000000101866b20, draw=0x0000000101867b20, array=0x00007fff5fbfca78, encode=true) + 333 at Geometry.cpp:363
    frame #2: 0x000000010a277876 libLavaVu.dylib`Lines::jsonWrite(this=0x0000000101866b20, draw=0x0000000101867b20, obj=0x00007fff5fbfd008) + 422 at Lines.cpp:287
    frame #3: 0x000000010a2806f9 libLavaVu.dylib`Model::jsonWrite(this=0x0000000101866140, os=0x00007fff5fbfd9f0, obj=0x0000000000000000, objdata=true) + 7737 at Model.cpp:1696
    frame #4: 0x000000010a243b7f libLavaVu.dylib`LavaVu::run(this=0x0000000101862c30) + 6463 at LavaVu.cpp:989
    frame #5: 0x000000010a238317 libLavaVu.dylib`execute(argc=6, argv=0x0000000101861fa0, myApp=0x0000000101862c30) + 4855 at LavaVu.cpp:161
    frame #6: 0x000000010a236fed libLavaVu.dylib`execute(argc=6, argv=0x0000000101861fa0) + 141 at LavaVu.cpp:62
    frame #7: 0x000000010a0deafb _LavaVu.so`_wrap_execute((null)=0x0000000000000000, args=0x000000010cd8c758) + 843 at LavaVu_wrap.cxx:9811
    frame #8: 0x0000000100089e95 Python`PyEval_EvalFrameEx + 14562
    frame #9: 0x000000010008c541 Python`___lldb_unnamed_function1476$$Python + 264
    frame #10: 0x000000010008930c Python`PyEval_EvalFrameEx + 11609
    frame #11: 0x00000001000863c1 Python`PyEval_EvalCodeEx + 1583
    frame #12: 0x000000010008c4ae Python`___lldb_unnamed_function1476$$Python + 117
    frame #13: 0x000000010008930c Python`PyEval_EvalFrameEx + 11609
    frame #14: 0x00000001000863c1 Python`PyEval_EvalCodeEx + 1583
    frame #15: 0x0000000100085d8c Python`PyEval_EvalCode + 54
    frame #16: 0x00000001000a5a42 Python`___lldb_unnamed_function1599$$Python + 53
    frame #17: 0x00000001000a5ae5 Python`PyRun_FileExFlags + 133
    frame #18: 0x00000001000a5634 Python`PyRun_SimpleFileExFlags + 698
    frame #19: 0x00000001000b7011 Python`Py_Main + 3137
    frame #20: 0x00007fff915945ad libdyld.dylib`start + 1
`

**Comment by OKaluza** [comment]
OK, so is fixed in pre-release with this hack and I've updated latest work in with proper fix to development so closing

**Comment by jmansour** [comment]
Thanks man. that'll be fine!
