### ISSUE TITLE
BSSCR Tolerance

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#139]
Hi all,

when I run, with jupyter notebook, a Stokes problem, in the shell appears the image I'm submitting. My question is, how can I change the Tolerance and the iterations via jupyter notebook? If it is not possible, how can I change it?

Because, I changed it once by going to SystemLinearEquation.c before compiling and change the default value, but in the previous version of UW it was easy to change the tolerance and iterations, thus there is an easy way in UW2, isn't it?

![tolerance](https://cloud.githubusercontent.com/assets/18324577/15607845/17a78b8e-2416-11e6-8d1f-1eba4029744c.png)

**Comment by lmoresi** [comment]
Have a look at the solver notebook on the development (soon to be mainstream) branch as this has some of the information you are looking for. Look at the help and this technique for finding out what has already been set:

```
solver.options.main.list()  # System level options
solver.options.scr.list()   # Specifics for the schur complement solve
solver.options.A11.list()   # Specifics for the inner (velocity) solve
solver.options.mg.list()    # Options relevant to multigrid (if chosen)
```

PS - as this is raised in the issue tracker, the actual issue for the developers is 1) to make a release of what is currently only on the dev branch and 2) consider if the docs are adequate to explain the solver options (probably not).

**Comment by AngelValverdePerez** [comment]
Did it.

But, if I change the solver's options (such as rtolerance) you are not changing the Tolerance of the image. The Tolerance that I sent you, is from the file: SistemLinearEquations.c, so when you compile, it's over, you can not change it from python.
