### ISSUE TITLE
Parallel running auto creat figures named LavaVu-xxx.png?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#141]
When I use mpiexec to run a script the code auto-creat a series of figures named "LavaVu-xxx.png", but i don't want these figures to be created, how can I turn this off in the code?

**Comment by garethkennedy** [comment]
These are automatically created when the command fig.show() is called. In notebooks this would result in a image on the screen, in parallel it outputs to the png files. If you don't want them then comment out the fig.show() commands in your python script.

**Comment by wkillers** [comment]
Thank you.

**Comment by OKaluza** [comment]
@garethkennedy @jmansour this is why I questioned whether automatically creating images on fig.show() was a good idea, I still have my doubts. If someone wants an image saved they should use fig.save(), changing the behaviour when you switch from running a notebook to a python script seems confusing.  
Thoughts? Perhaps I could add another method, like fig.image() that has this behaviour (always produces output, either inline or image with automatically generated filename) and keep fig.show()/save() as they were previously.

**Comment by jmansour** [comment]
I don't mind the automatic image creation.  In a sense, they have requested
an image by calling show().  If anything, I think we could perhaps
introduce some environment variables that can switch this behaviour.

UW_AUTOIMAGE=0

or something.

**Comment by OKaluza** [comment]
If you're happy with it as is then I'll leave it, all good

**Comment by jmansour** [comment]
Yeah I kinda like it! But we can reconsider down the track.
