### ISSUE TITLE
How to output and combine all the output data in parallel running?

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#142]
When I run a script in parallel mode, for example "mpirun -np 4 python xxx.py", I output the temperature field using numpy via "np.savetxt( np.c_[mesh.data temperatureField.data] )", but in parallel mode this only output 1/4 of the temperature field, i.e., one cpu core result. How can I output the results of all cpu cores, and can underworld auto-combine them and output into one single file? I didn't set any mpi issue in the script, what kind of parameters do I need to set?

**Comment by garethkennedy** [comment]
Have a look at the 1_06 RT example. There is a section called "Output in XDMF format". These are designed to output the entire field in parallel (also works in series).
Basically there is a ".save" method attached to each mesh variable (such as temperature) that you can use.

**Comment by wkillers** [comment]
So for now the underworld can not do the similar saving process just to output the data into ascii format in parallel?

**Comment by wkillers** [comment]
@garethkennedy ,
when I use the ".save" method to save the mesh variable, a problem comes up:
```
Traceback (most recent call last):
  File "01_GettingStarted.py", line 38, in <module>
    mesh.save(outputPath+"01_mesh_saved_new.h5")
  File "/Users/apple/Desktop/underworld/underworld-development/underworld/mesh/_mesh.py", line 473, in save
    h5f = h5py.File(name=filename, mode="w", driver='mpio', comm=MPI.COMM_WORLD)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 259, in __init__
    fapl = make_fapl(driver, libver, **kwds)
  File "/usr/local/lib/python2.7/site-packages/h5py/_hl/files.py", line 61, in make_fapl
    kwds.setdefault('info', mpi4py.MPI.Info())
NameError: global name 'mpi4py' is not defined

```
what's this problem means?

**Comment by lmoresi** [comment]
You could make every processor output the data itself using a unique name per proc. This is the old-style behaviour in something like citcom. 

Or let underworld take care of it for you with hdf5 and use h5py to read the information later.

**Comment by julesghub** [comment]
Hi Yongming,

The error message:
   *NameError: global name 'mpi4py' is not defined*
suggests that the h5py python library you are using is not built with mpi,
thus it errors in parallel.

You can test this by copying and pasting the example script at:
   http://docs.h5py.org/en/latest/mpi.html#using-parallel-hdf5-from-h5py

If h5py is not parallel i suggest you either rebuild your current h5py (to
be parallel enabled) or let Underworld's 'configure.py' build (and use) its
own version of h5py (always parallel enabled).

**Comment by wkillers** [comment]
@lmoresi , thanks.

**Comment by wkillers** [comment]
@julesghub , I just realise that my problem about mpi4py is caused by some path error in my script since I run the script in some other directory, and I made a mistake when I set the path to import the modules. Sorry for forgetting update and I am closing this issue.
