### ISSUE TITLE
ImportError when importing underworld module with the development branch

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#143]
Hi all, 
I've downloaded the last version of the development branch this monrning, and everything was ok. It was running. Bur this afternoon, I have the problem with libStgGermain.so 
The only thing I have done, is to close jupyter notebook and use internet to search for papers. I did not install anything else, and I did not change my user. Also, I did not change any chmod permission's. So I do not know what had happened.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4f65faa3f260> in <module>()
      5 import os
      6 
----> 7 import underworld as uw
      8 uw.matplotlib_inline()
      9 from underworld import function as fn

/home/angelUW/underworld2_Tol0.025/underworld/__init__.py in <module>()
     48 
     49 
---> 50 import libUnderworld
     51 import container
     52 import mesh

/home/angelUW/underworld2_Tol0.025/libUnderworld/__init__.py in <module>()
----> 1 from libUnderworldPy import *

/home/angelUW/underworld2_Tol0.025/libUnderworld/libUnderworldPy/__init__.py in <module>()
      1 import numpy
----> 2 import StGermain
      3 import StgDomain
      4 import StgFEM
      5 import Solvers

/home/angelUW/underworld2_Tol0.025/libUnderworld/libUnderworldPy/StGermain.py in <module>()
     30                 fp.close()
     31             return _mod
---> 32     _StGermain = swig_import_helper()
     33     del swig_import_helper
     34 else:

/home/angelUW/underworld2_Tol0.025/libUnderworld/libUnderworldPy/StGermain.py in swig_import_helper()
     26         if fp is not None:
     27             try:
---> 28                 _mod = imp.load_module('_StGermain', fp, pathname, description)
     29             finally:
     30                 fp.close()

ImportError: libStGermain.so: cannot open shared object file: No such file or directory

Any idea?

**Comment by AngelValverdePerez** [comment]
this is what appear in my terminal


angelUW@avalverde:~/underworld2_Tol0.01$ jupyter notebook
[I 16:15:20.186 NotebookApp] Serving notebooks from local directory: /home/angelUW/underworld2_Tol0.01
[I 16:15:20.187 NotebookApp] 0 active kernels 
[I 16:15:20.187 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 16:15:20.187 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 16:15:28.803 NotebookApp] Notebook docs/examples/2_09_ShearBandsPureShear.ipynb is not trusted
[I 16:15:30.471 NotebookApp] Kernel started: dc2e5999-8d94-431b-b893-8580312af488
[I 16:17:30.562 NotebookApp] Saving file at /docs/examples/2_09_ShearBandsPureShear.ipynb
[W 16:17:30.563 NotebookApp] Saving untrusted notebook docs/examples/2_09_ShearBandsPureShear.ipynb

**(process:22230): GLib-CRITICAL **: g_path_get_basename: assertion 'file_name != NULL' failed
Vector smash protection is enabled.
ATTENTION: default value of option force_s3tc_enable overridden by environment.**

**Comment by jmansour** [comment]
Hi Angel. Sorry for the late reply on this.  It looks like you needed to regenerate the python bindings via swigall.py.  Generally, you should just run `./compile.py`, which will also handle the binding generation.

**Comment by AngelValverdePerez** [comment]
Thank you! You were right. Now is working fine!
