### ISSUE TITLE
Ipyparallel or mpirun

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#144]
Which is the simplest way to run in parallel the models?
Has anybody done the comparation?
Any advice?

Thanks anticipated

**Comment by jmansour** [comment]
We do not have a lot of experience with ipyparallel, but it is something we are experimenting with. Actually, the latest docker images have ipyparallel enabled. I feel that the parallel notebook workflow will be mainly useful for model development, testing and debugging.  

But for larger simulations, mpirun is probably the best option still, but a direct comparison in terms of efficiency has not been done.

**Comment by AngelValverdePerez** [comment]
Mpirun is working fine.

Thanks!!
