### ISSUE TITLE
Ability to evaluate SwarmVariableFn at arbitrary locations

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#15]
So I can do this OK:
```python
print velocityField.evaluate(swarm)
```
outputting this:
```
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 ..., 
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
```

But when I try:
```python
print viscosity_Fn.evaluate(linearMesh)
```
I get this:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-39-c94b897fcb04> in <module>()
----> 1 print viscosity_Fn.evaluate(linearMesh)

/home/luke/Programs/uw2_dev/underworld/function/_function.pyc in evaluate(self, inputData, inputType)
    428             if inputType != None:
    429                 raise ValueError("'inputType' specification not supported for this input class.")
--> 430             return _cfn.Query(self._fncself).query(inputData._get_iterator())
    431         elif isinstance(inputData, np.ndarray):
    432             if inputType != None:

RuntimeError: Provided input to SwarmVariableFn does not appear to be of supported type.
Supported types are 'FEMCoordinate' and 'ParticleCoordinate'.
```

But if you look in https://github.com/underworldcode/underworld2/blob/development/libUnderworld/Underworld/Function/src/SwarmVariableFn.cpp line 73 - the code to actually do the mapping back to the mesh appears to be there - I just can't seem to find a way to produce a FEMCoordinate to feed to it.

Cheers,

**Comment by jmansour** [comment]
That code does something a bit different Luke.  It actually calls for a FEMCoordinate (ie, elementId & local coordinate), but the local coordinate must also be derived from an integration point swarm.  

Really what's required here is a nearest neighbour type approach which would simply grab the closest particle.  An alternative would be some sort of weighted average, but I would see this best implemented as a separate function which then can take the swarmvariablefn as an argument.

Leave this open for now, and i'll close it once the nearest-neighbour is implemented.

**Comment by lmoresi** [comment]
We could have a mapping to make a mesh-based FE variable from the Swarm using the shape functions to create an appropriate weighting to the nodes. But this would, necessarily, make a smooth version of the field. That's probably what the code already does.

We might have a distance weighted interpolation to any arbitrary point much as we did with the RBF Swarm capability.

A nearest neighbour is also useful.

My preference would be to default to the latter but to have some sort of interpolation_type argument which would allow people to choose more expensive or more smooth variants. For visualisation, perhaps the cheapest is to create an FEVariable ... 

L

**Comment by julesghub** [comment]
New MeshProjection functionality can help here.
5b67ae8c1967dc640b49d7e198e20993f750e52b

**Comment by RebeccaFarrington** [comment]
@garethkennedy to include an example

**Comment by julesghub** [comment]
Won't be adding this functionality in foreseeable future as the MeshProjection class can get this done.
Closing this ticket for now.
