### ISSUE TITLE
read density and viscosity data from input file?

### ISSUE THREAD

**Issue by geofarhan** [underworldcode/underworld2#150]
I have a detail density and viscosity data of the lithosphere( crust + upper mantle). I would like to compute the flow field using stroke equation. Can I read both variable data from input file? 

Farhan

**Comment by julesghub** [comment]
Yes you can define variables, i.e. density or viscosity, using an input
file or a function.
This is done in the python layer so the user has a lot of functionality
available to them.

For checkpointing functionality Underworld uses hdf5 file format to
save/load information from/onto discretisations, ie, lagrangian points or
mesh vertices.
To see an example of this checkout
https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/07_Utilities.ipynb

cheers
Julian

**Comment by jmansour** [comment]
I'll close this for now.  Feel free to reopen if you would like to discuss further.
