### ISSUE TITLE
Failed compilation

### ISSUE THREAD

**Issue by mgouiza** [underworldcode/underworld2#151]
Hi,

I am trying to compile Underworld2 on a multicore Linux-based HPC but it fails because it can’t locate the PETSc package.
Although the PETSc packages exist and is loaded on the HPC.
I’ve attached the config.log file.

Your help would be very much appreciated.

Thank you

------------------------------------------------- 
Mohamed Gouiza, Research Fellow
Basin Structure Group, Institute of Applied Geosciences 
University of Leeds, School of Earth and Environment
Leeds,  LS2 9JT, UK
M.Gouiza@leeds.ac.uk

[config.log.txt](https://github.com/underworldcode/underworld2/files/345925/config.log.txt)

------------------------

**Comment by julesghub** [comment]
Hi Mohamed,
The log shows the --petsc-dir option is backwards. ie, 
`--/apps/developers/libraries/petsc/3.4.3/1/bit-64-gnu-4.8.1-openmpi-1.6.5=PETSC_DIR`

Please try this instead:
   `./configure.py --petsc-dir=$PETSC_DIR`

To find all the options available at the configure stage run: `configure.py -h`

cheers,
Julian

**Comment by mgouiza** [comment]
Hi Julian,

That was not the issue. For some reason, it couldn't pick the petsc of the compiler. Besides, it seems that I can't load petsc and python libraries at the same time. I solved both issues by installing a local version of petsc and now the configuration finds all the necessary packages.

However, the compilation stops at: LavaVu_wrap.cxx 
Please see the attached log.

Thanks a lot for your help

Mohamed
[log.txt](https://github.com/underworldcode/underworld2/files/347645/log.txt)

**Comment by OKaluza** [comment]
Compiler specific issue perhaps, which compiler are you using?

**Comment by mgouiza** [comment]
gnu/4.8.1

**Comment by OKaluza** [comment]
That should be fine, then I think it might be a swig bug, what is your swig -version?
If you feel like some hacking, a workaround that might be worth trying is to add:

    #include <cstddef>

to libUnderworld/libUnderworldPy/LavaVu.i

immediately before the line:

    #include "../gLucifer/Viewer/src/LavaVu.h"

Then re-build with compile.py
(but if your version of swig is really old there may be more issues)

**Comment by mgouiza** [comment]
My swig version is quite old: 1.3.40
I will need to install a local version of swig and link it to the compilation. If I wait for the IT to update the swig version, it might take weeks.
Now can I set the path to my local swig during the configuration?

**Comment by OKaluza** [comment]
It will just use whichever swig it finds in the environment, so you could just add your local version's path at the front of your $PATH variable.
Alternatively edit swigcommandbase in libUnderworld/libUnderworldPy/swigall.py.

**Comment by mgouiza** [comment]
It worked. You were right, the new version of swig did the trick.
The compilation was successful but with many warnings.
Thank you @OKaluza

**Comment by OKaluza** [comment]
No worries @mgouiza, glad to hear it worked! There are always quite a few swig warnings but nothing to be concerned about. I'll close the ticket.
