### ISSUE TITLE
New particles

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#153]
Is it possible to add new particles to the domain, step by step in time instead of deforming the mesh?

**Comment by jmansour** [comment]
Hi Angel

Can you be a bit more specific on what you are trying to achieve?  You can certainly add particles via the AddParticlesWithCoordinates method on the swarm, but this may or may not be appropriate.

**Comment by jmansour** [comment]
i'll close this.  reopen if necessary.
