### ISSUE TITLE
A problem with figure.show

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#156]
I have installed the underworld2 on the local machine with macos-Yosemite system.
And when I use the example (getting start.ipynb) in the python notebook, I found the figure.show can not show the picture in the notebook. But I did note get any error on notebook. So why?

import glucifer
fig = glucifer.Figure(figsize=(800,400))
fig.append( glucifer.objects.Surface(mesh, temperatureField, colours="blue white red") )
fig.append( glucifer.objects.Mesh(mesh) )
fig.show()

## **The message inte terminal**
	
Global element size: 8x8
	Local offset of rank 0: 0x0
	Local range of rank 0: 8x8
Sampling (J71ZQEP7__dr) 100 x 100..100% (0) -- 0.019630 sec.
    160.012 kb of geometry data saved, 29.825 kb written.
    3.456 kb of geometry data saved, 0.618 kb written.

**Comment by OKaluza** [comment]
Seems like the graphics output features didn't get built correctly (which your other posted issue confirms).
You can verify by checking for the existence of the files:
```
libUnderworld/build/bin/LavaVu
libUnderworld/build/lib/libLavaVu.dylib

```
A warning message probably should be implemented, but it is designed so visualisation is a non-critical feature and the code will just continue if it fails.

**Comment by tyszwh** [comment]
I have checked this two files. It exists in the directory. But I still can not get the picture in notebook form the fig.show(). 
The configure log show 
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... yes
Checking for package libPNG... yes
Checking for package gl2ps... no
Checking for package CGL... no
Checking for package X11... yes
Checking for package OpenGL... yes

So, is it a problem with CGL? or

**Comment by OKaluza** [comment]
It should use CGL and it's very strange that CGL is not configuring on an OS X system, but it should still work with X11 instead, assuming XQuartz is configured correctly.
What happens if you run libUnderworld/build/bin/LavaVu?

**Comment by tyszwh** [comment]
When I run ./lavavu in the cmd, It will popup a window x11 with black screen( and the axis x,y,z), I think it should works fine. whether there have some ways to fix the configure of CGL? I have not found some package about CGL (Core OpenGL). I even reinstall the osX system. But it appears the same result.

**Comment by OKaluza** [comment]
OK, I see it built fine and is working correctly with X11 instead of CGL, so fixing CGL probably won't make any difference.

Perhaps it is a problem with the python interface, instead of running "jupyter notebook", could you try just running python and testing the module with the following command:

`python -c "import libUnderworld.libUnderworldPy.LavaVu"`

If it works correctly it should just return with no error message.

**Comment by tyszwh** [comment]
# **This is the result.**

tyszdeMacBook-Pro:~ tysz$ python -c "import libUnderworld.libUnderworldPy.LavaVu"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tysz/Underworld2/underworld2-7-30/libUnderworld/libUnderworldPy/LavaVu.py", line 2
    _LavaVu = swig_import_helper()
  File "/Users/tysz/Underworld2/underworld2-7-30/libUnderworld/libUnderworldPy/LavaVu.py", line 2
    return importlib.import_module('_LavaVu')
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/im
    __import__(name)
ImportError: No module named _LavaVu

**Comment by OKaluza** [comment]
Alright, one step closer to the problem.
Does this file exist:

`libUnderworld/libUnderworldPy/_LavaVu.so`

**Comment by tyszwh** [comment]
It exists in the directory. But not the original file. When I right click show the original file. It takes me to libgLucifer_swig.dylib

**Comment by OKaluza** [comment]
That all looks good, it must be a paths issue, did you already run 

`source updatePyPath.sh`

in your underworld2 directory?
What is the result of:

`echo $PYTHONPATH`

**Comment by tyszwh** [comment]
## **The path**
tyszdeMacBook-Pro:~ tysz$ echo $PYTHONPATH
:/Users/tysz/Underworld2/underworld2-7-30:/Users/tysz/Underworld2/underworld2-7-30

## **If there have a path problem. I should get error on" import underworld as uw" or "import glucifer"  But the result as follows in ipython**

In [3]: import underworld as uw

In [4]: import glucifer

In [5]: import libUnderworld.libUnderworldPy.LavaVu
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-aaad850361f3> in <module>()
----> 1 import libUnderworld.libUnderworldPy.LavaVu

/Users/tysz/Underworld2/underworld2-7-30/libUnderworld/libUnderworldPy/LavaVu.py in <module>()
     23         except ImportError:
     24             return importlib.import_module('_LavaVu')
---> 25     _LavaVu = swig_import_helper()
     26     del swig_import_helper
     27 elif _swig_python_version_info >= (2, 6, 0):

/Users/tysz/Underworld2/underworld2-7-30/libUnderworld/libUnderworldPy/LavaVu.py in swig_import_helper()
     22             return importlib.import_module(mname)
     23         except ImportError:
---> 24             return importlib.import_module('_LavaVu')
     25     _LavaVu = swig_import_helper()
     26     del swig_import_helper

/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.pyc in import_module(name, package)
     35             level += 1
     36         name = _resolve_name(name[level:], package, level)
---> 37     __import__(name)
     38     return sys.modules[name]

ImportError: No module named _LavaVu

**Comment by OKaluza** [comment]
True, but the module is there. what is the output of

`ls -l libUnderworld/build/lib/`

**Comment by tyszwh** [comment]
## The file in the directory

-rwxr-xr-x  1 tysz  staff    10344  8  1 15:45 PICellerator_Toolboxmodule.dylib
-rwxr-xr-x  1 tysz  staff    10208  8  1 15:45 Solvers_Toolboxmodule.dylib
drwxr-xr-x  3 tysz  staff      102  8  1 15:45 StGermain
-rwxr-xr-x  1 tysz  staff    10256  8  1 15:45 StgDomain_Toolboxmodule.dylib
-rwxr-xr-x  1 tysz  staff    10184  8  1 15:45 StgFEM_Toolboxmodule.dylib
-rwxr-xr-x  1 tysz  staff    10296  8  1 15:45 Underworld_Toolboxmodule.dylib
-rwxr-xr-x  1 tysz  staff    13332  8  1 15:45 Underworld_Velic_solAmodule.dylib
-rwxr-xr-x  1 tysz  staff    17580  8  1 15:45 Underworld_Velic_solBmodule.dylib
-rwxr-xr-x  1 tysz  staff    17364  8  1 15:45 Underworld_Velic_solHAmodule.dylib
-rwxr-xr-x  1 tysz  staff    13072  8  1 15:45 Underworld_Velic_solSmodule.dylib
-rwxr-xr-x  1 tysz  staff    10232  8  1 15:45 gLucifer_Toolboxmodule.dylib
-rwxr-xr-x  1 tysz  staff  2779700  8  1 15:48 libFunction_swig.dylib
lrwxr-xr-x  1 tysz  staff       87  8  1 15:48 libFunction_swig.so -> /Users/tysz/Underworld2/und
-rwxr-xr-x  1 tysz  staff  4878348  8  1 15:44 libLavaVu.dylib
-rwxr-xr-x  1 tysz  staff   515320  8  1 15:48 libLavaVu_swig.dylib
lrwxr-xr-x  1 tysz  staff       85  8  1 15:48 libLavaVu_swig.so -> /Users/tysz/Underworld2/under
-rwxr-xr-x  1 tysz  staff   139780  8  1 15:45 libPICellerator.dylib
-rwxr-xr-x  1 tysz  staff  1312620  8  1 15:45 libPICellerator_swig.dylib
lrwxr-xr-x  1 tysz  staff       91  8  1 15:45 libPICellerator_swig.so -> /Users/tysz/Underworld2
-rwxr-xr-x  1 tysz  staff   281128  8  1 15:45 libSolvers.dylib
-rwxr-xr-x  1 tysz  staff   504896  8  1 15:48 libSolvers_swig.dylib
lrwxr-xr-x  1 tysz  staff       86  8  1 15:48 libSolvers_swig.so -> /Users/tysz/Underworld2/unde
-rwxr-xr-x  1 tysz  staff   875224  8  1 15:45 libStGermain.dylib
-rwxr-xr-x  1 tysz  staff   236416  8  1 15:45 libStGermain_Tools_swig.dylib
lrwxr-xr-x  1 tysz  staff       94  8  1 15:45 libStGermain_Tools_swig.so -> /Users/tysz/Underwor
-rwxr-xr-x  1 tysz  staff  2031720  8  1 15:45 libStGermain_swig.dylib
lrwxr-xr-x  1 tysz  staff       88  8  1 15:45 libStGermain_swig.so -> /Users/tysz/Underworld2/un
-rwxr-xr-x  1 tysz  staff   807360  8  1 15:45 libStgDomain.dylib
-rwxr-xr-x  1 tysz  staff  3315032  8  1 15:45 libStgDomain_swig.dylib
lrwxr-xr-x  1 tysz  staff       88  8  1 15:45 libStgDomain_swig.so -> /Users/tysz/Underworld2/un
-rwxr-xr-x  1 tysz  staff   664928  8  1 15:45 libStgFEM.dylib
-rwxr-xr-x  1 tysz  staff  3644352  8  1 15:45 libStgFEM_swig.dylib
lrwxr-xr-x  1 tysz  staff       85  8  1 15:45 libStgFEM_swig.so -> /Users/tysz/Underworld2/under
-rwxr-xr-x  1 tysz  staff  1638584  8  1 15:45 libUnderworld.dylib
-rwxr-xr-x  1 tysz  staff  1838896  8  1 15:49 libUnderworld_swig.dylib
lrwxr-xr-x  1 tysz  staff       89  8  1 15:49 libUnderworld_swig.so -> /Users/tysz/Underworld2/u
-rwxr-xr-x  1 tysz  staff    82208  8  1 15:45 libc_arrays_swig.dylib
lrwxr-xr-x  1 tysz  staff       87  8  1 15:45 libc_arrays_swig.so -> /Users/tysz/Underworld2/und
-rwxr-xr-x  1 tysz  staff    34828  8  1 15:45 libc_pointers_swig.dylib
lrwxr-xr-x  1 tysz  staff       89  8  1 15:45 libc_pointers_swig.so -> /Users/tysz/Underworld2/u
-rwxr-xr-x  1 tysz  staff  1535316  8  1 15:45 libgLucifer.dylib
-rwxr-xr-x  1 tysz  staff  2842392  8  1 15:49 libgLucifer_swig.dylib
lrwxr-xr-x  1 tysz  staff       87  8  1 15:49 libgLucifer_swig.so -> /Users/tysz/Underworld2/und
-rwxr-xr-x  1 tysz  staff    45096  8  1 15:45 libpcu.dylib
-rwxr-xr-x  1 tysz  staff    51040  8  1 15:45 libpetsc_swig.dylib
lrwxr-xr-x  1 tysz  staff       84  8  1 15:45 libpetsc_swig.so -> /Users/tysz/Underworld2/underw

**Comment by OKaluza** [comment]
All fine, running out of ideas here, what about

`swig -version`

**Comment by tyszwh** [comment]
## Swig -version
tyszdeMacBook-Pro:~ tysz$ swig -version

SWIG Version 3.0.10

Compiled with clang++ [x86_64-apple-darwin15.5.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

## And I found that some  in libUnderworld/config.log, may indicate why CGL can't be configured.

scons: Configure: Checking for C++ library None... 
.sconf_temp/conftest_93.cpp <-
  |
  |
  |#include "OpenGL/OpenGL.h"
  |#include "OpenGL/gl.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
g++ -o .sconf_temp/conftest_93.o -c -std=c++11 -Wall -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DHAVE_LIBPNG -I/System/Library/Frameworks/OpenGL.framework/Headers .sconf_temp/conftest_93.cpp
In file included from /System/Library/Frameworks/OpenGL.framework/Headers/CGLCurrent.h:8:0,
                 from /System/Library/Frameworks/OpenGL.framework/Headers/OpenGL.h:9,
                 from .sconf_temp/conftest_93.cpp:3:
/System/Library/Frameworks/OpenGL.framework/Headers/CGLTypes.h:14:18: error: missing binary operator before token "("
 #if __has_feature(assume_nonnull)
                  ^
/System/Library/Frameworks/OpenGL.framework/Headers/CGLTypes.h:22:18: error: missing binary operator before token "("
 #if __has_feature(nullability)
                  ^
scons: Configure: no

**Comment by tyszwh** [comment]
Whether I should use the clang instead gcc to compile ?

**Comment by OKaluza** [comment]
Well the system gcc is clang (can check with g++ --version)
How did you switch compilers to solve the other issue, did you edit config.cfg or set an environment variable?

**Comment by tyszwh** [comment]
In fact, I have changed the system gcc (clang) with gcc-6 installed from the brew after i reinstall the osx.  I dont know whether it will cause the problem. 
## Show the gcc -v now 
tyszdeMacBook-Pro:~ tysz$ /usr/local/bin/gcc -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc/6.1.0/libexec/gcc/x86_64-apple-darwin15.6.0/6.1.0/lto-wrapper
Target: x86_64-apple-darwin15.6.0
Configured with: ../configure --build=x86_64-apple-darwin15.6.0 --prefix=/usr/local/Cellar/gcc/6.1.0 --libdir=/usr/local/Cellar/gcc/6.1.0/lib/gcc/6 --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-6 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-system-zlib --enable-libstdcxx-time=yes --enable-stage1-checking --enable-checking=release --enable-lto --with-build-config=bootstrap-debug --disable-werror --with-pkgversion='Homebrew gcc 6.1.0' --with-bugurl=https://github.com/Homebrew/homebrew/issues --enable-plugin --disable-nls --enable-multilib
Thread model: posix
gcc version 6.1.0 (Homebrew gcc 6.1.0)

**Comment by OKaluza** [comment]
Do g++/mpicc/mpicxx link to the same compiler or the system defaults? Perhaps post your libUnderworld/config.cfg too...

I think this might be a problem with some components being built with different compilers but I've run out of ideas, if you don't have a particular need for the development version you could look at using the docker image instead http://www.underworldcode.org/posts/Underworld-and-Dockers2

**Comment by tyszwh** [comment]
"How did you switch compilers to solve the other issue, did you edit config.cfg or set an environment variable?"
sorry ,I did not see clear about this question.  I solve this issue by changing the config.cfg with command "./configure.py --cc=gcc-6  --cxx=g++-6 "before I reinstall the osX. After that, I link the gcc-6 and g+-6 to gcc and g++.
I always like to compile the model in the local machine and I have deal this problem for several days. So I hope to fixed it.  

import libUnderworld.libUnderworldPy.LavaVu still show same error.

## below is config.cfg

prefix = '/Users/tysz/Underworld2/underworld2-7-30/libUnderworld'
build_dir = 'build'
with_debugging = 1
with_profiling = 0
optimisation_flag = 'default'
with_warnings = 1
lib_type = 'shared'
CC = 'mpicc'
CXX = 'mpicxx'
CFLAGS = []
CXXFLAGS = '-std=c++11'
with_credo = 1
with_glucifer = 1
with_graphics = 1
with_geothermal = False
with_solvers = True
with_importers = False
with_spherical = False
with_viscoelastic = False
with_sdl = 1
with_x11 = 1
with_cgl = 1
with_glut = 1
with_png = 1
with_avcodec = 0
with_gl2ps = 1
eptiming = 0
with_cautious_mode = 0
CPPPATH = ['/usr/include/libxml2', '/usr/include/python2.7', '/usr/local/petsc362/include', '/usr/local/lib/python2.7/site-packages/numpy/core/include', '']
LIBPATH = ['/usr/local/petsc362/lib', '/usr/local/lib/python2.7/site-packages/numpy/core/lib', '']
RPATH = ['/usr/local/petsc362/lib', '/usr/local/lib/python2.7/site-packages/numpy/core/lib', '']
LIBS = ['python2.7', 'python', 'hdf5', 'xml2', 'm', 'petsc']
CPPDEFINES = [['__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES', '0'], 'HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'DEBUG']
CFLAGS = []
CCFLAGS = ['-g', '-O0', '-Wall']
FRAMEWORKS = []
_RPATH = ''
SHLINKFLAGS = ['$LINKFLAGS', '-dynamiclib', '-dynamiclib', '-flat_namespace', '-single_module', '-undefined', 'suppress', '-install_name', '${_abspath(TARGET)}']
shared_libs = 1
static_libs = 0

**Comment by OKaluza** [comment]
Did you try first with the system clang compiler? What made you switch to homebrew gcc?

**Comment by tyszwh** [comment]
No, I have not try it.  I will reinstall the EI Capitan and try it now.  I will give feedback later.

**Comment by tyszwh** [comment]
Dear OKaluza  
I have tried compile it by using default compile (clang). Some good new is the CGL works finely at last. And " import libUnderworld.libUnderworldPy.LavaVu" also works finely. But when we tap the fig.show(), I still can not got the picture in the ipython notebook. 

## **ipython as follows**
In [1]: import libUnderworld.libUnderworldPy.LavaVu

In [2]: import underworld as uw

In [3]: mesh = uw.mesh.FeMesh_Cartesian( elementType = ("Q1"), 
   ...:                                  elementRes  = (8, 8), 
   ...:                                  minCoord    = (0., 0.), 
   ...:                                  maxCoord    = (2., 1.))
	Global element size: 8x8
	Local offset of rank 0: 0x0
	Local range of rank 0: 8x8

In [4]: temperatureField = uw.mesh.MeshVariable( mesh=mesh, nodeDofCount=1 )

In [5]: for index, coord in enumerate(mesh.data):
   ...:     temperatureField.data[index] = coord[1]
   ...:     

In [6]: import glucifer
   ...: fig = glucifer.Figure(figsize=(800,400))
   ...: fig.append( glucifer.objects.Surface(mesh, temperatureField, colours="bl
   ...: ue white red") )
   ...: fig.append( glucifer.objects.Mesh(mesh) )
   ...: 

In [7]: fig.show()

**## Configure output as follows**
Sampling (M26WHJMV__dr) 100 x 100..100% (0) -- 0.017367 sec.
    160.012 kb of geometry data saved, 29.825 kb written.
    3.456 kb of geometry data saved, 0.618 kb written.
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... 
Attempting to build private h5py version at /Users/tysz/underworld2/underworld2-7-30/h5py using cc=h5pcc. This may take a few minutes.
python setup.py configure -m --hdf5 /usr/local/hdf5-1.8.17

Attempting to build private h5py version at /Users/tysz/underworld2/underworld2-7-30/h5py using cc=mpicc. This may take a few minutes.
python setup.py configure -m --hdf5 /usr/local/hdf5-1.8.17
yes
Checking for package libPNG... yes
Checking for package gl2ps... no
Checking for package CGL... yes

**Comment by tyszwh** [comment]
I also found that the there are warning information when example start in jupyter notebook. I don know whether it is a problem.


tyszdeMacBook-Pro:underworld2-7-30 tysz$ jupyter notebook
[I 01:12:16.953 NotebookApp] The port 8888 is already in use, trying another port.
[I 01:12:16.954 NotebookApp] The port 8889 is already in use, trying another port.
[I 01:12:16.955 NotebookApp] The port 8890 is already in use, trying another port.
[I 01:12:16.956 NotebookApp] The port 8891 is already in use, trying another port.
[I 01:12:16.956 NotebookApp] The port 8892 is already in use, trying another port.
[I 01:12:16.965 NotebookApp] Serving notebooks from local directory: /Users/tysz/underworld2/underworld2-7
[I 01:12:16.965 NotebookApp] 0 active kernels 
[I 01:12:16.965 NotebookApp] The Jupyter Notebook is running at: http://localhost:8970/
[I 01:12:16.965 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip co
[I 01:12:39.999 NotebookApp] Kernel started: 46826792-174a-4887-8c07-bf2916ed1dbe
**[W 01:12:40.145 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js (::1) 17.81ms referer=**
	Global element size: 8x8
	Local offset of rank 0: 0x0
	Local range of rank 0: 8x8
Sampling (PQU6XE8B__dr) 100 x 100..100% (0) -- 0.018290 sec.
    160.012 kb of geometry data saved, 29.825 kb written.
    3.456 kb of geometry data saved, 0.618 kb written.
[I 01:14:40.002 NotebookApp] Saving file at /docs/user_guide/01_GettingStarted.ipynb

**Comment by OKaluza** [comment]
Well it's definitely an improvement.
Those warnings don't matter, it just means you have other notebook servers open or perhaps another program is using the ports 8888-8892

What happens if you run this python script:
```
import LavaVu
lv = LavaVu.load()
lv.image('temp')
```
It should save an image called "temp.png" in the current directory (image with black background and axes in corner)

**Comment by tyszwh** [comment]
## **I got the wrong message showing. I cant import the LavaVu.**

In [1]: import underworld as uw

In [2]: import libUnderworld.libUnderworldPy.LavaVu

In [3]: import LavaVu
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-05b34dcb9027> in <module>()
----> 1 import LavaVu

ImportError: No module named LavaVu

In [4]: import LavaVu
   ...: lv = LavaVu.load()
   ...: lv.image('temp')
   ...: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-2c919ed17e31> in <module>()
----> 1 import LavaVu
      2 lv = LavaVu.load()
      3 lv.image('temp')

ImportError: No module named LavaVu

**Comment by OKaluza** [comment]
Try this one
```
import libUnderworld.libUnderworldPy.LavaVu as LavaVu
lv = LavaVu.load()
lv.image('temp')
```

**Comment by tyszwh** [comment]
## got a attributerError

import libUnderworld.libUnderworldPy.LavaVu as LavaVu

lv = LavaVu.load()

lv.image('temp')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-bc9b92a42ea2> in <module>()
      1 import libUnderworld.libUnderworldPy.LavaVu as LavaVu
----> 2 lv = LavaVu.load()
      3 lv.image('temp')

AttributeError: 'module' object has no attribute 'load'

**Comment by OKaluza** [comment]
Ok so you are on the master branch, I'll have to write another test script for the old interface, will get back to you.

**Comment by OKaluza** [comment]
Try this one:
```
import glucifer
import _LavaVu as lavavu
lavavu.execute(['LavaVu', '-a'])
lavavu.image('temp')
```

**Comment by tyszwh** [comment]
## The message show Error 

import glucifer

import _LavaVu as lavavu

lavavu.execute(['LavaVu', '-a'])

lavavu.image('temp')

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-be6dc16c06fc> in <module>()
      1 import glucifer
----> 2 import _LavaVu as lavavu
      3 lavavu.execute(['LavaVu', '-a'])
      4 lavavu.image('temp')

ImportError: No module named _LavaVu

**Comment by OKaluza** [comment]
Any improvement if you change it to
import libUnderworld.libUnderworldPy._LavaVu as lavavu
?

**Comment by tyszwh** [comment]
## Yes，I have try it. Message is NameError: name 'lavavu' is not defined

import libUnderworld.libUnderworldPy.LavaVu as LavaVu
import glucifer
lavavu.execute(['LavaVu', '-a'])
lavavu.image('temp')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-822a62c47364> in <module>()
      1 import libUnderworld.libUnderworldPy.LavaVu as LavaVu
      2 import glucifer
----> 3 lavavu.execute(['LavaVu', '-a'])
      4 lavavu.image('temp')

NameError: name 'lavavu' is not defined

**Comment by OKaluza** [comment]
You capitalised the "as LavaVu" should be "as lavavu"

**Comment by tyszwh** [comment]
## I'm really sorry for it.  Now it  gives another wrong message

import libUnderworld.libUnderworldPy.LavaVu as lavavu

import glucifer

lavavu.execute(['LavaVu', '-a'])

lavavu.image('temp')

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-f6b4a5dd2e21> in <module>()
      2 import glucifer
      3 lavavu.execute(['LavaVu', '-a'])
----> 4 lavavu.image('temp')

RuntimeError: IBO creation failed!

**Comment by OKaluza** [comment]
Are you logged into this machine remotely or locally?

**Comment by tyszwh** [comment]
locally machine.
 And a python rocket show in dock with keep jumping and show no reponse.

**Comment by OKaluza** [comment]
What is the output of this script then:
```
import glucifer
import libUnderworld.libUnderworldPy._LavaVu as lavavu
lavavu.execute(['LavaVu', '-v', '-I', '-h'])
lavavu.image('test')
```

**Comment by tyszwh** [comment]
It woks fine. I can found the output in directory. 
this old one also woks fine now 

import libUnderworld.libUnderworldPy.LavaVu as LavaVu
import glucifer
lavavu.execute(['LavaVu', '-a'])
lavavu.image('temp')

import glucifer
import libUnderworld.libUnderworldPy._LavaVu as lavavu
lavavu.execute(['LavaVu', '-v', '-I', '-h'])
lavavu.image('test')

**Comment by tyszwh** [comment]
Dear OKaluza 
Oh, there are a good news. I compile model from the dev branch. I found it works fine now. the fig.show() gave a figure in notebook now.
Thanks a lot for your help to find the problem. I think It gets very close to the problem now.
I'm sure there are some problem with viewer in master branch or may be lack some deps . Because the fig.show still not work now.  If there have some fix on  master branch, I still like to try testing the problem. Everything seem ok but fig.show() did not show figure, why?

**Comment by OKaluza** [comment]
Great to hear the dev branch is working for you!
I think your problem on the master release branch is something to do with the swig module loading/paths, but it's difficult because I can't duplicate it and it works fine on all our test machines.
If you want to test the next thing I would try is replacing the line in glucifer/_glucifer.py
`import _LavaVu as lavavu`
with
`import libUnderworld.libUnderworldPy._LavaVu as lavavu`
as it seems the last test script we tried works.

Anyway the dev branch is very stable at the moment and actually has quite a few fixes that didn't make the last release.

**Comment by tyszwh** [comment]
Dear OKaluza 
I changed the code as you mentioned above and re-compiled the code. The code works fine now.
Congratulates! I think it solves problems because the LavaVu did not work before.
But why did not this problem occur with your machine? I guess that it may relate to your current python environments which has a dev branch. I'm not sure.

**Comment by OKaluza** [comment]
@tyszwh ok thanks, good to know that fixed it.
It's definitely something to do with your python env. It's not just my machine, the master branch version visualisations work on all the other machines we test on, Linux and OS X.
