### ISSUE TITLE
Another problem when compiling the CocoaViewer.mm

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#157]
## The erros message.
g++: error: gLucifer/Viewer/src/Main/CocoaViewer.mm: Objective-C++ compiler not installed on this system
scons: *** [build/gLucifer/Viewer/src/Main/CocoaViewer.os] Error 1

**Comment by OKaluza** [comment]
This suggests the wrong compiler is being used, the system clang compiler has built in support for objective c++. What is the output of **g++ --version** ?

@jmansour have you seen anything like this before? I don't have a yosemite system handy to test with.

**Comment by tyszwh** [comment]
I have solved this problem with new compile gcc-6. Because the old gcc compile can not support  the .mm file.

**Comment by OKaluza** [comment]
Ok, closing.
