### ISSUE TITLE
Visualisation for swarm based functions

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#16]
Currently the Points drawing object only accepts swarm variables.  It should be updated to use functions so that (in particular) swarm based functions can be directly visualised.  The current workaround is to evaluate the function and copy the results into a new swarm variable, which can then be visualised. 

Also, the Surface drawing object cannot draw swarm based functions because it evaluates on global coordinates. A nearest neighbour type algorithm would fix this.

**Comment by garethkennedy** [comment]
Another issue with plotting using Points is that it takes the min/max for the plot from the min/max of the swarm particles' coordinate data. This is a problem if you have a tracer particle in a swarm at (0.5, 0.9) say and the box size is (1.0, 1.0). It will make the window size only (0.5, 0.9).

**Comment by lmoresi** [comment]
My suggestion here would be to add some standard keyword arguments to the plotting interface that all gLucifer commands inherit - the size of the plot, and various max / min / colormap arguments should be standard. This is in the style of matplotlib (ugh !) that we are following broadly.


On 6 November 2015 at 11:30:22 AM, Gareth Kennedy (notifications@github.com<mailto:notifications@github.com>) wrote:

Another issue with plotting using Points is that it takes the min/max for the plot from the min/max of the swarm particles' coordinate data. This is a problem if you have a tracer particle in a swarm at (0.5, 0.9) say and the box size is (1.0, 1.0). It will make the window size only (0.5, 0.9).

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/16#issuecomment-154244361>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by OKaluza** [comment]
The plot size issue can now be controlled by the "boundingBox" parameter
when creating a figure, if a bounding box is provided it will use this
instead of just calculating the minimum bounding box required to fit the
objects. (The same as used to be set from the minX/Y/Z maxX/Y/Z in the xml)

eg: Figure(..., boundingBox=((0,0,0), (1,1,1)), ...)

On 6 November 2015 at 11:35, lmoresi <notifications@github.com> wrote:

> My suggestion here would be to add some standard keyword arguments to the
> plotting interface that all gLucifer commands inherit - the size of the
> plot, and various max / min / colormap arguments should be standard. This
> is in the style of matplotlib (ugh !) that we are following broadly.
>
>
> On 6 November 2015 at 11:30:22 AM, Gareth Kennedy (
> notifications@github.com<mailto:notifications@github.com>) wrote:
>
> Another issue with plotting using Points is that it takes the min/max for
> the plot from the min/max of the swarm particles' coordinate data. This is
> a problem if you have a tracer particle in a swarm at (0.5, 0.9) say and
> the box size is (1.0, 1.0). It will make the window size only (0.5, 0.9).
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/underworldcode/underworld2/issues/16#issuecomment-154244361>.
>
>
> ---
> Professor Louis Moresi
> louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
> (w) +61 3 8344 1217<tel://8344%201217>
> (m) +61 4 0333 1413<tel://0333%201413>
> (us) +1 505 349 4425<tel://349%204425>
> www.moresi.info<http://www.moresi.info/>
> www.underworldcode.org
> <http://www.underworldcode.org>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/underworldcode/underworld2/issues/16#issuecomment-154246318>
> .
>



-- 
Owen Kaluza <owen.kaluza@monash.edu>
Senior Visualisation Specialist, eResearch Support
Monash University, Clayton Campus, Rm.318, Building 82
Phone: 03 9902 9809, Mobile: 0410 545 824
