### ISSUE TITLE
swarmVariable save can fail in parallel

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#161]
swarmVariable save is crashing, probably when there are no particles on a processor. There is a notebook / script that should return the error (i ran on 16 processors)

https://github.com/dansand/uw-bits/blob/master/scratch2/par_swarm_save.ipynb

**Comment by julesghub** [comment]
i'll look into it

**Comment by julesghub** [comment]
60de666fcbd034116ec1b801483af0bdf1715891 fixes this up. Closing ticket for now.
