### ISSUE TITLE
LemialeEtAl2008 broken

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#164]
As such, i've demoted it to the 'broken' folder:

3a2e06a799d72cba5a5a9f7f094841c4d9b15007

It doesn't seem to converge anymore.  I'm not sure if something's changed in the way we handle the Picard iterations.

**Comment by RebeccaFarrington** [comment]
Ok, this actually converges just after 178 iterations solving in around 500s v 17s (previously, checked against the master branch).

Another issue with this notebook is the accuracy of the solution compared to the published results.  Some are out by up to 10\degrees.  

I'll have to sort out both these problems.

**Comment by lmoresi** [comment]
We never figured a good way to get the angles automatically- not sure how this is implemented but maybe necessary to first look for sanity of the result

Sent from my iPhone

On 27 Sep. 2016, at 19:30, RebeccaFarrington <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, this actually converges just after 178 iterations solving in around 500s v 17s (previously, checked against the master branch).

Another issue with this notebook is the accuracy of the solution compared to the published results. Some are out by up to 10\degrees.

I'll have to sort out both these problems.

**Comment by jmansour** [comment]
I'm going to close this ticket.  We should do periodic reviews of the broken folder, and this may be resurrected at some point as part of that.
