### ISSUE TITLE
glucifer surface renderer size

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#165]
Something is slightly amiss here:

![image](https://cloud.githubusercontent.com/assets/1439389/18370300/67c6f66c-766f-11e6-9701-2ec6e8dd7470.png)

This is what occurs when running through docker, and also when running mac native.

**Comment by OKaluza** [comment]
Fixed in 2090c9c1a9063ecdd63f70c0f942a9d68cbafe73
