### ISSUE TITLE
Saving Map Functions

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#166]
Hi all, I'm trying to save all the things into .xdmf format and is not difficult for a Field (like pressure, velocity or temperature) but I get in troubles with density or viscosity, because how is it constructed.

(viscosityMapFn = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap )) 

I have tried using:

a=viscosityMapFn.T.getfield(np.float64)
b=a.reshape () 
swarm.add_particles_with_coordinates(b)

But I don't know if this is ok, is there any other method? 

Any help would be useful

thanks!

**Comment by jmansour** [comment]
It'll probably be easiest to create a new swarm variable to record the viscosity into, and then save the swarm variable.  Something like this 

```python
....
visc_var = swarm.add_variable(1, 'float')
visc_var.data[:] = viscosityMapFn.evaluate(swarm)
swarmDat = swarm.save("saved_swarm.h5")
swarmVarDat = visc_var.save("saved_swarmvariable.h5")
swarmVar.xdmf("TESTxdmf", swarmVarDat, "var1", swarmDat, "MrSwarm" )
```

Note that you do not want to add a new swarm variable every time you do this.. only add the variable once or else you'll quickly chew through all your memory as swarm variables cannot be deleted (unless you delete the swarm itself).

**Comment by AngelValverdePerez** [comment]
Yeah, this is a simple way to do it, 
I have changed a little bit:

visc_var = swarm.add_variable(dataType="float", count=2) 
visc_var.data[:] = viscosityMapFn.evaluate(swarm)
swarmDat = swarm.save(outputPath+"saved_swarm.h5")
swarmFilename= outputPath+"/Swarm."+str(step)
swarmVarDat = visc_var.save(swarmFilename"saved_swarmvariable.h5")
visc_var.xdmf(swarmFilename, swarmVarDat, "viscosity", swarmDat, "MrSwarm" )

**Comment by jmansour** [comment]
I notice you have count=2.  Is this a mistake?

**Comment by AngelValverdePerez** [comment]
well, I'm trying different things and also I'm trying to save the material
shapes in the swarm, because I'm using paraview for the visualization

2016-09-13 3:47 GMT+02:00 jmansour <notifications@github.com>:

**Comment by AngelValverdePerez** [comment]
I'm having difficulties in this sense:

I can visualize the pressureField and the velocityField during time (or for
each step if you want) when I saved them in .xdmf format. But I cannot do
it with viscosity the way you just told me. I mean, pressure and velocity
is related to mesh, but viscosity with swarm, and I think this is why I'm
having problems to save swarm's things each step.

2016-09-13 10:17 GMT+02:00 Angel Valverde <angelvalverdeperez@gmail.com>:

**Comment by julesghub** [comment]
What is the exact problem - creating the swarmVariable xdmf, or opening the xdmf in paraview?
You can view the xdmf in a text editor to verify if it's valid.

**Comment by AngelValverdePerez** [comment]
the swarmVariable.xdmf is being created correctly the first step of the
loop (because I can see it with paraview), but then, next steps, the
variable is created, but I think in a wrong way, because when I tried to
visualize in paraview, it has no sense the output (is a mix of particles)
I'm trying to fix this.

Otherwise, imagine that I have 3 layers in a 3D model. Is it possible to
see the layer in the middle if I give the opacity property only to the top
layer?

2016-09-14 4:06 GMT+02:00 julesghub <notifications@github.com>:

**Comment by julesghub** [comment]
"but then, next steps, the variable is created, "
the variable shouldn't be recreated, (swarm.add_variable() ) in the loop.
Just modify the variable's values in the loop.

Here is another way to visualise the middle layer in your model - use glucifer. 
glucifer swarm visualisations can be 'masked' to only display certain particles. See the example  docs/publications/OzBenchEtAl-2008/OzBenchEtAl-2008.ipynb
Specifically look for 'fn_mask'

**Comment by jmansour** [comment]
I'll close this issue.  Reopen as necessary.
