### ISSUE TITLE
valueRange in glucifer doesn't seem to do anything

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#167]
It would be useful if it worked.  
Not sure what the issue is ...

cheers

**Comment by OKaluza** [comment]
Regression was causing by fix to #162

Here is a one liner fix that I suggest we patch into the release a8a9a4a60d30269cc4fcb010c3d0b56a00037da9

A better, long term fix is applied in subsequent commits to development, but it's probably too many changes for this close to a release.

**Comment by RebeccaFarrington** [comment]
Great!  Thanks Owen
