### ISSUE TITLE
volume rendered sometimes blows up

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#168]
The following causes a seg fault (docker dev and also OSX native)

```
import glucifer
import underworld as uw
import underworld.function as fn
mesh = uw.mesh.FeMesh_Cartesian( 
                                 elementRes  = (1,  1,  1), 
                                 minCoord    = (0., 0., 0.), 
                                 maxCoord    = (1., 1., 1.))

solA = fn.analytic.SolDB3d( Beta = 4. )
fig = glucifer.Figure()
fig.append(glucifer.objects.Volume(mesh, solA.fn_bodyforce[2]))
fig.show()
```

The results returned from solA.fn_bodyforce[2] seem sane.. and wrapping with fn.exception.SafeMath suggests the numbers are fine.  

Seems to work as expected for everything else  I tested (fn_viscosity, fn_velocity[0], fn_bodyforce[0], fn_bodyforce[1], etc), so not sure why it doesn't like this.  Not a huge priority or anything, but thought I'd just list it as something to keep an eye.

**Comment by OKaluza** [comment]
Fixed in 86b8ee3fcdc7e33c2c7bf67b6f16abdd68686de2

**Comment by jmansour** [comment]
So some weird edge case where the data simply didn't compress?

**Comment by OKaluza** [comment]
Yep pretty much, so nice find. It's supposed to skip compression if it doesn't reduce the size but instead it skips the whole output. It's been in the code for years and only just turned up, could have caused problems in the past that we didn't catch though.

This and #167 are good candidates to cherry pick for the release if it's not too late, let me know if you want me to commit them to 2.1.0b.

**Comment by jmansour** [comment]
Yeah sounds good man.. fold them in!

**Comment by jmansour** [comment]
I believe this is fixed now.

**Comment by OKaluza** [comment]
Yes it's fixed, so how are we doing this by the way?
Currently I'm not closing issues, leaving it to whomever reports it to confirm the fix... the other way would be to close after checking in a fix and reporter re-open if it still occurs.

**Comment by jmansour** [comment]
Yep, the latter def sounds like the best approach to me.

**Comment by OKaluza** [comment]
Ok, will change my evil ways and join the light side then.

**Comment by jmansour** [comment]
Or perhaps it's the dark side!
