### ISSUE TITLE
How can I run underworld at desired resolution and apple a periodic boundary condition?

### ISSUE THREAD

**Issue by QwZhang** [underworldcode/underworld2#171]
Hi all,
I have two problems when using Underworld (version 1.7.0).
(1) I find it's wired that when I run a 3D subduction model (similar to _Capitanio(2011)_'s configuration) at cell number of 96x64x96 (or 64x32x64, 96x48x96 or 128x64x128, etc.) in x-, y- and z- direction, respectively, at multigrid level of both 4 and 5 using 120 CPU cores on the supercomputer Tianhe-2, Underworld runs **extremely slow**, not even one step in one hour; while I try the same model with higher resolution (e.g., 192x64x192), Underworld runs well and the consumed CPU hours is about 5~10 minutes per step, which looks reasonable. So I have no idea why model with high resolution (e.g., #cell=192x64x192) takes much less CPU hours than the one with 1/8 or 1/4 of total number of cells (e.g., #cell=96x32x96). This is quite strange for a multigrid solver. I simply want to use #cell of 96x32x96, not 192x64x192, to get what I want without having to deal with much more output data and cosuming much more CPU hours.

(2)  No-slip boundary condition is not the best choice in some case when redistibution of materials leads to space problem and thus yields realistic results. So how can I apply a periodic velocity boundary condition on the sidewalls of a box to allow inflow/outflow of the materials? I tried but failed to find an example of this type of bondary condition in the documents of Underworld.

Any instructions or hints will be appreciated.

Best regards,
Qingwen

Reference
[Capitanio, F, et al, 2011, Subduction dynamics and the origin of Andean orogeny and the Bolivian orocline. Nature.](http://www.nature.com/nature/journal/v480/n7375/full/nature10596.html)

**Comment by jmansour** [comment]
Hi Qingwen.  We've recently added a github repo for Underworld1:

https://github.com/underworldcode/underworld1

I've added your issue there:

https://github.com/underworldcode/underworld1/issues/1

**Comment by QwZhang** [comment]
Okey, thank you very much for your reply.
Qw
