### ISSUE TITLE
image_tests.py not working on raijin

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#172]
Can we get this running on a machine without an x server?

Currently it won't run on raijin (& I imagine others).

**Comment by OKaluza** [comment]
dd1162729f19a329a3efc1361262ea0a272d333e

**Comment by RebeccaFarrington** [comment]
Thanks!  
can you commit this to 2.1.0b ?

**Comment by OKaluza** [comment]
No probs, done 73e0a6a4fbfb00b4dfdfa03280f1d4295168983d

**Comment by OKaluza** [comment]
I can't test on raijin as I don't have a build there right now so just ran it locally with my viewer turned off. Can you test and close if it does what it's supposed to?

**Comment by RebeccaFarrington** [comment]
Will do :)

**Comment by RebeccaFarrington** [comment]
all good
