### ISSUE TITLE
q2dpc1 elementType and the SUPG instabilities

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#174]
Instabilities occur with element Type other than q1dq0. We need to test all other elementTypes
@oliverjack38

**Comment by dansand** [comment]
Reducing `advDiff.get_max_dt*` by a factor of 0.5 seems to have fixed this instability in my models.

**Comment by jmansour** [comment]
@julesghub, did we end up updating the get_max_dt routines for supg to account for this?

**Comment by julesghub** [comment]
no update was made.
The internal c layer still sets a counrantFactor of 0.50

I suppose for this just a python level check for the mesh type at
get_max_dt() is required.

**Comment by julesghub** [comment]
A good resource for SUPG with Q2 elements
https://www.researchgate.net/publication/236120370_The_intrinsic_time_for_the_SUPG_formulation_using_quadratic_elements

We do not implement the above intrinsitc time for Q2 elements - our implementation if only based on Q1 elements.

As of change - f90d1fd1c0b8360b6c8ecc61682f92b0d3d2d51b - we have an error msg to occur if one uses Q2 and SUPG. This behaviour can be overridden with _allow_non_q1=True as a param to the uw.system.AdvectionDiffusion()

Long term solution will be the implementation of the SLADE (semi-lagrangian method)
