### ISSUE TITLE
petsc-3.7 compatiblity

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#176]
uw2 is not compatible with petsc-3.7. Need to fix this and re-address the petsc compatibility layer (we are supporting very old version)

**Comment by lmoresi** [comment]
Are any of the supported big machines like pawsey and NCI or the caltech machine ones where we have to use something older than 3.5.x ?   I'd suggest we support two earlier releases plus the current one as a guiding principle.

**Comment by OKaluza** [comment]
+1 Ubuntu 16.10 only has Petsc 3.7 in the repos and I got an itchy upgrade trigger finger again, damn back to building PetSc from source.

**Comment by julesghub** [comment]
@jmansour, was your recent commit to take care of this issue

**Comment by jmansour** [comment]
Yep!  3.7 should be all good now.
