### ISSUE TITLE
memory leaks?

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#179]
There seems to be a memory leak with my model, reaching the maximum allocated memory around 14,000 timesteps. 

I've come across this on raijin, running viscoelastic flexure models.
I'll need to look into this further, with simplified models.

**Comment by jmansour** [comment]
post a similified model when you can!  which branch of uw (or changset if dev)?

**Comment by jmansour** [comment]
I'll close this.  Reopen if needed!
