### ISSUE TITLE
Max value of field / swarm variable, in parallel. 

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#18]
At the moment the evaluate method returns a data array corresponding to the domain of each processor. Is there an easy way to return the max / min value of the global data?

**Comment by jmansour** [comment]
hey dan.  try using the fn.view.min_max function perhaps.  i'll be committing an improved version of it shortly, but for now you can use the min_global/max_global methods to achieve what you want.  

note that a few things will change soon:
*  'min_global' will be renamed to 'min'  (same for corresponding max)
* 'min' will be renamed to 'min_local' (same for corresponding max)
* default will be to return vector results for vector functions (ie, min/max for each component).  currently magnitude values are returned for vector functions, which is inconsistent with the scalar function operation.
* documentation (!)

**Comment by dansand** [comment]
Thanks John:

Example for maximum value of horizontal velocity at surface:

    def max_vx_surf(velfield, mesh):
        vuvelxfn = fn.view.min_max(velfield[0])
        vuvelxfn.evaluate(mesh.specialSets["MaxJ_VertexSet"])
        return vuvelxfn.max_global()
