### ISSUE TITLE
swarm.add_particles_with_coordinates bug

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#181]
Discovered a bug when trying to copy the coordinates of one swarm across to a new swarm. This problem generally arises in parallel and looks to be triggered processors where the original swarm has no particles. Can currently be circumvented (at least in my case) by doing:

```
if oldSwarm.particleCoordinates.data.shape[0] > 0:
        newSwarm.add_particles_with_coordinates(oldSwarm.particleCoordinates.data.copy())
```

**Comment by jmansour** [comment]
Hey Dan.  Can you forward me a simple example?  I can't seem to reproduce the issue.

**Comment by jmansour** [comment]
I'll close this.  Reopen if needed!
