### ISSUE TITLE
SwarmViewer avoid writing particle vertices more than once per time step

### ISSUE THREAD

**Issue by OKaluza** [underworldcode/underworld2#182]
LavaVu supports multiple value arrays per swarm so gLucifer should use this when writing Points objects that use the same swarm if possible

Would require single LavaVu object per swarm plotted, with different value data sets

gLucifer Objects would have to track if they share a swarm and use the appropriate LavaVu object if the swarm is already being visualised

**Comment by julesghub** [comment]
@OKaluza, does this still need doing? I'll close, reopen if required

**Comment by OKaluza** [comment]
@julesghub yeah this is not needed, can be implemented this way directly via lavavu python.
