### ISSUE TITLE
location of fn min / max

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#183]
Currently I'm using a bit of hack to get the location (x,y,z) of a function's min / max. 

Is there a straightforward  / direct way to do this?

**Comment by jmansour** [comment]
No there isn't currently.  The way to do it would be to provide an auxiliary function to the min_max function, and this would be also evaluated (and recorded) at the min_max values.  So to get the location of the max temp, it'd look something like this

```
min_max_temp = fn.misc.min_max( fn=temperatureField, auxilliary=fn.coord() )
ignore = min_max_temp.evaluate(mesh)

max_temp_coord = min_max_temp.aux_out_at_max()
```

I'll put it down as a feature request.

**Comment by julesghub** [comment]
i second this for a new feature request. Happy to look at it if you like @jmansour?

**Comment by jmansour** [comment]
Yep sure! Note that uw.functions.exception.CustomException also uses a similar auxiliary function (fn_print), so you might like to take a closer look at that one.  

http://underworld2.readthedocs.io/en/latest/underworld.function.exception.html#underworld.function.exception.CustomException

**Comment by jmansour** [comment]
Actually, I think we should add two new functions:
1. A function to take the input and process it in some way, and then record the resulting min/max.  For example, if you're processing a velocity field, you may simply want to calculate its magnitude and then check the min/max magnitude.
2. One or more print type functions, which are simply evaluated alongside the min/max for return to the user. For example, fn.coord(), and then perhaps also the actual velocity (not the magnitude), etc.   Though note that this may incur a potentially significant evaluation overhead.

**Comment by lmoresi** [comment]
I only now realised that the fn.view.min_max() is cumulative over multiple calls unless .reset() is invoked. I spent quite a while trying to work out what was going on with values not changing from one evaluation to the next.

This seems like a very odd default behaviour. 

I understand that functions need to have some evaluation call to give the min_max an appropriate scope, but why don't we have methods on the mesh /swarm variables that allow global max and min to be returned ? These are well defined concepts and intuitive, also simple to implement

**Comment by dansand** [comment]
I just had a discussion with Roberta, who also need this functionality. Could we bump this one up the to do list please?

**Comment by jmansour** [comment]
99a02bb387d90ff861d4a2f8855c144c92dfca81

**Comment by dansand** [comment]
Thanks John!

**Comment by jmansour** [comment]
👍

Let me know how you go with it.
