### ISSUE TITLE
Glucifer submodule fetching failed 

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#184]
I tried to compile the dev branch and got that error:

romain@icarus:~/sandbox/underworld2/libUnderworld$ ./configure.py --petsc-dir=/opt/petsc3.6 --hdf5-dir=/opt/hdf5-parallel
error: no such remote ref 9b70c68a39485af6cf177f2ef968df5d7dc9e4fc
Fetched in submodule path 'libUnderworld/gLucifer/Viewer', but it did not contain 9b70c68a39485af6cf177f2ef968df5d7dc9e4fc. Direct fetching of that commit failed.

Romain

**Comment by jmansour** [comment]
I'm going to assume this is no longer an issue and close this.  If it is, please reopen!
