### ISSUE TITLE
glucifer.surface plotting issue when setting min, max coordinates with 2 decimal places.

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#189]
@OKaluza 

I came across what appears to be a glucifer bug after trying to set a y-range on the mesh coordinates using 2 decimal places. I get a blank plot when I plot a field variable using glucifer.objects.Surface. (see jupyter notebook).
I tested both the docker version  '2.1.1b' and the '2.2.0-dev'
![download](https://cloud.githubusercontent.com/assets/3680918/21755665/7d6a1998-d66b-11e6-9851-780367df32bd.png)
`
import underworld as uw
import glucifer

# y-range with one decimal place min, max (works)
minX = -1.0
maxX = 1.0
minY = -1.0
maxY = 0.0

# y-range with one decimal place min, max (does not work)
minX = -1.0
maxX = 1.0
minY = -0.85 #<--
maxY = 0.15 #<--

nx = 32
ny = 8

elementType="Q1/dQ0"

mesh = uw.mesh.FeMesh_Cartesian(elementType = (elementType),
                                elementRes  = (nx, ny),
                                minCoord    = (minX, minY),
                                maxCoord    = (maxX, maxY),
                                periodic    = (False, False))

figMesh = glucifer.Figure( figsize=(1200,400))
figMesh.append(glucifer.objects.Mesh(mesh))
figMesh.show()

varField    = uw.mesh.MeshVariable( mesh=mesh, nodeDofCount=1 )
varField.data[:] = 5.

figMesh = glucifer.Figure( figsize=(1200,400))
figMesh.append(glucifer.objects.Surface(mesh, varField))
figMesh.show()
`

**Comment by OKaluza** [comment]
Thanks for the report, should be fixed now
