### ISSUE TITLE
raise RuntimeError("Error generating swig bindings.")

### ISSUE THREAD

**Issue by linkpond** [underworldcode/underworld2#190]
hello ~

../build/include/Underworld/Function/FunctionIO.hpp:46: Warning 512: Overloaded method FunctionIO::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:45: Warning 512: using non-const method FunctionIO::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< bool,char >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< bool,char >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< bool,char >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< bool,char >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< bool,char >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< bool,char >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< bool,char >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< bool,char >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< char,char >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< char,char >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< char,char >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< char,char >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< char,char >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< char,char >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< char,char >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< char,char >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< short,short >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< short,short >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< short,short >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< short,short >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< short,short >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< short,short >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< short,short >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< short,short >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< unsigned int,unsigned int >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< unsigned int,unsigned int >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< unsigned int,unsigned int >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< unsigned int,unsigned int >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< int,int >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< int,int >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< int,int >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< int,int >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< int,int >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< int,int >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< int,int >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< int,int >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< float,float >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< float,float >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< float,float >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< float,float >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< float,float >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< float,float >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< float,float >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< float,float >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< double,double >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< double,double >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< double,double >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< double,double >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< double,double >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< double,double >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< double,double >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< double,double >::dataRaw() instead.

Traceback (most recent call last):
  File "./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.

I use swig-3.0.10 but i got this error   help me  please~
(I use python-2.7.11 and icc (ICC) 15.0.3 20150407 and RHEL 6.5)

**Comment by jmansour** [comment]
Can you runs "./scons.py" (from the libUnderworld directory) and confirm that there are no errors when you do this?

**Comment by linkpond** [comment]
I try to run /root/underworld2/libUnderworld/scon.py  and I got following error

In file included from Underworld/Function/src/Arithmetic.cpp(12):
Underworld/Function/src/FunctionIO.hpp(16): catastrophic error: cannot open source file "typeindex"
  #include <typeindex>
                      ^

compilation aborted for Underworld/Function/src/Arithmetic.cpp (code 4)
scons: *** [build/Underworld/Function/src/Arithmetic.os] Error 4
scons: building terminated because of errors.

________________________________________
보낸 사람: jmansour [notifications@github.com]
보낸 날짜: 2017년 1월 12일 목요일 오전 11:28
받는 사람: underworldcode/underworld2
참조: 이 승연; Author
제목: Re: [underworldcode/underworld2] raise RuntimeError("Error generating swig bindings.") (#190)

Can you runs "./scons.py" (from the libUnderworld directory) and confirm that there are no errors when you do this?

**Comment by jmansour** [comment]
Ok, this is an issue with icc.  Can you use gcc on this machine?   Or if a more recent version of icc is available, it *might* fix this issue.  

Which machine are you trying to compile on?

**Comment by linkpond** [comment]
My machine is Red Hat Enterprise Linux Server release 6.5 (Santiago)
I use icc (ICC) 15.0.3 20150407 and mpicc2-1.4 (ICC 15.0.3 20150407 compiled) and pythone 2.7.11

**Comment by jmansour** [comment]
Is this a personal machine, or a HPC type machine?  If it's personal, I'd suggest you use the docker version. 

Otherwise, is gcc available?  If so, that would most probably be the path of least resistance.   If not, you will at least need the gcc C++11 headers installed, and then we can try compiling with icc but using the gcc headers.

**Comment by linkpond** [comment]
I try to install HPC type.
when I install underworld2 by gcc in RHEL 6.5
What is the most appropriate gcc version?

**Comment by jmansour** [comment]
Any recent version of gcc should be fine.

**Comment by linkpond** [comment]
now, I trying to install underworld2 by gcc-4.8.5
Is it okay to use gcc-4.8.5?

**Comment by jmansour** [comment]
Yes, that should be fine.

**Comment by linkpond** [comment]
another question!!
is it okay to use python 2.6.6?
if not, what is the most appropriate python version?

**Comment by jmansour** [comment]
Hmm.. I'm not exactly sure about 2.6.6.  2.7 is recommended.

**Comment by linkpond** [comment]
Search paths:
   ./
   ./swig_lib/python/
   /APP/swig-3.0.10/share/swig/3.0.10/python/
   ./swig_lib/
   /APP/swig-3.0.10/share/swig/3.0.10/
Preprocessing...
Starting language-specific parse...
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
ln: creating symbolic link `./lavavu.py': File exists
ln: creating symbolic link `./control.py': File exists
scons: Reading SConscript files ...
Copy("build/gLucifer/Viewer/graphics.cfg", "graphics.cfg")
scons: done reading SConscript files.
scons: Building targets ...
scons: `build' is up to date.
scons: done building targets.



I seem to have installed underworld2 successfully. hahahahaha
thank you so much!!!!

**Comment by jmansour** [comment]
Ok, so far so good!  You may still run into difficulties at runtime, so run
the tests (launch 'test_basic.sh') to make sure everything is working.
Remember to set your PYTHONPATH to include your underworld directory.

**Comment by jmansour** [comment]
I'll close this issue, but feel free to reopen if you have further difficulties.

**Comment by linkpond** [comment]
yes thank u haha
