### ISSUE TITLE
enhance the uw.system.swarmadvector to take a function

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#194]
Currently the SwarmAdvector requires a MeshVariable as input.
This limits its capabilities in functionality.

The idea is to allow the SwarmAdvector to take a function instead that specifies the advection velocity.
This would be more robust and useful. 

Example. Advecting a swarm in only one direction right now is ugly because we have to make duplicate velocity field and modify its values. A nicer solution would be to use a function like
newVelFn = velocityField[1] * (0.0,1.0,0.0) 

and supply newVelFn to the SwarmAdvector(velocityField=newVelFn, swarm=swarm, order=2)

**Comment by jmansour** [comment]
Won't be done for UW2, and isn't relevant for UW3.
