### ISSUE TITLE
Obtain the passive tracer position in  different time step

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#196]
Ok, About the  passive tracers can disappear,I think the flow out is main reason of it. I set the particleEscape is True . I close it now in underwolrd2. 
But I still got a wrong message in mainloop. And the code in jupyter notebook run really slower with 3d mesh(with low res, very fast in underwrold1, may be something wrong with my setting?).
Any way the code show below may help me to find the problem. It should have problem which I have not  found it.

## The wrong message 

```
step =      0; time = 0.000e+00;
step =      1; time = 6.080e-02;

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-2cff154aa4b6> in <module>()
     20 
     21     # finished timestep, update all
---> 22     time, step = update()

<ipython-input-19-da5287398617> in update()
      2     # get timestep and advect particles
      3     dt = advector.get_max_dt()
----> 4     advector.integrate(dt, update_owners=True)
      5     advector4.integrate(dt, update_owners=True)
      6 

/root/build/underworld2dev/underworld/systems/_timeintegration.pyc in integrate(self, dt, update_owners)
    150         """
    151         libUnderworld.StgFEM._FeVariable_SyncShadowValues( self._integrand.velocityField )
--> 152         super(SwarmAdvector,self).integrate(dt)
    153         # this check isn't necessary, but good. possibly get rid.
    154         libUnderworld.StgDomain.Swarm_CheckCoordsAreFinite( self._integrand.swarm );

/root/build/underworld2dev/underworld/systems/_timeintegration.pyc in integrate(self, dt)
     48     def integrate(self,dt):
     49         self.dt = dt
---> 50         libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
     51 
     52     def get_max_dt(self):

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "A03K9R2B__integrand" of type SwarmAdvector: When trying to find time deriv for item 16 in step 1, *failed*.

```

[Test3d.ipynb.tar.gz](https://github.com/underworldcode/underworld2/files/785587/Test3d.ipynb.tar.gz)

# ------------------------------
**I tried to delete the RemovalRoutine,  SplittingRoutine and  EscapedRoutine	 in underworld1 input scripts. But the number of tracer still change with time.**

**Comment by jmansour** [comment]
Your outflow boundary conditions effectively sends particles out of the domain, and therefore you must enable the 'particleEscape' parameter or you will encounter the message above.  Note that this error message occurs because you are trying to evaluate the velocity field for a particle outside the mesh, which is not possible.   

Also, looking at your model, I can see that you have setup outflow conditions, but you have not provided some measure to compensate for the mass flowing out, so therefore you are violating mass conservation and your model is inconsistent.  This is most probably why your models are running much slower than UW1.  For identical configurations, UW1/UW2 simulation should have very similar run times.   

To allow for mass outflow/inflow, there are a few option.  Often people will include a compressible layer to accommodate, or you can provide a BC which explicitly compensates the in/out flow.  Or, you can leave some part of the boundary _open_ (ie, the zero stress neumann condition which is obtained by not setting any bc).

**Comment by tyszwh** [comment]
Yes, It's right. It means I must set 'particleEscape' as true when I give a outflow boundary. And I change the boundary condition. The code running velocity normally. But I still got a wrong message. I did not understand it very well.
I change the boundary as (iWalls, base, kWalls), If I dont set pop_control.repopulate(), The code stoped after 2 timestep without any mention in notebook.
The terminal show like this.

```
Error running Underworld - Signal 11 'SIGSEGV' (Segmentation Fault).
This is probably caused by an illegal access of memory.
We recommend running the code in a debugger to work out where the problem is (e.g. 'gdb')
and also to contact the developers.
```
**If I set the  pop_control.repopulate(), The code also stoped but with a wrong message in jupyter notebook.**

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Something went wrong in _PCDVC_Calculate3D: Problem has an under resolved cell (Cell Id = 57).
You may need to check your initial particle layout configuration. A per cell layout might give better results than a global layout, especially where you have a deformed mesh. Also, if particles are able to escape the domain, you can enable aggressive population control by setting the 'particleEscape' swarm constructor parameter.

=====================================================================================

Beside How many material flow in domain  to accommodate? I did not understand well what different bettweem compressible layer to accommodate, explicitly compensates the in/out flow or  leave some part of the boundary open
