### ISSUE TITLE
stampede

### ISSUE THREAD

**Issue by huilin0302** [underworldcode/underworld2#197]
Hi,

I'm trying to run underworld2 on stampepde.  I followed the install guides for xsede stampede.  The only change is python/2.7.12,  because python/2.7.9 seems need to load intel/13.   

As I run a model,  I got the following error.  Do you have any idea how to solve this?  Thanks!

TACC: Starting up job 8295603
TACC: Setting up parallel environment for MVAPICH2+mpispawn.
TACC: Starting parallel tasks...
Traceback (most recent call last):
  File "./user_data/Delamination_v3.py", line 9, in <module>
    import underworld as uw
  File "/home1/04512/huilin/underworld/underworld2/underworld/__init__.py", line 50, in <module>
    import libUnderworld
  File "/home1/04512/huilin/underworld/underworld2/libUnderworld/__init__.py", line 1, in <module>
    from libUnderworldPy import *
  File "/home1/04512/huilin/underworld/underworld2/libUnderworld/libUnderworldPy/__init__.py", line 2, in <module>
    import StGermain
  File "/home1/04512/huilin/underworld/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 32, in <module>
    _StGermain = swig_import_helper()
  File "/home1/04512/huilin/underworld/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 28, in swig_import_helper
    _mod = imp.load_module('_StGermain', fp, pathname, description)
ImportError: libirc.so: cannot open shared object file: No such file or directory

**Comment by jmansour** [comment]
I notice in the build instructions, that we pass in the following numpy
path:

 --numpy-dir=/opt/apps/intel15/python/*2.7.9*
/lib/python2.7/site-packages/numpy/core

perhaps you should try

 --numpy-dir=/opt/apps/intel15/python/*2.7.12*
/lib/python2.7/site-packages/numpy/core

but I'm only guess here.

So I take it that running the original instructions exactly didn't work?

**Comment by huilin0302** [comment]
Thanks for the email!   I used “--numpy-dir=/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core”.  And the code seem already built successfully on machine.  The error I got is when I run models.

**Comment by jmansour** [comment]
I assume you have loaded the required modules?  In your case python/2.7.12
instead of python/2.7.9.

If you have, is it possible to force the load of the required intel/15
module?  Load petsc/2.7.9, then reload intel/15.0.2.

**Comment by huilin0302** [comment]
Thanks John!  yes, after loading all the modules. The model is working now.

**Comment by jmansour** [comment]
Excellent!  

Can you please share the modified build & run instructions?  I no longer have access to stampede for testing myself, and would like to add some notes to the build recipe.

**Comment by huilin0302** [comment]
Sure!  The following is my script for install and run underworld2 on stampede.

###############################################################
#!/bin/sh
# ensure we bail on errors
set -e

# modules
module purge
module load intel/15.0.2
module load mvapich2/2.1
module load xalt/0.6
module load TACC
module load petsc/3.6
module load phdf5
module load swig
module load python/2.7.12
export HDF5_DIR=$TACC_HDF5_DIR

# underworld
git clone https://github.com/underworldcode/underworld2.git
cd underworld2/libUnderworld
git checkout $1
./configure.py --with-debugging=0 --python-dir=$TACC_PYTHON_DIR --cxxflags='-std=c++11\ -cxxlib=/opt/apps/gcc/4.9.1/' --numpy-dir=/opt/apps/intel15/python/2.7.12/lib/python2.7/site-packages/numpy-1.11.1-py2.7-linux-x86_64.egg/numpy/core --with-graphics=0
./compile.py


#################################################################
# load modules before run models

module load mvapich2/2.1
module load xalt/0.6
module load TACC
module load petsc/3.6
module load phdf5
module load swig
export PYTHONPATH=/home1/04512/huilin/underworld/underworld2:\$PYTHONPATH
export LD_LIBRARY_PATH=/opt/apps/gcc/4.9.1/lib64:/opt/apps/gcc/4.9.1/lib:\$LD_LIBRARY_PATH
module load intel/15.0.2
module load python/2.7.12

#################################################################
