### ISSUE TITLE
mesh.deform_mesh() potential issue...

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#199]
I came across a bug while using the deform_mesh() option to advect my mesh.

This is related to the way we can slice numpy array.

so when deforming a mesh such as with:

```python
import underworld as uw
import glucifer

mesh = uw.mesh.FeMesh_Cartesian(elementType='Q1/DQ0', elementRes=(5,5), minCoord=(0.,0.), maxCoord=(1.,1.) )

top    = mesh.specialSets["MaxJ_VertexSet"]

# This works
with mesh.deform_mesh():
     mesh.data[list(top),1] += 2.0

mesh.reset()
# this should be equivalent but will not deform the mesh...
with mesh.deform_mesh():
     mesh.data[list(top)][:,1] += 2.0
```

The 2 assignments are not equivalent, the first one will update the mesh, the second won't do anything...

I don't know of any numpy rule going toward one or the other way....so I am assuming that the two ways are valid...

Note that here I use the call to list() which converts the special set to a python list.

doing:
```python
# this is not equivalent and will not deform the mesh...
with mesh.deform_mesh():
     mesh.data[somenodeindex][:,1] += 2.0
```
should throw an error...

**Comment by jmansour** [comment]
I think the difference is that the first call you actually return a slice of the existing numpy array, whereas in the second you return a view which slices the original array:

```python
mesh.data[list(top),1].base is None
```
Returns `True`

```python
mesh.data[list(top)][:,1].base is None
````
Returns `False`

So in the second case, you are writing changes to a temporary view. 

Also, note that you can simply access the underlying numpy data on your IndexSet objects:

```python
with mesh.deform_mesh():
     mesh.data[top.data,1] += 2.0
```

**Comment by rbeucher** [comment]
Yes, good point.

That is indeed what's happening here... I think we are dealing with some subtleties   of numpy arrays.

I found that doc in the scipy cookbook:

https://scipy-cookbook.readthedocs.io/items/ViewsVsCopies.html

and thanks for showing that .base attributes. Very useful.

**Comment by lmoresi** [comment]
I have become accustomed to using this syntax.

We should make sure that we are being consistent in the examples and also choosing whichever method is least likely to cause confusion if generalised.

John, you need to get back to your duties as baby cushion and stop answering questions here !

L


On 7 March 2017 at 5:08:40 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

with mesh.deform_mesh():
     mesh.data[top.data,1] += 2.0

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by rbeucher** [comment]
Yes, me too but for some reasons I used the other syntax and it gave me some hard time figuring out what was going on. 

And yes John you have better things to do!!!

**Comment by jmansour** [comment]
Ha.. no rest for the wicked!  Back into it already guys. 

Also, I think I messed up the numpy terminology... the first (working) version was a numpy **view**, whereas the second (non-working) version was a **copy**.
