### ISSUE TITLE
UW uses float32 objects with Numpy

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#2]
It looks like UW returns float32 objects from functions:
```python
visc.data[:] = visc_Fn.evaluate(swarm)

print visc.data.dtype  # prints: float32
print np.finfo(np.float32).max  # prints: 3.40282e+38
```
This means that if a function returns a number higher than ~3.4e38, it becomes inf in the numpy array.

This is potentially problematic, because the calculation of the power-law equation definitely would output numbers bigger than this. The idea would then be to apply a brittle-law (or peierls creep law) over the top of this big number to bring it back to reality.

Also, LavaVu cannot handle infs and fails unceremoniously:
```
SQL prepare error: (insert into geometry (object_id, timestep, rank, idx, type, data_type, size, count, width, minimum, maximum, dim_factor, units, minX, minY, minZ, maxX, maxY, maxZ, labels, data) values (1, 0, 0, 0, 1, 3, 1, 84120, 0, 1.86972e+19, inf, 1, '', 0, 0, 0, 0, 0, 0, ?, ?)) no such column: inf
```

I know scaling would fix this - but so would float64..?

**Comment by jmansour** [comment]
Hmm.. not sure Luke.  You're 'visc' object is a swarm variable right?  Have you created it using:

```
swarm.add_variable( dataType="float", count=1 )
````
or

```
swarm.add_variable( dataType="double", count=1 )
````

Note that numpy will cast the results from the function evaluation, so even if the function evaluates to 64 bit doubles, it will be downcast to 32 bit doubles if the target array is 32 bit.

**Comment by OlympusMonds** [comment]
Ah of course! Sorry about that, you are right.

**Comment by jmansour** [comment]
no probs!
