### ISSUE TITLE
Fail to configure due to h5py error "undefined symbol: H5Pget_dxpl_mpio".

### ISSUE THREAD

**Issue by wkillers** [underworldcode/underworld2#202]
I got the underworld using git clone from the development branch, and want to install it on a HPC cluster. When I do the configuring some error occurs about the h5py:

**[wangym@ln03 libUnderworld]$ python configure.py --petsc-dir=/home/wangym/software/petsc-3.7.5 --hdf5-dir=/home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel**
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... 
Attempting to build private h5py version at /home/wangym/underworld/underworld2/h5py using cc=h5pcc. This may take a few minutes.
python setup.py configure -m --hdf5 /home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel

Attempting to build private h5py version at /home/wangym/underworld/underworld2/h5py using cc=mpicc. This may take a few minutes.
python setup.py configure -m --hdf5 /home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel
no

****  ERROR ****
Failed to locate required package H5py.
Details in 'config.log'

***************************************
If you require help, send the files:
        config.log
        config.cfg (if it exists)
to: development@underworldproject.org
************************************

**Then I check the config.log file and found something like this:**

CONFIGURE H5PY
Checking if h5py in built in uw2 already, or provided by system (in that order of preference).
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_conv.c:7888)
  File "h5py/_objects.pxd", line 12, in init h5py.h5r (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/h5r.c:3575)
  File "h5py/_objects.pyx", line 1, in init h5py._objects (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_objects.c:8042)
ImportError: /home/wangym/underworld/underworld2/h5py/defs.so: undefined symbol: H5Pget_dxpl_mpio
h5py import failed.

No functional h5py found, lets try build our own using h5pcc.
h5py build completed successfully.
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_conv.c:7888)
  File "h5py/_objects.pxd", line 12, in init h5py.h5r (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/h5r.c:3575)
  File "h5py/_objects.pyx", line 1, in init h5py._objects (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_objects.c:8042)
ImportError: /home/wangym/underworld/underworld2/h5py/defs.so: undefined symbol: H5Pget_dxpl_mpio
h5py import failed.

Still no functional h5py found, lets try build our own using uw2 CC.
h5py build completed successfully.
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_conv.c:7888)
  File "h5py/_objects.pxd", line 12, in init h5py.h5r (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/h5r.c:3575)
  File "h5py/_objects.pyx", line 1, in init h5py._objects (/home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/_objects.c:8042)
ImportError: /home/wangym/underworld/underworld2/h5py/defs.so: undefined symbol: H5Pget_dxpl_mpio
h5py import failed.

I don't know how to solve this problem and anyone can help?
Thanks.

**Comment by julesghub** [comment]
Hi Yongming,

These errors are most usually due to the hdf5 installation not being quite
right.
Either:
1) hdf5 may not be parallel enabled or
2) hdf5 and mpi4py are built with two different mpi libraries. Parallel
h5py is dependent on hdf5 & mpi4py. An inconsistency in the versions of mpi
that the dependency packages use will cause this kind of compilation issues.

Hope this helps, let me know?

cheers,
Julian

**Comment by wkillers** [comment]
@julesghub 

I have tried to build hdf5 and mpi4py with the same mpi, and the original error disappeared, but a new error comes up in the config.log like this:

CONFIGURE H5PY
Checking if h5py in built in uw2 already, or provided by system (in that order of preference).
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: /home/wangym/underworld/underworld2/h5py/_errors.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
h5py import failed.

No functional h5py found, lets try build our own using h5pcc.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext
Still no functional h5py found, lets try build our own using uw2 CC.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext

**Comment by wkillers** [comment]
Hi Julian,

**I have tried to rebuild hdf5 and mpi4py with the same mpi and the original error disappeared, but another error comes up in config.log:**

CONFIGURE H5PY
Checking if h5py in built in uw2 already, or provided by system (in that order of preference).
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named h5py
h5py import failed.

No functional h5py found, lets try build our own using h5pcc.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext
Still no functional h5py found, lets try build our own using uw2 CC.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext

**Then I check the h5py_build.err file:**
Autodetection skipped [/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/_ctypes.so: undefined symbol: __intel_sse2_strcpy]
Autodetection skipped [/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/_ctypes.so: undefined symbol: __intel_sse2_strcpy]
In file included from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/api_compat.h:26,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/defs.c:481:
/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/api_compat.h:26,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/defs.c:481:
/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
/usr/bin/ld: /home/wangym/software/hdf5-1.8.13-parallel/lib/libhdf5.a(H5.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/wangym/software/hdf5-1.8.13-parallel/lib/libhdf5.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by jmansour** [comment]
Unfortunately h5py is currently the most fragile part of our build system.  @julesghub, we might get better results if we check in a version of h5py in our codebase, included cython generated bindings.   Not sure.

Anyhow, in the first instance, it appears that you have successfully built h5py, but then encountered issues when trying to import h5py. It looks like it's possibly loading the non-parallel hdf5 at runtime possibly.  What does 
```bash
ldd /home/wangym/underworld/underworld2/h5py/defs.so
```
tell you?  

In the second instance, you aren't even getting successful compilation.  Hard to give you any useful help with that as many things could be at play.  To be sure, I will suggest that you remove the libUnderworld/h5py_ext/ directory before each configuration.. I suspect that sometimes stale compilation states can conflict with future attempts.

**Comment by wkillers** [comment]
@jmansour 

Acturally this is nothing in '/home/wangym/underworld/underworld2/h5py' directory after I run the configuring, so nothing happened when I type ldd /home/wangym/underworld/underworld2/h5py/defs.so

**Comment by wkillers** [comment]
I am not sure if there is something wrong with my hdf5 installation, so I change to use another hdf5 that provide by the HPC cluster which is suposed to be installed correctly, and run:
`python configure.py --petsc-dir=/home/wangym/software/petsc-3.7.5/ --hdf5-dir=/home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel/`

**the configuration still not work, and the config.log file report:**
CONFIGURE H5PY
Checking if h5py in built in uw2 already, or provided by system (in that order of preference).
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: /home/wangym/underworld/underworld2/h5py/_errors.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
h5py import failed.

No functional h5py found, lets try build our own using h5pcc.
Failed building h5py :(
Please check 'h5py_build.out' and 'h5py_build.err' in libUnderworld/h5py_ext
Still no functional h5py found, lets try build our own using uw2 CC.
h5py build completed successfully.
Attempting to import h5py...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/wangym/underworld/underworld2/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: /home/wangym/underworld/underworld2/h5py/_errors.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
h5py import failed.
**The h5py_build.err file reports:**
Autodetection skipped [/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/_ctypes.so: undefined symbol: __intel_sse2_strcpy]
Autodetection skipped [/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/_ctypes.so: undefined symbol: __intel_sse2_strcpy]
In file included from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/api_compat.h:26,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/defs.c:481:
/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
.......
In file included from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/api_compat.h:26,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/h5ac.c:481:
/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:26:0,
                 from /home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/api_compat.h:26,
                 from /home/wangym/underworld/underworld2/libUnderworld/h5py_ext/h5py/h5ac.c:481:
/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1629:1: warning: ‘_import_array’ defined but not used [-Wunused-function]
 _import_array(void)
 ^
Autodetection skipped [/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/_ctypes.so: undefined symbol: __intel_sse2_strcpy]

**For this time, I got many files in the '/home/wangym/underworld/underworld2/h5py/' directory, and the ldd command shows below results:**
```
[wangym@ln03 libUnderworld]$ ldd /home/wangym/underworld/underworld2/h5py/defs.so 
        linux-vdso.so.1 =>  (0x00007ffcccbeb000)
        libhdf5.so.8 => /home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel/lib/libhdf5.so.8 (0x00002b888a5b8000)
        libhdf5_hl.so.8 => /home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel/lib/libhdf5_hl.so.8 (0x00002b888ab8b000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b888adc0000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b888afdc000)
        libz.so.1 => /lib64/libz.so.1 (0x00002b888b39d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002b888b5b3000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b888b7b7000)
        libmpifort.so.12 => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpifort.so.12 (0x00002b888bab9000)
        libmpi.so.12 => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib/libmpi.so.12 (0x00002b888be62000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b888cb79000)
        libimf.so => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libimf.so (0x00002b888cd81000)
        libsvml.so => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libsvml.so (0x00002b888d26d000)
        libirng.so => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libirng.so (0x00002b888e178000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002b888e4ed000)
        libintlc.so.5 => /home/SystemSoftware/intel2017/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00002b888e703000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b888a162000)
```

**Comment by jmansour** [comment]
Ok, I think we're getting close to success.  It appears now to be a mismatch between the python headers used to compile and the python library used at runtime.  For your configuration, try setting  `--python-dir=` to point to your python directory (I'm guessing `/home/wangym/software/Python-2.7.12/`)

**Comment by wkillers** [comment]
@jmansour 
I have tried what you suggested about setting the --python-dir, but I still can not pass the configuring with some errors below:
```
[wangym@ln01 libUnderworld]$ python configure.py --petsc-dir=/home/wangym/software/petsc-3.7.5/ --hdf5-dir=/home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel/ --python-dir=/home/wangym/software/Python-2.7.12/
Submodule path 'libUnderworld/h5py_ext': checked out '1a0ac18b6e97a7df0cbbd541590a172a1eefdbdb'
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
IndexError: list index out of range:
  File "/home/wangym/underworld/underworld2/libUnderworld/SConfigure", line 194:
    env.ConfigurePackage(packages.Numpy, required=True)
  File "/home/wangym/underworld/underworld2/libUnderworld/config/scons/scons-local-1.2.0/SCons/Environment.py", line 217:
    return apply(self.method, nargs, kwargs)
  File "/home/wangym/underworld/underworld2/libUnderworld/config/config.py", line 29:
    pkg(**kw)
  File "/home/wangym/underworld/underworld2/libUnderworld/config/Package.py", line 148:
    for env in self.gen_envs(loc):
  File "/home/wangym/underworld/underworld2/libUnderworld/config/packages/Numpy.py", line 32:
    env.AppendUnique(CPPPATH=[self.location[1][0]])
Checking for package Numpy... [wangym@ln01 libUnderworld]$  
```
**Since there are too mant lines in config.log file, so I uploaded it in the attachment.
**
**It looks like in this time there is something wrong when configuring the numpy. To check whether the numpy is installed right, I tried the following command and it seems no problem:**
```
[wangym@ln01 libUnderworld]$ python
Python 2.7.12 (default, Mar  3 2017, 14:15:44) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> 
```
[config.log.txt](https://github.com/underworldcode/underworld2/files/837084/config.log.txt)

**Comment by jmansour** [comment]
Ok, so we have succeeded with HDF5, but now numpy is failing.  Perhaps try pointing to it by adding something like the following to your configure command: `--numpy-dir=usr/local/lib/python2.7/site-packages/numpy/core`

**Comment by wkillers** [comment]
Hi, I have tried by adding the numpy directory in my configure command but it still not works:
```
[wangym@ln01 libUnderworld]$ python configure.py --petsc-dir=/home/wangym/software/petsc-3.7.5/ --hdf5-dir=/home/PublicSoftware/intel2017-software/hdf5-1.8.13-parallel/ --python-dir=/home/wangym/software/Python-2.7.12/ --numpy-dir=/home/wangym/software/Python-2.7.12/lib/python2.7/site-packages/numpy/core/ 
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... no

****  ERROR ****
Failed to locate required package Numpy.
Details in 'config.log'


***************************************
If you require help, send the files:
        config.log
        config.cfg (if it exists)
to: development@underworldproject.org
************************************
```
[config_log.txt](https://github.com/underworldcode/underworld2/files/843185/config_log.txt)
**Something in the config.log file reports:**
```
/home/wangym/software/Python-2.7.12/lib/libpython2.7.a(posixmodule.o): In function `posix_forkpty':
/home/wangym/software/Python-2.7.12/./Modules/posixmodule.c:4012: undefined reference to `forkpty'
/home/wangym/software/Python-2.7.12/lib/libpython2.7.a(posixmodule.o): In function `posix_openpty':
/home/wangym/software/Python-2.7.12/./Modules/posixmodule.c:3952: undefined reference to `openpty'
collect2: error: ld returned 1 exit status
scons: Configure: no
```
I am not sure if this is what cause the configuring of numpy failed.

**Comment by jmansour** [comment]
Not really sure what's causing this, but google suggests other people have
had success by adding `-lutil`, so trying adding `--cflags='-lutil'` to
your config line.

**Comment by wkillers** [comment]
Still not work, anyway, thanks for the help. I will try to install underworld on other machines that can connect to the network which is much easier to install.
