### ISSUE TITLE
non-global swarm crash

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#204]
The non-global swarm functionality does not seem to like being passed a swarm variable:

Example here: https://github.com/dansand/newSlab/blob/master/Convection_non-global.ipynb

```
#This works!
densityFn = fn.branching.conditional( ((swarm.fn_particle_found(), Ra*temperatureField), 
                                           (True,                      Ra*temperatureField))  )
    
#This crashes with a seg fault!
densityFn = fn.branching.conditional( ((swarm.fn_particle_found(), Ra*tempProxyVar), 
                                           (True,                      Ra*temperatureField))  )
    
```

**Comment by jmansour** [comment]
This is actually an initialisation issue.  So, prior to any _heavy_ function evaluation, and initial test evaluation is performed, mainly to check the output the provided function will return.  In the case of the conditionals, **all** consequent functions are evaluated to ensure they return identical data (size & type). 

In your case, the first consequent function cannot be evaluated because there are no particles there, so this logic breaks down..  I'll have to have a think about how to resolve this.

**Comment by dansand** [comment]
`RuntimeErrorTraceback (most recent call last)
<ipython-input-18-6ab54204ea70> in <module>()
      3                             conditions    = velBC,
      4                             fn_viscosity  = viscosityFn,
----> 5                             fn_bodyforce  = buoyancyFn )
      6 
      7 # get the default stokes equation solver

/root/underworld2/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
     96         # create the instance as normal.  this will invoke the class's
     97         # __init__'s as expected.
---> 98         self = super(_SetupClass, cls).__call__(*args, **kwargs)
     99 
    100         # this steps through the MRO in ascending order (so that child

/root/underworld2/underworld/systems/_stokes.pyc in __init__(self, velocityField, pressureField, fn_viscosity, fn_bodyforce, fn_one_on_lambda, fn_lambda, fn_source, voronoi_swarm, conditions, _removeBCs, _fn_viscosity2, _fn_director, _fn_stresshistory, **kwargs)
    252         self._forceVecTerm   = sle.VectorAssemblyTerm_NA__Fn(   integrationSwarm=intswarm,
    253                                                                 assembledObject=self._fvector,
--> 254                                                                 fn=_fn_bodyforce)
    255 
    256         if fn_source:

/root/underworld2/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
    108                 _setup = _setup.__get__(self, cls)
    109             if callable(_setup):
--> 110                 _setup()
    111 
    112         return self

/root/underworld2/underworld/systems/sle/_assemblyterm.pyc in _setup(self)
     53         # lets setup fn tings.. note that this uses the 'property' above
     54         if self._set_fn_function:
---> 55             self.fn = self._fn
     56 
     57 class VectorAssemblyTerm(AssemblyTerm):

/root/underworld2/underworld/systems/sle/_assemblyterm.pyc in fn(self, value)
     48             raise ValueError( "Provided 'fn' must be of, or convertible to, 'Function' class." )
     49         self._fn = _fn
---> 50         self._set_fn_function( self._cself, self._fn._fncself )
     51 
     52     def _setup(self):

RuntimeError: Error occurred while trying to evaluate swarm variable. This can occur when there are no particles found in a given element. You may wish to add population control mechanisms. Please contact developers if this does not appear to be the issue.`

**Comment by dansand** [comment]
Hi John. The workaround you suggested helps, but we hit another problem. The error message is posed above. Is there another quick fix for this one?

**Comment by dansand** [comment]
Deleted some comments here - I realized there was a problem in the way I implemented your suggested workaround. Will try again.

**Comment by jmansour** [comment]
I've pushed a fix Dan.  Can you give it a shot and report back?

**Comment by jmansour** [comment]
Will close for now.  Reopen if required.
