### ISSUE TITLE
fn_source setter

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#205]
The following are not equivalent:

``` python
stokes._cforceVecTerm.fn = velocitySourceField  # works
stokes.fn_source = velocitySourceField                 # doesn't
```

This is a case where the @...setter function is conditional on this term being supplied and does not appear to be implemented correctly.

@julesghub , you may also want to check if the one_on_lambda term is also messed up since this has identical code in stokes.py.

**Comment by jmansour** [comment]
This does not appear to be an issue any more. `VolumetricSourceTerm.ipynb` works as expected.   That said `_stokes.py` could do with some tidying in how it handles these terms.
