### ISSUE TITLE
paraview/xdmf tensor6 element ordering different to uw2

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#206]
Raghu:

>The 6 components in symmetric tensor output in uw2 is in the order a00,a11,a22,a01,a02,a12 if I am not wrong.
>
>https://cmake.org/pipermail/paraview/2010-October/019066.html
>
>In the light of this, and the xdmf (written by uw2) not explicitly mentioning the order, I think the order in which the tensor is written to disk for visualization in paraview is wrong.
>
>What am saying is a default tensor6 will expect the input in the order a00,a01,a02,a11,a12,a22 if the order is not mentioned while writing xdmf file.
>
>There is a chance for misinterpretation of tensors if this is true.

**Comment by jmansour** [comment]
Currently the xdmf data for the tensor6 object is written to directly map to the hdf5 data (which is incorrect).  I propose:
1. We retain the h5 data ordering as it corresponds to our uw2 ordering.
2. We write the xdmf schema as a hyperslab to effectively reorder the data for the paraview/xdmf ordering.

**Comment by julesghub** [comment]
yeah ragu. This is some legacy code that never got a good test!
I'm happy to convert the tensor6 to a HyperSlab description to reorder our uw2 ordering.

How is the our full 9 component tensor stored in memory? I can do the same trick there.

**Comment by julesghub** [comment]
2910b34 this change, on the dev branch, reoders the tensor to XDMF's Tensor6.

I'll close this ticket for now.
