### ISSUE TITLE
glucifer.objects.Surface crashes in parallel with onMesh=True

### ISSUE THREAD

**Issue by adambeall** [underworldcode/underworld2#208]
I am trying to plot a field on a cylindrical mesh in parallel.
Using glucifer.objects.Surface, the cylindrical mesh likes the onMesh=True option, which seems to avoid the evaluation of points outside of the cylindrical mesh.

glucifer.objects.Surface does not work with onMesh=True in parallel, though I can't get to the error description. 

glucifer.objects.Surface works in parallel with onMesh=False, but only with a cartesian mesh. With a cylindrical mesh, points outside of the domain are evaluated for some reason:
"FeVariable interpolation at location (-1.4292, -1.4292) does not appear to be valid.
Location is probably outside local domain."

The cylindrical mesh lives in the regionalMesh branch and here is an example of the problem:
https://github.com/underworldcode/underworld2/blob/regionalMesh/docs/development/broken_models/parallel_gLuc_saveimage.ipynb

**Comment by OKaluza** [comment]
Thanks for the detailed report and example, this should fix it! 3399d6a912eebcfffb54cb1b0fb96d3fa33b5427

**Comment by OKaluza** [comment]
Damnit! I commited that fix to the master branch by mistake, now fixed and pushed to devlopment c5b6927a809b84cb1d0e8b324178f3a7cea78278

**Comment by OKaluza** [comment]
... also added to regionalMesh branch now
