### ISSUE TITLE
import underworld

### ISSUE THREAD

**Issue by huilin0302** [underworldcode/underworld2#209]
Hi,  

I compiled underworld but  when run job I got an error "  ImportError: No module named underworld ".  Any help will be appreciated!  Thanks!

If I just open python and import underworld,  I got 
----------------------------------------------------------------------------------------------------------------
### _Python 2.7.4 (default, May 14 2013, 12:13:57) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import underworld
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "underworld/__init__.py", line 50, in <module>
    import libUnderworld
  File "/global/scratch/huilin/underworld2/libUnderworld/__init__.py", line 1, in <module>
    from libUnderworldPy import *
  File "/global/scratch/huilin/underworld2/libUnderworld/libUnderworldPy/__init__.py", line 2, in <module>
    import StGermain
  File "/global/scratch/huilin/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 25, in <module>
    _StGermain = swig_import_helper()
  File "/global/scratch/huilin/underworld2/libUnderworld/libUnderworldPy/StGermain.py", line 24, in swig_import_helper
    return importlib.import_module('_StGermain')
  File "/usr/local/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _StGermain_

Here is my config.cfg file,  if you need
-----------------------------------------------------------------------------------------------------
prefix = '/global/scratch/huilin/underworld2/libUnderworld'
build_dir = 'build'
with_debugging = 0
with_profiling = 0
optimisation_flag = 'default'
with_warnings = 1
lib_type = 'shared'
CC = 'mpicc'
CXX = 'mpicxx'
CFLAGS = '-O3 -xSSSE3 -axSSE4.2,SSE4.1 -ip'
CXXFLAGS = '-std=c++11'
with_credo = 1
with_glucifer = 1
with_graphics = 0
with_geothermal = False
with_solvers = True
with_importers = False
with_spherical = False
with_viscoelastic = False
with_sdl = 1
with_x11 = 1
with_cgl = 1
with_glut = 0
with_png = 1
with_avcodec = 0
with_gl2ps = 1
eptiming = 0
with_cautious_mode = 0
CPPPATH = ['/usr/include/libxml2', '/usr/local/python/include', '/usr/local/python/include/python2.7', '/usr/local/numpy-1.11.0/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/include', '']
LIBPATH = ['/usr/local/python/lib', '/usr/local/numpy-1.11.0/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/lib', '']
RPATH = ['/usr/local/python/lib', '/usr/local/numpy-1.11.0/lib/python2.7/site-packages/numpy-1.11.0-py2.7-linux-x86_64.egg/numpy/core/lib', '']
LIBS = ['python2.7', 'hdf5', 'xml2', 'm', 'petsc']
CPPDEFINES = ['HAVE_LIBM', 'HAVE_LIBXML2', 'HAVE_MPI', 'HAVE_HDF5', 'HAVE_PYTHON', 'HAVE_PETSC', 'HAVE_NUMPY', 'HAVE_MPI4PY', 'HAVE_H5PY', 'NDEBUG']
CFLAGS = '-O3 -xSSSE3 -axSSE4.2,SSE4.1 -ip'
CCFLAGS = ['-O2', '-Wall']
FRAMEWORKS = []
_RPATH = '${_concat(RPATHPREFIX, RPATH, RPATHSUFFIX, __env__)}'
SHLINKFLAGS = ['$LINKFLAGS', '-shared']
shared_libs = 1
static_libs = 0

**Comment by rbeucher** [comment]
Hi,

You need to set the PYTHONPATH environment variable so it includes the path to your underworld build.
On linux and mac you can just source the updatePyPath.sh file that is at the root of the underworld repository.

or do:

```
export PYTHONPATH=$PYTHONPATH:/path_to_your_underworld_build
```

Romain

**Comment by huilin0302** [comment]
Hi Romain,
Thanks for reply!  But I already set PYTHONPATH  to directory to where underworld built.  
> echo "$PYTHONPATH" 
> /home/huilin/data/underworld2

**Comment by jmansour** [comment]
Huilin, it doesn't seem that you've generated the bindings.  You need to install `swig`, and the run compile.py.  Alternatively, you can generate the bindings elsewhere and copy them over, but i'd suggest it's easier to simply install swig.

**Comment by huilin0302** [comment]
Hi,  the odd thing is I already installed swig.  Here are the last lines after run compile.py, if this is helpful

Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
../build/include/gLucifer/Base/Database.h:39: Warning 451: Setting a const char * variable may leak memory.
../build/include/gLucifer/Base/Database.h:40: Warning 451: Setting a const char * variable may leak memory.
Language subdirectory: python
Search paths:
   ./
   ./swig_lib/python/
   /home/huilin/scratch/swig/share/swig/3.0.10/python/
   ./swig_lib/
   /home/huilin/scratch/swig/share/swig/3.0.10/
Preprocessing...
Starting language-specific parse...
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
ln: creating symbolic link `./lavavu.py': File exists
ln: creating symbolic link `./control.py': File exists
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `build' is up to date.
scons: done building targets.

**Comment by huilin0302** [comment]
Hi all.  it's solved by re-setting the environment.  Thanks for all your suggestions!

**Comment by btokay** [comment]
Hi,

I am trying to install firstly Underworld and then UWgeoydnamics on Raijin following Python3-related instructions from documentation of HPC Installation. There is no problem up to last step of underworld installation part (i.e. `python -c "import underworld"`). But when it is run, an error is obtained as below.

> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'underworld'

The directory of Underworld built is included into PYTHONPATH as well. I do not know why available module underworld cannot be found. 

Could you please help me to solve this problem?

Best,

Bülent

**Comment by jmansour** [comment]
Hi @btokay 

You will need to set your PYTHONPATH to where underworld is _installed_.  Ie, what you set your `--prefix` to.  For example, if you configured with 
```bash
./configure.py --prefix=/some/install/dir
```
You will need to set PYTHONPATH as 
```bash
export PYTHONPATH=/some/install/dir:$PYTHONPATH
```

If that doesn't work for you, start a new issue and we'll have a closer look.
