### ISSUE TITLE
expose the weak resudual

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#212]
It looks like the following code returns the weak residual for the momentum equation. If i've got this right, can we expose to it to the Python solver class?

https://github.com/underworldcode/underworld2/blob/07eb3c0597ee556f7cc1391c45114bcabe41a1f6/libUnderworld/Solvers/KSPSolvers/src/BSSCR/stokes_residual.c

**Comment by julesghub** [comment]
Yep it does - I can expose it.
I'll get to that this arvo.

**Comment by dansand** [comment]
Thanks Julian!

**Comment by julesghub** [comment]
@dansand have you tried the code yet? Does it function as expected?
