### ISSUE TITLE
True free surface and Stick-air layer

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#213]
Hi
I have some question about top-surface boundary True free surface and Stick-air layer.
**Underworld1** 
If  one model with stick air layer  in res (16x16x16 ) will cause disturbed velocity field  and abnormal value () . If I remove the stick-air layer without any other change,the velocity field return normal. (both model leave the top surface boundary open, the left-right have an outflow velocity.) 
So, does the model without  stick-air layer represent the true free surface in underworld1?  
If not, how to set it? Whether the two model will produce the same result by increasing the resolution .
What difference between it? because the model without the  stick-air layer will increase the magnitude of topography evolution.
How the **Underworld2** deal with free surface problem?

**Comment by rbeucher** [comment]
Not Sure what your problem with sticky air is... I guess we needto know a bit more about the kind of viscosity contrast you are using...etc.
You can implement a free surface easily in UW2. Have a look at The updatefreesurface.ipynb i the docs/development/inprogress_models folder. I have also added one of my early experiment with free surfaces...
Pb with free surfaces is that they need extra precautions to avoid numerical instabilities. We are working on implementing different solutions to address that issue.

**Comment by tyszwh** [comment]
Thanks rbeucher
The  sticky air is low visocity and density layer to simulate the true free surface (some  research paper have discussed on it ). It cause the numerical instabilities and increase the computed time due to high contrast between air layer and crust. To remove the airlayer will  made the model more easy to solve and produce the smooth velocity field. But the suface change magnitude (by using the passive marker )  larger than model with air layer.

**Comment by jmansour** [comment]
Yep, both the sticky air and free surface can be easily implemented in UW2.  I'll close this ticket for now, but feel free to reopen if you have further queries.
