### ISSUE TITLE
New VectorAssemblyTerm_NA__Fn for Darcy Flow Calculation

### ISSUE THREAD

**Issue by adambeall** [underworldcode/underworld2#214]
A new version of VectorAssemblyTerm_NA__Fn.cpp needs to be made, which can return a force term formed by integrating the dot product of a provided vector and the gradient of the shape function over the element.

**Comment by julesghub** [comment]
Can you provide a mathematical description for the equation and force term
you wish to use. The implementation should be fairly straight forward,
similar to the VEP term.

**Comment by jmansour** [comment]
Basically he wants this one:

https://github.com/underworldcode/underworld1/blob/master/Underworld/Utils/src/VectorAssemblyTerm_NA_i__Fi.c

Would be good to consolidate this and the VEP guy, if reasonable.

**Comment by adambeall** [comment]
The background is that we want to be able to solve $\nabla \cdot \kappa(\nabla P + S) = 0$ where $P$ is the ground-water pressure gradient, $\kappa$ hydraulic diffusivity and S is the new term which introduces gravity induces flow. S needs to be a vector.
So this force term needs to be added: $\int_{\Omega} v \cdot \nabla N d{\Omega}$, where $v$ is a provided vector, in this case $v=\kappa S$. This term was added in the UW1 file John pointed out.

**Comment by jmansour** [comment]
@adambeall, I've ported the required term.  The python proxy is `uw.systems.sle.VectorAssemblyTerm_NA_i__Fn_i`.  

Give it a shot, and when you're satisfied with its operation, close this ticket.

**Comment by julesghub** [comment]
@adambeall, please reopen if you experience problems with this.

**Comment by adambeall** [comment]
The shape function gradient isn't being added to the force vector correctly. The issue seems to be that GNx is pointing to empty memory. It looks like L189 - L192 in libUnderworld/Underworld/Utils/src/VectorAssemblyTerm_NA_i__Fn_i.cpp should be replaced with:

`ElementType_ShapeFunctionsGlobalDerivs( elementType, mesh, lElement_I, xi, dim, &detJac, self->GNx );`

With this change, the code works. However, I would rather John or Julian check and commit the change in case something else is needed.

**Comment by jmansour** [comment]
Was this fixed @adambeall ?

**Comment by adambeall** [comment]
Yes @jmansour, I just went ahead and made the change [here](https://github.com/underworldcode/underworld2/commit/7b5414d2944857742c9f2281ee1d70dd61fa7969). It works now and passes a benchmark. 

I won't commit the benchmark yet, because it needs a new darcyflow class to also be committed and it probably shouldn't go in the new release. I'll commit the benchmark and darcyflow class to development after the fork for the new release has been made.

**Comment by jmansour** [comment]
Ah cool, ok, good work!  I'm gonna do a minor tweak to this, just just will reopen as a reminder.
