### ISSUE TITLE
Swarm partitioning between cpus...potential bug???

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#216]
Hi All,

@jmansour , @julesghub 

So I had some weird outputs from one of my model this afternoon so I investigated a bit...
It looks like there is an issue with swarm variables partitioning when we run in parallel...

(Feel free to kick me if I just did something stupid)

Here is a minimal example:

I just create a regular mesh, a swarm and a swarm variable which is then initialised with some cos functions...   no rocket science here...
I then save my swarm variable to a h5 file.

Now the result changes when I run the model depending on the number of cpu I use..
So I guess there is either an issue with the parallel partitioning or I am doing something wrong when initialising the swarm. First I thought it was a visualisation issue, but I get the same results with both Paraview and glucifer....Then I thought I had mixed global and local indices... but I don't think that's the case....

Here is a minimal example (using current dev branch):

```python

import underworld as uw
import underworld.function as fn
import numpy as np
import os

outputDir = './test/'
        
if uw.rank() == 0:
    if not os.path.exists(outputDir):
        os.makedirs(outputDir)

nx = 200
ny = 50

minX = 0.
maxX = 4.0
minY = 0.0
maxY = 1.0

mesh = uw.mesh.FeMesh_Cartesian(elementType = ("Q1/dQ0"),
                                elementRes  = (nx, ny),
                                minCoord    = (minX, minY),
                                maxCoord    = (maxX, maxY),
                                periodic    = (False, False))

swarm  = uw.swarm.Swarm( mesh = mesh, particleEscape=True)
swarmLayout = uw.swarm.layouts.GlobalSpaceFillerLayout( swarm = swarm, particlesPerCell=25 )
swarm.populate_using_layout( layout = swarmLayout )

plasticStrain = swarm.add_variable( dataType="double", count=1)
plasticStrain.data[...] = 0.0

def damage(xx, yy):
    return np.sin(np.pi * x / (maxX-minX)) * np.sin(np.pi * y / (maxY-minY))

for id, (x,y) in enumerate(swarm.particleCoordinates.data):
    plasticStrain.data[id] = damage(x, y)
    
plasticStrain.data[...] = plasticStrain.data[...] / plasticStrain.data.max() * 1.5
plasticStrain.data[...] *= np.random.rand(*plasticStrain.data.shape[:])

checkpoint_number = 0
time_years = 0.0

sH = swarm.save(os.path.join(outputDir, 'swarm-%s.h5' % checkpoint_number))
file_prefix = os.path.join(outputDir, 'Pstrain-%s' % checkpoint_number)
handle = plasticStrain.save('%s.h5' % file_prefix)
plasticStrain.xdmf('%s.xdmf' % file_prefix, handle, 'Pstrain', sH, 'swarm', modeltime=time_years)
```
SERIAL
![serial](https://cloud.githubusercontent.com/assets/3680918/25521921/b46e8dc8-2c44-11e7-94c3-97b040b417a0.png)

2 CPUS
![2cpus](https://cloud.githubusercontent.com/assets/3680918/25521920/b46df26e-2c44-11e7-9efa-65b29768cc0e.png)

4 CPUS
![4cpus](https://cloud.githubusercontent.com/assets/3680918/25521919/b46d288e-2c44-11e7-9425-f217eb7d8d12.png)

6 CPUS
![6cpus](https://cloud.githubusercontent.com/assets/3680918/25521918/b46d1f6a-2c44-11e7-8d84-20bcdee0097f.png)

**Comment by lmoresi** [comment]
What about that max() function - is that parallel safe ?

Sent from my iPhone

On 28 Apr 2017, at 19:04, rbeucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All,

@jmansour<https://github.com/jmansour> , @julesghub<https://github.com/julesghub>

So I had some weird outputs from one of my model this afternoon so I investigated a bit...
It looks like there is an issue with swarm variables partitioning when we run in parallel...

(Feel free to kick me if I just did something stupid)

Here is a minimal example:

I just create a regular mesh, a swarm and a swarm variable which is then initialised with some cos functions... no rocket science here...
I then save my swarm variable to a h5 file.

Now the result changes when I run the model depending on the number of cpu I use..
So I guess there is either an issue with the parallel partitioning or I am doing something wrong when initialising the swarm. First I thought it was a visualisation issue, but I get the same results with both Paraview and glucifer....Then I thought I had mixed global and local indices... but I don't think that's the case....

Here is a minimal example (using current dev branch):

import underworld as uw
import underworld.function as fn
import numpy as np
import os

outputDir = './test/'

if uw.rank() == 0:
    if not os.path.exists(outputDir):
        os.makedirs(outputDir)

nx = 200
ny = 50

minX = 0.
maxX = 4.0
minY = 0.0
maxY = 1.0

mesh = uw.mesh.FeMesh_Cartesian(elementType = ("Q1/dQ0"),
                                elementRes  = (nx, ny),
                                minCoord    = (minX, minY),
                                maxCoord    = (maxX, maxY),
                                periodic    = (False, False))

swarm  = uw.swarm.Swarm( mesh = mesh, particleEscape=True)
swarmLayout = uw.swarm.layouts.GlobalSpaceFillerLayout( swarm = swarm, particlesPerCell=25 )
swarm.populate_using_layout( layout = swarmLayout )

plasticStrain = swarm.add_variable( dataType="double", count=1)
plasticStrain.data[...] = 0.0

def damage(xx, yy):
    return np.sin(np.pi * x / (maxX-minX)) * np.sin(np.pi * y / (maxY-minY))

for id, (x,y) in enumerate(swarm.particleCoordinates.data):
    plasticStrain.data[id] = damage(x, y)

plasticStrain.data[...] = plasticStrain.data[...] / plasticStrain.data.max() * 1.5
plasticStrain.data[...] *= np.random.rand(*plasticStrain.data.shape[:])

checkpoint_number = 0
time_years = 0.0

sH = swarm.save(os.path.join(outputDir, 'swarm-%s.h5' % checkpoint_number))
file_prefix = os.path.join(outputDir, 'Pstrain-%s' % checkpoint_number)
handle = plasticStrain.save('%s.h5' % file_prefix)
plasticStrain.xdmf('%s.xdmf' % file_prefix, handle, 'Pstrain', sH, 'swarm', modeltime=time_years)

SERIAL
[serial]<https://cloud.githubusercontent.com/assets/3680918/25521921/b46e8dc8-2c44-11e7-94c3-97b040b417a0.png>

2 CPUS
[2cpus]<https://cloud.githubusercontent.com/assets/3680918/25521920/b46df26e-2c44-11e7-9efa-65b29768cc0e.png>

4 CPUS
[4cpus]<https://cloud.githubusercontent.com/assets/3680918/25521919/b46d288e-2c44-11e7-9425-f217eb7d8d12.png>

6 CPUS
[6cpus]<https://cloud.githubusercontent.com/assets/3680918/25521918/b46d1f6a-2c44-11e7-8d84-20bcdee0097f.png>

**Comment by rbeucher** [comment]
Argh.... of course it's not... I knew I was doing something stupid...
May I suggest I keep those models and we create a webpage...we could call it Romain's dumb models...

**Comment by lmoresi** [comment]
It's a great example - we should have a parallel python / underworld tutorial

Sent from my iPhone

On 29 Apr 2017, at 06:57, rbeucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Argh.... of course it's not... I knew I was doing something stupid...
May I suggest I keep those models and we create a webpage...we could call it Romain's dumb models...

**Comment by jmansour** [comment]
Little tidbids like this would be great for blog posts I think.  Perfectly displays common pitfalls that even experienced users may encounter. 

As for a solution, you can use fn.misc.min_max to obtain the global max. We currently have the methods _min_local_ and _min_global_.  I think having users explicitly specify local/global is a good thing, as it makes them think about what they require, and also what is the appropriate way to use the method.  For example, generally they are probably after _global_ results, but they would not want to call mpi global methods inside a low level loop, both for efficiency and because of the possibility of deadlocks.

**Comment by rbeucher** [comment]
That's what I did... It's actually fn.view.min_max... I am not a big than of that function I must say... However, I agree about explicitly specifying what we require in term of global or local value..
thanks @jmansour

**Comment by jmansour** [comment]
Hey! What's wrong with that function!? That Moresi character has been in your ear hasn't he? 😆
