### ISSUE TITLE
discrete colourmaps in colourbar

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#217]
Colorbars always seem to show a continuous version of the colourmap.  It would be good to have discrete fields / variables shown with a discrete colourbar.

**Comment by OKaluza** [comment]
You can do this already when creating an object with a colourbar:

`fig.Points(..., discrete=True, ....)`

Or modify an existing saved object:

`obj.colourBar["discrete"] = True`

**Comment by rbeucher** [comment]
I have just tried with the Viz example and it does not work... Can you have a look again?

**Comment by OKaluza** [comment]
Ok I admit I didn't try the first example.. which seems to not work, so I'll check it out.

The second method posted works however.

**Comment by rbeucher** [comment]
Ok, haven't try the second method... ;-)

**Comment by rbeucher** [comment]
@Okaluza,  so from what I can see, you get a discrete representation of the colors used to build the continuous colormap... I think what @dansand was suggesting is to have a colour bar with the discrete values of a field. It would be useful for the material swarm for examples where we have a limited number of int values (1 / material). Is it possible? @dansand does that make sense?

**Comment by rbeucher** [comment]
An example here I have 6 materials but only 3 colors showing... 

![screenshot from 2017-06-05 13-46-44](https://cloud.githubusercontent.com/assets/3680918/26769844/7d554c36-49f5-11e7-8ba0-ae4078669cd0.png)

**Comment by OKaluza** [comment]
OK I see, the current implementation assumes you will provide the same number of colours as the field has values, will look at improving it.

**Comment by lmoresi** [comment]
Quite a bit of this could be given to the user to work out if we could specify colours and how they map to specific values. I don’t see how to do this currently. It’s useful for some of the things we do in maps where we would like (for example) to have the zero (sea level) contour be at a particular value and to have a strong shift in colours at that value.



On 5 June 2017 at 1:52:35 pm, OKaluza (notifications@github.com<mailto:notifications@github.com>) wrote:

OK I see, the current implementation assumes you will provide the same number of colours as the field has values, will look at improving it.

**Comment by rbeucher** [comment]
I agree. A colormap object maybe like in matplotlib?

This is how I do it in matplotlib:

```python
base = plt.cm.get_cmap(base_cmap)
color_list = base(np.linspace(0, 1, N))
cmap_name = base.name + str(N)
ncmap = base.from_list(cmap_name, color_list, N)
```

**Comment by lmoresi** [comment]
OK, but if I had to suggest a piece of software to copy, rather than matplotlib, I would suggest we look at how GMT does this. This is so widely used in the geo community that it would have to be the best place (for us) to seek compatibility.

L



On 5 June 2017 at 2:11:17 pm, rbeucher (notifications@github.com<mailto:notifications@github.com>) wrote:

I agree. A colormap object maybe like in matplotlib?

This is how I do it in matplotlib:

base = plt.cm.get_cmap(base_cmap)
color_list = base(np.linspace(0, 1, N))
cmap_name = base.name<http://base.name> + str(N)
ncmap = base.from_list(cmap_name, color_list, N)

**Comment by rbeucher** [comment]
Here is a link to the GMT doc:

https://www.google.com.au/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj-5b_x66XUAhXLyLwKHXRMDgcQFggnMAA&url=https%3A%2F%2Fweb.mst.edu%2F~sgao%2FGMT-manual%2FGMT_Docs_Part111.pdf&usg=AFQjCNEP6DiWH1ZDnBWQctHmwg7ImtB-BA&sig2=KqvCscCDDgBLvF7wFfGcnw

**Comment by jmansour** [comment]
I'm not sure how the GMT/matplotlib colourmap objects work, but we do have an explicit colourmap object in glucifer:

http://underworld2.readthedocs.io/en/development/glucifer.objects.html#glucifer.objects.ColourMap

You can create this, and then pass it in with your objects at creation time.

**Comment by rbeucher** [comment]
Yes but we lack the possibility of extracting a set of N discrete colors from a continuous colormap...

**Comment by OKaluza** [comment]
Just pushed through an update 1a7e7216d3b08782d8bc835ea6d404128ebc3c02, also wrote up a notebook included in LavaVu repo to document things better: https://github.com/OKaluza/LavaVu/blob/master/notebooks/ColourMaps.ipynb

Most of the features mentioned were already implemented to some degree but there was a lack of examples and a few holes in the python interface to the functionality.

The notebook linked shows examples using LavaVu python interface standalone, but this can all be done via glucifer too of course.

**Comment by rbeucher** [comment]
Great! I like that. Thanks Owen
