### ISSUE TITLE
Raijin Paths

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#221]
This is in the raijin instructions:

``` bash
export PETSC_DIR=/projects/m18/opt/petsc-3.6.3
export PYTHONPATH=/projects/m18/opt:$PYTHONPATH
export PATH=/projects/m18/opt/swig-3.0.10/bin:$PATH
```

But these should point to the underworld project not m18 since that is not accessible to people in other projects (whereas we can add anyone to the underworld group)

**Comment by jmansour** [comment]
yep, i agree.  been meaning to fix this.

i think we have the projects/underworld space where we should put
depedencies.

**Comment by lmoresi** [comment]
Yes - I just built a new petsc there with mumps etc.

Sent from my iPhone

On 16 May 2017, at 19:23, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:

yep, i agree. been meaning to fix this.

i think we have the projects/underworld space where we should put
depedencies.

**Comment by ssduarte** [comment]
Hi,

I'm following these instructions to install underworld on raijin, however it' not working.
On the ./configure step it fails to load petsc, and on the config.log files is 

_In file included from /projects/Underworld/petsc-3.6.3/include/petscbag.h:4:0,
                 from /projects/Underworld/petsc-3.6.3/include/petsc.h:5,
                 from .sconf_temp/conftest_37.c:4:
/projects/Underworld/petsc-3.6.3/include/petscsys.h:130:6: error: #error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
 #error "PETSc was configured with one OpenMPI mpi.h version but now appears to be compiling using a different OpenMPI mpi.h version"
      ^
scons: Configure: no_

Can you advise please?
Thank you

**Comment by julesghub** [comment]
ok I have install the following into /projects/Underworld on raijin:
petsc-3.7.6
mpi4py
h5py
swig-3.0.10

And I have updated the raijin install instructions to use the above 
https://github.com/underworldcode/underworld2/commit/880d012b90fafec8c8f2cc13bed1e00940636282

So alter your environment variables and you should be fine to compile and run the code.

I'll close this ticket for now but feel free to reopen if troubles continue.

**Comment by julesghub** [comment]
@lmoresi not all people in our team are part of the 'underworld' group on raijin. Thus they don't have access to the new software. To fix you (or sudo) can either,
1) Open the directory /project/Underworld group to be read/execute by others `chmod o+rw ...`
2) Add everyone into the underworld group.

I vote option 1.

**Comment by lmoresi** [comment]
3 install it as a module.

I vote 1 as well because I have to manually add all these users otherwise !

The alternative is to tell NCI to add anyone to underworld if they wish without asking us. That’s only if they have some polity about world writeable …

Would it work as read only ?

L



On 1 June 2017 at 5:09:43 pm, julesghub (notifications@github.com<mailto:notifications@github.com>) wrote:

@lmoresi<https://github.com/lmoresi> not all people in our team are part of the 'underworld' group on raijin. Thus they don't have access to the new software. To fix you (or sudo) can either,

  1.  Open the directory /project/Underworld group to be read/execute by others chmod o+rw ...
  2.  Add everyone into the underworld group.

I vote option 1.

**Comment by julesghub** [comment]
It wouldn't work as read only. We need to execute some executables from
within the directory.

**Comment by julesghub** [comment]
Users now such request to be in the 'underworld' group on raijin and they can use the install guide instructions provided https://github.com/underworldcode/underworld2/commit/880d012b90fafec8c8f2cc13bed1e00940636282

**Comment by jmansour** [comment]
@lmoresi can we just make this directory (& contents) ```chmod o+rx``` (which is what @julesghub meant to say).

**Comment by jmansour** [comment]
ie, write access isn't required for ```other``` group, only read & execute access.

**Comment by lmoresi** [comment]
That’s not what he explained - said you need to write to the directory too …

I certainly would see no problem with having this world readable (and world cd’able)

L





On 5 June 2017 at 12:49:31 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

ie, write access isn't required for other group, only read & execute access.

**Comment by julesghub** [comment]
To be clean, I think @lmoresi should write
chmod -R o+rx /projects/Underworld

this would make the directory useful to anyone on raijin

**Comment by lmoresi** [comment]
@lmoresi did that, but found that there were a large number of errors due to directories being owned / created by others

Those others might need to do something similar to @lmoresi


On 5 June 2017 at 3:25:15 pm, julesghub (notifications@github.com<mailto:notifications@github.com>) wrote:

To be clean, I think @lmoresi<https://github.com/lmoresi> should write
chmod -R o+rx /projects/Underworld

this would make the directory useful to anyone on raijin

**Comment by julesghub** [comment]
Should be all good now because my directory
/projects/Underworld/opt

is read/execute to others. So the instructions should now work.
I'll get ting to test tomorrow.
