### ISSUE TITLE
Population control in limited region

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#222]
It would be useful to be able to pass a (Boolean) function into population control, so that we can remove/add particles only in elements where function evaluates to True. For my purpose, the ideal default behaviour would be that if any element nodes evaluate to True, the whole element gets tagged as True and pop. control applies.

**Comment by jmansour** [comment]
This would be easy to do.  And while there, we should also reintroduce the NoSplitInInterfaceCells option.  

This would also allow pop control with sparse swarms.

**Comment by lmoresi** [comment]
I would prefer this to be implemented as a query so that a boolean of interface cells could be obtained and used to create a mask.

In most interface problems you actually want to split more aggressively around the interface to preserve the structure.

(though not necessarily using the method we currently have).

L



On 19 May 2017 at 12:01:17 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

This would be easy to do. And while there, we should also reintroduce the NoSplitInInterfaceCells option.

**Comment by jmansour** [comment]
Yeah, this sounds like a good way to generalise things. However, I'd
suggest before we put too much energy into this, we have more of a think
about decoupling the swarm from the mesh, and what opportunities this
presents in regards to doing pop control.

The voronoi algorithm has served us well and is robust, but it's also a
dogs breakfast in terms of the implementation and the options to drive it.

**Comment by lmoresi** [comment]
I found myself unable to make this suggestion without saying kdtree.

So I was quiet.

For a while.



On 19 May 2017 at 12:20:14 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Yeah, this sounds like a good way to generalise things. However, I'd
suggest before we put too much energy into this, we have more of a think
about decoupling the swarm from the mesh, and what opportunities this
presents in regards to doing pop control.

The voronoi algorithm has served us well and is robust, but it's also a
dogs breakfast in terms of the implementation and the options to drive it.

**Comment by julesghub** [comment]
Dan and I just had a poke around and found this 

https://github.com/underworldcode/underworld2/blob/development/libUnderworld/PICellerator/Weights/src/WeightsCalculator.c#L135

we could make a function here and query it to see if population control should happen or not.

I agree this code is a dog's breakfast and we should clean it up.

**Comment by jmansour** [comment]
This won't be done for UW2.  A new ticket should be created for UW3 when appropriate.
