### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Cheltone** [underworldcode/underworld2#226]
Hello,
     So I am getting a warning about multiple IP address and also I can't connect the web address that is listed. Any ideas? I am brand new to Underworld 2 and would greatly appreciate any help! The link below is a screenshot of the errors.

Cheltone
![u2 errors](https://cloud.githubusercontent.com/assets/29169654/26758230/214abb4c-48a6-11e7-9e85-a840068b4b81.JPG)

**Comment by jmansour** [comment]
Hi there.   Can you give us more information about the platform you are running on (Windows/OSX/Linux)?  I assume you are using docker?

**Comment by Cheltone** [comment]
Yes, I'm using Windows 10 along with Docker/Kitematic. 

Thanks

**Comment by jmansour** [comment]
Is it the latest version of docker?  

Is your windows firewall possibly blocking your connection? 

Virtualbox is sometimes utilised with older versions of docker, but shouldn't be required with **Docker for Windows** (as opposed to the **Docker Toolbox**).  Perhaps have a look at this page to see if you find any clues as to what's going wrong:

https://docs.docker.com/docker-for-windows/

Also, from a terminal/shell, try and execute this:

```bash
docker run --rm -it underworldcode/underworld2 /usr/bin/python
```

And then try ```import underworld``` from within python.

**Comment by Cheltone** [comment]
Figured it out! Thanks for your help!

**Comment by jmansour** [comment]
Great!  What was the issue in the end?  Please share for the benefit of others who may encounter this issue.

**Comment by Cheltone** [comment]
I needed to add my IP address in place of "localhost". Running it through the terminal helped as well.
Thanks again!

**Comment by jmansour** [comment]
Hmm.. ok, not sure why localhost doesn't work, but as long as you've found a way forward!  

I'll close the ticket, but feel free to reopen if necessary.
