### ISSUE TITLE
Update install instructions on Raijin

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#229]
Hi All,

I was getting some weird MPI error messages last Friday so I asked the NCI people what could that be. 

They suggested I move to openmpi 1.10 (at least). Instructions in the repo use 1.8.4 which is now quite old...

They also suggested that we use a more recent version of GCC... 

I have recompiled the code using that set of modules and everything works fine:

```bash
module load dot pbs gcc/6.2.0 hdf5/1.8.14p python/2.7.11 python/2.7.11-matplotlib openmpi/1.10.2 petsc/3.7.4
```

Was there a reason to use our own petsc build? The most recent available on raijin is 3.7.4 (compiled with openmpi 1.10.2, it has MUMPS...

I run a lot of tests and my MPI error messages are not showing anymore...

Note that although openmpi 1.10 series is still supported, the most recent version is now 2.1. but they don't have petsc build with that version.

Romain

**Comment by jmansour** [comment]
If these more recent modules (openmpi & petsc) work directly with underworld, we should definitely use them. 

We should update the recipe for the new release.

**Comment by rbeucher** [comment]
Well I'm using them now...

**Comment by rbeucher** [comment]
An underworld module on raijin would be ideal...I know @julesghub was thinking of asking them to build one. Shouldn't be too much of an issue, no?

**Comment by RebeccaFarrington** [comment]
No, it should be an problem.  Also good timing with the up coming release!

**Comment by julesghub** [comment]
That all sounds good.
I think for the release we should update/review our dependencies, so let's
look at openmpi 1.10 and an underworld module.

For the instructions I was just using @lmoresi version of petsc-3.7, happy
to switch.
J
