### ISSUE TITLE
gLucifer working directory

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#23]
A gLucifer error has cropped up a couple of times when working in notebooks. The images are generated (i.e. the code reports activity ) but not written to disk. I found this error while running notebooks as a different user from the one that installed the code but Joe seems to be getting this on a OS X 10.11 installation that otherwise seems ok. 

Joe O'Rourke [reported the error for Mac OS](http://disq.us/url?impression=d7df0e28-7a97-11e5-9724-002590f38886&forum=3795435&thread=4196974316&url=http%3A%2F%2Fwww.underworldcode.org%2Fposts%2FMacOS-Installation%2F%23comment-2325139304%3An95Htse81PDuN3hUS0VwKGEHVeY&variant=active&experiment=digests&behavior=click&post=2325139304&type=notification.post.moderator&event=email)

One thing that might help is if we could have a verbose / debugging flag to tell us where the images are supposed to be going. 

It might also be useful to have some notebooks which show an alternative to the gLucifer output mode.

**Comment by jmansour** [comment]
Definitely some refinement is required around the glucifer image writing is required.  But my guess for Joe O'Rourke's issue is that Lavavu was never built.

**Comment by lmoresi** [comment]
Is there a test for that ?



Sent from my iPhone

On 25 Oct 2015, at 15:44, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Definitely some refinement is required around the glucifer image writing is required. But my guess for Joe O'Rourke's issue is that Lavavu was never built.

**Comment by jmansour** [comment]
Actually, just taking a look now, this *should* be caught out (_pylab.py:278).  So perhaps it's another issue. Possibly the logic around locating a temporary directory is falling down somehow, or more likely LavaVu was built, but is busted.

**Comment by lmoresi** [comment]
Just wondered if there was any security difference in the new os that required different / special calls. It doesn't happen on my laptop.

I might have a chance to go through a few things with joe tomorrow afternoon so perhaps we can list a few things to try.

Sent from my iPhone

On 25 Oct 2015, at 16:53, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, just taking a look now, this should be caught out (_pylab.py:278). So perhaps it's another issue. Possibly the logic around locating a temporary directory is falling down somehow, or more likely LavaVu was built, but is busted.

**Comment by jmansour** [comment]
Could be the case Louis.  Let me know if you discover anything.  I

**Comment by OKaluza** [comment]
This should help identify what's going wrong https://github.com/underworldcode/underworld2/commit/541adb4cf612f7ea479c468b2d1326be73231cc6

**Comment by OKaluza** [comment]
I was unable to test from Underworld this last week as the brew petsc install failed completely on the OS X machine I was using but I was able to build the viewer standalone with this minor fix... https://github.com/OKaluza/LavaVu/commit/e608141b9d31e1706229fd4654a62126193586c9

The stand alone build system is actually pretty reliable, I might tweak it so scons just calls this rather than doing it's own build in future.

Things have changed a bit here too, by default the rendering is now done by a call to the LavaVu library rather than running the executable, and the image returned as a string so no temporary files are required. A vis database is still created but exists in memory only.

**Comment by julesghub** [comment]
if still an issue please reopen
