### ISSUE TITLE
internal dirichlet bcs stokes

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#231]
The link below provides a simple stokes system where I use a function to define some nodes, then try to apply a velocity boundary condition to them. Running the script in serial / parallel produces very different output. Output suggests that in parallel the internal velocity BCs are not being seen in the stokes system. 

Is there a better way to set these, or a deeper problem?

https://github.com/dansand/issues/tree/master/internal_bcs

*this issue first arose in a more complicated model in which a petsc error occurred. In this simple example, the petsc error doesn't appear, but I assume the problems are related.

**Comment by jmansour** [comment]
Hey Dan.  At line 69:70, why are you doing this only on the root proc, or
was this only added for testing?

**Comment by dansand** [comment]
That was a legacy from some testing in the original model. It looks like it 'fixes' the problem I reported above. I'm going to close this issue and post the original model despite it being somewhat more complex. Sorry. Trying to make things easier, and failing.
