### ISSUE TITLE
petsc crash / penalty method

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#232]
I first noticed petsc crashes in model where I am setting internal velocity BCs. After some investigation, it appears the crash only occurs when using the penalty method w/ mumps, and a resolution above 24 x 24. So quite specific. 

Not urgent, as I can probably run with other solvers for the time being ...

As setup now, the model should reproduce the crash. 

https://github.com/dansand/issues/tree/master/petsc_bcs

**Comment by dansand** [comment]
Okay, so it's not the penalty method itself causing the crash, it's the preconditioner choice. 
The system solves when `solver.options.main.Q22_pc_type='uw'`, but for any other PC type, the petsc error arises. 

The penalty method fails because the PC type gets set to 'gkgdiag'

**Comment by jmansour** [comment]
does an identical issue occur when you leave use standard direct solve? (ie, in serial).

**Comment by dansand** [comment]
In serial all solver combinations (preconditioner choices) I have tried seem to work without Petsc errors being reported.

**Comment by dansand** [comment]
The comment that __the petsc error appears when using Q22_pc_type='uw', but is non-fatal__
does not seem to be reproducible. Testing the default solver `Q22_pc_type='uw'()` it seems to run without error in serial or parallel.

**Comment by julesghub** [comment]
Closing this for now as it's a stale issue. Please reopen is required.
