### ISSUE TITLE
Solver class rework

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#236]
As per #220, the solver still leaks memory, though in relatively minor amounts.  A few aspects of the solver class probably require further consideration.  

In particular, the entire petsc solver structure is recreated every time `solve()` is called.  Perhaps this is the correct design for petsc, but I'm not sure. It seems that it would be better to create all the petsc objects when we initialise the solver, and then basically only call the ksp solve when the `solve()` method is called.  One consequence of the current design is that the reuse previous solution as initial guess is broken (and was also previously leaking).

**Comment by julesghub** [comment]
With the focus on uw3 this is no longer a relevant issue

**Comment by ythaha** [comment]
Sorry to bother you, just wandering what is uw3, i saw it on underworldcode conda repository. Is their any plan to release it and what's the major change from uw2 ? Will underworld2 be abandoned later?

As for uw2, is it possible for user to use `underworld.systems.sle` module to modify the behavior of uw2 ? such as modifying the basic equations to add other items or so, just out of curiosity.

Thanks!

**Comment by jmansour** [comment]
Hi @ythaha 

UW3 is the next iteration of the underworld project. It will include better meshing functionality (full spherical mesh for example), Newton-method for non-linearity solutions, and other improvements.  The interface will be slightly different, but an important goal is to keep UW3 as close to UW2 as possible.  So, while user's models will need updating for UW3, only relatively minor changes should be required. 

UW2 will not be abandoned any time soon, and will continue to be developed and supported for the foreseable future. 

As for `underworld.systems.sle`, it is possible to use it for custom behaviour. But it'd be best if you start a new ticket with your specific requirements and we can consider the best approach there.

**Comment by ythaha** [comment]
Thank you @jmansour ! Looking forward to hearing the release of UW3. I will open a issue if i need to use `underworld.systems.sle` someday, but for now the default functionality is sufficient for me.
