### ISSUE TITLE
mg unstable where internal BCs are set

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#238]
@dansand provide the following model which fails under certain configurations for mg:

https://github.com/dansand/issues/blob/master/petsc_bcs/simple_wedge.ipynb

Note that Neumann conditions don't appear to affect the solution.  

Model always seems to solve satisfactorily for *nomg* simulations.  For *mg* sometimes it works, sometimes it doesn't.   For example, translating the BC wedge downward (so less internal BCs) eventually results in the mg solve working again.  Some resolutions work, some don't.  

I'm not how this is related to  #231, #232.  @dansand?

Also, from a notebook, no issue is apparent to the user, though the solve results are useless. We need to resolve this asap.  We have a ticket: #158

**Comment by dansand** [comment]
@jmansour, all these problems did emerge from the same original model. 
I've updated the simplified 'wedge' model so that it should now crash when run in parallel, when you set the Q22 preconditioner to something other than the default `uw`, which was the bug identified in #231, #232

**Comment by dansand** [comment]
@lmoresi, @jmansour, In these models I'm applying internal BCs to entire chunks of the domain. IS this problematic?  I recall some discussions about problems in the pressure solve when there are no velocity DOFs in an element.

**Comment by lmoresi** [comment]
You can't solve for pressure if there are no unknowns in that element.

Perhaps the pressure-fixing callback function would be useful here.

We had this discussion when thinking about the spherical mesh and blocking out a core.

Sent from my iPhone

On 13 Jul 2017, at 16:57, Dan Sandiford <notifications@github.com<mailto:notifications@github.com>> wrote:


@lmoresi<https://github.com/lmoresi>, @jmansour<https://github.com/jmansour>, In these models I'm applying internal BCs to entire chunks of the domain. IS this problematic? I recall some discussions about problems in the pressure solve when there are no velocity DOFs in an element.

**Comment by jmansour** [comment]
Yeah good point. So those pressure unknowns are decoupled from the problem. Would it be useful to also block them out? (ie, declare them BCs)

**Comment by dansand** [comment]
All problems identified disappear when internal BCs are chosen so that all elements have at least one unknown

**Comment by jmansour** [comment]
@dansand can you elaborate on this?  How would you do this with your wedge model?

**Comment by dansand** [comment]
This is the diagram from the Van Keken  benchmark:
![screen shot 2017-07-15 at 2 00 27 pm](https://user-images.githubusercontent.com/10967872/28236302-125dbc02-6966-11e7-94e9-bd5331945a5f.png)

**Comment by dansand** [comment]
I guess my working solution is just avoid stamping entire elements with Dirichlet conditions. For instance, in the diagram, the subduction velocity condition is only applied along the diagonal line that divides the slab and the wedge (often they use tailored meshed with nodes that lie right on the line). 

Another approach I played with yesterday is defining a checkerboard pattern in the node configuration, so when you set the velocity in a region, it only constrains the every other node - example in the updated notebook.
