### ISSUE TITLE
locating 3d geometry over the mesh 

### ISSUE THREAD

**Issue by SehsahH** [underworldcode/underworld2#239]
I want to locate 3d objects into the 3d mesh, but "underworld.function.shape.Polygon"is strictly a 2d shape. Please, how could I  do so?
Thanks in advance
Haytham

**Comment by jmansour** [comment]
Hi Haytham

Yep, Polygon is fundamentally a 2d object, with the idea being that it would be used with rotation functions to affect some polygon extrusion in 3d.  Unfortunately, we have not as of yet added rotation functions to Underworld.  However, you can still do rotations directly within python.   Here's an example:

https://gist.github.com/jmansour/5635b3de575ca55639ac66ffef0a2170

Alternatively, you can simply use pure Python routines, such as in this example:

https://github.com/underworldcode/underworld2/blob/master/docs/publications/OzBenchEtAl-2008/OzBenchEtAl-2008.ipynb

You can also use any third party Python libraries such as https://pypi.python.org/pypi/Shapely.

**Comment by SehsahH** [comment]
Thanks John

**Comment by jmansour** [comment]
No probs!  Keep us posted on your model development.
