### ISSUE TITLE
Publications !

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#24]
The publications directory should reproduce results that other people have done with Underworld. I think it is ok to have benchmarks too, but I think we should be quite specific. 

In the Arrhenius example, the notebook reproduces figure 1a of that M&S paper. I would note that the Ra is supposed to be 10^7 with \Delta\eta 3.10^4 and the viscosity is the Frank-Kamenetskii linearlised form. Even though this is a bit old fashioned, for reproducibility I suggest doing the same !  And then show how to do Fig 1b !

I would also recommend not calling the mesh linearMesh when using Q2 elements.

**Comment by jmansour** [comment]
This is probably good info for the guidelines.md file.

#118
