### ISSUE TITLE
isosurface 'isovalue' vs 'isovalues'

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#240]
Just a quick note that this explodes:

```python
import underworld as uw
import glucifer
mesh = uw.mesh.FeMesh_Cartesian(elementRes=(4,4,4), minCoord=(-1.,-1.,-1.), maxCoord=(1.,1.,1.))
fig = glucifer.Figure()
fig.append(glucifer.objects.IsoSurface(mesh, uw.function.input()[0], isovalue=[1.]))
fig.show()
```

This is because I'd mistakenly used the parameter 'isovalue' instead of 'isovalue**s**'.  I believe 'isovalue' is used somehow for the dynamic isosurfaces.  

Not  a huge drama, but did waste a bit of time on it, so just flagging it here as a user error that could be caught better. 🙂

**Comment by OKaluza** [comment]
Ah cheers, I'll add a check to that parameter existing, sorry you wasted time on this!
Also watch out for this one I found yesterday: #241

**Comment by jmansour** [comment]
Time wasted was mainly owing to my stupidity. I was comparing with the IsoSurface usage in OzBench, which works fine, but it still took me like an hour to realise that OzBench had 'isovalues' and my code had 'isovalue'.

**Comment by OKaluza** [comment]
Validating the params now and can use either "isovalue" or "isovalues" list e6801709c19b7a07fecc1b7a995d739f4e2cb842
