### ISSUE TITLE
mpi4py problem

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#242]
I'd like to be able able to collect global particle coordinates onto all processors (intended use case is for small swarms). It seems like it should be a straightforward mpi4py task, as we know in advance the global swarm size. 

In the following example, the swarm is localised, so that running this with > 2 processors, means that some procs will have no local particles.

The following code produces and I get an mpi error (unfortunately not very descriptive):

```python
localData = np.ascontiguousarray(swarmCustom.particleCoordinates.data)
globalShape = swarmCustom.particleGlobalCount


if localData.shape[0]:
    sendbuf = np.array(localData, dtype=np.float64)
else:
    #sendbuf = np.empty((1,2),  dtype=np.float64 )
    sendbuf = np.empty((0,2),  dtype=np.float64 )
    
    
recvbuf = np.empty([globalShape,2], dtype=np.float64 )

comm.barrier()

comm.Allgatherv([sendbuf, MPI.DOUBLE] , [recvbuf,MPI.DOUBLE])
```

**Comment by dansand** [comment]
This is an analogous mpi4py problem, but no Underworld data handles are used (this one works):

```

if rank % 2 == 0:
    sendbuf = np.ones((1,2), dtype=np.float64)
else:
    sendbuf = np.empty((1,2), dtype=np.float64)
    #sendbuf =np.array([], dtype=np.float64)


recvbuf = np.empty([np.int(np.ceil(size)), 2])

#print(sendbuf.shape,  recvbuf.shape)
comm.Allgatherv([sendbuf, MPI.DOUBLE] , [recvbuf,MPI.DOUBLE])

```

**Comment by dansand** [comment]
I think the problem is simply how do you handle an empty array in an `Allgather` call?
Unfortunately there seem to be very few examples relavent to to this problem...

**Comment by OKaluza** [comment]
I can't answer your question re mpi4py because I haven't used it much, only the MPI C interface, in C you have to calculate the counts and offsets and broadcast that data before using it for the Gatherv call but I'm guessing mpi4py does that bit for you.

An alternative option though, as the swarm is small: if you plot the swarm with glucifer, it gathers the particle coords in order to visualise them. You can then retrieve those vertices in python from the Figure object on the root node. Can provide an example if you like.

**Comment by dansand** [comment]
Thanks Owen, 

I have a workaround now, which is is simply to expose all the data on all processors (i.e. not use swarms). As I say, it seems like a trivial procedure when arrays are not empty, but when they are, I can't find a way of sending 'nothing'. I'll close this issue now, as it's not directly Underworld related.

**Comment by jmansour** [comment]
I did have a bit of a look into this, but it seems it's a shortcoming of mpi4py.  There's some discussion here which seems to suggest it should be possible, but I tried what is suggested without any luck.

**Comment by dansand** [comment]
Sneaky workaround Mr Mansour! I think that would be a good solution for the time being.
