### ISSUE TITLE
plate rotation

### ISSUE THREAD

**Issue by Cheltone** [underworldcode/underworld2#243]
Hello everyone,
      Have any of you all ever used Underworld to model tectonic plate rotation? 

Thanks!

Cheltone

**Comment by RebeccaFarrington** [comment]
Hi Cheltone,

What type of plate rotation modelling were you thinking of? 
More details please.

Cheers,
Rebecca

**Comment by julesghub** [comment]
Close due to inactivity. Feel free to reopen if required.
