### ISSUE TITLE
Polygon creation broken...

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#244]
@jmansour 

The following fails. I think it is related to your recent commit...

```python
import underworld as uw
import numpy as np
uw.function.shape.Polygon(np.array([(0.0,0.0), (1.0, 0.0), (1.0, 1.0), (1.0, 0.0)]))
```

**Comment by jmansour** [comment]
hmm... that works for me, both compiled locally (OSX) and via docker on latest stable.

**Comment by rbeucher** [comment]
Of course... I forgot to recompile... My bad...

**Comment by jmansour** [comment]
amateur's mistake! 😆
