### ISSUE TITLE
tokens for launch docker web preview

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#245]
we should remove the need to paste in the token when starting up the web preview!

**Comment by lmoresi** [comment]
Hard to remove completely with the way Jupyter now works. But you can set a password instead - and perhaps a blank one ?


On 3 August 2017 at 8:22:28 pm, RebeccaFarrington (notifications@github.com<mailto:notifications@github.com>) wrote:

we should remove the need to paste in the token when starting up the web preview!

**Comment by jmansour** [comment]
Yes, blank one is the trick according to this:

http://jupyter-notebook.readthedocs.io/en/latest/security.html

So i created  `~/.jupyter/jupyter_notebook_config.json` with the following content:

```json
{
  "NotebookApp": {
    "password": "",
    "token": ""
  }
}
```

and it works on my Jupyter notebook, which is version 5.0.  it, no password or token required, as was previously the case. The docker images are currently running jupyter 4.4, so I'm not sure if this will work there yet, but it might. 

As we have ipython pegged at some older versions (for tooltip/autocomplete compatibility reasons), we can't currently the base docker image software for the latest jupyter, but we will have to tackle this issue before the next release I think.

**Comment by lmoresi** [comment]
It should work - there is also a command line option which I used for the teaching notebooks a few months ago.

L


On 3 August 2017 at 9:05:38 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

and it works on my Jupyter notebook, which is version 5.0. it, no password or token required, as was previously the case. The docker images are currently running jupyter 4.4, so I'm not sure if this will work there yet, but it might.

**Comment by jmansour** [comment]
Ah yes, `jupyter notebook password` also works (with blank password as suggested), but it expects interactive input, so not really suited to Dockerfile execution.

**Comment by lmoresi** [comment]
True, though it is not useless in a docker environment - it authenticates when you open the home page and so is fine for notebooks on docker. Not ideal if you want the password to be blank, though.

L



On 4 August 2017 at 8:56:10 am, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

Ah yes, jupyter notebook password also works (with blank password as suggested), but it expects interactive input, so not really suited to Dockerfile execution.
