### ISSUE TITLE
Possible implementation of thin skinned tectonics?

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#247]
This is more of a question and an issue, being a complete beginner with underworld i'd like to know how to implement thin-skinned deformation models with it. I have seem the geodynamics module being implemented in the development branch, is the implementation of the geomod2004 compression benchmark with that module possible? help and guidance with this would be gratifying

**Comment by julesghub** [comment]
Hi Arijit,
The geodynamics module is currently under development. It is designed to be a wrapper interface to the existing Underworld functionality. So far with the module we have reproduced the extensional geomod2004 model and not the compressional benchmark.

What specific modelling questions are you interested in? perhaps I could point you to some other more established models in Underworld

**Comment by arijitlaik** [comment]
I am working on modelling thrusts specifically, similar to the geomod2004 compression benchmark, similar to the ones done by Feng et al 2015 jsg DOI: 10.1016/j.jsg.2015.03.002

**Comment by arijitlaik** [comment]
If you could please provide the geomod 2004 extensional Benchmark Python file either here or as an email I'd really grateful

**Comment by rbeucher** [comment]
Hi Arijit,

I am away until next week. I will send you something if you don't mind waiting a few more days...

Best is to contact me on my email as it is not really a code issue...

R

**Comment by arijitlaik** [comment]
ya sure, thank you. will contact you via email

**Comment by arijitlaik** [comment]
I have send in an email, we do not university email ids here, if it gets to you spam box please consider checking it @rbeucher

**Comment by rbeucher** [comment]
I got your email. Thanks
