### ISSUE TITLE
New build script for Magnus

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#248]
dev branch of Underworld builds using our current build script, but glucifer doesn't

(glucifer needs gcc 4.9 for C++11 support...)

But the Magnus gcc 4.9.0 compiler isn't compatible with a bunch of the library versions we've been using

```
dsandiford@magnus:/group/m18/dsandiford/underworld2_devel> bash uwbuildscript.sh 
swig/3.0.8(42):ERROR:150: Module 'swig/3.0.8' conflicts with the currently loaded module(s) 'gcc/4.9.0'
swig/3.0.8(42):ERROR:102: Tcl command execution failed: conflict gcc/4.9.0

numpy/1.10.1(24):ERROR:150: Module 'numpy/1.10.1' conflicts with the currently loaded module(s) 'gcc/4.9.0'
numpy/1.10.1(24):ERROR:102: Tcl command execution failed: conflict gcc/4.9.0

scipy/0.16.1(34):ERROR:150: Module 'scipy/0.16.1' conflicts with the currently loaded module(s) 'gcc/4.9.0'
scipy/0.16.1(34):ERROR:102: Tcl command execution failed: conflict gcc/4.9.0

mpi4py/2.0.0(24):ERROR:150: Module 'mpi4py/2.0.0' conflicts with the currently loaded module(s) 'gcc/4.9.0'
mpi4py/2.0.0(24):ERROR:102: Tcl command execution failed: conflict gcc/4.9.0

cmake/2.8.12.2(51):ERROR:150: Module 'cmake/2.8.12.2' conflicts with the currently loaded module(s) 'gcc/4.9.0'
cmake/2.8.12.2(51):ERROR:102: Tcl command execution failed: conflict gcc/4.9.0
```

https://github.com/underworldcode/underworld2/blob/development/docs/install_guides/pawsey_magnus.sh

**Comment by OKaluza** [comment]
If you feel like trying this again @dansand, this commit from LavaVu is now in Underworld:
https://github.com/OKaluza/LavaVu/commit/6bc2b3a43361a49a8e1a9f2749e533f1a3d1ea17

It seems the C++11 features that are not completely implemented in gcc-4.8 aren't are only used by parts of json.hpp that I'm not using in LavaVu, I managed to build and pass all tests by just removing the restriction.

**Comment by dansand** [comment]
This works now Owen. I've updated the Magnus build script, for anyone else needing to rebuild on that machine.

**Comment by RebeccaFarrington** [comment]
Thanks dan ☺
