### ISSUE TITLE
parallel min/max problem 

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#250]
The following script, which should return a function's global max on the top boundary of the domain, crashes when I increase the parallelism. It runs up to 15 procs, but crashes without much detail for 16 procs and greater. 

* the problem does not seem to be resolution dependent (it appears at high resolution()
* the problem does not occur when I evaluate the view function on the mesh (rather than the top boundary)

https://github.com/dansand/issues/blob/master/twalls_minmax/min_max_topbound.ipynb

**Comment by jmansour** [comment]
Ok, this type of evaluation will lead to no evaluation on certain procs, which is probably the cause of the problem.  Will have a look.

**Comment by jmansour** [comment]
Yo @dansand.  Update and give it a crack.
