### ISSUE TITLE
glucifer on raijin

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#252]
Hello!

I'm having issues running glucifer on raijin with the latest dev branch Underworld.
Looking back through my files I have glucifer working with code checked out on 23/08, using the current dev install guide.

Any chance the 5/9 commit require changes on raijin?

Let me know if you can take a look :)

**Comment by jmansour** [comment]
What are the issues @RebeccaFarrington?   No chance my little changes from Monday have caused this?

**Comment by RebeccaFarrington** [comment]
Bah!  I was mistaken :)
I cleared my environment and it's working. 
apologises for the noise @OKaluza !

It's creating a gldb as I type

**Comment by RebeccaFarrington** [comment]
egh.  So my update was incorrect - I'd just recompiled the old code :/

On the current dev branch with raijin install instructions OpenGl can't be found.

> Checking for package X11... yes
Checking for package OpenGL... no
****  WARNING ****
OpenGL not found, graphics disabled, skipping LavaVu build

we're linking to the central mesa builds

> [rjf565@raijin5 01:31 PM] libUnderworld $ echo $OPENGL_LIB
/projects/Underworld/mesa-17.1.5/build/linux-x86_64/gallium/targets/libgl-xlib/

**Comment by OKaluza** [comment]
Hi Bec, perhaps it could be a permissions issue with the Mesa path, can you see libGL? `ls -l $OPENGL_LIB; ls -l $OPENGL_INC`
Anyway I re-ran `chmod -R +rX /projects/Underworld/mesa-17.1.5` to make sure you can access it.

It's working here though, I logged in and pulled the latest dev branch, configures and builds with no problems.
If you still get OpenGL not found, perhaps send me the graphics.cfg file and I can try and track it down.

**Comment by rbeucher** [comment]
I recompiled yesterday and no problem...so far...

**Comment by RebeccaFarrington** [comment]
Sorry for the noise everyone - it's working!
