### ISSUE TITLE
Load a txt file

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#253]
Hi everyone,
There are examples of loading data with h5 or inp format but not in txt file format. The doubt is, if I have a transect for a region with x and z coordinates and for each coordinate a value of temperature, how can I use it as temperatureField? 

x         z        T
10     -1        320
...

Is easy for instance to write a single geotherm, but if my region changes due to subduction zones, I will have non similar geotherms, and I was wondering how to use the entire xzT.txt file instead of writing conditions such as:
if coord[0]>10 and coord[0]<100:
     geotherm1
if coord[0]>100 and coord[0]<200:
    geotherm2
....

Thanks

**Comment by jmansour** [comment]
Hi Angel! 

Can you post a small example of your data file? 

Numpy has the loadtxt method:

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.loadtxt.html

which can certainly be used to read the data.  How you cast this to your temperature field will depend on the structure of the data.

How this works in parallel should also be considered.

**Comment by AngelValverdePerez** [comment]
So this is more or less my data:
-300.000     0.000   0.000000E+00
  -300.000    -0.476   8.024459E+00
  -300.000    -1.429   2.408447E+01
  -300.000    -1.905   3.210246E+01
  -300.000    -2.381   4.011829E+01
  -300.000    -2.857   4.813196E+01
  -300.000    -3.333   5.614348E+01
  -300.000    -3.810   6.416968E+01
  -300.000    -4.286   7.217688E+01
  -300.000    -5.238   8.818555E+01
  -300.000    -5.714   9.618629E+01
  -300.000    -6.190   1.041849E+02
  -300.000    -6.667   1.121981E+02
  -300.000    -7.619   1.281852E+02
  -300.000    -8.571   1.441638E+02
  -300.000    -9.524   1.601504E+02
  -300.000   -10.476   1.761118E+02
  -300.000   -11.429   1.920813E+02
  -300.000   -12.381   2.080254E+02
  -300.000   -13.333   2.239609E+02
  -300.000   -14.286   2.399047E+02
  -300.000   -16.190   2.717357E+02
  -300.000   -18.095   3.035493E+02
  -300.000   -20.000   3.353289E+02
  -300.000   -21.905   3.670746E+02
  -300.000   -23.810   3.987865E+02
  -300.000   -25.714   4.304480E+02
-290.000     0.000   0.000000E+00
  -290.000    -0.476   8.024471E+00
  -290.000    -1.429   2.408379E+01
  -290.000    -1.905   3.210179E+01
  -290.000    -2.381   4.011764E+01
  -290.000    -2.857   4.813133E+01
  -290.000    -3.333   5.614288E+01
  -290.000    -3.810   6.416910E+01
  -290.000    -4.286   7.217634E+01
  -290.000    -5.238   8.818440E+01
  -290.000    -5.714   9.618521E+01
  -290.000    -6.190   1.041839E+02
  -290.000    -6.667   1.121972E+02
  -290.000    -7.619   1.281838E+02
  -290.000    -8.571   1.441619E+02
  -290.000    -9.524   1.601483E+02
  -290.000   -10.476   1.761093E+02
  -290.000   -11.429   1.920786E+02
  -290.000   -12.381   2.080226E+02
  -290.000   -13.333   2.239581E+02
  -290.000   -14.286   2.399019E+02
  -290.000   -16.190   2.717306E+02
  -290.000   -18.095   3.035421E+02
  -290.000   -20.000   3.353199E+02
  -290.000   -21.905   3.670640E+02
  -290.000   -23.810   3.987744E+02
  -290.000   -25.714   4.304346E+02
  -290.000   -27.619   4.620779E+02
  -290.000   -29.524   4.936879E+02
  -290.000   -31.017   5.184382E+02
  -290.000   -33.333   5.567916E+02
  -290.000   -35.238   5.883021E+02
  -290.000   -38.095   6.354980E+02
  -290.000   -40.952   6.826203E+02
  -290.000   -43.810   7.296857E+02
-280.000     0.000   0.000000E+00
  -280.000    -0.476   8.023785E+00
  -280.000    -1.429   2.408173E+01
  -280.000    -1.905   3.209904E+01
  -280.000    -2.381   4.011420E+01
  -280.000    -2.857   4.812721E+01
  -280.000    -3.333   5.613807E+01
  -280.000    -3.810   6.416359E+01
  -280.000    -4.286   7.217015E+01
  -280.000    -5.238   8.817681E+01
  -280.000    -5.714   9.617692E+01
  -280.000    -6.190   1.041749E+02
  -280.000    -6.667   1.121875E+02
  -280.000    -7.619   1.281727E+02
  -280.000    -8.571   1.441494E+02
  -280.000    -9.524   1.601342E+02
  -280.000   -10.476   1.760938E+02
  -280.000   -11.429   1.920616E+02
  -280.000   -12.381   2.080040E+02
  -280.000   -13.333   2.239380E+02
  -280.000   -14.286   2.398802E+02
  -280.000   -16.190   2.717056E+02
  -280.000   -18.095   3.035137E+02
  -280.000   -20.000   3.352880E+02
  -280.000   -21.905   3.670284E+02
  -280.000   -23.810   3.987350E+02
  -280.000   -25.714   4.303914E+02
  -280.000   -27.619   4.620308E+02
  -280.000   -29.524   4.936366E+02


...

**Comment by rbeucher** [comment]
Hi Angel, 

So if I understand you correctly you want to use that 2D profile to force the temperature field as a function of depth.

I don't have an example ready but you can easily do that with numpy

1) load the text file using numpy.loadtxt()
2) create a function T(z) using numpy.interp()
3) feed the new created function with the mesh or swarm coordinates, depending on what you want to do...
You should be able to use a numpy array as input to the new T(z) function (the one you get from numpy.interp) A python loop will do but will be much slower:

```
f = numpy.interp(Z, x) # Get Z, x from your text file using numpy.loadtxt
TemperatureField.data[:] = f(mesh.data[:,1))
``` 

Sorry for the clunky answer...

**Comment by rbeucher** [comment]
I just realized that you are actually providing a field T(x,Z)...

That should still be possible with numpy. Other solutions are KD-tree (have a look at scipy), or just build a nearest neighbor function.

**Comment by lmoresi** [comment]
I would actually recommend the kdtree from scipy.

Load the data (assuming the whole thing will fit on one process), build the tree, find a near-neighbour or weighted neighbour value at the nodes.

The tree can be truncated spatially so that you don’t have to use information that is outside the bounds of the mesh on an individual process.

The only real issue is if you have a massive dataset that is too large to read on a single process.

Of course there are likely to be some efficiencies that you could think to try, but you only have to do this once, right, after that you can save it as an underworld mesh file and use the standard tools.

L



On 17 October 2017 at 8:12:42 am, rbeucher (notifications@github.com<mailto:notifications@github.com>) wrote:

I just realized that you are actually providing a field T(x,Z)...

That should still be possible with numpy. Other solutions are KD-tree (have a look at scipy), or just build a nearest neighbor function.

**Comment by julesghub** [comment]
Closing ticket. Reopen if necessary.
