### ISSUE TITLE
SwarmLoad Problem

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#254]
I'm using a supercomputer with underworld 2.2.2 version. 
The thing is that, some models, don't know why, while trying to load swarm and materialVariable it gives me a runtime error like:

Cannot load /workspace/my_data/underworld2/docs/MyModels/materialVariable_1508.h5's data on current swarm. Incompatible numbers of particles in file '/workspace/my_data/underworld2/docs/MyModels/materialVariable_1508.h5'. Particle count: file 11519664, this swarm 8115104

But other's models does not have this problem.

**Comment by AngelValverdePerez** [comment]
I think is related to parallelization, due to I have checked a model that I run in only one processor and I don't have problem to load again the swarm and the materialVariable, but same model in parallel, does not works the load option (it works for variables related to the mesh, as velocityField, but not for variables saved with the swarm, as material)

**Comment by jmansour** [comment]
Hi Angel

A few things to check for that can cause issues in parallel.  So, lets say you want to save/checkpoint at timestep 17, and then in proceeding simulation you want to reload the swarm data from timestep 17.

1. At timestep 17, save the swarm:  `some_swarm.save("swarm17.h5")`
2. Save the swarmvariable:  `some_swarmvariable.save("swarmvariable17.h5")`

Now for the restart.  I'll assume you have already created a swarm, and it is empty (ie, you haven't added and particles). 

1.  Load the saved swarm: `some_swarm.load("swarm17.h5")`
2. Load the swarmvariable: `some_swarmvariable.load("swarmvariable17.h5")`

If I recall correctly, you had a similar issue previously, so just double check that you are using the correct files and doing all the above steps.  If there's still an issue, post up a minimal example and we'll take a closer look.

**Comment by AngelValverdePerez** [comment]
I save like this:

swarmDat = swarm.save(h5Path+"saved_swarm"+str(checkpointstep)+".h5")

materialFilename = h5Path+"/materialVariable_"+str(checkpointstep)
mFH = materialVariable.save(materialFilename+".h5")
materialVariable.xdmf(materialFilename, mFH, "material",swarmDat,"myMaterial")


When I load:
I create the mesh with same resolution and a new empty swarm:
newSwarm = uw.swarm.Swarm(mesh=mesh, particleEscape=True)
newSwarm.load(inputPath+'saved_swarm'+last_checkpoint_step+'.h5')

materialVariableCopy = newSwarm.add_variable( dataType="int", count=1 )
materialVariableCopy.load(inputPath+'materialVariable.'+last_checkpoint_step+'.h5')

And then I have the error...

The only difference with your steps is that I created also the materialVariableCopy, otherwise I cannot simply do:

materialVariable.load(inputPath+'materialVariable.'+last_checkpoint_step+'.h5')

it would say: materialVariable is not defined...

And I don't have this problem if I run a model with one processor and then load again in jupyter. The problem appears when running in parallel the model and then trying to load in jupyter
This is why I'm confuse...

**Comment by jmansour** [comment]
What you've posted looks right.  The only other thing I'd suggest trying is to add the variable to the swarm **before** loading the swarm:
```python
newSwarm = uw.swarm.Swarm(mesh=mesh, particleEscape=True)
materialVariableCopy = newSwarm.add_variable( dataType="int", count=1 )

newSwarm.load(inputPath+'saved_swarm'+last_checkpoint_step+'.h5')
materialVariableCopy.load(inputPath+'materialVariable.'+last_checkpoint_step+'.h5')
```

but this *shouldn't* make a difference. If it does, let us know. 

Otherwise, the final thing I'll suggest is double checking that the files you are saving **are** the files you're trying to load from.  It's not clear from your posted code that this need be the case (`h5Path`  vs `inputPath`). 

If all this fails, post up a **minimal** version of your model that produces the issue, and we'll take a closer look.

**Comment by julesghub** [comment]
We're closing this ticket.
If it's still an issue can you retest this against the latest version of uw2 as it contains upgrades to the reloading functionality. 
Feel free to reopen ticket if you encounter reload issues.
