### ISSUE TITLE
Pushing only a portion of the sidewalls

### ISSUE THREAD

**Issue by VinceUW** [underworldcode/underworld2#258]
Hi UW2 team!

In a 2D model, I want to have boundary conditions on my sidewalls such that I apply a horizontal velocity only on a portion (in the centre) of each side wall. The upper and lower part of each side wall should be fixed (by deforming the mesh) or they can move but the particles need to go out.

Anyway, I could manage to create Indexsets that define different portions of the sidewalls but I do not know how to tie them to the mesh. Should I use a function in uw.libUnderworld.StgDomain.RegularMeshUtils_?

I attach my ipynb in case you want to have a closer look (see section on boundary conditions).

Thanks in advance for your help!

Vincent
[PushingOnlyAPortionOfSideWalls.ipynb.zip](https://github.com/underworldcode/underworld2/files/1498952/PushingOnlyAPortionOfSideWalls.ipynb.zip)

**Comment by julesghub** [comment]
Hi VinceUW,
What you want to use is a 'uw.mesh.FeMesh_IndexSet' - this ties the index set to a mesh.

A straightforward way to define one is by using an empty set from an existing mesh. Eg,
```
mesh  = uw.mesh.FeMesh_Cartesian()
mySet = mesh.specialSets["Empty"] # copies the empty set
mySet.add([0,3,5])
print mySet
```

Good luck with it.

**Comment by VinceUW** [comment]
Hi Julian,

Thanks! It worked.

Cheers,

Vincent

**Comment by julesghub** [comment]
I'm closing this ticket.
Vincent feel free to reopen if you have more questions on this topic
