### ISSUE TITLE
deforming mesh in parallel

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#259]
in dockers, I deform the mesh without problems and in the loop does not break, also using the jupyter terminal in parallel.  However t breaks in the other computer with this message:

``` bash
###########################################################################################
###########################################################################################
An uncaught exception was encountered on processor 5.
Traceback (most recent call last):
  File "Temp_2.py", line 1408, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 66216 in cell 47 of swarm "LL7IX7L1__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (262.025,-27.998,0.000).
Conversion to local coord was (0.7566,48.9433,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 5 in communicator MPI COMMUNICATOR 3 DUP FROM 0
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

This message appears after solving stokes in the main loop...  What is wrong?

**Comment by julesghub** [comment]
Hi Angel,
The repopulation() function is failing. A particle is being found at (262.025,-27.998,0.000) on processor 5, but proc 5 can't locate it in the mesh.
Is this a valid coordinate for the swarm? Is the mesh deformation sensible?

**Comment by jmansour** [comment]
Also, importantly, when you say other computers, can you be a bit more specific?  Are you using the same processor count on the other computer?  If not, can you retry using a parallel notebook using the same processor count?  

Are your versions of Underworld identical?  

Also, if you aren't running the very latest version (v2.4.1b), please update and try again.

**Comment by AngelValverdePerez** [comment]
this is the way I construct the new mesh:

xRes= 384
yRes = 96
dim  = 2
boxLength = 1500.0
boxHeight = 250.0
minX=-300.0
maxX=1200.0
minY=-230.0
maxY=20.0
n_part = 30

linearMesh = uw.mesh.FeMesh_Cartesian( elementType = ("Q1/dQ0"),
                                 elementRes  = (xRes,yRes), 
                                 minCoord    = (minX,minY), 
                                 maxCoord    = (maxX,maxY),
                                 periodic    = [True, False] ) 

#create a dictionary that maps from the original regular mesh positions (y positions), to the new spacing, 
print yRes, 'Resolution y axis'
print maxY, 'maximum of Y axis'
print minY, 'Minimum of Y axis'

print '------'
original_values = np.unique(linearMesh.data[:,1])
dy0 = boxHeight/yRes
print dy0, ' vertical cell length'

print '------'
print '  '

dyabove = 1. #que cambie cada kilometro
stickyair=20. #kilometros de sticky air
crustdepth=-30.
lithosdepth=-90.
print crustdepth, '  crust level in kilometers'
print lithosdepth, ' lithosphere level in kilometers '

print '------'
print '  '

numabove = (-crustdepth+stickyair)/dyabove
numabove=round(numabove)
if numabove%2!=0:
    numabove=numabove-1
dyabove=(-crustdepth+stickyair)/numabove

print numabove, 'cells above lithosphere level with'
print dyabove, 'km of resolution above lithosphere'

print '------'
print '  '

dymiddle = dyabove*2.
nummiddle= (-lithosdepth+crustdepth)/dymiddle
nummiddle=round(nummiddle)
if nummiddle%2!=0:
    nummiddle=nummiddle-1
else:
    nummiddle=nummiddle-2
dymiddle=(-lithosdepth+crustdepth)/nummiddle

print nummiddle, 'cells between lithosphere level & crust level with'
print dymiddle, 'km of resolution in the middle'

print '------'
print '  '

numbelow=yRes-numabove-nummiddle
if numbelow%2!=0:
    numbelow=numbelow
else:
    numbelow=numbelow
dybelow = -(minY-lithosdepth)/(numbelow)

print numbelow, 'cells below lithosphere level with '
print dybelow, 'km of resolution below lithosphere'

if dybelow>dymiddle*4.:
    print '   ###################################################################################################### '
    print 'CAUTION!! The resolution of ',dybelow,'km is huge in the asthenosphere and can cause convergency problems'
    print '   ###################################################################################################### '

if numbelow<=0:
    raise RuntimeError('Negative cells!!! Change dyabove to lower resolution')    
print '------'

print 'Total of new cells', numbelow+nummiddle+numabove
print ' '
new_values1 = np.arange(minY, lithosdepth, dybelow) 
print len(new_values1),'length values below',lithosdepth,'km'
print '+'
new_values2 = np.arange(lithosdepth, crustdepth, dymiddle) 
print len(new_values2),'length values in lithospheric mantle'
print '+'
new_values3 = np.arange(crustdepth, maxY, dyabove)
print len(new_values3),'lenght values above', crustdepth,'km'
print '_______'

print len(new_values1)+len(new_values2)+len(new_values3)


if dymiddle>=dybelow:
    raise RuntimeError('More resolution in asthenospher than in lithosphere')

newys = np.concatenate((new_values1, new_values2, new_values3))
#print newys
#newys = np.unique(newys.round(decimals=2))

if len(newys)>yRes:
    
    raise RuntimeError('new len newys must be same than yRes')
#np.add?
newys = np.append(newys, (maxY))

d = {}
for i in range(len(original_values)):
    d[original_values[i]] = newys[i]

print 'Minimum value of new resolution: ', newys[0], 'Maximum value of new resolution: ', newys[-1]   
    


# In[157]:
print 'Deforming mesh'
#Walk mesh nodes and use dictionary to lookup new Y positions
with linearMesh.deform_mesh():
    for index, coord in enumerate(linearMesh.data):
        y0 = coord[1]
        yn = d[y0]
        linearMesh.data[index][1] = yn


so  (262.025,-27.998,0.000) on processor 5 should be inside the domain.... 

I'm using dockers in my office with underworld 2.2.2b version
And in our supercomputer we are not using dockers, but we install the 2.2.2b version 

So same version in both machines... 
But, in the jupyter terminal is working fine... but not in the other supercomputer. 

Is not that simple to update to the new version, I don't have administration power to install it in the supercomputer machine, so I have to work with this version.

**Comment by jmansour** [comment]
So are you running the Jupyter jobs (the ones that are working) in parallel, or just serial?  If parallel, is the processor count the same as that used on the supercomputer?   

Can you simplify the model you've posted as much as possible?  Really, we want *only* the bare essentials that still reproduce the issue.

**Comment by AngelValverdePerez** [comment]
Ok, I tried the code with: mpiexec -np 4 etc...  and it works in parallel in our supercomputer.

I tried again with -np 32 and it fails:

An uncaught exception was encountered on processor 18.
Traceback (most recent call last):
  File "Temp_3.py", line 1029, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate


###########################################################################################
###########################################################################################
An uncaught exception was encountered on processor 17.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 24 in communicator MPI COMMUNICATOR 3 DUP FROM 0 
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

###########################################################################################
###########################################################################################


self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 3824 in cell 1 of swarm "MTJLSRNA__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (-105.165,-77.119,0.000).
Conversion to local coord was (0.7556,36.3123,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 3824 in cell 1 of swarm "YCU375SS__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (-105.164,-74.986,0.000).
Conversion to local coord was (0.7558,36.8609,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
Traceback (most recent call last):
  File "Temp_3.py", line 1029, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 23045 in cell 29 of swarm "7R3FGYL7__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (-184.065,-74.996,0.000).
Conversion to local coord was (0.3586,36.8580,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
Traceback (most recent call last):
  File "Temp_3.py", line 1029, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
        self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 480 in cell 1 of swarm "DFVW1NWC__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (457.433,-74.988,0.000).
Conversion to local coord was (0.8059,36.8602,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
Traceback (most recent call last):
  File "Temp_3.py", line 1029, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 3824 in cell 1 of swarm "281SKQ66__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (-105.165,-74.995,0.000).
Conversion to local coord was (0.7558,36.8585,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 3824 in cell 1 of swarm "I7319QQ7__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (832.270,-74.996,0.000).
Conversion to local coord was (0.7220,36.8581,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 950 in cell 1 of swarm "7FGOXSQ1__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (82.405,-74.983,0.000).
Conversion to local coord was (0.7911,36.8614,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
Traceback (most recent call last):
  File "Temp_3.py", line 1029, in <module>
    population_control.repopulate()
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_population_control.py", line 93, in repopulate
    self._swarm._voronoi_swarm.repopulate(weights_calculator=self._weights)
  File "/home/avalverde/underworld2-2017.03.14/underworld2/underworld/swarm/_integration_swarm.py", line 137, in repopulate
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 23040 in cell 16 of swarm "K1C8C2ER__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (-236.187,-77.134,0.000).
Conversion to local coord was (-0.3277,36.3085,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 950 in cell 1 of swarm "KK9ELDXC__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (82.404,-77.123,0.000).
Conversion to local coord was (0.7907,36.3112,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.
    libUnderworld.PICellerator._CoincidentMapper_Map( self._mapper )
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _CoincidentMapper_Map(): unable to map swarm particle 22114 in cell 1 of swarm "120JVLHC__swarm" (type GeneralSwarm) coord to a valid element local coordinate.
Particle coord was (1019.769,-77.140,0.000).
Conversion to local coord was (0.7216,36.3070,0.0000).
Note that this error can occur when the mesh is overly deformed,
or when you have deformed the mesh but not updated swarm particle ownerships.

###########################################################################################
###########################################################################################

**Comment by AngelValverdePerez** [comment]
Is this possible due to repopulation option should be more agressive or to use other option, or maybe repopulate every timestep? 
I attach my model if you want to look at it, but, how can I solve the problem? I mean, if it is due to the number of proccesors working and trying to repopulate, I don't really know which is the suitable way to use the options of the repopulation, and therefor, the proper number of proccesors to use.
[model.tar.gz](https://github.com/underworldcode/underworld2/files/1526939/model.tar.gz)

**Comment by jmansour** [comment]
Hi @AngelValverdePerez 

I started looking at this model, but you haven't simplified it, and it's very hard for me to know what I can and can't remove.  You need to help us if you want us to help you 🙂. 

1. Update to the latest version of the code and make sure your model runs against it. 
2. Provide us with the absolute minimum code that still reproduces your issue. 
3. Reduce the resolution **as much as possible** such that the issue still presents.  

I ran into problems at point 3. I tried to bring down the resolution (to 128*32), but this tripped up parts of your model configuration and was a roadblock to me debugging your code.  At full resolution, it is much too slow for me to debug. 

Also, the mesh deform is commented out inside the timestepping loop.  Should this still create the issue?

**Comment by AngelValverdePerez** [comment]
Hi @jmansour 
As I said, I can update to the latest version in my office but I cannot do it in the other supercomputers, one is called marenostrum located in Barcelona, the other is our cluster located in the ITCJA bulding. And I cannot run a parallel notebook there. So I need to do it in version 2.2.2b (that is the same version in the 3 computers I'm using).

I don't know how is the absolute minimum code that reproduces the issue. 

The thing is that I want to have more resolution in the crust than in other parts of the domain in parallel and do it in a proper way to not to have problems, if a change the resolution. The issue comes when trying to repopulate in the first time step of the main loop, particles are going out of the domain. 


I I use n_processor=4, goes correctly ( in parallel (not jupyter terminal))
If I increment the number of proccesor, it breaks, with the message I wrote above.

I attached what I think is the most simplified code version. 
[model.zip](https://github.com/underworldcode/underworld2/files/1681541/model.zip)


I'm going to explain the parts deforming the mesh:
xRes is 128 
yRes is 32 

dyabove is to divide the mesh above crust level (y coord) with a new resolution (2km in this case), and numabove gives me how many new cells I have after deforming the mesh. 

same for the dybelow but:   numabove+numbelow = number of cells I had before deforming. 

So with this, depending on the first xRes, yRes you can play to have more or less resolution, 

But I dont understand why is working when using 4 processors, but not for example 8

**Comment by julesghub** [comment]
Is this still an issue for you @AngelValverdePerez?

**Comment by AngelValverdePerez** [comment]
Not really, thank you very much!
