### ISSUE TITLE
MeshVariable_Projection with Q2/dQ1 Elements

### ISSUE THREAD

**Issue by adambeall** [underworldcode/underworld2#260]
Hi, I'm wondering if MeshVariable_Projection is completely unusable with a Q2/dQ1 mesh?

I thought it would work if I chose the gauss integration points option, but the result is still erroneous. 
I've attached an example, where the resulting field has a minimum smaller than the lowest swarm variable value.

[test_proj.tar.gz](https://github.com/underworldcode/underworld2/files/1511746/test_proj.tar.gz)

Thanks,

Adam

**Comment by lmoresi** [comment]
Well it’s not guaranteed that the bounds will be respected when you fit Quadratics … but it is really rubbish ?

The alternative might be to do a radial basis function averaging to the nodes using (wait for it) the scipy kdTree to provide distance information. Within reason, this works in parallel given the shadow information.

L





On 29 November 2017 at 9:01:22 am, adambeall (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi, I'm wondering if MeshVariable_Projection is completely unusable with a Q2/dQ1 mesh?

I thought it would work if I chose the gauss integration points option, but the result is still erroneous.
I've attached an example, where the resulting field has a minimum smaller than the lowest swarm variable value.

test_proj.tar.gz<https://github.com/underworldcode/underworld2/files/1511746/test_proj.tar.gz>

Thanks,

Adam

**Comment by julesghub** [comment]
Louis is spot on about the quadratics not respecting the bounds.

Can you use a q1 mesh variable instead with the Projection() operation?

J

**Comment by jmansour** [comment]
I believe even with Q1 element types, weighted residual (type:1)
projections are not guaranteed to respect min/max values. The weighted
average (type:0) should however.

**Comment by lmoresi** [comment]
Because of extrapolation at the boundaries ?


On 29 November 2017 at 12:47:05 pm, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

I believe even with Q1 element types, weighted residual (type:1)
projections are not guaranteed to respect min/max values. The weighted
average (type:0) should however.

**Comment by jmansour** [comment]
No, although that may in some cases also be a consideration. I haven't really considered the maths in any details, this is just from from experience. 

https://gist.github.com/jmansour/388ee4a5e382dfe07a41735d6a01ebe3

**Comment by adambeall** [comment]
Apologies, I misunderstood and didn't realise that the weighted average would be shape function dependent. Thanks for clarifying!

Thanks for the kdTree (surprise, surprise) and linear mesh recommendations.
