### ISSUE TITLE
Plot deviatoric stress in xx

### ISSUE THREAD

**Issue by VinceUW** [underworldcode/underworld2#263]
Hello Underworld 2 team,

Is there a function to plot deviatoric stress in xx? I saw there is a function to compute deviatoric stress (uw.function.tensor.deviatoric), but can we specify to plot only the xx component?

Vincent

**Comment by julesghub** [comment]
Hi Vincent,
To visualise the deviatoric stress in xx I would recommend first constructing a function for the full deviatoric stress and isolating the 0th component ie, xx. 

`devstressFn = 2.0*mystokes.fn_viscosity*fn.tensor.symmetric( myvel.fn_gradient )`

To visualise only the first component one can do.
`fig.append(glucifer.objects.Surface(mesh, devstressfn[0])) # visualise on a mesh
 fig.append(glucifer.objects.Points(swarm, devstressfn[0])) # visualise on a swarm`
(The above code assumes several data structure, most notably the stokes system 'mystokes' which can be used to attain the viscosity function 'fn_viscosity')

For an example see the section ' Calculate stress values for benchmark comparison' in https://github.com/underworldcode/underworld2/blob/v2.4.1b/docs/examples/1_03_BlankenbachBenchmark.ipynb

Hope this helps.

Also note `uw.function.tensor.deviatoric` is for isolating the deviatoric part of a 2nd order tensor.

**Comment by VinceUW** [comment]
Hi Julian,

Thanks! It works fine that way indeed. Please note that using glucifer.objects.Surface returns an error though (see below). Do you know any way to fix this?

Cheers,

Vincent

RuntimeErrorTraceback (most recent call last)
<ipython-input-20-4bbced516ac6> in <module>()
     44 stressFn = 2.0*viscosityMapFn*fn.tensor.symmetric( velocityField.fn_gradient )
     45 figStress = glucifer.Figure(store, figsize=(1500,300), name="Stress", boundingBox=((0.0, 0.5), (maxX, 1.0)) )
---> 46 figStress.append(glucifer.objects.Surface(mesh, stressFn[0], pointSize=2, valueRange=[-0.2,0.2], colours='blue green white yellow red'))
     47 
     48 figStrainMesh.show()

/root/underworld2/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
    107                 _setup = _setup.__get__(self, cls)
    108             if callable(_setup):
--> 109                 _setup()
    110 
    111         return self

/root/underworld2/glucifer/objects.pyc in _setup(self)
    422 
    423     def _setup(self):
--> 424         _libUnderworld.gLucifer._lucCrossSection_SetFn( self._cself, self._fn._fncself )
    425         if self._offsetEdges != None:
    426             self._dr.offsetEdges = self._offsetEdges

RuntimeError: Provided input to SwarmVariableFn does not appear to be of supported type. Supported types are 'FEMCoordinate' and 'ParticleCoordinate'. From Python, these are provided by respectively 'VoronoiIntegrationSwarm' and 'Swarm' type `FunctionInput` objects.

**Comment by julesghub** [comment]
Hi Vincent,

That's my bad - visualise the stress only on the swarm particles. ie,

fig.append(glucifer.objects.Points(swarm, devstressfn[0]))

Currently we can't visualise the 'raw' viscosity on the mesh, therefore the
stress (a function of viscosity) is failing.

**Comment by VinceUW** [comment]
Hi Julian,

No worries! Regarding the “Surface” tool that works to plot e.g. strain, I could realise that when using it instead of “Points” the data looks very pixellated, kind of down-sampled. Do you know anything about this?

Cheers,

Vincent

**Comment by julesghub** [comment]
I assume 'strain' is the 'strain rate 2nd invariant'?...
Yes i know about this... 1st) When 'q1' elements (underworld's default) are
used a discretise a field; the field's gradients are not continuous across
element boundaries.

The strain rate is a function of velocity gradients. So if the velocity is
defined using q1 elements then non continuous strain rates (across element
boundaries) will result.

You can 'smooth' out the strain rate by using the
class underworld.utilts.MeshVariable_Projection, see
http://underworld2.readthedocs.io/en/latest/underworld.utils.html#underworld.utils.MeshVariable_Projection
An example of it in use
https://github.com/underworldcode/underworld2/blob/v2.4.1b/docs/examples/2_08_ShearBandsSimpleShear.ipynb

**Comment by VinceUW** [comment]
Hi Julian,

Yes, it is the strain rate 2nd invariant.

OK, I see. Thanks for the links. I have already tried using the class underworld.utilts.MeshVariable_Projection but it does not help much in my case as the new smoothed strain rate 2nd invariant still does not look continuous.

Anyway, tries and errors I guess…

Thanks for the help!

Cheers,

Vincent
