### ISSUE TITLE
General questions on figure options

### ISSUE THREAD

**Issue by VinceUW** [underworldcode/underworld2#264]
Hi Underworld 2 team,

Is there any update or planned update on the improvement of vector quality in gLucifer? Currently, the vectors appear quite pixelated and there is no option to get smoothed vectors. Also, is there an option to avoid having the vector width and head size scale with the velocity magnitude?

Another question: what is a practical way to access options on plotting colours? I found that we can use names of colour palettes that are commonly used in iPython, but it would be nice to have a list of the available colour options. Is such list available?

Thanks for your help!

Cheers,

Vincent

**Comment by OKaluza** [comment]
Hi Vincent, sorry only just noticed this question... 

Vector quality is easy to improve, but the quality defaults to low for speed. If you pass quality=2 or quality=3 when creating a figure it will anti-alias, smoothing out vector lines, text and other jagged edges.

To have fixed arrow scaling, use the "length" property, this sets a fixed vector length that will apply to all vectors, ignoring the magnitude.
If you want to adjust between having the magnitude set the length and a fixed length you can also use the "normalise" property, when 1.0 (default) and length is set, the vector length is always the "length" property value.
When normalise=0, the vector length is the vector magnitude. Values between allow a small amount of magnitude scaling to be used, eg: ..., length=0.05, normalise=0.8
https://github.com/OKaluza/LavaVu/wiki/Property-Reference#objectvector

Regarding colours, there is an example notebook in LavaVu which show the built in colour maps and how to define your own or download from the net:
https://github.com/OKaluza/LavaVu/blob/master/notebooks/ColourMaps.ipynb

**Comment by VinceUW** [comment]
Hi Owen,

Thank you for your reply and for providing the links.

Is there any option to scale the size of arrow heads?

Cheers,

Vincent

**Comment by OKaluza** [comment]
No problem, the property you need is "arrowhead"
You can set it two ways:
[0,1] : multiple of the arrow length
>1: multiple of arrow shaft radius

**Comment by VinceUW** [comment]
Hi Owen,

Yes, I know this property. But somehow you always need to play with the arrow length if you do not want to end up with very large arrow heads. Would there be a direct way to fix the size of arrow heads (and only scale the vector length)?

Cheers,

Vincent

**Comment by OKaluza** [comment]
Sorry, there's no way of setting the arrow head size to a fixed value, the width and head are always plotted in proportion to the length.
The only suggestion I can think of now is to try setting the length and using the normalise property with a value nearer to 1 to reduce the level of length scaling so the difference between the large and small arrows is not so extreme.

I am open to suggestions for the vector plotting properties, so if you want to sketch up an example of exactly what you want to plot and submit an issue on the [LavaVu tracker](https://github.com/OKaluza/LavaVu/issues) I can look at how we could implement it.

**Comment by VinceUW** [comment]
Hi Owen,

OK, using the normalise property seems indeed the best option and that’s what I will do.

Thanks for the help!

Cheers,

Vincent
