### ISSUE TITLE
Solver warnings and scaling issues

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#267]
This is from @adambeall 

> Aside from the POSIX warnings, there are no errors and it finishes compiling. I can run models and the output looks fine. I do however get the warning "The resultant solution fields are most likely erroneous, check them thoroughly." which I don't get when running the same model on my local machine.
> 
> Sorry I didn't explain - the installed code is not scaling. When I run models with >4 cpus, its solves, but the total solve time (reported from PETSc) blows up (ie. 8 cpus takes 2x longer than 4). I'm running a simple model, which scales fine on Pawsey. UW sees multiple CPUs and they're all doing something .... but I thought maybe there was something funny happening with MPI communication during the solve. There is enough memory available and no excessive disk writing.
> 

@adambeall, are you encountering this for your models only, or also for the standard models?  Are you using any special petsc options?  Did you build your own petsc?

@julesghub, any thoughts?  The error originates here:
https://github.com/underworldcode/underworld2/blob/master/underworld/systems/_bsscr.py#L438

**Comment by adambeall** [comment]
I'll try a standard model and let you know.

I've attached my install script:
[install.txt](https://github.com/underworldcode/underworld2/files/1665641/install.txt)

Let me know if there are any PETSc flags I can switch on to provide more information.
Thanks for your help!


I get the following warning about conflicting POSIX definitions during the build, in case it's useful:


Compiling ==> PICellerator/MaterialPoints/src/CoincidentMapper.c
In file included from /software/tools/pyenv/versions/2.7.11/include/python2.7/Python.h:8:0,
                 from build/include/StGermain/Base/Context/Variable.h:14,
                 from build/include/StGermain/Base/Context/Context.h:18,
                 from build/include/StGermain/Base/Base.h:19,
                 from build/include/StGermain/StGermain.h:17,
                 from PICellerator/MaterialPoints/src/CoincidentMapper.c:11:
/software/tools/pyenv/versions/2.7.11/include/python2.7/pyconfig.h:1194:0: warning: "_POSIX_C_SOURCE" redefined
 #define _POSIX_C_SOURCE 200112L

In file included from /usr/include/stdint.h:26:0,
                 from /software/compilers/gnu/6.2.0/lib/gcc/x86_64-pc-linux-gnu/6.2.0/include/stdint.h:9,
                 from /software/compilers/intel/2017.2/impi/2017.2.174/intel64/include/mpi.h:81,
                 from PICellerator/MaterialPoints/src/CoincidentMapper.c:10:
/usr/include/features.h:213:0: note: this is the location of the previous definition
 #  define _POSIX_C_SOURCE 200809L

**Comment by rbeucher** [comment]
Don't know if it is related but we do get some POSIX warnings when importing underworld on Raijin.
I noticed that yesterday. It was not there before Christmas.

**Comment by adambeall** [comment]
It appears to only occur for a particular solver configuration and probably not related to the compile stage after all. I'll close this and reopen a new issue when I've pinpointed what the specific issue is.

Thanks!
