### ISSUE TITLE
Tutorial for parallel

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#27]
Hi all,

Could someone give me a refresher on how to invoke UW in parallel with the new Python stuff? Can you do this in IPython OK?
I saw somewhere there is a plan for a tutorial in the docs.

Cheers,
Luke

**Comment by jmansour** [comment]
Hi Luke.  There's not much magic required.. Simply run something like this:

mpirun -np 4 python yourPythonScript.py

It's probably going to be generally easier for you to simply boil down to python from your ipython.  We don't really have a workflow for parallel notebooks, though we did do some experimenting using their notebook mpi backend.  Another option is to trying using the 'runipy' command, but it (along with ipython) would need to be installed on your machine.

**Comment by OlympusMonds** [comment]
OK, thanks John!
