### ISSUE TITLE
TauHistoryFn

### ISSUE THREAD

**Issue by AngelValverdePerez** [underworldcode/underworld2#271]
I tried to have two different elastic rheologies: crust and lithosphere

tauHistory_C_Fn           = eta_eff_c / ( Shearmodulus_crust * dt_e_c ) * previousStress
tauHistory_M_Fn           = eta_eff_m / ( Bulkmodulus_lithomant * dt_e_m ) * previousStress

viscoelasticeStress_C_Fn  = viscousStressFn + tauHistory_C_Fn
viscoelasticeStress_M_Fn  = viscousStressFn + tauHistory_M_Fn    

But introducing tauHistory in Stokes...:

stokesPIC = uw.systems.Stokes( velocityField = velocityField, 
                               pressureField = pressureField,
                               voronoi_swarm = swarm, 
                               conditions    = [newVC,],
                               fn_viscosity   = viscosityMapFn, 
                               fn_bodyforce   = buoyancyFn,
                               _fn_stresshistory = [tauHistory_M_Fn,tauHistory_C_Fn])

Didn't work... how can I introduce 2 different elastic rheologies and take them into account for the stress?

**Comment by RebeccaFarrington** [comment]
Hi Angel,

I’d suggest creating a branching map for the shear modulus, as you would do for the viscosity.
You can then define the material properties for different material types.

Cheers,
Bec

**Comment by AngelValverdePerez** [comment]
Ok, I will try it, but, which elastic time I need to use in the main loop? The smallest one?

**Comment by lmoresi** [comment]
Hi angel,

You use the appropriate step for the time you are interested in modelling. See Rebecca’s paper and some earlier ones I wrote. There is a lot of thought behind the implementation that makes it stable for whichever step you choose but the physics should guide your choice.

Sent from my iPhone

On 3 Feb 2018, at 01:57, AngelValverdePerez <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I will try it, but, which elastic time I need to use in the main loop? The smallest one?

**Comment by AngelValverdePerez** [comment]
Nice! Everything clear! Closing issue
