### ISSUE TITLE
Underworld2 demo access

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#276]
I was working on a notebook over there a few , when the server became unresponsive ,https://underworld.geoanalytics.csiro.au, and now the login seems to be restricted, is there any chance of getting back access, i would be obliged if i just get the working notebook file and with temporary access?

**Comment by jmansour** [comment]
@julesghub can we get @arijitlaik access? 

@arijitlaik, I'm not sure if your previous notebooks will still be available.

**Comment by arijitlaik** [comment]
It would be great if i get access, I am new to using underworld and our University if not equipped with clusters, Thanks @jmansour

**Comment by lmoresi** [comment]
Your data should be persistent but you may find changes in the underworld image that is run on the demo. This is currently being used for a 2 day course and this will be the course notes for a few days.

By the way, this is not actually running on a cluster, so the kind of performance you get from the site is also what you would get on a typical laptop, The docker image is a good way to get this installed - you’ll see exactly the same thing as is on the demo site.

L


On 25 Feb 2018, at 4:36 am, Arijit Laik <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be great if i get access, I am new to using underworld and our University if not equipped with clusters, Thanks @jmansour<https://github.com/jmansour>

**Comment by arijitlaik** [comment]
Thanks, @lmoresi, we have a simple workstation(Single Xeon e3 processor) at out Lab were i compiled  (on Ubuntu 18.04)  underworld(development branch) , but the workstation is not on a public ip and accessing it outside our University is hugely problematic(slow network -ssh latency etc), but thankfully the demo-site provided me with something i could work on remotely, and then run them on our workstation , I currently am attempting to model simple fold‐and‐thrust belts mostly with the UWGeodynamics module by @rbeucher, I would be really glad if i could be provided access to the demo site.

**Comment by rbeucher** [comment]
I have updated the cloud. You should have access now. Give it a try. @arijitlaik

**Comment by arijitlaik** [comment]
Thanks, just did. should i revoke github permissions and try again @rbeucher 
![screenshot_2018-03-05_05-44-29](https://user-images.githubusercontent.com/10157121/36952618-5aa3ad94-2038-11e8-97ff-eaba5cd82643.png)
