### ISSUE TITLE
global index on swarm

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#277]
The functionality to create a global index is disabled. Was that because of restarting difficulties???
https://github.com/underworldcode/underworld2/blob/659bececdf5abe9331b5a48ed85b7ecda29f700b/underworld/swarm/_swarmabstract.py#L120

We need it working again... 

I propose using a swarmvariable and some mpi4py to evaluate the global ids. 
Need to remember that population control and a global id won't play well together and, of course, test in under a checkpoint-restart.

**Comment by jmansour** [comment]
Was this ever available in Python?  I notice in the C library, we create the variable, but don't do anything with it. I have vague recollections of potentially there being some issues in the migration to Python. 

My preferred schema for the global id is to store 2 ints,  

1. rank particle was created on
2. increment on that rank.. (max ~2billion).

This would allow us to add particles global ids without any communications.  It will play fine with population control too, just as long as no more than 2 billion particles are created on any given process.  Even in that case, there are some further measures that could be taken.

**Comment by lmoresi** [comment]
As long as the id is stored as an entity that supports testing for equality then it should be alright, right ?

e.g. as a tuple of those 2 ints ?   Not sure though, if we just want a single value in a numpy array - some sort of hash ?

L



On 27 Feb 2018, at 1:23 pm, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Was this ever available in Python? I notice in the C library, we create the variable, but don't do anything with it. I have vague recollections of potentially there being some issues in the migration to Python.

My preferred schema for the global id is to store 2 ints,

  1.  rank particle was created on
  2.  increment on that rank.. (max ~2billion).

This would allow us to add particles global ids without any communications. It will play fine with population control too, just as long as no more than 2 billion particles are created on any given process. Even in that case, there are some further measures that could be taken.

**Comment by rbeucher** [comment]
+1

**Comment by jmansour** [comment]
We could easily construct a 64bit int from two 32bit ints.  The first 32bits are for rank, the second for the unique (processor wise) increment.  Thus we'd have an array of long ints which are easier to use for comparison (if perhaps ugly looking numbers).

From python, we could then provide 2 views to this data.. the long int view (or comparison purposes), or the tuple (rank, index) view  (potentially useful for determine particle origins etc).

**Comment by jmansour** [comment]
Ok, this looks good.  

While the numbers are ugly, in a way this is better than neatly incremented numbers which may be misleading for users, especially in the transition to parallel.  We should ensure that the numbers are ugly even for serial operation.

**Comment by rbeucher** [comment]
@jmansour, It looks like swarm variable only support int, float and double datatype. int is int32 right?
When I assigned my int64 array, values gets truncated.
Any chance we can get int64 support on swarm variables?

**Comment by jmansour** [comment]
Hey @rbeucher, I've added the 'long' type.  After pulling, you will need to recompile, and also rerun swig.

**Comment by rbeucher** [comment]
Thanks @jmansour!! Will have a go

**Comment by rbeucher** [comment]
Thanks @jmansour!! Will have a go

**Comment by rbeucher** [comment]
OK just to clarify we now have "short" (16bits) and "int" (32 bits)? @jmansour 
I thought we wanted to store  a 64bits int ("long long int" if I'm correct). 
I don't think a 16 bits int is enough for a local particle index. We will get far more particles than 2**16.
R

**Comment by rbeucher** [comment]
Sorry,my  bad. There is short int and long... Fine!!!

**Comment by jmansour** [comment]
Yep!  Here's the test:

https://github.com/underworldcode/underworld2/blob/development/docs/test/swarmvariable_types.ipynb

**Comment by rbeucher** [comment]
Yes sorry, I was using a wrong version of my docker image

**Comment by julesghub** [comment]
Nearly there, now we just need to create a demo notebook that makes use of a globalId.
