### ISSUE TITLE
PCDVC python interface 

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#28]
Following on from https://github.com/underworldcode/underworld2/issues/26

* Can we access the Inflow population control routine through Python? 
* Does this happen automatically if I set 
  swarm.particleEscape = True   ?

**Comment by jmansour** [comment]
No you'll need to set this option via the "particleEscape" Swarm
constructor parameter.  Setting it later won't work (that attribute should
be private really).

Generally, the population control mechanisms aren't really exposed at the
python layer yet.

**Comment by julesghub** [comment]
#83
