### ISSUE TITLE
checkpoint setting raises different results from models starting from timestep zero

### ISSUE THREAD

**Issue by yanghappy1991** [underworldcode/underworld2#280]

**Comment by yanghappy1991** [comment]
# coding: utf-8

# The constant extension rate 1e-14 (unit: 1/second) is applied box two sides. Setting extremely large yielding strength, it behaves like a viscoelastic rheology while a relatively small one for yieldstrenghFn produces a plastic behavior.

# In[1]:

import underworld as uw
from underworld import function as fn
import glucifer
uw.matplotlib_inline()

import matplotlib.pyplot as pyplot
pyplot.ion()  # this is need so that we don't hang on show() for pure python runs
import numpy as np
import math
import os
import mpi4py
comm = mpi4py.MPI.COMM_WORLD

from unsupported.lithopress import lithoPressure
#from unsupported.LMR import *
import unsupported.scaling as sca
from unsupported.scaling import nonDimensionalize as nd


LoadFromFile = True

outputPath = os.path.join(os.path.abspath("."),"output/checkPointTestContinue8/")
inputPath = os.path.join(os.path.abspath("."),"output/checkPointTest/")
if uw.rank() == 0:
    if not os.path.exists(outputPath):
        os.makedirs(outputPath)
uw.barrier()


if(LoadFromFile == True):
    step = 8
    fo = open(inputPath+"time"+str(step).zfill(4),"r")
    t = fo.read()
    time = float(t)
else:
    step = 0
    time = 0.  # Initial time

nsteps = 1501

u = sca.UnitRegistry

# Define scale criteria
tempMin = 273.*u.degK 
tempMax = (1400.+ 273.)*u.degK
bodyforce = 3300 * u.kilogram / u.metre**3 * 9.81 * u.meter / u.second**2
velocity = 1e-9*u.meter/u.second

KL = 100e3*u.meter
Kt = KL/velocity
KT = tempMax 
KM = bodyforce * KL**2 * Kt**2
K  = 1.*u.mole
lengthScale = 100e3

sca.scaling["[length]"] = KL
sca.scaling["[time]"] = Kt
sca.scaling["[mass]"]= KM
sca.scaling["[temperature]"] = KT
sca.scaling["[substance]"] = K

gravity = nd(9.81 * u.meter / u.second**2)
R = nd(8.3144621 * u.joule / u.mole / u.degK)

elementType = "Q1/dQ0"  
    
resX = 64
resY = 64
materialA = 0
  
minX  = nd(-0.5e2 * u.kilometer)
maxX  = nd(0.5e2 * u.kilometer)
minY  = 0.
maxY  = nd(1.0e2 * u.kilometer)
  

mesh = uw.mesh.FeMesh_Cartesian( elementType = (elementType), 
                                 elementRes  = ( resX, resY), 
                                 minCoord    = ( minX, minY), 
                                 maxCoord    = ( maxX, maxY),
                                 periodic    = [False, False]  ) 



velocityField    = uw.mesh.MeshVariable( mesh=mesh,         nodeDofCount=mesh.dim )
pressureField    = uw.mesh.MeshVariable( mesh=mesh.subMesh, nodeDofCount=1 )

velocityField.data[:] = [0.,0.]
pressureField.data[:] = 0.


#  Boundary conditions
 
# Pure shear with moving  walls — all boundaries are zero traction with 

# In[4]:

iWalls = mesh.specialSets["MinI_VertexSet"] + mesh.specialSets["MaxI_VertexSet"]
jWalls = mesh.specialSets["MinJ_VertexSet"] + mesh.specialSets["MaxJ_VertexSet"]
base   = mesh.specialSets["MinJ_VertexSet"]
top    = mesh.specialSets["MaxJ_VertexSet"]

allWalls = iWalls + jWalls

Vy = nd(4*u.centimeter/u.year)

for index in mesh.specialSets["MinI_VertexSet"]:
    velocityField.data[index] = [0., Vy]        
for index in mesh.specialSets["MaxI_VertexSet"]:
    velocityField.data[index] = [ 0., 0.]

       
velocityBCs = uw.conditions.DirichletCondition( variable        = velocityField, 
                                                indexSetsPerDof = (iWalls+jWalls, iWalls) )


    


swarm  = uw.swarm.Swarm( mesh=mesh,particleEscape=True )
pop_control = uw.swarm.PopulationControl(swarm,aggressive=True,particlesPerCell=60)
frictionInf  = swarm.add_variable( dataType="double",  count=1 )
cohesion  = swarm.add_variable( dataType="double",  count=1 )

advector        = uw.systems.SwarmAdvector( swarm=swarm,            velocityField=velocityField, order=2 )

plasticStrain  = swarm.add_variable( dataType="double",  count=1 )
materialVariable = swarm.add_variable( dataType="int", count=1 )

if(LoadFromFile == True):    
    swarm.load(inputPath+"swarm"+str(step).zfill(4))
    #import ipdb; ipdb.set_trace()
    materialVariable.load(inputPath+"materialVariable"+str(step).zfill(4))   
    velocityField.load(inputPath+"velocityField"+str(step).zfill(4))
    plasticStrain.load(inputPath+"plasticStrain"+str(step).zfill(4))    

        
if(LoadFromFile == False): 
    swarmLayout = uw.swarm.layouts.GlobalSpaceFillerLayout( swarm=swarm, particlesPerCell=80 )
    swarm.populate_using_layout( layout=swarmLayout )


    plasticStrain.data[:] = 0.
    dx = 2 * 0.5*maxY/resY
    faultShape1  = np.array([ (0.- dx,maxY/2-dx), (0.+dx,maxY/2-dx),(0.+dx,maxY/2+dx),(0.-dx,maxY/2+dx)])
    fault1 = fn.shape.Polygon( faultShape1 )

    plasticStrain.data[:] = 0.
    for index in range( len(swarm.particleCoordinates.data) ):
        coord = swarm.particleCoordinates.data[index][:]        
        if (fault1.evaluate(tuple(coord))):
            plasticStrain.data[index] = 2.


 
    coord = fn.input()
    conditions = [
                  (       True ,           materialA ) ]


    materialVariable.data[:] = fn.branching.conditional( conditions ).evaluate(swarm)


    
C0 = nd(2.0e7* u.pascal)
F0 = 0.4
C1 = nd(2.0e6* u.pascal)
F1 = 0.02

strainLow = 0.5
strainUp = 1.5
cohesion.data[:]  = C0
frictionInf.data[:]  = F0 
# Drucker-Prager yield criterion
for index, coord in enumerate(swarm.particleCoordinates.data):

    if plasticStrain.data[index]>strainLow  and plasticStrain.data[index]<=strainUp:
        cohesion.data[index] = C0+(C1-C0)/(strainUp-strainLow)*(plasticStrain.data[index]-strainLow)
        frictionInf.data[index]  = F0+(F1-F0)/(strainUp-strainLow)*(plasticStrain.data[index]-strainLow)

    if plasticStrain.data[index] >strainUp:
        cohesion.data[index]  = C1
        frictionInf.data[index]  = F1
yieldStressFn   = cohesion  + frictionInf * pressureField        



densityMap = { materialA: 0.0}

densityFn = fn.branching.map( fn_key=materialVariable, mapping=densityMap )

# And the final buoyancy force function. For the benchmark model, no bouyancy is considered.
z_hat = ( 0.0, 0.0 )      
buoyancyFn = -densityFn * z_hat





viscosityA = nd(1e22 * u.pascal * u.second) 
strainRateFn = fn.tensor.symmetric( velocityField.fn_gradient )
strainRate_2ndInvariantFn = fn.tensor.second_invariant(strainRateFn)+nd(1e-18/u.second)
min_viscosity = nd(1e18*u.pascal*u.second)   


mappingDictViscosity   = { materialA: viscosityA}
viscosityMapFn   = fn.branching.map( fn_key=materialVariable, mapping=mappingDictViscosity )

yieldingViscosityFn =  0.5 * yieldStressFn / strainRate_2ndInvariantFn
#viscosityFn = fn.exception.SafeMaths( fn.misc.max( 
#                                                              viscosityMapFn,min_viscosity))
viscosityFn = fn.exception.SafeMaths( fn.misc.max(fn.misc.min(yieldingViscosityFn, 
                                                              viscosityMapFn), min_viscosity))
stressMapFn = 2.0 * viscosityFn*strainRateFn

stokes = uw.systems.Stokes(velocityField = velocityField, 
                           pressureField = pressureField,
                           voronoi_swarm = swarm, 
                           conditions    = velocityBCs,
                           fn_viscosity  = viscosityFn, 
                           fn_bodyforce  = buoyancyFn)   

solver = uw.systems.Solver( stokes )


if(uw.nProcs()==1):
    solver.set_inner_method("lu")
else:
    solver.set_inner_method('mg') 
solver.set_penalty(1.0e0) 


#solver.options.scr.ksp_rtol = 1.0e-3

# test it out



# In[17]:

surfaceArea = uw.utils.Integral(fn=1.0,mesh=mesh, integrationType='surface', surfaceIndexSet=top)
surfacePressureIntegral = uw.utils.Integral(fn=pressureField, mesh=mesh, integrationType='surface', surfaceIndexSet=top)


def second_invariant(intensor):
    return fn.math.sqrt(
                0.5*(intensor[0]*intensor[0]+ 
                     intensor[1]*intensor[1]+
                     intensor[2]*intensor[2])
    )   

time_factor = nd(1*u.year)

def update():
    # get timestep and advect particles
    dt = advector.get_max_dt()
     
    print dt/time_factor       
    advector.integrate(dt)

    # particle population control
    pop_control.repopulate()
    
   
    # update plastic strain
    swarmYield = viscosityMapFn.evaluate(swarm) > viscosityFn.evaluate(swarm)
 
    swarmStrainRateInv = strainRate_2ndInvariantFn.evaluate(swarm)
    
    plasticStrainIncrement = dt * np.where(swarmYield, swarmStrainRateInv , 0.0 )
    plasticStrain.data[:] += plasticStrainIncrement

            
    return time+dt, step+1




while step<nsteps:
    # Obtain V,P and remove null-space / drift in pressure

    solver.solve( nonLinearIterate=True,  nonLinearTolerance=1e-5, nonLinearMaxIterations=30)
    
    (area,) = surfaceArea.evaluate()
    (p0,) = surfacePressureIntegral.evaluate() 
    pressureField.data[:] -= p0 / area
    

    
    if (step%2 ==0):  
        
        meshViscosity = uw.mesh.MeshVariable( mesh, 1 )
        projectorViscosity = uw.utils.MeshVariable_Projection( meshViscosity,viscosityFn, type=0 )
        projectorViscosity.solve() 
        
        meshAllStress = uw.mesh.MeshVariable( mesh, 1 )
        allStress = fn.tensor.second_invariant(stressMapFn)
        projectorStress = uw.utils.MeshVariable_Projection( meshAllStress, allStress, type=0 )
        projectorStress.solve() 
        
        
        mesh.save(outputPath+"mesh"+str(step).zfill(4))
        meshViscosity.save(outputPath+"meshViscosity"+str(step).zfill(4))
        meshAllStress.save(outputPath+"meshAllStress"+str(step).zfill(4)) 
        swarm.save(outputPath+"swarm"+str(step).zfill(4))
        materialVariable.save(outputPath+"materialVariable"+str(step).zfill(4))
        velocityField.save(outputPath+"velocityField"+str(step).zfill(4))

        pressureField.save(outputPath+"pressureField"+str(step).zfill(4))
        plasticStrain.save(outputPath+"plasticStrain"+str(step).zfill(4))        
        
        fo = open(outputPath+"time"+str(step).zfill(4),"w")
        print >> fo, time
        fo.close()
        
        dicMesh = { 'elements' : mesh.elementRes, 
                    'minCoord' : mesh.minCoord,
                    'maxCoord' : mesh.maxCoord}

        fo = open(outputPath+"dicMesh"+str(step).zfill(4),'w')
        fo.write(str(dicMesh))
        fo.close()       
        
    if uw.rank()==0:   
        print('step = {0:6d}; time = {1:.3e};'.format(step,time/time_factor))
    uw.barrier()
    
    # finished timestep, update all
    time, step = update()

**Comment by jmansour** [comment]
Hi there

Can you give some more details about your issue?

**Comment by lmoresi** [comment]
Is the viscoelastic stored stress being reloaded correctly ?

Sent from my iPhone

On 8 Mar 2018, at 08:30, yanghappy1991 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi John,

For two cases, model1 starting from timestep 0 to timestep 10, model2
starting from timestep 8 of model1, comparing timestep from model1 and
model2, I find they are different in the results.

Model1,

*LoadFromFile = False*

Model2

*LoadFromFile = True *

outputPath = os.path.join(os.path.abspath("."),"output/checkPointTestContinue8/")
inputPath = os.path.join(os.path.abspath("."),"output/checkPointTest/")if
uw.rank() == 0:
if not os.path.exists(outputPath):
os.makedirs(outputPath)
uw.barrier()

if(LoadFromFile == True):
*step = 8*
fo = open(inputPath+"time"+str(step).zfill(4),"r")
t = fo.read()
time = float(t)else:
step = 0
time = 0. # Initial time

Please try these two models to see the differences!


Cheers,

Haibin

**Comment by yanghappy1991** [comment]
It is a viscoplastic model, so the stored stress is not considered here.

**Comment by julesghub** [comment]
Hi @yanghappy1991 any updates on this model? Is it still an issue for you?

**Comment by yanghappy1991** [comment]
no problem any more!
Thanks!
