### ISSUE TITLE
Explicitly setting penalty to 0.0 not equivalent to not setting anything.

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#283]
Hi All,

I am playing with the penalty (and MUMPS).
I have different results when setting the penalty to 0. and when I don't use the penalty setter.
Looks like using the penalty setter somehow triggers internal machinery that should (?) not be used...

See simplified example (comment and uncomment solver.set_penalty())
[Model_Simple_Extension.zip](https://github.com/underworldcode/underworld2/files/1817571/Model_Simple_Extension.zip)

R

**Comment by jmansour** [comment]
Is penalty set to zero with mumps valid?

**Comment by rbeucher** [comment]
Well I don't know. I expect it to be "no penalty"
If you look at the "main" options of the solver object the penalty is 0 by default.
solver.options.main

**Comment by rbeucher** [comment]
Playing with the penalty value is interesting. You get spurious results at the bottom corners. Not sure why.

**Comment by lmoresi** [comment]
The equations with penalty set to zero are not changed from those without the penalty (formally in the mathematics and in the code as it simply multiplies the added matrix)

BUT- Julian added some logic to make sure that the compressible terms and penalty are not used together and I wonder if some differences occur in the case of penalty None v. Penalty 0 or some such minor thing.

Maybe a choice of preconditioning that is disallowed with the penalty ?

Sent from my iPhone

On 16 Mar 2018, at 12:53, rbeucher <notifications@github.com<mailto:notifications@github.com>> wrote:


Well I don't know. I expect it to be "no penalty"
If you look at the "main" options of the solver object the penalty is 0 by default.
solver.options.main
