### ISSUE TITLE
Surface Tracking and basic Diffusion questions / porting from GALE/Underworld1

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#285]
Hi all,
I would like to know what would be the most suitable way of diffusing an interface (sticky air and sediment), with inflow boundaries on the left and or right in Underworld2, Gale had a surface plugin? anyway that could be ported into Underworld2, with our without a mesh deformation, using pybadlands with the linkage module for a basic hillslope diffusion is a bit overkill for 2d models, suggestion.
although #282 has some code on doing it with python i would like to know what are the options within Underworld to do that.

Moreover, I guess an issue may not be appropriate for this question, i am open guidance via emails.

**Comment by jmansour** [comment]
I'm not quiet sure I understand what you mean by 'diffusing an interface'.  Are you talking about surface process type dynamics?

Inflow boundary conditions should be straightforward enough. 

This is a perfectly fine place for these type of questions. Although it's called an 'issue tracker' at github, we use it for all Underworld usage discussion.

**Comment by arijitlaik** [comment]
exactly: "talking about surface process type dynamics:, basic hillslope diffusion of the sticky air and material/sediment interface for example 

![](https://raw.githubusercontent.com/arijitlaik/Underworld2-Wedge_Models/master/medresThrustWedge_15/Material_2.8%20megayear.png)

My basic model code is in my repo
https://github.com/arijitlaik/Underworld2-Wedge_Models

**Comment by arijitlaik** [comment]
@jmansour  Any ideas/help on this?

**Comment by rbeucher** [comment]
There is no plan to implement that in Underworld for now. I am working on things in UWGeodynamics as you know and they might be included in Underworld in the future but that is pretty low on the to-do list...

It is rather straightforward to implement a finite difference solution in numpy, especially in serial. Parallelism requires a bit more thinking but that can be done (needs a global index and some spline magic I think).

**Comment by arijitlaik** [comment]
Fine, then. :+1:  closing the issue
