### ISSUE TITLE
velocity boundary

### ISSUE THREAD

**Issue by huilin0302** [underworldcode/underworld2#29]
Hi,   I am new to Underworld.  Right now,  I am trying to set different velocities at side boundaries using Stepfunction.    I already tried using uniform velocity at side boundaries and the results turns out all right.   But when I use step function (convergent in the upper part and Vx=0 in the lower part of model), there are no velocity  shown in result.  Does anyone know where is wrong?  I attached my input file here.  

<StGermainData xmlns="http://www.vpac.org/StGermain/XML_IO_Handler/Jun2003">

  <list name="import">
     <param>Underworld</param>
  </list>

  <include>/Users/InputFiles/BaseApps/ExtensionBaseApp.xml</include>

  <list name="plugins" mergeType="merge">
     <struct>
        <param name="Type">StgFEM_FrequentOutput</param>
        <param name="Context">context</param>
     </struct>
     <struct>
        <param name="Type">Underworld_Vrms</param>
        <param name="Context">context</param>
        <param name="GaussSwarm">gaussSwarm</param>
        <param name="VelocityField">VelocityField</param>
     </struct>
     <struct>
        <param name="Type">StgFEM_CPUTime</param>
        <param name="Context">context</param>
     </struct>
      <struct>
         <param name="Type">StgFEM_StandardConditionFunctions</param>
         <param name="Context">context</param>
      </struct>
  </list>

  <struct name="components" mergeType="merge">

   
   <struct name="viscosityLimiter">
     <param name="Type">ViscosityLimiter</param>
     <param name="maxViscosity" units="Pa*s">10e24</param>
     <param name="minViscosity" units="Pa*s">1e0</param>
   </struct>

     
     
     <struct name="default_scaling">
        <param name="Type">Scaling</param>
        <param name="spaceCoefficient_meters"> 1e6 </param>
        <param name="timeCoefficient_seconds"> 316.223 </param>
        <param name="massCoefficient_kilograms"> 8e19 </param>
        <param name="temperatureCoefficient_kelvin"> 1 </param>
     </struct>

     
     <struct name="upperMantleShape">
        <param name="Type">Everywhere</param>
     </struct>
     <struct name="lowerMantleShape">
        <param name="Type">Box</param>
        <param name="startX" units="km">0.0</param>
        <param name="endX" units="km">4000</param>
        <param name="startY" units="km">0.0</param>
        <param name="endY" units="km">350</param>
     </struct>
     <struct name="ContinentShape">
        <param name="Type">Box</param>
        <param name="startX" units="km">0</param>
        <param name="endX" units="km">0</param>
        <param name="startY" units="km">0</param>
        <param name="endY" units="km">0</param>
     </struct>
	<struct name="mainSlab">
        <param name="Type">Box</param>
        <param name="startX" units="km">1200</param>
        <param name="endX" units="km">3400</param>
        <param name="startY" units="km">900</param>
        <param name="endY" units="km">1000</param>
     </struct>
     <struct name="slabPerturbation">
        <param name="Type">PolygonShape</param>
        <list name="vertices">
           <asciidata>
              <columnDefinition name = "x" type="double" units="km"/>
              <columnDefinition name = "y" type="double" units="km"/>
              1200   1000 
              1200   900 
              1020   800 
              1020   900 
           </asciidata>
        </list>
     </struct>
     <struct name="slabShape">
        <param name="Type">Union</param>
        <list name="shapes">
           <param>mainSlab</param>
           <param>slabPerturbation</param>
        </list>
     </struct>

     
     <struct name="upperMantleViscosity">
        <param name="Type">MaterialViscosity</param>
        <param name="eta0" units="Pa*s">1e20</param>
     </struct>
     <struct name="upperMantle">
        <param name="Type">RheologyMaterial</param>
        <param name="Shape">upperMantleShape</param>
        <param name="density" units="kg*m^-3">3300</param>
        <param name="Rheology">upperMantleViscosity</param>
     </struct>

     
     <struct name="lowerMantleViscosity">
        <param name="Type">MaterialViscosity</param>
        
        <param name="eta0" units="Pa*s">1e22</param>
     </struct>
     <struct name="LowerMantle">
        <param name="Type">RheologyMaterial</param>
        <param name="Shape">lowerMantleShape</param>
        <param name="density" units="kg*m^-3">3300</param>
        <param name="Rheology">lowerMantleViscosity</param>
     </struct>

     
     <struct name="ContinentViscosity">
        <param name="Type">MaterialViscosity</param>
        
        <param name="eta0" units="Pa*s">1e20</param>
     </struct>
     <struct name="Continent">
        <param name="Type">RheologyMaterial</param>
        <param name="Shape">ContinentShape</param>
        <param name="density" units="kg*m^-3">3300</param>
        <param name="Rheology">ContinentViscosity</param>
     </struct>

     
     <struct name="slabViscosity">
        <param name="Type">MaterialViscosity</param>
        
        <param name="eta0" units="Pa*s">1e22</param>
     </struct>
     <struct name="slabYielding">
        <param name="Type">Byerlee</param>
        <param name="StrainRateField">StrainRateField</param>
        <param name="BlockGeometry">geometry</param>
        <param name="FeMesh">linearMesh</param>
        <param name="cohesion" units="Pa">32e6</param>
        <param name="depthCoefficient">0.25</param>
     </struct>
     <struct name="Slab">
        <param name="Type">RheologyMaterial</param>
        <param name="Shape">slabShape</param>
        <param name="density" units="kg*m^-3">3380</param>
        <list name="Rheology">
           <param>slabViscosity</param>
           <param>slabYielding</param>
        </list>
     </struct>
     
     <struct name="SlabField">
        <param name="Type">MaterialFeVariable</param>
        <param name="Swarm">picIntegrationPoints</param>
        <param name="Material">Slab</param>
        <param name="Context">context</param>
        <param name="Mesh">linearMesh</param>
     </struct>

     
     <struct name="LowerMantleField">
        <param name="Type">MaterialFeVariable</param>
        <param name="Swarm">picIntegrationPoints</param>
        <param name="Material">LowerMantle</param>
        <param name="Context">context</param>
        <param name="Mesh">linearMesh</param>
     </struct>
  </struct>

   <struct name="leftBoundaryShape">
     <param name="Type">Box</param>
     <param name="startX">minX</param>
     <param name="endX">0.1</param>
     <param name="startY">minY</param>
     <param name="endY">maxY</param>
   </struct>

  <param name="journal.info.Context-verbose">true</param>
  <param name="journal.debug">t</param>
  <param name="journal-level.info.Stg_ComponentFactory">2</param>
  <param name="journal-enable-branch.debug.StgFEM">t</param>
  <param name="journal-level-branch.debug.StgFEM">2</param>
  <param name="journal-enable-branch.debug.Swarm">f</param>
  <param name="journal-level-branch.debug.Swarm">2</param>
  <param name="journal-level.debug.lucDebug">2</param>
  <param name="journal-enable-branch.debug.lucDebug">f</param>

  
  <param name="maxTimeSteps">1</param>
  <param name="dumpEvery">1</param>
  <param name="outputPath">./output/Subduction_BC</param>
  <param name="gravity" units="m*s^-2">9.8</param>   
  <param name="checkpointEvery">0</param>

  

  

  
  <param name="dim">2</param>
  
  <param name="elementResI">128</param>
  <param name="elementResJ">64</param>

  <param name="shadowDepth">1</param>
  <param name="minX" units="km"> 0 </param>
  <param name="maxX" units="km"> 4000 </param>
  <param name="minY" units="km"> 0 </param>
  <param name="maxY" units="km"> 1000 </param>
  <param name="allowUnbalancing">True</param>
  <param name="buildElementNodeTbl">True</param>

  
  <param name="nonLinearMaxIterations">20</param>

  
  <param name="particlesPerCell">20</param>
 <param name="gaussParticlesX">2</param>
 <param name="gaussParticlesY">2</param>
 <param name="gaussParticlesZ">2</param>

       <struct name="EulerDeform">
		<list name="systems">

                       <struct>
                               <param name="mesh"> velocityMesh </param>
                               <param name="remesher">velocityRemesher</param>
                               <param name="velocityField"> VelocityField </param>
                               <list name="fields">
                                       <struct>
                                               <param name="field">VelocityField</param>
                                               <param name="variable">velocity</param>
                                       </struct>
                               </list>
                       </struct>
               </list>
       </struct>/struct>

  
  <include>/Users/huilin/Downloads/InputFiles/velocityBCs_HL.xml</include>

       
       <include>Underworld/Viewports/ParticleMaterialVP.xml</include>
       <include>Underworld/Viewports/VelocityMagnitudeVP.xml</include>
       <include>gLucifer/window.xml</include>
       <struct name="components" mergeType="merge">
        	<struct name="window" mergeType="merge">
          		<param name="Viewport">ParticleMaterialVP VelocityMagnitudeVP</param>
        	</struct>
       </struct>

</StGermainData>

<?xml version="1.0"?>
<!DOCTYPE StGermainData SYSTEM "stgermain.dtd">

<StGermainData xmlns="http://www.vpac.org/StGermain/XML_IO_Handler/Jun2003">

	
	<struct name="velocityBCs">
		<param name="type">CompositeVC</param>
		<list name="vcList">
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> bottom </param>
				<list name="variables">
					<struct>
						<param name="name">vy</param>
						<param name="type">double</param>
		           			<param name="value"> 0 </param>
                                       </struct>
				</list>
			</struct>
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> left </param>
				<list name="variables">
					<struct>
						<param name="name">vx</param>
						<param name="type">func</param>
                                               <param name="value">StepFunctionProduct2</param>
					</struct>
				</list>
			</struct>
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> right </param>
				<list name="variables">
					<struct>
						<param name="name">vx</param>
						<param name="type">func</param>
                                               <param name="value">StepFunctionProduct1</param>
					</struct>
				</list>
			</struct>
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> front </param>
				<list name="variables">
					<struct>
						<param name="name">vz</param>
						<param name="type">double</param>
                                               <param name="value"> 0 </param>
					</struct>
				</list>
			</struct>
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> back </param>
				<list name="variables">
					<struct>
						<param name="name">vz</param>
						<param name="type">double</param>
                                               <param name="value"> 0 </param>
					</struct>
				</list>
			</struct>
			<struct>
				<param name="type"> WallVC </param>
				<param name="wall"> top </param>
				<list name="variables">
					<struct>
						<param name="name">vy</param>
						<param name="type">double</param>
                                               <param name="value"> 0 </param>
					</struct>
				</list>
			</struct>
		</list>
	</struct>
<param name="StepFunctionProduct1Start">0.3</param>
<param name="StepFunctionProduct1End">0.7</param>
<param name="StepFunctionProduct1Value">e-11</param>
<param name="StepFunctionProduct2Start">0.3</param>
<param name="StepFunctionProduct2End">1</param>
<param name="StepFunctionProduct2Value">e-11</param>
</StGermainData>

**Comment by jmansour** [comment]
Your model files are haven't uploaded correctly. Perhaps tarball/zip them and upload them somewhere. 

But are you trying to use a step boundary condition and a deforming mesh?  I can't imagine this would end well, as the mesh would turn to rubbish very quickly.

**Comment by huilin0302** [comment]
Thanks for your responds!  I am trying to construct a subduction model that lithosphere are converging and underlying mantle could flow out.   I have no clue what kind of meshing method is suitable here.  I would appreciate if you could help me with this.  I convert model files to a PDF and upload here. 
[SubductionTest.pdf](https://github.com/underworldcode/underworld2/files/31279/SubductionTest.pdf)

**Comment by jmansour** [comment]
Perhaps you can draw a diagram of exactly what you are hoping to achieve?  Also, I'd suggest if you are just starting to use Underworld, you should switch to using Underworld2, as the original Underworld is no longer being developed.

**Comment by huilin0302** [comment]
Hi,  I draw two diagrams.  The upper one has both inflow and outflow at side boundaries.  I hope to keep side boundaries fixed.  I tried to modify viscous_inflow.xml in Gale cookbook to achieve this.  But the model does't to converge.  

Another way I think could work for me is compressing the side boundaries and allow materials flow out from lower boundary.  In order to keep mass balance in the model domain, the lower boundary may need StressBC.  I looked at input examples of Underworld. Will ExtensionIncompressibleQ1Q1CompensatedFreeBaseApp.xml suitable for this situation?  

Another question:  does Underworld has phase change? Like when one material particles gets to a certain pressure and/or temperature field, they can change to another material with different viscosity and/or density?  Thanks!

![subduction](https://cloud.githubusercontent.com/assets/15789625/11221004/9c3a082c-8d17-11e5-80fe-2d129b14e100.jpg)

**Comment by jmansour** [comment]
Yes, you would have to be careful that you do not violate mass conservation, or else you will encounter big difficulties with the solver.  

You might even try only enforcing the  BCs for the lithosphere, having no-slip on the bottom, and then having 'open' for the mantle (ie, don't prescribe anything).  This way you won't have any conservation issues.  

Alternatively, you might set the boundary conditions as close to mass equilibrium as possible (equal inflow to outflow), but also include a small compressible layer which might take up any _slack_.  

We do not currently have stress BC, but they will be available in the near future (in Underworld2).  

I can't really give recommendations on any XML files in honesty.  Many of these are broken and outdated.  Underworld2 is the solution.  Also, you can easily implement phase change in Underworld2.  Did I mention Underworld2?  

You can find some tutorials here:
https://github.com/underworldcode/underworld2/tree/development/docs/tutorials

**Comment by OlympusMonds** [comment]
Hi John, how would one leave the mantle open in UW2? Doesn't everything fall out the bottom due to gravity? <sorry to derail>

**Comment by huilin0302** [comment]
Thanks for your reply and information about underworld2.  I was trying to install underworld2, but I met an error when configure it.   It says "Failed to locate required package HDF5."   But I already has install hdf5-1.8.16 on my mac.  Do you have any idea where goes wrong? 

scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... no

****  ERROR ****
Failed to locate required package HDF5.
Details in 'config.log'

**Comment by jmansour** [comment]
Luke, I believe it should be sufficiently constrained to prevent everything falling out the bottom... whether it's sufficiently physical is another question. 

huilin, perhaps you'd like to give dockers a shot:

http://www.underworldcode.org/posts/Underworld-and-Dockers/

**Comment by lmoresi** [comment]
Maybe - but beware the null space

Sent from my iPhone

On 19 Nov 2015, at 14:26, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Luke, I believe it should be sufficiently constrained to prevent everything falling out the bottom... whether it's sufficiently physical is another question.

huilin, perhaps you'd like to give dockers a shot:

http://www.underworldcode.org/posts/Underworld-and-Dockers/

**Comment by huilin0302** [comment]
Thanks!  I'll try Underworld2.
