### ISSUE TITLE
matplotlib (kiwisolver) causes segfault

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#292]
This package (required in recent versions of matplotlib) conflicts with Underworld for some reason.  

If you import `kiwisolver` (via matplotlib) after you import `underworld`, segfault results.  If you import kiwisolver first, everything works fine.  Also, I believe it occurs the other way around on some platforms too (though can't 100% remember).

**Comment by jmansour** [comment]
Note that we currently have a hack in our dockers which ensures kiwisolver is always imported first:

https://github.com/underworldcode/underworld2/blob/development/docs/development/docker/underworld2_untested/Dockerfile#L55

**Comment by OKaluza** [comment]
Currently on the development branch tests are failing (1_05_StokesSinker.ipynb) due to this bug, so I checked in a workaround

Strangely utils/run_tests.py seems to lock up and never return from subprocess.check_call() if this segfault occurs

**Comment by jmansour** [comment]
@OKaluza  yeah I've noticed this about the test runner.  Not sure on solution, but it is annoying.  

Commit above resolves this.
