### ISSUE TITLE
SLADE crashes with deformed mesh in parallel 

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#294]
the slade system crashes when the mesh is deformed and running in parallel (but not in serial) .

There's a notebook setup to reproduce the crash here:

https://github.com/dansand/issues/blob/master/slade_par/2DCosineHillAdvection.ipynb

**Comment by julesghub** [comment]
gdb traces the error in parallel back to here.
https://github.com/underworldcode/underworld2/blob/845d877f7159be06545da998c14e938ae1268d9e/libUnderworld/StgFEM/Utils/src/SemiLagrangianIntegrator.c#L470

**Comment by julesghub** [comment]
64282ab414f9fd2c0ed61234921a6bad0a04e69d addresses the issue above. The issue was caused by the cubic interpolant assuming element widths were constant across each processor. Now using a dynamic element width per interpolant. Not perfect but it's a fix.
@dansand, please test, comment and close.

**Comment by dansand** [comment]
At the moment Slade is working with uniform mesh, Q1 elements, but has substantial problems for deformed meshes, and Q2 elements.  
  
The fix we implemented for a deformed mesh was only partially successful. It enabled us to run the toy model (see the first post in this thread) but fell down when I tried to run a subduction model: there were two specific problems: first, there were clearly artefacts developing at processor boundaries, second, even with the switch to a 'dynamic element width', the code still occasionallly tries to search for data on spurious global element numbers, and crashes. 

I'll close this for now

**Comment by jmansour** [comment]
Sounds like it's far from resolved.

**Comment by lmoresi** [comment]
I think we should thoroughly benchmark this for the serial case and make sure it works well.

First with a regular mesh, then with a distorted mesh.

Then we have something to target in parallel.

L

On 4 Jun 2018, at 8:49 am, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds like it's far from resolved.
