### ISSUE TITLE
Review all examples for parallel safety and scalability

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#295]
In a lot of our examples/tests/etc, we import `mpi4py` to extract rank/nproc information, however we should obtain this information via the `underworld` provided methods  (`uw.rank()` and `uw.nProcs()`) instead, as `mpi4py` is probably overly _low level_ for most users.

**Comment by jmansour** [comment]
Also, many models appear to do things in ways which aren't parallel safe, or not scalable (such as building unpartitioned mesh).  We should replace with equivalent fn/integral implementation asap. Where unavoidable, reconsider if it's required. 

This model generates an unpartitioned mesh to create a parallel safe (I guess) way of extracting values from the mesh.  Bad.
https://github.com/underworldcode/underworld2/blob/development/docs/examples/1_03_BlankenbachBenchmark.ipynb

This one uses numpy and isn't parallel safe.  Sad.
https://github.com/underworldcode/underworld2/blob/development/docs/examples/1_12_Internally_Heated_Convection.ipynb

This one might be ok, but needs a closer look.  Uses `evaluate_global()`.  Also, ipynb needs to regenerated.
https://github.com/underworldcode/underworld2/blob/development/docs/examples/1_13_Groundwater_Flow.ipynb

This one also doesn't not appear to be entirely parallel safe. 
https://github.com/underworldcode/underworld2/blob/development/docs/examples/1_15_Rayleigh_Taylor_GrowthRate.ipynb

Not parallel safe. There's a message at least, but we should aim for 100% parallel examples.
https://github.com/underworldcode/underworld2/blob/development/docs/examples/1_16_Groundwater_Topography.ipynb

Don't think these are parallel safe:
https://github.com/underworldcode/underworld2/blob/development/docs/examples/2_08_ShearBandsSimpleShear.ipynb
https://github.com/underworldcode/underworld2/blob/development/docs/examples/2_09_ShearBandsPureShear.ipynb

If we must have non-parallel safe examples, then they should include a catch to abort if running in parallel.

**Comment by jmansour** [comment]
No you are correct. I had suspicions because particle coordinates were generate by `np.linspace()`, but of course when added all non-local particles are simply disregarded.  

Much apologies 🙏🙂

**Comment by RebeccaFarrington** [comment]
Agreed!

**Comment by julesghub** [comment]
Need to consider all models in 'model_inprogress' as well. Documentation day activites!

**Comment by julesghub** [comment]
And models in "broken"

**Comment by jmansour** [comment]
@julesghub I think we should address all the examples and fix this for the current release.

**Comment by julesghub** [comment]
Agreed! Want to talk today and divide up the work?

**Comment by jmansour** [comment]
yep! let me know when works.
