### ISSUE TITLE
Hi~I'm beginner with Underworld

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/underworld2#297]
Hello~if anyone can help me, I had searched the code, I need to make a 3D rifting model, is there any example for 3D rifting model? Up to now , all I saw were 2D codes on this website.

**Comment by arijitlaik** [comment]
Hey There,
Have a look at @rbeucher UWGeodynamics, and the 3d basic model here https://github.com/rbeucher/UWGeodynamics/blob/master/tutorials/Tutorial_7_3D_Lithospheric_Model.ipynb

**Comment by jmansour** [comment]
Note the UWGeodynamics is a seperate project to Underworld, but uses Underworld for all its modelling. Its API is generally _higher level_ than Underworld's.  Most definitely worth a look as it might be a better starting place for you. 

@julesghub / @RebeccaFarrington , what's the best UW goto example for 3d?  We really should add a few 3D models in the examples directory, as I suspect this is where people look first.

**Comment by RebeccaFarrington** [comment]
I'd suggest having a look at a simple subduction model in 3D - check out   https://github.com/underworldcode/underworld2/tree/master/docs/publications/OzBenchEtAl-2008
It's a 3D model with a straight forward geometry.

Hope it helps!
