### ISSUE TITLE
Mask Mesh plots with swarm variables?

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#299]
when plotting with glucifer, is there a way to mask a mesh variable(being plotted on the mesh, not on the swarm) by a swarm variable
my typical use case would be plotting the velocity field or pressure field where the material swarm is not 0(sticky air/accommodation)

**Comment by jmansour** [comment]
Not directly.  This _might_ work:

1. Make a binary swarm variable that is zero where your material swarm is zero, and one otherwise.
2. Cast this binary variable onto a mesh variable using a [MeshVariable_Projection](https://underworld2.readthedocs.io/en/latest/underworld.utils.html#underworld.utils.MeshVariable_Projection) object. You now have a mask mesh variable.
3. Multiply this mask variable by some value (the mask value) that doesn't appear in your desired mesh variable.
4. Multiply by your desired variable and visualize using a colourmap which sends the mask value to transparent or other (@OKaluza?).  Perhaps a discrete colour map will be required. 

Alternatively, you could possibly invert the mask, and then use the Points objects to colour over the parts you don't want.

**Comment by arijitlaik** [comment]
Thanks, @jmansour i was doing the alternative, plotting white points to colourover, could a possible feature be enhancement be possible in the forthcoming releases?

**Comment by jmansour** [comment]
Hmm... In honesty I'm really not sure how well this would fit with surface based drawing objects. With particles, the mask complete drops particles that are masked. Surfaces however are continuous, so it kinda doesn't make sense to drop a node. 

Perhaps being able to provide a transparency function would be reasonable.  Possibly it's already doable using lavavu directly.  We'll wait to hear from @OKaluza as he's the guru.

**Comment by arijitlaik** [comment]
@jmansour sure, the fact that surfaces are continuous and dropping node does not make much sense, given that I am modelling compression, and have a large sticky air layer over a crustal layer, to accommodate the shortening and upliftment, plotting velocity field and or strain rate on the accommodation layer isn't what others call aesthetically pleasing, plotting them on swarm, however, is an option but its rather a bit time consuming. so all I was thinking about was truncating a surface plot by another surface(the sticky air/sediment interface).

**Comment by jmansour** [comment]
And doesn't the alternative (using particles to _white out_ Surface plotted regions) work ok? 

That actually seems the best option, given sticky air layers are defined on particles.

**Comment by arijitlaik** [comment]
yes it does :)

**Comment by arijitlaik** [comment]
@OKaluza any ideas on this, or masking with particles is the best choice?

**Comment by jmansour** [comment]
Hi @arijitlaik.  

I think it's a bit unclear what further functionality you require here.  Can you describe exactly what you are hoping to do that can't be achieved by masking with particles?

**Comment by arijitlaik** [comment]
if i have materials(swarm variable) described as sticky air + rock, I want to visualize the velocity and or any mesh variable only on the rock and not on the sticky air layer. 
possible solution being : plot the velocity field on mesh, plot sticky air swarm in white.

**Comment by lmoresi** [comment]
This kind of problem has multiple different solutions and no one right way to do it.

The projection of a swarm variable to the mesh will degrade the discrete representation of materials as there is a requirement to interpolate from one set of points to the other.
The mesh variables do, at least, have a valid interpolant which is constructed for the FEM and so can be defined everywhere. Thus is is possible to map the mesh variables uniquely to
the swarm and display those masked.

For velocity vectors, this will produce an over-dense sampling for visualisation purposes (Probably - but overlaying a huge number of transparent vectors might work and look cool). You would then need to decide what you want to show.

L

On 22 Jun 2018, at 3:51 pm, Arijit Laik <notifications@github.com<mailto:notifications@github.com>> wrote:


if i have materials(swarm variable) described as sticky air + rock, I want to visualize the velocity and or any mesh variable only on the rock and not on the sticky air layer.
possible solution being : plot the velocity field on mesh, plot sticky air swarm in white.

**Comment by arijitlaik** [comment]
@lmoresi thanks:
i had you at "This kind of problem has multiple different solutions and no one right way to do it."
:)

**Comment by OKaluza** [comment]
Hi @arijitlaik, sorry missed this one earlier. On the vis side, you can create an opacitymap that maps a variable to opacity of an object, allowing this to be a different variable than that used to colour the object or to use a predefined colour map without having to bake alpha values into the map.

Of course the disadvantages of doing this on the vis side as opposed to masking the data before plotting are:
- the data is plotted anyway, just discarded by the renderer at the shader stage, so larger data and slower rendering
- you can run into depth masking problems with transparent objects, usually if they are 100% transparent it should be ok as should be discarded before writing to depth buffer. If it's just particles, they are sorted before renderering so transparency should be handled well enough. Vectors can be more complicated as they are plotted as a triangle mesh, which can be sorted but the individual vector arrow meshes are not usually, for efficiency.

To use in lavavu:
```
points.opacitymap([0, 0.8, 1])
points["opacityby"] = "varname"
```

Via glucifer, you have to pass colour:alpha for the moment until the interface is improved, eg:
```
fig.Points(..., opacitymap="black:0 black:0.8 black:1", opacityby="varname")
```
