### ISSUE TITLE
How to use mumps?

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#3]
In my old UW models, I often provide:
```
-Uzawa_velSolver_pc_factor_mat_solver_package mumps
-Uzawa_velSolver_ksp_type preonly
-Uzawa_velSolver_pc_type lu
```
to use mumps as a direct solve.

Is there an equivilant to pass through to the solver options? I tried passing them as kwargs to the .solve() function, but it seemed to ignore them.

**Comment by mirkovelic** [comment]
Try this Luke,

from libUnderworld import petsc

petsc.OptionsInsertString("-Uzawa_velSolver_pc_factor_mat_solver_package
mumps -Uzawa_velSolver_ksp_type preonly -Uzawa_velSolver_pc_type lu
-Uzawa_velSolver_ksp_converged_reason -Uzawa_velSolver_ksp_view")

**Comment by OlympusMonds** [comment]
Cheers Mirko, that works. 

Is there a better way to use a mumps direct solve? Looking through the solver setup, things like set_direct() jump out at me.

**Comment by mirkovelic** [comment]
There will be soon..just haven't implemented that yet.

**Comment by OlympusMonds** [comment]
No worries then, sorry to be a pain ;)

**Comment by julesghub** [comment]
@mirkovelic have you implemented the mumps in the new solver? Can you update this ticket with info or close it?

**Comment by mirkovelic** [comment]
Yes mumps can be accessed now.

Have a look at 09_StokesSolver.ipynb in docs/user_guide
