### ISSUE TITLE
solver bug

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#30]
Solver class appears to attach assembled objects to SLE at C level.. however the assembled objects lifetime is managed at the python level.  ie, this explodes

```
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian()
vel = uw.fevariable.FeVariable(mesh,2)
pres = uw.fevariable.FeVariable(mesh.subMesh,1)
sys = uw.systems.Stokes(vel,pres,1.,(0.,0.))

solv = uw.systems.Solver(sys)
solv = uw.systems.Solver(sys)

solv.solve()
```

Either the solver class should make this interdependency explicit at the python level (so that lifetimes are managed correctly), or the objects should not be attached to the sle (if possible).

**Comment by mirkovelic** [comment]
Not attaching anything extra to sle now and now it works. This was a problem at the c level.

**Comment by jmansour** [comment]
you're a star!
