### ISSUE TITLE
Underworld container won't give me root privileges

### ISSUE THREAD

**Issue by rsbyrne** [underworldcode/underworld2#305]
Hi!

I'm running Underworld on an Ubuntu virtual box. I'm trying to use the Python memory profiler package to assess the memory usage of my models. This will require me to pip install the memprof module (pip install memory_profiler) inside the container.

Unfortunately, the container throws up an error message querying whether I am the root user. As far as I can tell, I am not.

I would usually get around this using the 'sudo' command, but unfortunately the container does not recognise it (i.e. it does not appear when I use compgen -c to list known commands).

Let me know how to proceed.

Cheers,
Rohan

**Comment by jmansour** [comment]
Are you doing this within a container or a VM?  Or is it a container running in a VM?

**Comment by arijitlaik** [comment]
Wasn't docker the default password su access with UW dockers?

**Comment by rbeucher** [comment]
```python

pip install memory_profiler --user 
```

should work but you will have to do that each time you start a new container...

Writing a quick Dockerfile which adds memory_profiler is probably the way to go!!!!

``` bash
FROM underworldcode/underworld2_untested:latest  

RUN pip install memory_profiler
CMD ["jupyter", "notebook", "--ip='*'", "--no-browser"]
```

then

```bash
docker build -t myImage .
```

**Comment by jmansour** [comment]
All good suggestions! @arijitlaik, the current dockers do not use `root` user, though you can still select `root` user at container launch (and also you might need `--privileged`).

Another option is to start the container, install required package via @lmoresi's suggestion, then commit the container into a new image which you can then use in the future (and will include your installed package).
