### ISSUE TITLE
How to cut and slice 3D-figures?

### ISSUE THREAD

**Issue by cgoise** [underworldcode/underworld2#308]
Hi!

Is there a way to cut or slice glucifer 3D images in order to have a look inside the 3D body?

An example of what I try to do in the notebook:
```python
figEffectiveViscosity = glucifer.Figure( title="effectiveViscosity, t(a) = " + time, name="effectiveViscosity", rulers=True )
figEffectiveViscosity.append( glucifer.objects.Points(swarm, particleEffectiveViscosity, pointSize=3, colourBar=True, logScale=False) )
figEffectiveViscosity.window()
```

Maybe even better: is there a way to save and open *.h5 files in an interactive external viewer, eg in Paraview?

Please let me know how to do this,
Thanks!

**Comment by julesghub** [comment]
To answer the even better part.
You can directly checkpoint the swarm as a .h5 file and create an associated .xdmf for use with Paraview. See the bottom of this [user guide](https://github.com/underworldcode/underworld2/blob/v2.5.1b/docs/user_guide/07_Utilities.ipynb) for details.

In 3D swarm checkpoints can become huge. Be mindful of hard disk limitations and I/O times. A few ideas to get around this:
1. Passive Tracers - use another (smaller) swarm to track / vizualise what you're interested in.
2. Projection - Project the swarm properies to a `MeshVariable`. Checkpoint and visualise the `MeshVariable` with paraview instead. To project use the function `MeshVariable_Projection()`. See this [model](https://github.com/underworldcode/underworld2/blob/v2.5.1b/docs/publications/OzBenchEtAl-2008/1_OzBenchEtAl-2008.ipynb) for an example.

**Comment by arijitlaik** [comment]
although i personally dislike paraview for its huge ui, at times it easier to do things up there.  slicing thresholding etc
