### ISSUE TITLE
swig/python detected a memory leak of type 'Vec *', no destructor found.

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#309]
I'm almost certain we don't need to worry about these, but we should get confirmation, and then squelch this message, as it happens per proc so stdout gets a bit ugly.

**Comment by rbeucher** [comment]
Yeah, Lunch to the one who get us rid of that...!

**Comment by rbeucher** [comment]
I spent a bit of time at lunch on this and here is what I found:

Memory leak appears when we call:
```
underworld/systems/_bsscr.py:509:        petsc.SetVec(self._vmfvector._cself.vector, 0.0)
underworld/systems/_bsscr.py:510:        petsc.SetVec(self._junkfvector._cself.vector, 0.0)
```
SetVec is a wrapper around petsc VecSet that we can found in  /libUnderworldPy/petsc.i

StackOverflow give us one interesting pb that I think is related:
https://stackoverflow.com/questions/918180/swig-python-memory-leak-detected

Based on the above I ran swig on the petsc.i file with the following debug options:
-debug-typemap -debug-tmsearch -debug-tmused -debug-typedef

And I get a series of messages such as:

```
petsc.i:35: Searching for a suitable 'default' typemap for: Vec vec
  Looking for: Vec vec
  Looking for: Vec
  Looking for: SWIGTYPE vec
  Looking for: SWIGTYPE
  None found

petsc.i:35: Searching for a suitable 'arginit' typemap for: Vec vec
  Looking for: Vec vec
  Looking for: Vec
  Looking for: SWIGTYPE vec
  Looking for: SWIGTYPE
  None found

petsc.i:35: Searching for a suitable 'argout' typemap for: Vec vec
  Looking for: Vec vec
  Looking for: Vec
  Looking for: SWIGTYPE vec
  Looking for: SWIGTYPE
  None found
```
I am not sure that is the issue but I think we need to define some typemaps for the petsc Vec object.

I have tried to install petsc4py and have included the petsc4py.petsc4py.i file
(https://github.com/erdc/petsc4py/blob/master/src/include/petsc4py/petsc4py.i) But it was a bit of a blind shot... Did not work...

@jmansour ?

**Comment by jmansour** [comment]
Ok, nice sleuthing Romain. Those calls simply set the petsc vecs to the provided value, and as such are not memory leaks. 

Fix incoming.

**Comment by jmansour** [comment]
e7743828a4ae438f19b9e9a4a9655825944718e6

@rbeucher can you check if this is fixed at your end?

**Comment by jmansour** [comment]
@rbeucher, did you get a chance to check this?
