### ISSUE TITLE
Free surface

### ISSUE THREAD

**Issue by adambeall** [underworldcode/underworld2#310]
Hi,
I've been looking at this 'true' free-surface example:
https://github.com/underworldcode/underworld2/blob/042d2904201419d3465a00eff98d3380e918ad7b/docs/development/models_inprogress/FreeSurface_Simple_example.ipynb

Were there any issues you (particularly @rbeucher) were running into with it?
Just wondering why it never made it out of 'models_inprogress'.

Cheers,
Adam

**Comment by rbeucher** [comment]
I have never really tested this properly. Do you want to give it a go?

**Comment by rbeucher** [comment]
Looking at the code it is a serial version. I had a parallel version... I'll find it.

**Comment by adambeall** [comment]
That's fine, just checking for any known issues. I'll close this and share any tests I or others do (I'm mainly asking for another user).
