### ISSUE TITLE
Post v27 release action items

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#312]
Module reorganisation.  For example, the `utils` submodule currently is a catchall for things that don't fit elsewhere.  I'd like to move the following items elsewhere

- Integral
Remove explicit class, store on mesh and/or fn.
- MeshVariable_Projection
Remove explicit class, access via `var.project_from_fn()`, or `fn.project(var)`
- is_kernel (stays)
- SavedFileData (stays)
- matplotlib_inline (-> underworld.utils)
- barrier (-> underworld.mpi)
- rank (-> underworld.mpi)
- nProcs (-> underworld.mpi)

The mpi related items should go into an `mpi` submodule. Not so sure about the others. Similarly, the `function` submodule could do with some reorganisation & culling.

**Comment by rbeucher** [comment]
MeshVariable_Projection --> /Mesh would make sense...

**Comment by jmansour** [comment]
Perhaps even simply add a `project()` method to the variable itself.

**Comment by rbeucher** [comment]
That could be good too.

**Comment by julesghub** [comment]
I like. As long as only one projector class is made underneath
On 26 Jul 2018, at 13:16, rbeucher <notifications@github.com<mailto:notifications@github.com>> wrote:

That could be good too.

**Comment by jmansour** [comment]
Yep, would simply cache the object. 

I think we could do the same for the `Integral()` class.  Currently it's tied to the mesh, but I kinda prefer the idea of tying it to a particular function instance. Also, we probably avoid circular dependency complications that way.

**Comment by julesghub** [comment]
Closing this because most has been done. Adding a new ticket for the idea of MeshProjection #488
