### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by elisafierro** [underworldcode/underworld2#315]
Hi Underworld2 team,

I got the following error after my model ran for 2 time steps. 
Can someone help me?

Thanks!!!
Elisa 

`RuntimeErrorTraceback (most recent call last)
<ipython-input-29-ef3904ea1a0e> in <module>()
    132     dt = advDiff.get_max_dt()
    133     swarm_strain.data[:] += strainRate.evaluate(swarm)*(strain_rate_scaling * dt * time_scaling)
--> 134     strain_proj.solve()
    135     advDiff.integrate(dt)
    136     advector.integrate(dt, update_owners=True)

/root/underworld2/underworld/utils/_meshvariable_projection.pyc in _solve_average(self)
    208             self._swarm._voronoi_swarm.repopulate()
    209         libUnderworld.StgFEM.ForceVector_Zero( self._fvector._cself )
--> 210         libUnderworld.StgFEM.ForceVector_GlobalAssembly_General( self._fvector._cself )
    211         libUnderworld.StgFEM.SolutionVector_UpdateSolutionOntoNodes( self._fvector._cself );
    212 

RuntimeError: Error occurred while trying to evaluate swarm variable. This can occur when there are no particles found in a given element. You may wish to add population control mechanisms. Please contact developers if this does not appear to be the issue.`

I already have population control mechanisms in my code.

**Comment by rbeucher** [comment]
Hi Elisa

It basically means that the swarm advection resulted in one or several of your elements being empty. Meaning there was no particle left on that element. 
If you are confident that this should not happen I suggest checking your velocity field. If you advect particles outside the Domain, you may want to use population control. I suggest you look at the manual for that. 

Romain

**Comment by elisafierro** [comment]
Hi,

I use population control mechanism in my code, so I think the problem is something related to my velocity field. 

Thanks!

**Comment by jmansour** [comment]
Will close this for now.  Feel free to reopen or start a new issue.
