### ISSUE TITLE
colourbar & constant functions

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#316]
Colour bars don't seem to play nice with any function returning a constant value:

```python
import underworld as uw
import glucifer
from glucifer.objects import Surface
mesh = uw.mesh.FeMesh_Cartesian()
fig = glucifer.Figure()
fig.append(Surface(mesh, 1.))
fig.show()
```
gives
<img width="561" alt="screen shot 2018-09-04 at 4 27 35 pm" src="https://user-images.githubusercontent.com/1439389/45013695-79676100-b05f-11e8-9e5b-f506f5e9f9f2.png">

**Comment by OKaluza** [comment]
This is fixed in latest release https://github.com/OKaluza/LavaVu/releases/tag/1.2.50
