### ISSUE TITLE
Multigrid levels raises an error not a warning

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#319]
SROpGenerator_SimpleFinestLevel: time = 8.58500e-03 
(MG) Error: Too many levels specified for geometric multigrid.
            Please modify mesh size or reduce number of levels.

This is poor behaviour for the notebook as this "warning" is issued to the terminal and produces a kernel restart. In the cloud, or for a novice user, this is hard to diagnose. Should warn and not solve or something fixable.

**Comment by jmansour** [comment]
And the conditions that lead to this @lmoresi?

**Comment by lmoresi** [comment]
Setting too many levels for mg -which is an easy mistake to make when you don’t have 100% certainty on what the algorithms do.

The gamg might be a good thing to consider. Trying that at the moment

Sent from Astro<https://www.astro.ai> for iOS


On 7 Sep 2018 at 08:41, jmansour <notifications@github.com> wrote:


And the conditions that lead to this @lmoresi<https://github.com/lmoresi>?

**Comment by jmansour** [comment]
Oh right so where you explicitly set the levels.  We can easily (and should) catch this issue in the Python layer. 

We should definitely be exploring AMG options.
