### ISSUE TITLE
Swarm evaluation problem

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#32]
Hi John 

Here's the Swarm evaluation problem in a much simpler example. If you switch the refineMesh parameter on / off, the swarm evaluation output value changes quite a bit. 

https://github.com/dansand/vueesc/blob/master/swarm_int_bug.ipynb  

Cheers

**Comment by jmansour** [comment]
I haven't had a chance to have a closer look at this yet Dan.  Will shortly, but let me know if you've discovered anything.

**Comment by jmansour** [comment]
what was the conclusion here?

**Comment by dansand** [comment]
The interim conclusion is that I feel I should do some more tests and learn
a little more about the problem. I'll start a new issue once I've gone
through that process. Basically, I felt I'd done a half arsed effort of
describing the problem, which doesn't help you guys much.

**Comment by jmansour** [comment]
ok no probs!  yep, definitely if you can isolate the issue as much as possible, makes it much easier for us to get to the bottom of things.  cheers.
