### ISSUE TITLE
A memory leak in UW

### ISSUE THREAD

**Issue by rsbyrne** [underworldcode/underworld2#322]
Hi all!

For the past few months I've been tracking down some memory problems in my model code. I've finally figured out the problem, or part of it: a garbage collection issue with the `utils.Integral` class - exacerbated, I'll admit, by some sloppy usage on my side, but a legitimate issue nonetheless.

The following code exhibits the problem in a big way, fast. I've calculated the leak in this case to be around 10 kilobytes per step per core:

```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian(elementRes = (16, 16))
while True: uw.utils.Integral(mesh = mesh, fn = 1.)
```

Of course 10 kilobytes isn't much, but if one calls a dozen integrals across 16 procs a hundred times an hour (as I've rather blithely been doing) it quickly adds up. The above code accounts for about half the memory leakage I've measured in my actual model code, so there could be garbage collection issues relating to some of the other global methods too. Interestingly, the leak does NOT seem to scale with resolution.

---

I'd like to add something on a philosophical note as a user. The problematic code above is without a doubt very 'lazy'. The proper method is of course to create a single 'Integral' object and evaluate it as needed. However, this sort of discipline does not always come naturally to a Python user who is used to being pampered and tends to favour what 'makes sense' or 'feels right' or 'reads well' over what actually works well under the hood.

An example of a very Pythonic equivalent of the problematic code might be:

```python
while True: sum(range(int(1e6)))
```

This code repeatedly creates, operates on, and destroys a very heavy (tens megabytes) class instance. It is extremely wasteful, but if time is not a limiting factor, it makes up for this wastefulness in readability. It doesn't leak at all because Python is designed to be unfailingly forgiving like that - to the extent that the distinction between functions and classes in ordinary usage tends to become blurred, particularly for novice users like myself.

Whether or not it's possible to plug this particular leak in the `utils.Integral` class, might I recommend introducing a new tutorial into the official user guide, outlining a few amateur pitfalls like this and describing in broad terms the Underworld philosophy and idiom. When approached from the right perspective, UW is incredibly robust. But like any code it will always have its problems, and the best way to avoid them is with clean and idiomatic usage. I've learned this the hard way - let others be spared my mistake!

Cheers,
Rohan

**Comment by rbeucher** [comment]
Thanks for that Rohan. Lots of good suggestions! I agree about your comment on doing what makes sense. That's the Python philosophy, I'm sure we can do better!

**Comment by RebeccaFarrington** [comment]
Great work Rohan – Thanks for the details, and simple code example!

**Comment by jmansour** [comment]
Ok, I've had a look, and there is a leak, but it's actually not a bug, just a design shortcoming. 

So, whenever we create an object in C, a small struct is created which records all the object's information.  This struct is *never* deleted, by design, as it is often required to prevent double deletions of objects.   Check:

```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian(elementRes = (16, 16))
integral = uw.utils.Integral(mesh = mesh, fn = 1.)
print(integral._integral._sizeOfSelf +
      integral._integrationSwarm._cself._sizeOfSelf +
      integral._integrationSwarm._cellLayout._sizeOfSelf +
      integral._integrationSwarm._particleLayout._sizeOfSelf)
# prints 1376
```
So that's evidence for over a kb of loss, but then there's a bunch of further other nested objects as well.  My measurements suggest ~4kb loss per `Integral` constructor call, which seems about right. 

In any case, this is just something we'll have to live with for now, and as you highlight if you avoid redundantly calling constructors it should rarely be an issue.
