### ISSUE TITLE
'function.branching.conditiona'l and 'if statement'

### ISSUE THREAD

**Issue by elisafierro** [underworldcode/underworld2#323]
Hi Underworld II team,

I need to input in the stokes system the following fn_viscosity: a viscoelastic rheology where the temperatureField <=T_LAB  (i.e in the lithosphere) and a viscous rheology in the underlying mantle. 

I performed the viscosityFn using the branching function and then two functions such that my viscosities are included in minimum and maximum values, but I got incorrected results of viscosity. Are the instructions of the conditional branching function correct? 

```python
fn_lithosphere = temperatureField <= T_LAB

total_rheology = fn.branching.conditional(((fn_lithosphere,viscoelasticity),(True,viscous_rheology)))

viscosity_1 = fn.exception.SafeMaths( fn.misc.max(eta_min , total_rheology))
viscosityFn = fn.exception.SafeMaths( fn.misc.min(viscosity_1 , eta_max) )`
```

I also tried to use the following 'if statement' to input the same viscosityFn, but I got improper outcomes. Are the following instructions correct?

```python
for index, coord in enumerate (mesh.data):
    if temperatureField.data[index] <= T_LAB:
        rheology = viscoelasticity
    else:
        rheology = viscous_rheology

viscosity_1 = fn.exception.SafeMaths( fn.misc.max(eta_min , rheology))
viscosityFn = fn.exception.SafeMaths( fn.misc.min(viscosity_1 , eta_max) )`
```
Thanks a lot!!!
Elisa

**Comment by rbeucher** [comment]
Hi Elisa,

Your first try was not so far... 

```python

total_rheology = fn.branching.conditional([( temperatureField <= T_LAB, viscoelasticity),
                                                                  (True, viscous_rheology)])
```

**Comment by jmansour** [comment]
Hi @elisafierro 

It looks like what you have coded (in your first example) is correct.  It should give you `viscoelasticity` for `T <= T_LAB` and `viscous_rheology` for `T > T_LAB`.  

In what way are the results you are obtaining incorrect?

**Comment by elisafierro** [comment]
Hi,

It seems that the viscous_rheology is disregarded: where the T > T_LAB I only have eta_max (i.g 1e20 [Pa s]).
I attach here the picture

Thanks!!!!
Elisa

![viscosity0000](https://user-images.githubusercontent.com/26709780/45613117-87f14780-ba65-11e8-8bb4-330a9cbf10fb.png)

**Comment by jmansour** [comment]
Can you post a plot of `total_rheology`?   (ie, plot without the min/max limits).

**Comment by elisafierro** [comment]
![viscosity0000](https://user-images.githubusercontent.com/26709780/45622040-f8f32800-ba82-11e8-9b30-0daa747feb8d.png)

**Comment by jmansour** [comment]
It's constant?

**Comment by elisafierro** [comment]
The problem is that I obtained a constant viscosity but actually it shouldn't be like this!!

**Comment by jmansour** [comment]
Ok, perhaps post your model.
