### ISSUE TITLE
How to specify the 'depth'

### ISSUE THREAD

**Issue by elisafierro** [underworldcode/underworld2#327]
Hi Underworld II team,

I need to modify that branching function that I posted in GitHub last time: I need to add another 'if statement' inside that branching function where I say that for a depth < z_T (where z_T = 1.- 410/660.), viscosity = 1.e23 Pa s. How can I specify 'depth' in python?

the branching function was: 

`total_rheology = fn.brancing.conditional([(temperatureField <= T_LAB, viscoelasticity),(True, viscous_rheology)])`

Thanks so much again for your help!!!

Elisa

**Comment by rcarluccio** [comment]
Hi Elisa,

It is not clear to me if you are trying to add this in case to the existing "if" condition or if you are trying to add this as a separate condition.

1) if you are trying to add this existing one (e.g.  if temperatureField <= T_LAB && depth < z_T, -->  viscous_rheology = 1.e23 Pa s ), I am not sure it's possible to prescribe two different conditions at the same time with the branching function, so maybe you have to break it down in different steps; 

2) however, if you want the depth condition as a separate one , you can try this:

# depth mark
z_T = = 1.- 410/660.

# coordinate function
coordinate = fn.coord()

# extract your coord values on Z
Z_coord= fn.coord()[1]

# viscosity given value
 new_eta=1.e23

total_rheology = fn.brancing.conditional([(temperatureField <= T_LAB, viscoelasticity), 
                                                                      (Z_coord > z_T ,  new_eta), 
                                                                       (True, viscous_rheology)])

# note that the  fn.coord() may change the sign of your coordinate system.

**Comment by rbeucher** [comment]
Hi Elisa,

You can use the fn.input or fn.coord function which will return the coordinates of the swarm on which you are evaluating the function.

The 2 functions are equivalent. You can access the components by indexing the result. 
```python
coords = fn.input()
first_component = coords[0]
second_component = coords[1]
```
Note that you should not have any problem using multiple conditions.
(condition1) & (condition2) is valid.

**Comment by elisafierro** [comment]
Thanks so much guys!!

Elisa

**Comment by jmansour** [comment]
Excellent!  I'll close this for now.
