### ISSUE TITLE
Advice on Mac uw usage

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#328]
I recently got a mac, and have been using uw installed natively there, in generally i followed the docker compilation steps for mpich and petsc. Few stray observations: 1using petsc with openmpi is faster than mpich, like a lot faster. Docker comes with a performance overhead.
So this is to ask general advice/suggestion and or experiences on the usage and performance in macs, given that i would be using it as a primary environment.

**Comment by jmansour** [comment]
Hi @arijitlaik 

I've used openmpi / mpich both native & containered on OSX and haven't noticed any dramatic differences.  Can you post more specifics about your findings?  Are you using docker _native_ or the VirtualBox version? 

Currently I'm doing all development and usage via docker on OSX. It's not perfect, but does keep my setup simpler.

**Comment by arijitlaik** [comment]
Docker: using native docker on mojave.
and the openmpi vs mpich is not on docker, but purely native installation.
I get get you some metrics, if you could specify any specific model ?

**Comment by rbeucher** [comment]
Strange, dans our docker use mpich now but I haven't noticed any slow down. Truth is I don't run any big model on my machine.... As for your native install, no idea... I haven't look at the difference between mpich and openmpi on my machine...it's not a mac anyway lolz

**Comment by rbeucher** [comment]
I have been using docker for development for a bit more than a year now... It's not perfect as John said but it makes thinks a lot easier and gives you a contained environment.

**Comment by arijitlaik** [comment]
Yup. true. but the slowdown is definitely there with mpich in mac. i guess, i too have to get containerized ;/

**Comment by lmoresi** [comment]
You mentioned it was a petsc slowdown and that would be worth investigating. Particularly since mpich and petsc are from the same lab while openmpi is not.



Sent from Astro<https://www.astro.ai> for iOS


On 30 Sep 2018 at 16:13, Arijit Laik <notifications@github.com> wrote:


Yup. true. but the slowdown is definitely there with mpich in mac. i guess, i too have to get containerized ;/

**Comment by rbeucher** [comment]
Again, might be a good idea to directly reach to the petsc team...?

**Comment by arijitlaik** [comment]
Since I just moved to a new city, and there noting else to do on a sunday
tested on PETSc 3.10.1 (on solver_1.py)

certianly proves something, and results would definitely be larger with high res

| MPI             | MPICH    | OPENMPI  | MPICH    | OPENMPI  | MPICH    | OPENMPI  | MPICH    | OPENMPI  |
|-----------------|----------|----------|----------|----------|----------|----------|----------|----------|
| NP              | 1        | 1        | 2        | 2        | 3        | 3        | 4        | 4        |
| Multigrid setup | 0.00283  | 0.002311 | 0.007676 | 0.00239  | 0.01004  | 0.002485 | 0.01525  | 0.002552 |
| RHS V Solve     | 0.004737 | 0.005711 | 0.01337  | 0.003182 | 0.02075  | 0.002765 | 0.03105  | 0.00261  |
| Pressure Solve  | 0.006481 | 0.005909 | 0.01783  | 0.0036   | 0.0236   | 0.002963 | 0.0409   | 0.002885 |
| Final V Solve   | 0.00242  | 0.002177 | 0.005883 | 0.001295 | 0.008762 | 0.001036 | 0.018    | 0.000955 |
|                 |          |          |          |          |          |          |          |          |
| Total BSSCR     | 0.020435 | 0.021095 | 0.056969 | 0.016190 | 0.078789 | 0.014927 | 0.128895 | 0.014983 |
|                 |          |          |          |          |          |          |          |          |
| real            | 0m0.748  | 0m0.934s | 0m0.830  | 0m0.687s | 0m0.853  | 0m0.695s | 0m0.942  | 0m0.774s |
| user            | 0m0.894  | 0m0.814s | 0m1.593  | 0m1.416s | 0m1.845  | 0m1.515s | 0m2.479  | 0m2.059s |
| sys             | 0m0.214  | 0m0.319s | 0m0.632  | 0m0.577s | 0m1.147  | 0m1.059s | 0m1.452  | 0m1.243s |

**Comment by rbeucher** [comment]
Can you tell us what versions of openmpi, mpich?

**Comment by arijitlaik** [comment]
openmpi 2.0.2
mpich 3.3b

and about petsc, i should i use 3.8 or 3.9?

**Comment by jmansour** [comment]
Interesting numbers @arijitlaik, thanks for sharing.   

Generally we are mainly concerned with solver time, as this is usually the most expensive and most frequent operation. As such, I'd suggest you run these for ~10 solver calls to bias total times to the solve operation.  Similarly, representative resolutions (256*256, or 32*32*32) would be telling, as would averaging 10 runs of each simulation. 

Also note that mpich/openmpi handle some things different, in particular setting up the communicator when it is first created.  For this one off cost there may be some significant differences, but it usually isn't a concern.

Note we have a new built in timing routine which you might like to use.  Just call `uw.timing.start()` at after you import underworld, and `uw.timing.print_table()` at the end.  It doesn't break the different solver components, but might be useful.

**Comment by arijitlaik** [comment]
Thanks @jmansour, that's something i get going on the next weekend :)

**Comment by arijitlaik** [comment]
@jmansour could there be a docker image for v27, or v26c with the timing module, more specifically a python2 version with the timing module, i could build it from a dockerfile but would be convenient to have one up on the dockerhub

**Comment by rbeucher** [comment]
You can get an image for most of the released version using the version tag...

**Comment by arijitlaik** [comment]
the 2.7.0-dev is not a tagged release, and its the only python2 version with the timing module

**Comment by jmansour** [comment]
Hi Arijit

I've triggered the build of a pre-release v2.7 image. It will be tagged
'2.7.0_prerelease'. It should be available within the hour (if it builds
successfully).

**Comment by arijitlaik** [comment]
@jmansour thanks :)

**Comment by jmansour** [comment]
@arijitlaik, ok, with some further tweaking we have a successful build, `underworldcode/underworld2:2.7.0_prerelease`.  Python 2.7, uw + timing. 

Let us know if you're finding the timing info useful.

**Comment by jmansour** [comment]
Ok, that's good to hear.  I believe there were some minor updates to the timing module that won't be in the 2.7.0_prerelease, but nothing significant.  But please let us know if you're finding any discrepancies.
