### ISSUE TITLE
runipy now deprecated

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#329]
Recommended alternative is:
```bash
jupyter nbconvert --to notebook --execute mynotebook.ipynb
```

**Comment by julesghub** [comment]
No more runipy, we now use `jupyter nbconvert --execute`. 
Changes - 1a7d785b8ec3cd8c2b0bc46dc7c0495071ca730a and 050de4d913c351d1e60872176021cbe40a156a44

Info on how to use `jupyter nbconvert --execute` https://nbconvert.readthedocs.io/en/latest/execute_api.html
