### ISSUE TITLE
Ideal UW method to deal with passive tracers in parallel

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#330]
having passive tracers in parallel to track their coordinates or movement etc in parallel, is there something better? or should i have tracers on a single processors

MWE 
```python
import underworld as uw
# import glucifer
import numpy as np

mesh = uw.mesh.FeMesh_Cartesian()
# fig = glucifer.Figure()
# fig.Mesh(mesh)


lonely_swarm = uw.swarm.Swarm(mesh)
lonely_swarm.add_particles_with_coordinates(np.array([[0, 1]]))
# fig.Points(lonely_swarm,pointsize=10)

# fig.show()

try:
    lonely_swarm.particleCoordinates.data[0]
except IndexError:
    print("Lonely swarm is not at Processor-{0:d}".format(uw.rank()))
else:
    print("The lonely swarm is at Processor {0:d} and is sitting at {0:f},{0:f}".format(
        uw.rank(), lonely_swarm.particleCoordinates.data[0]))

```

**Comment by jmansour** [comment]
That was quick!  

I was a bit confused about what exactly you're trying to achieve here. If it's just to track the location of a single particle, it might be easiest to simply checkpoint the passive swarm, and that would work in parallel.

**Comment by arijitlaik** [comment]
yup, its kind-of to track the location of a few particles , but got away with checking for particleLocalCount>0 for now.

**Comment by arijitlaik** [comment]
just a simple question on this one, 
what is the future of  'FunctionInput'  w.r.t evaluate_global, the use case being querying a very small set of passive tracers and getting evaluated values of some function on them etc, although i am aware that using a swarm variable and saving hd5 is the suitable alternative or using comm.gather/comm.allgather

**Comment by jmansour** [comment]
We're really not sure what's the future in honesty! It was introduced as a convenience, but it's far from perfect. 

Can you explain what you are trying to achieve?

**Comment by arijitlaik** [comment]
In the simplest of all, I would like to track the velocity/pressure/temperature and or coordinator of 2/3 passive tracers (points) at every step of the model and save them to a text file for monitoring

**Comment by rbeucher** [comment]
Hi Arijit,

You can do that in UWGeo. The passive tracers have a global index that can be used to track them across processors...
