### ISSUE TITLE
glucifer, submesh with dQ1 elements, Surface plot returns an error

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#331]
Here is a minimal example:

```python
mesh = uw.mesh.FeMesh_Cartesian( elementType = ("Q2/dQ1"), 
                                 elementRes  = (8, 8), 
                                 minCoord    = (0.0, 0.0), 
                                 maxCoord    = (2.0, 1.0) )

var = mesh.subMesh.add_variable(dataType="double", nodeDofCount=1)

figMesh = glucifer.Figure(figsize=(1200,600))
figMesh.Surface(mesh.subMesh, var)
figMesh.show()
```

returns:

```
RuntimeErrorTraceback (most recent call last)
<ipython-input-8-da2ea8d9f255> in <module>()
      1 figMesh = glucifer.Figure(figsize=(1200,600))
----> 2 figMesh.Surface(mesh.subMesh, var)
      3 figMesh.show()

/opt/underworld2/glucifer/_glucifer.pyc in method(*args, **kwargs)
    444             def addmethod(constr):
    445                 def method(*args, **kwargs):
--> 446                     obj = constr(*args, **kwargs)
    447                     self.append(obj)
    448                     return obj

/opt/underworld2/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
    111                 _setup = _setup.__get__(self, cls)
    112             if callable(_setup):
--> 113                 _setup()
    114 
    115         te = time.time()

/opt/underworld2/underworld/_stgermain.pyc in _setup(self)
    240             # lets build
    241             for compName, compPtr in self._objpointerDict.iteritems():
--> 242                 libUnderworld.StGermain.Stg_Component_Build( compPtr, None, False )
    243             # lets initialise
    244             for compName, compPtr in self._objpointerDict.iteritems():

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in _lucCrossSection_Build(): provided Mesh "Q7AV578X__mesh" doesn't have a Vertex Grid.
Try visualising with lucScalarField instead.
```
{: .error .language-python}

**Comment by OKaluza** [comment]
If you pass onMesh=False it should work, as onMesh=True is now the default

lucScalarField creates its own sampling grid in a cross section over the domain, default res is 100x100 but you can modify that. It can be slow if you end up sampling outside the mesh, but should always work.
lucScalarFieldOnMesh uses the mesh nodes as the sampling grid but only works for some element types, this is why it wasn't the default in the past.

I think it was changed a while back, I did discuss reverting it with @jmansour but we didn't get around to it.

**Comment by jmansour** [comment]
Yep, you can set `onMesh=False`, or not use the subMesh:

```python
mesh = uw.mesh.FeMesh_Cartesian(elementType="Q2/dQ1")
var = mesh.subMesh.add_variable(dataType="double", nodeDofCount=1)
figMesh = glucifer.Figure()
figMesh.Surface(mesh, var)
figMesh.show()
```

@OKaluza, how hard would it be to actually use the submesh for `onMesh=True` type rendering? So for dQ0, it would just render a quad with constant value, and for dQ1 it would render a quad sampled at the 3 nodes to generate a linear profile across the quad. 

We should improve the messaging at the very least.

**Comment by OKaluza** [comment]
Problem is in this file [here](https://github.com/underworldcode/underworld2/blob/master/libUnderworld/gLucifer/DrawingObjects/src/CrossSection.cpp#L298)

It uses this ugly thing to get a vertex grid:
` vertGrid = *(Grid**)ExtensionManager_Get( mesh->info, mesh, self->vertexGridHandle );`

and iterates over element res while using that to project indices to vertices [here](https://github.com/underworldcode/underworld2/blob/master/libUnderworld/gLucifer/DrawingObjects/src/CrossSection.cpp#L615)

Yeah the check and resulting message is a bit useless and out of date.

TBH happy to try and fix it if it's straightforward but I don't like putting hours into working on this old vis stuff, my opinion is that time would be better spent porting to use a higher level python interface now, but it really needs to be done all at once. I was holding out as not sure of your plans regarding full python underworld (UW3?) via petsc-python - if all the old code is going then that would be the time for a fresh approach to viz code, and also need to ask Steve.Q about funding status, we should talk about it.

**Comment by rbeucher** [comment]
That's fine. I think we can live with that.
