### ISSUE TITLE
Mixed elements support (Q2/Q1), (Q2/dQ0)

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#332]
The manual states that we can use mixed elements such as Q2/dQ0, Q2/Q1 etc...

I tried and in only works for discontinuous elements.

I think that is OK as those are the ones we use. 
Would be good to raise a proper exception, unless we want to support them...
In that case we need to update the manual...

```

NameErrorTraceback (most recent call last)
<ipython-input-9-428b3fa9c230> in <module>()
      4                                  elementRes  = (8, 8),
      5                                  minCoord    = (0.0, 0.0),
----> 6                                  maxCoord    = (2.0, 1.0) )
      7 
      8 # visualising the result

/opt/underworld2/underworld/_stgermain.pyc in __call__(cls, *args, **kwargs)
    111                 _setup = _setup.__get__(self, cls)
    112             if callable(_setup):
--> 113                 _setup()
    114 
    115         te = time.time()

/opt/underworld2/underworld/mesh/_mesh.pyc in _setup(self)
   1142         if len(self._elementTypes) == 2:
   1143             if  self._elementTypes[1].upper() == self._supportedElementTypes[1]:
-> 1144                 genSecondary = LinearCartesianGenerator(elementRes=elementRes, minCoord=minCoord, maxCoord=maxCoord, periodic=periodic, **kwargs)
   1145             elif self._elementTypes[1].upper() == self._supportedElementTypes[2]:
   1146                 genSecondary = dQ1Generator( geometryMesh=self )

NameError: global name 'elementRes' is not defined
```

**Comment by julesghub** [comment]
For reference http://femtable.org/

**Comment by julesghub** [comment]
You're right. Different element pairs for stokes aren't suitable mathematically. This needs an update quick. 
@jmansour what were the pairs you used for the analytic sols?

**Comment by lmoresi** [comment]
I thought we only used ones which are “stable” - though Q2/dQc1 is allowed and so is Q1/Q0 which was the default but usually unstable. Sometimes they work and would be worth having anyway.

Also - what if we had multiple meshes to allow a common decomposition but for different equations - Q2/Q1/dPc1 to introduce a different temperature element.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 17 Oct 2018, 17:21 +1030, Julian Giordani <notifications@github.com>, wrote:

You're right. Different element pairs for stokes aren't suitable mathematically. This needs an update quick.
@jmansour<https://github.com/jmansour> what were the pairs you used for the analytic sols?

**Comment by jmansour** [comment]
I originally set this up to only allow the discontinuous types for the submesh, but it drifted. What's there now is an outright bug, but agree we should lock down permissible combos. 

Where in the documentation are you referring to @rbeucher?

**Comment by rbeucher** [comment]
The part about the mesh. In the user guide notebooks...

**Comment by jmansour** [comment]
That notebook needs a big overhaul.

**Comment by rbeucher** [comment]
I just tried with SLADE. Seems to work fine.

**Comment by lmoresi** [comment]
I’d like to see the convection benchmarks with SLADE

Also … Q2 / {dPc1,dQc1} … the former is the stable combo but the latter also works in many cases and should be allowed.
It doesn’t have the asymmetry between top and bottom that is caused by the triangles all pointing up or down in the submesh

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 18 Oct 2018, 7:01 AM +1030, rbeucher <notifications@github.com>, wrote:

I just tried with SLADE. Seems to work fine.
