### ISSUE TITLE
[Question] Error - in TimeIntegrand_SecondOrder()

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#335]
Could anyone kindly explain what could cause this issue
EDIT:

- I use static mesh refinement, but no mesh deformation
- No outflow, all boundaries are free slip
- Issue occurs after 800 timesteps with np 3, and 801 with np 4

```
In func SystemLinearEquations_NonLinearExecute: Iteration 1 of 500 - Residual 0.00039288 - Tolerance = 0.001
Non linear solver - Residual 3.92880097e-04; Tolerance 1.0000e-03 - Converged - 4.301104e+00 (secs)

In func SystemLinearEquations_NonLinearExecute: Converged after 1 iterations.
Advecting Particles...
Time Integration
An uncaught exception was encountered on processor 1.
Traceback (most recent call last):
  File "uwIe_2d-v0.0.1.py", line 508, in <module>
    
  File "uwIe_2d-v0.0.1.py", line 474, in model_update
    advector.integrate(dt)
  File "/Users/arijit/underworld2/underworld/timing.py", line 320, in timed
    return routine(*args, **kwargs)
  File "/Users/arijit/underworld2/underworld/systems/_timeintegration.py", line 152, in integrate
    super(SwarmAdvector,self).integrate(dt)
  File "/Users/arijit/underworld2/underworld/timing.py", line 320, in timed
    return routine(*args, **kwargs)
  File "/Users/arijit/underworld2/underworld/systems/_timeintegration.py", line 50, in integrate
    libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "PLZS2P44__integrand" of type SwarmAdvector: When trying to find time deriv for item 314975 in step 1, *failed*.



=====================================================================================
Error running Underworld - Signal 15 'SIGTERM' (Termination Request).
This is caused by an external call to terminate the code.
This could have happened by a queueing system (e.g. if the code has run longer than allowed),
the code might have been killed on another processor or it may have been killed by the user.



```

**Comment by jmansour** [comment]
Hi @arijitlaik 

What are you using for your timestep size?

**Comment by arijitlaik** [comment]
the default uw thing  advector.get_max_dt() its just a large(whole mantle) slab subduction model
```python
def smooth_pressure():
    if uw.rank() == 0:
        print("Smoothing Pressure...")
    Cell2Nodes.solve()
    Nodes2Cell.solve()


def pressure_calibrate():
    (area,) = surfaceArea.evaluate()
    (p0,) = surfacePressureIntegral.evaluate()
    offset = p0/area
    pressureField.data[:] -= offset
    smooth_pressure()
    if uw.rank() == 0:
        print("Calibration and Smoothing of PressureField... Done")


def model_update():
    dt = advector.get_max_dt()
    if uw.rank() == 0:
        print("Advecting Particles...")
    advector.integrate(dt)

    if uw.rank() == 0:
        print("Repopulating Particles...")
    swarm_popcontrol.repopulate()

    uw.barrier()

    return time+dt, step+1
```

**Comment by jmansour** [comment]
🤔 Not sure about this. What is the nature of your mesh refinement?  

If you use a smaller timestep does it help?  You can setup a variable timestep if you don't want to sacrifice efficiency when everything is running correctly.

**Comment by arijitlaik** [comment]
The just a exponential refinement around a centre

**Comment by arijitlaik** [comment]
i tried with a lower resolution and lower dt, i guess something is wrong with the mesh refinement, till i do more checks, till just close this issue. maybe, this kind of question could be redirected to in gitter? if that is checked regularly, I really hate putting up these as an issue. 
thanks @jmansour

**Comment by jmansour** [comment]
Gitter will be live soon, but this is perfectly fine for an issue. 

Definitely worth double checking your mesh refinement. It's easy to get it wrong. I believe it is also possible for this issue to present for overly aggressive refinements which result in oblique elements. 

Thanks for pull requests btw.

**Comment by arijitlaik** [comment]
I am running a model with a bit less aggressive mesh refinement.
at a lower vertical resolution, i encountered the same issue but at much "much" later(4250) timesteps(way beyond whats necessary)
@jmansour  welcome :)

**Comment by arijitlaik** [comment]
The gauss integration scheme seems to work, there isn't any error yet, i checked the mesh it was consistent

**Comment by jmansour** [comment]
Sorry, what are you using Gauss for?

**Comment by arijitlaik** [comment]
as in not using the voronoi_swarm argument for the solver

**Comment by tingyang2004** [comment]
I met a similar problem today, 

step =    714; time = 1.50116e-04; time_myr = 3.97301e+01
Plastic Strain - max = 0.00999996293003
('hgn 7: ', datetime.datetime(2018, 12, 27, 4, 58, 26, 724140))
Time Integration
An uncaught exception was encountered on processor 4.
Traceback (most recent call last):
  File "input14C.py", line 981, in <module>
    
  File "input14C.py", line 871, in update
    advector2.integrate(dt,update_owners=True)
  File "/BIGDATA1/unimelb_tang_1/UW/Nov062018/underworld2-master/underworld/systems/_timeintegration.py", line 152, in integrate
    super(SwarmAdvector,self).integrate(dt)
  File "/BIGDATA1/unimelb_tang_1/UW/Nov062018/underworld2-master/underworld/systems/_timeintegration.py", line 50, in integrate
    libUnderworld.StgDomain._TimeIntegrator_Execute(self._cself, None)
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error - in TimeIntegrand_SecondOrder(), for TimeIntegrand "H3R7JPKS__integrand" of type SwarmAdvector: When trying to find time deriv for item 221631 in step 1, *failed*.

This issue is platform dependent or depends on the version of dependencies, cause I ran the same script on Pawsey without any issue. The Gaussian integration scheme does not work for me. This is reasonable since the issue lies in tracer advection, not in the stokes solver  @jmansour @arijitlaik

**Comment by arijitlaik** [comment]
Well, just and update on this,  Gaussian integration too fails at times, from what I have seen is this issue isn't platform dependent for me, i have had this issue with al types of systems, my issue was somewhat resolved by lowering the dt by a factor of 0.6-0.8 and using bit more conservative mesh refinement.
the workaround that i follow is to catch the exception, repopulate and run the advector again.

**Comment by jmansour** [comment]
I'm not sure what's the best way forward here.  At the very least, we should improve our error messaging so the user can at least know which particle has become problematic.

We could also provide an option to simply drop problematic particles.  In many cases, this will be fine, unless the model is bleeding particles en masse.  For tracer particles, this is also probably not ideal however. 

Fundamentally, there's an issue with the timestep calculation being overly optimistic. We use the node locations to calculate typically length scales, however for strongly (affine or projective) deformed  elements this will not necessarily give the smallest length scale for an element.

**Comment by tingyang2004** [comment]
It is a 2D slab subduction model with free-slip boundary conditions. Static mesh refinement is used with the maximum mesh refinement around 3. Model setup is very similar to Yang et al., 2018 Cenozoic lithospheric deformation in Northeast Asia and the rapidly-aging Pacific Plate. At least I did not have this Runtime error issue on Pawsey.

**Comment by arijitlaik** [comment]
Thanks for the information @ti gyang2004 , I too have a similar setup and comparable mesh refinement.

**Comment by tingyang2004** [comment]
To me, the timestep when the issue pops out is very random. With the same model setup and same platform, one model reports the error message at around 70 time step, another at around 800 and the third one at around 1700 step. 

Since the number of tracer particles is usually much smaller than normal particles, so I guess for a large probability, the tracer particles are always safe.

**Comment by arijitlaik** [comment]
@tingyang2004 i have noticed the same behavior and a straightforward additional factor to reduce the dt doesn't work efficiently 
BTW what version of UW were you using when you didn't have any issue?

**Comment by tingyang2004** [comment]
It was 2.5.0-dev @arijitlaik

**Comment by arijitlaik** [comment]
@jmansour @tingyang2004 I quickly ran a test with the same number of processors(24) and model here are some stray observations:

resolution 512x256

v-27_pre and v-dev
------------------------0-
**using max_dt:** model fails after 24 timesteps
**reducing the dt, _dt*0.04_ :** model fails at 900-1000 timesteps
**perCellRandomLayout** : model fails at 1700 

2.5.1b
------------------------
**using max_dt:**  currently at step = 733, and still running

I am still working out to build something that is simpler to reproduce and at lower number of timesteps. But the whole thing is a bit random for a minimal example

**Comment by jmansour** [comment]
Thanks @arijitlaik.  This is useful information.  If this is occurring for orthogonal mesh deformations, I suspect there's something broken. 

Is the reported `max_dt` identical  for both versions?

**Comment by arijitlaik** [comment]
and i can finally confirm that v2.5 doesn't have the issue. and the max_dt as you can see in the file attached does seem to be a bit more in case of the dev version, i did check it out with other model configs as well.

**Comment by jmansour** [comment]
Ok, we'll have to have a closer look.  Post a basic model when you can.

**Comment by tingyang2004** [comment]
That is interesting, I am using UW version 2.6.0b and it has the RuntimeError problem. @arijitlaik  @jmansour

**Comment by arijitlaik** [comment]
@jmansour it's a bit difficult for me to post it up here, I'll rather be comfortable with sending it over via email(i am at laikarijit_at_gmail.com)? would that be okay. As i am unsure how to make a basic version of the model, i guess its is very sensetive to the functions used.
and by the stride of luck, I have a configuration that fails really quick at the second timestep
```
underworld2-dev
step =      0; dt = 7.176e+01 Nd; time = 5.036e-01 Ma, Vrms = 6.515085e-07
step =      1; dt = 6.946e+01 Nd; time = 9.910e-01 Ma, Vrms = 6.780063e-07
***advector aborted****
----------------------------------------------------------------------------------------------------
underworld2-2.5.1b
step =      0; dt = 7.173e+01 Nd; time = 5.033e-01 Ma, Vrms = 6.527503e-07
step =      1; dt = 6.939e+01 Nd; time = 9.903e-01 Ma, Vrms = 6.796614e-07
step =      2; dt = 6.932e+01 Nd; time = 1.477e+00 Ma, Vrms = 6.809570e-07
step =      3; dt = 6.535e+01 Nd; time = 1.935e+00 Ma, Vrms = 7.316744e-07
step =      4; dt = 6.770e+01 Nd; time = 2.410e+00 Ma, Vrms = 7.142361e-07
step =      5; dt = 6.924e+01 Nd; time = 2.896e+00 Ma, Vrms = 7.014540e-07
step =      6; dt = 7.105e+01 Nd; time = 3.395e+00 Ma, Vrms = 6.886817e-07
step =      7; dt = 7.397e+01 Nd; time = 3.914e+00 Ma, Vrms = 6.728500e-07
step =      8; dt = 7.575e+01 Nd; time = 4.446e+00 Ma, Vrms = 6.524477e-07
step =      9; dt = 7.573e+01 Nd; time = 4.977e+00 Ma, Vrms = 6.375889e-07
step =     10; dt = 7.165e+01 Nd; time = 5.480e+00 Ma, Vrms = 6.718023e-07
***10 runs done***
```

**Comment by arijitlaik** [comment]
@tingyang2004 i have had no issues with -2.5.1b, so far.

**Comment by arijitlaik** [comment]
@jmansour welcome, incidentally I had that address in my Gmail address book.

**Comment by tingyang2004** [comment]
I have a problem compiling 2.5.1b on my HPC platform now. Tried various combinations of petsc and swig versions today, but all gave me the 'Error generating swig bindings' error. So hope John, Julian and Rebecca can find the issue causing the TimeIntegrand_SecondOrder() error.

**Comment by jmansour** [comment]
@tingyang2004 perhaps start another ticket for your swig binding issues.  Usually we can resolve binding problems without too much difficulty.

**Comment by jmansour** [comment]
This should be fixed via merged pull request above.  I'll close, but reopen if necessary.
