### ISSUE TITLE
A few problems compiling on Mac

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#34]
Tried to build on Mac at commit 0610383

Found that I had to revert a couple of files: swigall.py, and ./config/packages/HDF5.py:

git checkout 2675978e5c832e206ce0c2042310539b441aa503 swigall.py

git checkout d969231e8b67ebc3b4c2f991d32cd3ec0c68e5f0 ./config/packages/HDF5.py

Otherwise it couldn't find HDF5, and the swigging didn't work.

Dan

**Comment by jmansour** [comment]
Hi Dan.  The swigall.py was my bad.  Committed that by accident.  Fixed now!

The HDF5.py config script we changed recently, but seems a few people are having difficulties with it.  I've committed a new version.  Can you give it a shot and report back here?  

Cheers

**Comment by dansand** [comment]
All good now,

Thanks John
