### ISSUE TITLE
Error image_tests on dev

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#340]
Running the current dev docker I'm getting only this error in the testing suit.
Running the image_test.py
```
Testing Notebook: 08_Visualisation
PASS: ./Figure_2.png Image comp errors 0.000064, within tolerance 0.001000 of ref image.
PASS: ./Figure_3.png Image comp errors 0.000000, within tolerance 0.001000 of ref image.
PASS: ./Figure_4.png Image comp errors 0.000001, within tolerance 0.001000 of ref image.
PASS: ./Figure_5.png Image comp errors 0.000000, within tolerance 0.001000 of ref image.
PASS: ./Figure_6.png Image comp errors 0.000000, within tolerance 0.001000 of ref image.
PASS: ./Figure_7.png Image comp errors 0.000219, within tolerance 0.001000 of ref image.
PASS: ./Figure_8.png Image comp errors 0.000064, within tolerance 0.001000 of ref image.
FAIL: ./highdef.png Image comp errors 0.087308, not within tolerance 0.001 of reference image
```
@OKaluza any ideas?

**Comment by jmansour** [comment]
![expected](https://user-images.githubusercontent.com/1439389/47492729-5efc7780-d899-11e8-8939-478518568625.png)
![highdef](https://user-images.githubusercontent.com/1439389/47492730-5efc7780-d899-11e8-8b1b-847f9fa32a97.png)

**Comment by OKaluza** [comment]
So now the Surface has been changed to set onMesh=True by default it's quite sensitive to any change in the triangulation. 

This example looks awful either way with onMesh=True because there is not enough resolution in the 2x2 mesh grid to get any decent interpolation between nodes as it just plots 8 triangles without using the old 100x100 default sample grid.

At some point I updated lavavu to make the ordering of vertices more consistent and since the update the test images must have been updated to match the old ordering.

Either, revert to using onMesh=False by default, or just regenerate the test images. One option I considered was: supply resolution=[x,y] to Surface() and it will sample on user-defined grid, otherwise onMesh=True and uses the mesh.

Anyway it's up to you guys, the onMesh mode is fast and good as long as it supports the type of elements you are using and there is enough resolution in the mesh, but it was never the default because it will bomb out if it can't make certain assumptions about the node layout.

**Comment by lmoresi** [comment]
Perhaps a different form of test is needed. I am not sure what would be better though.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 27 Oct 2018, 09:22 +1100, jmansour <notifications@github.com>, wrote:
But it appears that the main issue is the location of the colour bar, title
etc. I'll note that the image files are of very different resolutions too,
as in #341

**Comment by jmansour** [comment]
The tests are doing their job correctly. The images are different.

**Comment by lmoresi** [comment]
But they are different for reasons that cannot be given a tolerance.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 27 Oct 2018, 10:10 +1100, jmansour <notifications@github.com>, wrote:

The tests are doing their job correctly. The images are different.

**Comment by OKaluza** [comment]
Sorry my mistake, trying to meet a deadline on another project so I just scanned the issue too quickly.
The onmesh thing is definitely making the image look terrible but that is another issue.

Yes there's something wrong with the colourbar scaling in the version you are using - I should get a chance to look at it tomorrow.

I assume the docker image uses the latest lavavu pip package?

**Comment by julesghub** [comment]
Yes indeed https://github.com/underworldcode/underworld2/blob/ea5ab8edae96adeba005d67d8c41169e43eb2baa/docs/development/docker/underworld2/Dockerfile#L14

**Comment by OKaluza** [comment]
Can't seem to run the docker image at all, any idea what this is about?
```
$ docker run -v $PWD:/workspace/home -p 8888:8888 underworldcode/underworld2_untested:dev
[I 05:38:06.525 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1379, in init_webapp
    self.jinja_environment_options,
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 251, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by arijitlaik** [comment]
i think the ```underworldcode/underworld2:dev``` is the development branch now

**Comment by jmansour** [comment]
Yeah there were some issues at some stage to do with the latest version of Jupyter.  I thought they were resolved (even on `underworld2_untested`), but as @arijitlaik pointed out, automated image generation (from the `development` branch) are created at `underworldcode/underworld2:dev` now.  The `underworld2_untested` repo will be renamed and be used for all auxiliary images.

**Comment by arijitlaik** [comment]
@jmansour i was using the untested dev for a while but then suddenly it stopped trying to launch jupyter for sometime after the new release was done.
 
P.S. finally switching to docker. ;)

**Comment by OKaluza** [comment]
This is proving impossible to duplicate outside this docker image, everywhere else it works fine.
How can I rebuild it with modifications?
It doesn't seem to want to copy files in, COPY succeeds but does nothing.
Tried running from underworld root dir:
`
docker build -t uwtest docs/development/docker/underworld2
`
I get
```
 ---> 1b2d03e4a0eb
Step 10/15 : COPY . $UW2_DIR/
 ---> 78bc804320fc
Step 11/15 : RUN cd underworld2/libUnderworld &&     ./configure.py --with-debugging=0  &&     ./compile.py                 &&     rm -fr h5py_ext              &&     rm .sconsign.dblite          &&     rm -fr .sconf_temp           &&     cd build                     &&     rm -fr libUnderworldPy       &&     rm -fr StGermain             &&     rm -fr gLucifer              &&     rm -fr Underworld            &&     rm -fr StgFEM                &&     rm -fr StgDomain             &&     rm -fr PICellerator          &&     rm -fr Solvers               &&     find $UW2_DIR/docs -name \*.ipynb  -print0 | xargs -0 jupyter trust &&     rsync -av $UW2_DIR/docs/. $NB_WORK                               &&     cd /opt/underworld2                                              &&     find . -name \*.os |xargs rm -f                                  &&     cat .git/refs/heads/* > build_commit.txt                         &&     env > build_environment.txt                                      &&     rm -fr .git                                                      &&     chown -R $NB_USER:users $NB_WORK $UW2_DIR /home/$NB_USER
 ---> Running in 676bfab3c9b4
/bin/sh: 1: cd: can't cd to underworld2/libUnderworld
The command '/bin/sh -c cd underworld2/libUnderworld &&     ./configure.py --with-debugging=0  &&     ./compile.py                 &&     rm -fr h5py_ext              &&     rm .sconsign.dblite          &&     rm -fr .sconf_temp           &&     cd build                     &&     rm -fr libUnderworldPy       &&     rm -fr StGermain             &&     rm -fr gLucifer              &&     rm -fr Underworld            &&     rm -fr StgFEM                &&     rm -fr StgDomain             &&     rm -fr PICellerator          &&     rm -fr Solvers               &&     find $UW2_DIR/docs -name \*.ipynb  -print0 | xargs -0 jupyter trust &&     rsync -av $UW2_DIR/docs/. $NB_WORK                               &&     cd /opt/underworld2                                              &&     find . -name \*.os |xargs rm -f                                  &&     cat .git/refs/heads/* > build_commit.txt                         &&     env > build_environment.txt                                      &&     rm -fr .git                                                      &&     chown -R $NB_USER:users $NB_WORK $UW2_DIR /home/$NB_USER' returned a non-zero code: 2
```
If I put an `ls /opt/underworld2` in it just shows Dockerfile and nothing else copied.

**Comment by jmansour** [comment]
You need to build from the top level directory now @OKaluza:

```bash
$ docker build -f docs/development/docker/underworld2/Dockerfile .
```

I've updated the Dockerfile with a comment to this effect:

ee07aa4b4d8800177a1c97d3fb77e9a4955d7af3

**Comment by OKaluza** [comment]
Thanks! I was 99% there, but left off the final .

**Comment by jmansour** [comment]
Note that one key difference with the docker environment is the usage of XVFB.

**Comment by OKaluza** [comment]
Hmm, true, I did try a build with a Mesa GL but not sure I used Xvfb, will give that a try

**Comment by OKaluza** [comment]
Unfortunately running with mesa libGL and Xvfb does not duplicate the error, I'm stuck working in docker, because of the way the build is structured every tiny change I make triggers a full rebuild from scratch, argh!

**Comment by OKaluza** [comment]
This was fixed a long time ago, guessing it was lost in a bad merge, not sure when:

https://github.com/underworldcode/underworld2/commit/255fa942a78b23ab8f1aa5749cca0a2c465b02e9

I hate notebooks in git, there is so much cruft that you can't see changes when merging

**Comment by julesghub** [comment]
@OKaluza jenkins is back up and running. 
dev is failing on image_tests.py again.
See here.
http://130.56.252.251:32779/job/Underworld2/job/development/2/execution/node/3/ws/utils/testResults/test_30__image_tests.py.err/*view*/

Any ideas? 
If I try locally with the dev docker it works. So maybe something about having an output device?

**Comment by OKaluza** [comment]
@julesghub no idea, not much information there. Is this MacOS? If so user needs to be logged locally etc for permissions to use display.

**Comment by julesghub** [comment]
No, it's not on MacOS. It's run on our dev container in the cloud. It's being run via jenkins so there's no active display environment. 
The problem also appears to be intermittent. I am not 100% on why. Permissions?

**Comment by julesghub** [comment]
Closing this off. image_test.py are passing on the 2.8 rc.
