### ISSUE TITLE
Imposing tractions as BC

### ISSUE THREAD

**Issue by techas** [underworldcode/underworld2#344]
Hi!
Is there some way to impose tractions as boundary conditions to the mechanical problem?
Thanks!
SZ

I'm thinking in something like: 
   \sigma \cdot \vec{n} = -p \vec{n} + 2 \eta \cdot \nabla^s \vec{v}

where
\sigma is the stress tensor
\vec{n} is the normal to the boundary
p is the pressure
\eta is the viscosity
\vec{v} is the velocity
and \nabla^s is the symmetrized gradient

**Comment by julesghub** [comment]
Hi Sergio,

Yes there is. It's called the NeumannConditions() class. The user defines the tractions as a meshvariable that is then applied on the boundaries.
See this example here.
https://github.com/underworldcode/underworld2/blob/master/docs/test/StokesEq_PoiseuilleFlow.ipynb
where the tractions are applied in the normal direction to produce a pressure gradient.

The user can define tangential tractions as well.

Care by the user must be taken to not apply both Neumann and Dirichlet conditions on the same dof. Currently we don't have a mechanism to check that.

**Comment by techas** [comment]
Great! Thanks Jules!
