### ISSUE TITLE
Problem with meshVariable 'interpolate' option

### ISSUE THREAD

**Issue by rsbyrne** [underworldcode/underworld2#350]
Hi

I've run into a problem with the 'interpolate' option for loading mesh variables. The error only occurs when interpolating from one mesh onto a different-sized mesh; 'interpolating' onto an identical mesh is no problem, as the code snippet below demonstrates.

Cheers

Error message:
`TypeError: 'elementRes' list must only contain positive integers.`

Code:
`import underworld as uw`
`mesh = uw.mesh.FeMesh_Cartesian()`
`var = mesh.add_variable(1)`
`meshHandle = mesh.save("tempmesh.h5")`
`var.save("tempvar.h5", meshHandle)`
`mesh2 = uw.mesh.FeMesh_Cartesian()`
`var2 = mesh2.add_variable(1)`
`var2.load("tempvar.h5", interpolate = True)`
`mesh3 = uw.mesh.FeMesh_Cartesian(elementRes = (5, 5))`
`var3 = mesh3.add_variable(1)`
`var3.load("tempvar.h5", interpolate = True)`

**Comment by julesghub** [comment]
Looks like a py2 --> py3 issue. 
Previously, h5py loaded a mesh and used py2 and `tuple()` to convert type `np.int64` to python `int`.
This isn't happening in py3. We can use `tolist()` in py3 to convert types.

**Comment by julesghub** [comment]
Fix is here 1c85883cc9ec11cc2298d30606103f38616ce10c. In the development. I haven't tested this fix for 2.7 release branch. Still to do.
I have added a test as well - loading a field with the interpolate method on. As per the above snippet.
Thanks for the bug report Rohan!
