### ISSUE TITLE
unknown bug in solver

### ISSUE THREAD

**Issue by yanghappy1991** [underworldcode/underworld2#352]
# coding: utf-8

import numpy as np
import math
import os

import underworld as uw
from underworld import function as fn
import glucifer

import mpi4py
comm = mpi4py.MPI.COMM_WORLD

# In[14]:

outputPath = os.path.join(os.path.abspath("."),"test")
if uw.rank() == 0:
    if not os.path.exists(outputPath):
        os.makedirs(outputPath)
uw.barrier()

# Create mesh and finite element variables
# ------
# 
# Note: the use of a pressure-sensitive rheology suggests that it is important to use a Q2/dQ1 element 

# In[15]:

minX  = -2.0;   minY = 0.0
maxX  =  2.0;   maxY = 1.0
minXv =  1.0
maxXv = -1.0

resX = 128
resY = 64

elementType="Q2/dPc1"  # This is enough for a test but not to use the code in anger

mesh = uw.mesh.FeMesh_Cartesian( elementType = (elementType), 
                                 elementRes  = ( resX, resY), 
                                 minCoord    = ( minX, minY), 
                                 maxCoord    = ( maxX, maxY),
                                 periodic    = [True, False]  ) 

velocityField    = uw.mesh.MeshVariable( mesh=mesh,         nodeDofCount=mesh.dim )
pressureField    = uw.mesh.MeshVariable( mesh=mesh.subMesh, nodeDofCount=1 )

velocityField.data[:] = [0.,0.]
pressureField.data[:] = 0.

# ### Boundary conditions
# 
# Pure shear with moving  side walls — all boundaries are zero traction with outflow top and bottom
# to accommodate changing volume

# In[16]:

iWalls = mesh.specialSets["MinI_VertexSet"] + mesh.specialSets["MaxI_VertexSet"]
jWalls = mesh.specialSets["MinJ_VertexSet"] + mesh.specialSets["MaxJ_VertexSet"]
base   = mesh.specialSets["MinJ_VertexSet"]
top    = mesh.specialSets["MaxJ_VertexSet"]

#velocityField.data[mesh.specialSets["MinJ_VertexSet"]] = 0.

for index in mesh.specialSets["MinJ_VertexSet"]:
    velocityField.data[index] = [0.5, 0.]
for index in mesh.specialSets["MaxJ_VertexSet"]:
    velocityField.data[index] = [0., 0.]
    
periodicBC = uw.conditions.DirichletCondition( variable        = velocityField, 
                                               indexSetsPerDof = ( jWalls, jWalls) ) 

# ### Setup the material swarm and passive tracers
# 
# The material swarm is used for tracking deformation and history dependence of the rheology
# 
# Passive swarms can track all sorts of things but lack all the machinery for integration and re-population

# In[17]:

# Create a swarm.
swarm = uw.swarm.Swarm( mesh=mesh, particleEscape=True )

# Create a data variable. It will be used to store the material index of each particle.
#materialIndex = swarm.add_variable( dataType="int", count=1 )
director = swarm.add_variable(dataType="double", count=3)
StrainRate = swarm.add_variable( dataType="double", count=3 )
vis1 = swarm.add_variable( dataType="double", count=1 )
vis2 = swarm.add_variable( dataType="double", count=1 )
#StrainRate_local = swarm.add_variable( dataType="double", count=3 )
AniStress = swarm.add_variable( dataType="double", count=3 )
# Create a layout object, populate the swarm with particles.

swarmLayout = uw.swarm.layouts.PerCellSpaceFillerLayout( swarm=swarm, particlesPerCell=50 )
swarm.populate_using_layout( layout=swarmLayout )

pop_control = uw.swarm.PopulationControl(swarm,aggressive=True,particlesPerCell=50)

# Initialise director in z (fault normal) direction

director.data[:] = (0.0, 0.0, 1.0)

# ### Add swarm variables
# 
# We are using a single material with a single rheology. We need to track the plastic strain in order to have some manner of strain-related softening (e.g. of the cohesion or the friction coefficient). For visualisation of swarm data we need an actual swarm variable and not just the computation.
# 
# Other variables are used to track deformation in the shear band etc.
# 
# **NOTE**:  Underworld needs all the swarm variables defined before they are initialised or there will be / can be memory problems (at least it complains about them !). That means we need to add the monitoring variables now, even if we don't always need them.

# In[18]:

# Tracking different materials

materialVariable = swarm.add_variable( dataType="int", count=1 )

# Tracking the director orientation

directorVector   = swarm.add_variable( dataType="double", count=2)

# ### Initialise swarm variables
# 
# (Other than the material distribution)

# In[19]:

orientation = 0.0 * math.pi / 180.0 
directorVector.data[:,0] = math.cos(orientation)
directorVector.data[:,1] = math.sin(orientation)

# ### Material distribution in the domain.
# 
# 

# In[20]:

# Initialise the 'materialVariable' data to represent different materials. 

materialA  = 0 # accommodation layer a.k.a. Sticky Air (NOT USED HERE)
materialV  = 1 # Squasher blocks
materialTI = 2 # Sample (transversely isotropic)

# The particle coordinates will be the input to the function evaluate (see final line in this cell).
# We get proxy for this now using the input() function.

coord = fn.input()
xCoord = fn.coord()[0]
yCoord = fn.coord()[1]

# Setup the conditions list for the following conditional function. Where the
# z coordinate (coordinate[1]) is less than the perturbation, set to lightIndex.

conditions = [ (       fn.math.abs(yCoord-0.5)  < 0.1,     materialTI),
               (       True ,                              materialV ) ]

# The actual function evaluation. Here the conditional function is evaluated at the location
# of each swarm particle. The results are then written to the materialVariable swarm variable.

materialVariable.data[:] = fn.branching.conditional( conditions ).evaluate(swarm)

viscosityA   = 0.01
viscosityV   = 1.0
viscosityTI  = viscosityV

viscosityA2   = 0.0  
viscosityV2   = 0.0
viscosityTI2  = viscosityTI * 0.9  # -> \eta_2 = 0.1 * \eta_1

viscosityMap  = { materialA: viscosityA,  materialV:viscosityV,  materialTI:viscosityTI  }
viscosity2Map = { materialA: viscosityA2, materialV:viscosityV2, materialTI:viscosityTI2 }

firstViscosityFn   = fn.branching.map( fn_key = materialVariable, 
                                       mapping = viscosityMap )

secondViscosityFn  = fn.branching.map( fn_key = materialVariable, 
                                       mapping = viscosity2Map )

# System setup
# -----
# 
# Setup a Stokes equation system and connect a solver up to it.  
# 
# In this example, no buoyancy forces are considered. However, to establish an appropriate pressure gradient in the material, it would normally be useful to map density from material properties and create a buoyancy force.

# In[ ]:

stokes = uw.systems.Stokes( velocityField  = velocityField, 
                               pressureField  = pressureField,
                               conditions     = [periodicBC,],
                               fn_viscosity   = firstViscosityFn, 
                               #_fn_viscosity2 = secondViscosityFn,
                               #_fn_director   = directorVector,                         
                               fn_bodyforce   = None )

solver = uw.systems.Solver( stokes )

## MUMPS is a good choice for small / 2D problems
solver.set_inner_method("mumps")
#solver.set_penalty(1000000.0)
#solver.options.main.restore_K=False

# ## Main simulation loop
# 
# To see if things are working correctly, we plot strain rate at (0.0, 0.5) which is at the centre of the aniso block as a function of the orientation of the director.  
# 
# We could specify the director as a function as there is no history or advection in the problem, but let's leave it as a swarm variable for now.
# 
# 

# In[ ]:

#for orientationDegrees in range(1, 92, 30):

step = 0

solver.solve( nonLinearIterate=True,  nonLinearTolerance=1e-3, nonLinearMaxIterations=25)

# theta = math.pi/2.+orientation
# l1 = math.cos(theta)
# l2 = math.sin(theta)
# m1 = -math.sin(theta)
# m2 = math.cos(theta)

StrainRate.data[:] = fn.tensor.symmetric( velocityField.fn_gradient).evaluate(swarm)
# Exx = StrainRate_local.data[:,0]
# Eyy = StrainRate_local.data[:,1]
# Exy = StrainRate_local.data[:,2]
# StrainRate.data[:,0] = Exx*l1*l1+Eyy*m1*m1+Exy*l1*m1
# StrainRate.data[:,1] = Exx*l2*l2+Eyy*m2*m2+Exy*l2*m2
# StrainRate.data[:,2] = Exx*l1*l2+Eyy*m1*m2+Exy*(l1*m2+l2*m1)

vis1.data[:] = firstViscosityFn.evaluate(swarm)
vis2.data[:] = secondViscosityFn.evaluate(swarm)
#devStressFn = 2.0*(viscosityFn-viscosity2Fn)*strainRateFn 
for index, coord in enumerate(swarm.particleCoordinates.data):
    AniStress.data[index][0] = 2.0*vis1.data[index]*StrainRate.data[index][0]
    AniStress.data[index][1] = 2.0*vis1.data[index]*StrainRate.data[index][1]
    AniStress.data[index][2] = 2.0*(vis1.data[index]-vis2.data[index])*StrainRate.data[index][2]
meshAniStress = uw.mesh.MeshVariable( mesh=mesh,         nodeDofCount=3 )
projectorStress = uw.utils.MeshVariable_Projection(meshAniStress,AniStress,type=0 )
projectorStress.solve()    

# In[ ]:

#print orientation,theta,l1,l2,m1,m2

# In[ ]:

swarm.save(outputPath+"swarm"+str(step).zfill(4))
meshAniStress.save(outputPath+"meshDevStress"+str(step).zfill(4))
materialVariable.save(outputPath+"materialVariable"+str(step).zfill(4))
velocityField.save(outputPath+"velocityField"+str(step).zfill(4))
#AniStress.save(outputPath+"AniStress"+str(step).zfill(4))
  

# In[ ]:

**Comment by julesghub** [comment]
Aghh haibin, can you attach the file instead copying and pasting it. Something like this.
[some.txt](https://github.com/underworldcode/underworld2/files/2678269/some.txt)

**Comment by yanghappy1991** [comment]
This is the simplest case where only isotropic model is implemented. It complains like this in the solver part:
_A floating-point operation error has been detected during the solve.
The resultant solution fields are most likely erroneous, check them thoroughly.
This is likely due to large number variations in the linear algrebra or fragile solver configurations.
Consider rescaling the fn_viscosity or fn_bodyforce inputs to avoid this problem.
This warning can be supressed with the argument 'fpwarning=False'.
  warnings.warn(estring)_

**Comment by julesghub** [comment]
Try this 
[4Haibin.ipynb.txt](https://github.com/underworldcode/underworld2/files/2678773/4Haibin.ipynb.txt)
