### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by adambeall** [underworldcode/underworld2#358]
I am in the process of compiling the latest UW version on a cluster and it looks like Python 3 is now required? Is this true or is there a way to set the Python environment to 2?

**Comment by rbeucher** [comment]
The dev branch is now python 3 only... yes..

**Comment by adambeall** [comment]
So there is no way to compile it with Python 2? Ok, thanks for confirming Romain.
It might be handy to have the latest dependencies listed somewhere.

**Comment by rbeucher** [comment]
Yes I agree. It is the dev branch though so things are still evolving. There is a 2.7 branch that is still python2 if you want to use something recent. We won't make UW python3 only before 2.8

**Comment by adambeall** [comment]
Excellent, I didn't see the 2.7 branch. Thanks for your help.

**Comment by rbeucher** [comment]
You can have a look at my UWGeo documentation, It explains how to install the python3 version on raijin with the latest librairies... that could help
https://uwgeodynamics.readthedocs.io/en/latest/Installation.html#hpc-installation

**Comment by julesghub** [comment]
@adambeall you can also checkout the dev branch dockerfile for the dependencies required.
https://github.com/underworldcode/underworld2/blob/development/docs/development/docker/base/Dockerfile
