### ISSUE TITLE
Periodic BC problem

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#36]
Hi John 

I have a model where periodic BCs seem to be working fine for a unit square version, but when I extend to a rectangular domain, they no longer seem to apply. I set the  BCs like this :

`slipBC = uw.conditions.DirichletCondition(     variable=velocityField, 
                                              nodeIndexSets=(None, JWalls) ) `

i.e. I pass None to the X velocity component. (I realise that this could introduce a null space problem, but I don't think that's the problem here)

As I say, in the unit square model, I'm getting periodic BC, and I can ask, for instance, what the max X velocity component on the IWalls is; in the rectangular model, the velocities on the IWalls look completely vertical, and a query on the boundary X velocities returns something like:

None Type has not attribute max...

As if the None argument in the BC setup is being taken literally. 

Script is here: 

https://github.com/dansand/vueesc/blob/master/base_model.py

`MINX = 0` for the square model
`MINX = -1.`, for the rectangular model

**Comment by dansand** [comment]
Actually, I think the Periodic BCs are working in both cases. 

The rectangular model has a completely symmetric temperature profile around x = 0, so I think the zero X velocity component on the boundaries may be realistic even with periodic BCS (though i would have expected perhaps very small X velocities) - anyway, I'm checking this now with a small random perturbation.

**Comment by julesghub** [comment]
if still an issue please reopen
