### ISSUE TITLE
Add purge method to swarm.

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#360]
To delete all particles.

**Comment by rbeucher** [comment]
I am still waiting!!

**Comment by jmansour** [comment]
I'll do it for Christmas for you!

**Comment by arijitlaik** [comment]
So am I, especially helpful when post processing swarms
Arijit Laik,
*Faculteit der Bètawetenschappen: Geologie en geochemie D (2923D)* |*
Promovendus*
*(PhD Candidate**, Geology and Geochemistry Cluster, Department of Earth
Sciences,*
*Faculty of Science, Vrije University Amsterdam)*
[image: email_vu_logo_beta_en.png]
☎️ +31 20 59 87294, 📱 +91 8116114002
📧 a.laik@vu.nl,laikarijit@gmail.com
https://alaik.me
🏢 Gebouw Wis- en Natuurkunde E-229,
De Boelelaan 1081- 1087, 1081 HV, Amsterdam
