### ISSUE TITLE
average temperature at a certain depth

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#361]
Hi all,

I am wondering if there is a convenient way to get the average temperature at a certain depth in uw2?
Basically, I want to plot the evolution of the average temperature profile of my model.
Thanks.

Best regards,
Ting

**Comment by jmansour** [comment]
`Function.evaluate_global()` is probably the best bet:

https://underworld2.readthedocs.io/en/latest/underworld.function.html#underworld.function.Function.evaluate_global

**Comment by tingyang2004** [comment]
Thanks John.
This seems a viable way. Is there any convenient way to get the global coordinate extent then, so that I can know where to evaluate the temperature?

**Comment by lmoresi** [comment]
I thought the global coordinate range is something that you know because you set it up in the first place. It is the local coordinate extent that is problematic since you have no control over the decomposition.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 28 Feb 2019, 2:54 PM +1100, tingyang2004 <notifications@github.com>, wrote:

Thanks John.
This seems a viable way. Is there any convenient way to get the global coordinate extent then, so that I can know where to evaluate the temperature?

**Comment by rbeucher** [comment]
I would do it in Paraview. Create a line source, extract the values and calculate the average.

**Comment by jmansour** [comment]
Save it for the Hub workshop @rbeucher 😜

**Comment by lmoresi** [comment]
Except it would be useful to be able to use these kinds of values in the scripts while they are running.

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 28 Feb 2019, 3:17 PM +1100, Romain Beucher <notifications@github.com>, wrote:

I would do it in Paraview. Create a line source, extract the values and calculate the average.

**Comment by tingyang2004** [comment]
Thanks all.
The average temperature may be needed in a model if, for example, you have both the bottom and top thermal boundary layers and you want to track the location of the plumes at each time step based on the excess temperature relative to the horizontal average. Well, for now, you can do these in the post-process phase.

Best regards,
Ting

**Comment by rbeucher** [comment]
In that case you can just use a set of tracers that are not advected... You do a global evaluation on them...

**Comment by rbeucher** [comment]
As for the global coordinate extent you get it from the mesh.minCoords and mesh.maxCoords...

**Comment by tingyang2004** [comment]
Thanks, Romain.
Seems mesh.maxCoords and mesh.minCoords only gives the initial extent of the coordinates.
I used two ways to generate the horizontal average. One is with fn.evaluate_global as John suggested, the other is utils.Integral of a field whose surface is iteratively changed to be each line of the temperature field. Both methods give consistent results. So I will stop further exploring now.

![image](https://user-images.githubusercontent.com/26615840/53542922-a0f53d00-3b5b-11e9-9bc7-6be6df5f0c52.png)

**Comment by lmoresi** [comment]
Ting, don’t forget that there is a fn.coords that you can use together with the fn for global max/min evaluations that should be helpful here.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 28 Feb 2019, 4:25 PM +1100, tingyang2004 <notifications@github.com>, wrote:

Thanks, Romain.
Seems mesh.maxCoords and mesh.minCoords only gives the initial extent of the coordinates.
I used two ways to generate the horizontal average. One is with fn.evaluate_global as John suggested, the other is utils.Integral of a field whose surface is iteratively changed to be each line of the temperature field. Both methods give consistent results. So I will stop further exploring now.

[image]<https://user-images.githubusercontent.com/26615840/53542922-a0f53d00-3b5b-11e9-9bc7-6be6df5f0c52.png>

**Comment by jmansour** [comment]
@tingyang2004  yep you're correct `minCoord` etc only give the initial values.  We should fix this.

**Comment by tingyang2004** [comment]
Thanks, Louis, I did a bit research today.
I guess you meant 
tmp=fn.view.min_max(fn.coord()[0]).evaluate(mesh)
print tmp.min(), tmp.max(), len(tmp)

**Comment by rbeucher** [comment]
I believe this is fixed @tingyang2004. I am closing. Feel free to reopen if needed.
