### ISSUE TITLE
install on Ubuntu 18.04.02

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/underworld2#362]
I have success install underworld script on Ubuntu 18.04.02

./configure .py and ./compile.py

but still can't import underworld module

and I have set pythonpath export PYTHONPATH=$PYTHONPATH:/home/cgw0814/nm/underworld2
and still not use

I think lost something @@

![underworld install](https://user-images.githubusercontent.com/38973778/54515448-0ab47a00-4997-11e9-8219-b732c11b77f2.JPG)

**Comment by arijitlaik** [comment]
kindly install the pint module via pip,
pip install --user pint

**Comment by cgw0814** [comment]
thank you @arijitlaik , it's totally work!!!!

**Comment by julesghub** [comment]
Cheers @arijitlaik. Closing ticket for now.
