### ISSUE TITLE
Surface topography precision with sticky-air method

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#363]
Hi all,

I tried to reproduce the topography evolution of Case 2 in Crameri et al., 2012 GJI with UW recently. Sticky-air method is used (A 150 km thick sticky-air layer, sticky-air viscosity 1e18 Pas, similar to Fig. 7 of Crameri).
Although I can generally reproduce the result of Crameri, some significant differences still exist. Even with a resolution of 2.5 km as used in the paper, 1-2 hundred meter topography difference from Crameri still exists. For example, at x=1400 km, my model predict 1 km topography, while Crameri gives 0.8 km topo. The script is attached below. Any suggestions on how to enhance the model efficiency or precision will be appreciated. Thanks a lot.

The .py script is uploaded as a txt file.
[input6EA.txt](https://github.com/underworldcode/underworld2/files/2981027/input6EA.txt)

Topography calculated from UW at 16 Myr is as below:
![TotalTopo410](https://user-images.githubusercontent.com/26615840/54572968-177faf00-4a25-11e9-85bd-1057b76b6d81.png)

Topography from Crameri as below:
![Fig1](https://user-images.githubusercontent.com/26615840/54575381-dd1b0f80-4a2e-11e9-8542-ac82cfcb7289.jpg)

Best regards,
Ting

**Comment by julesghub** [comment]
Hi Ting,
I am not familiar with the details of the setup. I'll do some reading and get back to you. 
Thanks for the model upload. What material is your sticky air layer? `WaterIndex`

**Comment by tingyang2004** [comment]
Thanks very much, Julian.
WaterIndex actually points to air (density set zero) instead of water in this case.

Another thing I found is that when I ran model evolution for the whole domain, that is, did not use the symmetric condition and only the right half of the domain, the resulted topography is much worse. This is reasonable given the larger degree of freedom for the whole domain model. But it may also have revealed the large instability of topography calculation.
![TotalTopo410](https://user-images.githubusercontent.com/26615840/54656585-2e93cf00-4b01-11e9-96c7-ff3560ffaa47.png)


Best regards,
Ting

**Comment by rcarluccio** [comment]
Have you tried to increase a bit the density of your sticky air layer? In
the past, I'd use a value of  airDensity     = 1.0,  and a slightly lower
viscosity for the air layer.  There should also be a paper from Taras that
addresses a similar problem.

**Comment by rbeucher** [comment]
I'm gonna give it a try with UWGeo... Feels like something I should have

**Comment by tingyang2004** [comment]
Increasing the sticky-air layer density does help to reduce the instability since the solver instability mainly comes from the large density and viscosity contrast at fluid-solid interface. But 'slightly lower viscosity' is not suggested cause it may not meet the criteria for zero traction force assumption at the fluid-solid interface.

**Comment by rcarluccio** [comment]
I think, there is often a trade off in these cases. An air layer has a very
low viscosity and density. Using a air viscosity of 1e18 Pa*s and 1 kg*m-3
worked quite well for me in the past, those are just my two cents..

Goodluck!

**Comment by tingyang2004** [comment]
Thanks Roberta. 
My fault, I thought 'slightly' means something like just one order smaller than the background viscosity. I was using sticky-air viscosity as 1E18 or 1E19.

**Comment by rbeucher** [comment]
OK so I have one Model running with a full-extent set-up, sticky air is 1e18, and the thickness of the sticky air is 100km...
I will check how it goes and then maybe we can run the sweep of models.
3 different viscosities: 1x 18-20
3 different sticky air thicknesses: 50, 100, 200 

The sticky air thickness and viscosity clearly control the time step dt...

**Comment by rbeucher** [comment]
@tingyang2004  They run the model for 100kyrs in the paper... Why are you running it for Myr?

**Comment by tingyang2004** [comment]
Thanks Romain.
100 kyrs for Case 1 while 20 Myrs for Case 2.

**Comment by julesghub** [comment]
This looks like a drunken sailor instability, decreasing the timestep (maybe an order of magnitude) should help. Naturally this means more compute steps/time.

> Another thing I found is that when I ran model evolution for the whole domain, that is, did not use the symmetric condition and only the right half of the domain, the resulted topography is much worse (see below topography at 16 Myr). This is reasonable given the larger degree of freedom for the whole domain model. But it may also have revealed the large instability of topography calculation.
> ![TotalTopo1490](https://user-images.githubusercontent.com/26615840/54656656-6d298980-4b01-11e9-886e-27db20e200a5.png)
> 
> Best regards,
> Ting

**Comment by rbeucher** [comment]
Arg.. How long does it take to run the model?

**Comment by julesghub** [comment]
I haven't read the paper thoroughly, but section 5.1 "Time step requirements", looks like a good discussion for the drunken sailor instability.

**Comment by tingyang2004** [comment]
I also noticed the time interval requirement. The authors seem to suggest a step interval of less than 3 kyrs. Some stability schemes can be used to loose this constraint, but not sure if they are easy to implement in UW. Right now, I just used the default CFL criteria for time interval, which is usually 10 - 50 kyrs. @julesghub 

The calculation is quite fast, with a resolution of 2.5 km and half domain size, it takes me around two hrs to evolve to 30 myrs with 6 CPUS on my own desktop. @rbeucher

**Comment by lmoresi** [comment]
The usual interface-stability criteria apply (same as for a free surface). If we implement something like the Kaus et al scheme then perhaps having a true free surface would be better - that way the matrix conditioning would not be affected.



Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 20 Mar 2019, 6:11 AM +0000, tingyang2004 <notifications@github.com>, wrote:

I also noticed the time interval requirement. The authors seem to suggest a step interval of less than 3 kyrs. Some stability schemes can be used to loose this constraint, but not sure if they are easy to implement in UW. Right now, I just used the default CFL criteria for time interval, which is usually 10 - 50 kyrs. @julesghub<https://github.com/julesghub>

The calculation is quite fast, with a resolution of 2.5 km and half domain size, it takes me around two hrs to evolve to 30 myrs with 6 CPUS on my own desktop. @rbeucher<https://github.com/rbeucher>

**Comment by rbeucher** [comment]
What's the thickness of your sticky air layer? The Model I am running now has a 150km sticky air. It is quite fast to run but you do see instabilities... I think the dt is way too high (10-50kyrs)

**Comment by tingyang2004** [comment]
I was also using a 150 km thick sticky air layer. @rbeucher

**Comment by rbeucher** [comment]
Hi Ting,

OK so here is some results:
![Crameri_Case2](https://user-images.githubusercontent.com/3680918/54887166-e2bb9e00-4ee3-11e9-8f98-2dfe1641b675.png)

I am tracking the topography using passive tracers. There is quite a lot of noise as you can see.
Grid size is 560 x 340, which gives dx = 5.0km, dy = 2.5km.
The sticky Air layer is 150km thick.

Now I have just realised that my stickyair density is 1e18 pascal second... while it is 1e19 pascal second in Crameri's Fig 7C. That could explain why my topography is a bit higher... 
I used a density of 1kg/m3 for the sticky air... 

Solver: Mumps, without penalty. dt forced to 3000. yr

Romain

**Comment by rbeucher** [comment]
I have started another one with a viscoisty of 1e19

**Comment by rbeucher** [comment]
Actually based on what I see in the paper, that should not make a difference....

**Comment by tingyang2004** [comment]
Thanks Romain, that is extremely helpful.
My other model setups are similar to yous except allowing dt to evolves under the CFL conditions. So forcing dt as small as 3 kyr is necessary for topography estimates now in UW. And this dt constraint can easily increase your computational time from 2 days to one month.
I have tried setting the sticky-air viscosity as 1e19 or 1e18, they gave me quite similar topography evolution.

**Comment by rbeucher** [comment]
Yes so we have a 200m excess topography... We need to figure out where that comes from ...

**Comment by tingyang2004** [comment]
![TotalTopo5000](https://user-images.githubusercontent.com/26615840/55449402-f3fc5d00-55fd-11e9-9226-7d01e305b28d.png)

Seems reducing the maximum step interval to 3 kyr can reduce the maximum topography for me. Will reduce the maximum step interval to 2 kyr and see if it helps to remove the left 100 m excess topography.

**Comment by rbeucher** [comment]
They don't really discuss that much in the paper. That is annoying. There is a paragraph of course but we don't know what they used.

**Comment by tingyang2004** [comment]
![TotalTopo8000](https://user-images.githubusercontent.com/26615840/55538855-f0e29900-56f1-11e9-80a8-0e3ab686aea3.png)
Well, reducing the step interval from 3 kyr to 2 kyr does help to reduce the excess topography slightly.
So in principle, we can reproduce topography evolution of Crameri et al., 2012 with UW2 with high resolution models and small step intervals.

**Comment by RebeccaFarrington** [comment]
Great work Ting & co!

**Comment by rbeucher** [comment]
I don't see much of a difference Ting. And we are still off by 100m...I will do some more tests using different averaging techniques.

**Comment by lmoresi** [comment]
Why don’t we step back for a moment and solve an analytic solution (e.g. post glacial rebound) and double check nothing has changed. I think Ting did this a while ago while looking at the various free-surface implementations.

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 5 Apr 2019, 10:18 AM +1100, Romain Beucher <notifications@github.com>, wrote:

I don't see much of a difference Ting. And we are still off by 100m...I will do some more tests using different averaging techniques.

**Comment by tingyang2004** [comment]
The improvement is slight.
Note zoom in of Crameri figure shows maximum topo around 850 m, my 3 kyr experiment shows topp around 950, but my 2 kyr experiment shows topo around 900.

Yes, i compared topo between free slip and pseudo-free surface for stokes problem. They were quite comparable. but did not try to benchmark Crameri paper. Will dig in the old ecperiments.

**Comment by tingyang2004** [comment]
The improvement is slight.
Note zoom in of Crameri figure shows maximum topo around 850 m, my 3 kyr experiment shows topp around 950, but my 2 kyr experiment shows topo around 900.

Yes, i compared topo between free slip and pseudo-free surface for a stokes problem. They were quite comparable. but did not try to benchmark Crameri paper. Will dig in the old ecperiments.

**Comment by tingyang2004** [comment]
The improvement is slight.
Note that zoom in of Crameri figure shows maximum topo around 840 m, my 3 kyr experiment shows topp around 920, but my 2 kyr experiment shows topo around 900.

Yes, i compared topo between free slip and pseudo-free surface for a stokes problem. They were quite comparable. but did not try to benchmark Crameri paper. Will dig in the old ecperiments.

**Comment by julesghub** [comment]
@tingyang2004 I'm happy to help you out with this. 
Also it would be nice to try a higher order swarm advection in the original model. I have some code for that somewhere. @rbeucher interested?

**Comment by tingyang2004** [comment]
What do you mean by higher order swarm advection? 4th order Runge-Kutta?
Not sure if this will help, but worth a try.

**Comment by julesghub** [comment]
No, not 4th order. It's a 2nd order method midpoint method in time.

**Comment by tingyang2004** [comment]
ok, so it is implicit now?

**Comment by tingyang2004** [comment]
ok, so it is implicit? 
How is the implicit method for temperature going now?

**Comment by lmoresi** [comment]
That’s what I would expect to be the low order method … surely we are not using 1st order by default.


Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 5 Apr 2019, 2:27 PM +1100, Julian Giordani <notifications@github.com>, wrote:

No, not 4th order. It's a 2nd order method midpoint method in time.

**Comment by julesghub** [comment]
@tingyang2004 

the previous idea I mentioned for higher order particle advection is this
1) Create a new field the represents a previous `velocityField` solution
```python
v_prev = velocityField.copy()
v_prev.data[:] = 0.
```
2) In the time loop use `v_prev` to modify the actual `velocityField`, i.e.
```python
theta = 0.5 # you can play with this factor
while time < end_time:
    # regular solve
    solver.solve(...)

    # time average with the previous time step
    velocityField.data[:] = theta*velocityField.data[:] + (1.-theta)*v_prev.data[:]
   
    # regular update routine
    updateParticle(...)

    # update v_prev
    v_prev.data[:] = velocityField.data[:]
```
Modifying `theta` value will effect the advection time discretisation. theta=1 Forward Euler, theta=0.5 mid point.
As yet I haven't tested this idea very much.

**Comment by tingyang2004** [comment]
That looks like some correction to the simple Euler forward stepping. May worth a try, but is there any support for this method?

**Comment by julesghub** [comment]
No support yet for the algorithm. You'll need to explicitly write it in your model.

**Comment by tingyang2004** [comment]
Sorry, I mean, is there any proof that this correction can increase the precision and is robust?

**Comment by julesghub** [comment]
No, i don't have any verification of it. When I find time I'll put something together.

**Comment by rbeucher** [comment]
I think this could be material for a blog post. I will have a closer look at the different options we have.
