### ISSUE TITLE
publications folder not found in docs

### ISSUE THREAD

**Issue by rcarluccio** [underworldcode/underworld2#366]
Hi everyone,

I've just heard someone looking for examples on how to project swarm variables on the mesh and plot them in paraview. I was looking for the publications folder but I couldn't find it. 

Meanwhile I referred them to https://underworld2.readthedocs.io/en/latest/user_guide/06_Utilities.html#writing-to-xdmf-files and https://buildmedia.readthedocs.org/media/pdf/underworld2/latest/underworld2.pdf notes.

Regards,
R.

**Comment by arijitlaik** [comment]
Hello,
I had to look up something a few days back and got stuff here: https://github.com/underworldcode/model_library

**Comment by jmansour** [comment]
Yep a lot of models have been moved out of the UW repository and into the model_library repo. We haven't publicised this yet as there is a little more work to do still.
