### ISSUE TITLE
[Error] Add more particles to the model

### ISSUE THREAD

**Issue by jerryjohn42** [underworldcode/underworld2#369]
Hi all,
I built a subduction model with temperature influence, it would work for a while about 200 steps and interrupted with an error which asked me to add more particles to my model. I want to figure out why it happened and how to solve it, not simply increase the particles number. The boundary condition is free slip boundary type, and original particles number in cell is 30.
Thanks for your help.
                                                                                                 Jerry
                                                                                               

RuntimeErrorTraceback (most recent call last)
<ipython-input-20-78f3d994dd51> in <module>()
      1 while time < timeEnd:
      2     # Get instantaneous Stokes solution
----> 3     solver.solve(nonLinearIterate=True)
      4     # Calculate the RMS velocity.
      5     vrms = math.sqrt( mesh.integrate(vdotv)[0] / mesh.integrate(1.)[0] )

/opt/underworld2/underworld/systems/_bsscr.pyc in solve(self, nonLinearIterate, nonLinearTolerance, nonLinearKillNonConvergent, nonLinearMinIterations, nonLinearMaxIterations, callback_post_solve, print_stats, reinitialise, fpwarning, petscwarning, **kwargs)
    406 
    407         if self._stokesSLE._swarm and reinitialise:
--> 408             self._stokesSLE._swarm._voronoi_swarm.repopulate()
    409 
    410         # set up objects on SLE

/opt/underworld2/underworld/swarm/_integration_swarm.pyc in repopulate(self, weights_calculator)
    140         # if weights calculator is PCDVC, then we need to always run as it potentially performs population control
    141         if (self._mappedToState != self._mappedSwarm().stateId) or isinstance(weights_calculator,uw.swarm._weights.PCDVC):
--> 142             libUnderworld.PICellerator.WeightsCalculator_CalculateAll( weights_calculator._cself, self._cself )
    143             libUnderworld.PICellerator.IntegrationPointsSwarm_ClearSwarmMaps( self._cself )
    144 

RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Error in _DVCWeights_Calculate2D: Problem has an under resolved cell (Cell Id = 1963), add more particles to your model

**Comment by arijitlaik** [comment]
Hi John,
It might be useful to repopulate your particles/swarm after certain timesteps by setting non-default values for the population control.
something on the lines of 

```python
swarm_popcontrol = uw.swarm.PopulationControl(
    swarm,
    deleteThreshold=0.002,
    splitThreshold=0.20,
    maxDeletions=0,
    maxSplits=80,
    aggressive=True,
    aggressiveThreshold=0.98,
    particlesPerCell=20,
)
def model_update():
    # do advection etc and then
    swarm_popcontrol.repopulate()
```
a detailed description of these parameters are given in [here](https://underworld2.readthedocs.io/en/latest/underworld.swarm.html#underworld.swarm.PopulationControl)
This works for me, with similar setup(s) and a bit of mesh refinements as well.

**Comment by julesghub** [comment]
Hi John,
Deforming models can lead to highly distorted particle distributions. This is bad for the FEM+PIC implementation which currently requires that an element has at least one local particle to perform the required integration. 
High deformation is often caused by stagnation points or inflow in the model. Watch the particles as the model evolves and you should be able to visualise the deformation and particle sparsity. 

The population control mechanism ensures particle numbers are populated and balanced (according to the user parameters) in each element. Run it every few timesteps and the problem should resolve.

**Comment by jerryjohn42** [comment]
Thanks all,
The Problem is solved.
: )
John
