### ISSUE TITLE
Temperature field error

### ISSUE THREAD

**Issue by jerryjohn42** [underworldcode/underworld2#370]
Hi all,
Last time I ran a subduction model with temperature influence. The results of mantle temperature field worked well at the begining, the range of temperature value is [261, 1756.5]. But suddenly that range turned to [-17064, 22901] and started to narrow to [192.4, 4785.3] after several steps. I guess it would finally narrow close to my initial temperature range set, but this temperature disturbance affect the convection mode and break the continuity. 
Anyone know why this happened and how to solve it?
![temperature0160](https://user-images.githubusercontent.com/49113183/56195298-4494a100-6067-11e9-892b-b4b1d6fbfa67.png)
![temperature0180](https://user-images.githubusercontent.com/49113183/56195304-49595500-6067-11e9-89b1-8405f78e6525.png)

John

**Comment by julesghub** [comment]
Hi John,
Are your temperature gradients high over a few elements initially? This can cause difficulties for the advection diffusion solver. 
Try to "diffusion" the temperature field out and then let the model evolve. You can do this by hand, setting the temperature field via the numpy array, or by running a `uw.systems.SteadyStateHeat()` initially. I recommend the `uw.systems.SteadyStateHeat()`. An example of running that is here.
https://nbviewer.jupyter.org/github/underworldcode/underworld2/blob/master/docs/examples/01_Steady_State_Heat.ipynb

**Comment by jerryjohn42** [comment]
> Hi John,
> Are your temperature gradients high over a few elements initially? This can cause difficulties for the advection diffusion solver.
> Try to "diffusion" the temperature field out and then let the model evolve. You can do this by hand, setting the temperature field via the numpy array, or by running a `uw.systems.SteadyStateHeat()` initially. I recommend the `uw.systems.SteadyStateHeat()`. An example of running that is here.
> https://nbviewer.jupyter.org/github/underworldcode/underworld2/blob/master/docs/examples/01_Steady_State_Heat.ipynb

Hi,
I have tried to set the initial temperature gradients with uw.systems.SteadyStateHeat(). The results are still similar with previous results with temperature error.
For this test model I set viscosity as 1 and density as 1. The top boundary temperature is 10 and bottom boundary temperature is 100. From step 0 to step 180 the results are normal. Since step 200 the value range of temperature start to increase, the max temperature increases to about 114, and mix temperature decreases to -3. It has beyond the max and min temperature I set for the models.  After step 300 the range of temperature value narrow back to [10,100]. 
Any conjecture why the temperature range beyong my initial set?
Best,
John
Step0
![temperature0000](https://user-images.githubusercontent.com/49113183/56489895-ea3b8a80-6515-11e9-8fef-f4f987e05aff.png)
Step280
![temperature0280](https://user-images.githubusercontent.com/49113183/56489931-04756880-6516-11e9-9ab6-b9aca22d34e9.png)
Step400
![temperature0400](https://user-images.githubusercontent.com/49113183/56489943-0f2ffd80-6516-11e9-8ccd-7af435d0ca8c.png)

**Comment by jerryjohn42** [comment]
![temperature0000](https://user-images.githubusercontent.com/49113183/56490729-c299f180-6518-11e9-92eb-682fcec7e7ba.png)
![temperature0280](https://user-images.githubusercontent.com/49113183/56490732-c3328800-6518-11e9-8c3d-0163e2343cdd.png)
![temperature0400](https://user-images.githubusercontent.com/49113183/56490733-c3328800-6518-11e9-9a84-79e634098feb.png)

**Comment by tingyang2004** [comment]
Increasing the resolution should help.

**Comment by jerryjohn42** [comment]
> Increasing the resolution should help.

The results still get temperature error. I test the model with and without slab, the former one gets temperature error, and the latter one does not. So I guess that is due to deformation of slab?

**Comment by jmansour** [comment]
@jerryjohn42, the forthcoming release will include a new advection-diffusion solver that you might like to try out.

**Comment by alexstruc** [comment]
Hi, jerry.
    Have you ever solved the issue? I also encountered the same error of temperature in my several models. I have no way to cope with it. If you successfully solved it, could you please share me your experience? Thanks a lot.
Alex.
