### ISSUE TITLE
Suggestions for help installing on cluster

### ISSUE THREAD

**Issue by lydiadicaprio** [underworldcode/underworld2#371]
Just a couple of comments and a request for documentation for help installing on cluster without dockers. 

Installing the pre requisites is black box. More information about which options underworld needs would be helpful. Specifically, 
1)  the PETSc installation has a large number of optional solvers.  Unless you are already an expert with Underworld2, it would not be at all obvious what PETSc installation options are "required" and which are truly optional.

2) Great if noted somewhere in the documentation that the HDF5 parallel version was necessary

3) Some general information clarifying the purpose of SWIG would help with installing it correctly (version and specific langage support option needed)

4)  Intel vs GNU compilers. Are there any recommendations or limitations?

Finally, it would be great to also include some sanctioned example scripts suitable for a non-graphical cluster environment. Copying and pasting from notebooks is not convenient. Need testable output (h5 files) not graphical output for cluster installs.

**Comment by jmansour** [comment]
Hi Lydia

Thanks for feedback and apologies if you've had difficulties. Unfortunately compilation on clusters is often quite challenging. You might also like to speak with the cluster admins as to whether they can install Singularity or Shifter for Docker amenability. 

A minimal set of compilation instructions is provided here:
https://github.com/underworldcode/underworld2/blob/master/COMPILE.md

We also provided compilation instructions for a limited number of platforms here:
https://github.com/underworldcode/underworld2/tree/master/docs/install_guides

Also, you might like to refer to our `Dockerfile` for compilation instructions which are somewhat generic:
https://github.com/underworldcode/underworld2/blob/master/docs/development/docker/base/Dockerfile
https://github.com/underworldcode/underworld2/blob/master/docs/development/docker/underworld2_untested/Dockerfile

In reference to your specific points:
1.  Only _vanilla_ PETSc is _required_. Ie, it is not necessary to specify any special compilation instructions. Of course, if you wish to use an additional PETSc packages (such as MUMPS), you will need to ensure your PETSc is compiled against them. Our standard Docker images include PETSC _with the lot_ to give maximum coverage. Refer to the base `Dockerfile` above for details. Note that we avoid providing _unnecessary_ instructions for third party requirements as they tend to go out of date very quickly.
2. For the most recent UW release, `HDF5` itself is not specifically a requirement. `H5py` however is, and it must be a parallel enabled version. This is mentioned in the `COMPILE.md` file listed above, and an older version of the same file specifies that parallel `HDF5` is required (as per the corresponding release). Note that UW will still try to build `H5py` if not locally available (and in this case `HDF5` must be available and parallel), however we now recommend that you build `H5py` independently. 
3. SWIG builds the Python/C bindings which allow us to execute C code from Python. Again, only the default configure/build options are required for SWIG, and almost any version will work. Are there any particular problems you are encountering here? 
4. We have successfully used both on various platforms, although we have more experience with GNU. Performance wise there shouldn't be a significant difference, so use which ever provides the path of least resistance. 
5. A pure Python example is probably not a bad idea. Note that we do have a few _test_ Python scripts here:
https://github.com/underworldcode/underworld2/tree/master/docs/test
Also, you can easily convert notebooks to pure Python either directly from the notebook interface (file->download as), or at the command line using `jupyter-nbconvert`:
```bash
jupyter-nbconvert --to python YourNotebook.ipynb
```
All our notebooks should run fine on a cluster (once converted to Python). Data saving operations (to h5) will be unchanged in either case, but perhaps if you can share the specifics of what you wish to test we can give you better direction.  Similarly, if you are having particular problems compiling on your cluster, feel free to post more details.

**Comment by jmansour** [comment]
I'll close this ticket, but please reopen if you would like further assistance with cluster installation.
