### ISSUE TITLE
Suggestion: pip installation of python3

### ISSUE THREAD

**Issue by El-minadero** [underworldcode/underworld2#373]
Quick suggestion: make underworld2 locally installable via pip for python 3. I know its possible using docker or more advanced installations on HPC clusters

**Comment by lmoresi** [comment]
We should check to see the status of pip petsc again - we would have to forego most of the fancy solver options but that was the main reason we gave up on pip previously.

That and the relocatability.

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 19 Apr 2019, 13:02 -0700, Kevin Mendoza <notifications@github.com>, wrote:

Quick suggestion: make underworld2 locally installable via pip for python 3. I know its possible using docker or more advanced installations on HPC clusters

**Comment by jmansour** [comment]
```bash
ubuntu@uw-compute:~$ pip3 install petsc
Collecting petsc
  Using cached https://files.pythonhosted.org/packages/31/0a/aecec2c090617258c813d369e631cb4882bb6844e3bbfed917cb3391035e/petsc-3.11.1.tar.gz
Building wheels for collected packages: petsc
  Running setup.py bdist_wheel for petsc ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-m7dkvfke/petsc/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpwmqe9oxnpip-wheel- --python-tag cp36:
  petsc: this package cannot be built as a wheel

  ----------------------------------------
  Failed building wheel for petsc
  Running setup.py clean for petsc
Failed to build petsc
Installing collected packages: petsc
  Running setup.py install for petsc ... done
Successfully installed petsc-3.11.1
```

**Comment by RebeccaFarrington** [comment]
Pip install Underworld is a go?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jmansour** [comment]
No, not yet.  I think `petsc` works now with Py3, but it still seems a bit flakey.  More testing required.

**Comment by jmansour** [comment]
pip install will be coming soon!
