### ISSUE TITLE
How to set slab density change with x coordinate?

### ISSUE THREAD

**Issue by jerryjohn42** [underworldcode/underworld2#376]
Hi all,

I build a slab subduction model like example 1_07 and try to set the slab density increases with x coordinate as a function in density map. But I cannot set proper function for that. 
Any suggestion how to achieve that?

Thanks,
Jerry

**Comment by jmansour** [comment]
There's a few way to do this, but it depends exactly what you're after.  Do you want your density to move with the slab, or to be fixed in space (but apply to only one material type).  If it's the former, you'll want to create a swarm variable which records the density values but advects with the slab.  If it's the latter, it'd be best to create it as a `Function` object.  

Let me know and I can give you further instructions.

**Comment by jerryjohn42** [comment]
> There's a few way to do this, but it depends exactly what you're after. Do you want your density to move with the slab, or to be fixed in space (but apply to only one material type)? If it's the former, you'll want to create a swarm variable which records the density values but advects with the slab. If it's the latter, it'd be best to create it as a `Function` object.
> 
> Let me know and I can give you further instructions.

I guess I want the latter one. The material of subduction slab is one type, the initial slab density distribution is set as x coordinate change. While the slab subducts (for example, to the nagetive x coordinate), the slab density should varied with coordinate change.

**Comment by jmansour** [comment]
Check the branching function examples in the `Functions` section of the user guide:

https://underworld2.readthedocs.io/en/latest/user_guide/04_Functions.html#branching-functions

Here we construct a `fn.branching.map` function that returns a linear function (in z) for the `outside_circle` material type, and a trigonometric function (in x) for the `inside_circle` material type.  I believe that's similar to what you're after, but have a look and let us know how you go.

**Comment by jerryjohn42** [comment]
> Check the branching function examples in the `Functions` section of the user guide:
> 
> https://underworld2.readthedocs.io/en/latest/user_guide/04_Functions.html#branching-functions
> 
> Here we construct a `fn.branching.map` function that returns a linear function (in z) for the `outside_circle` material type, and a trigonometric function (in x) for the `inside_circle` material type. I believe that's similar to what you're after, but have a look and let us know how you go.

Thanks for your reply. I guess the example you gave set two material types and different density for each type. 
Here I have set slab and mantle as two different materials. Now I want to give slab material type a variable density distribution.

**Comment by jerryjohn42** [comment]
I have figure it out how to set it. Thanks for your help. @jmansour
