### ISSUE TITLE
Mesh locking?

### ISSUE THREAD

**Issue by cgoise** [underworldcode/underworld2#377]
Hi!

I'm trying to use underworld2 in order to model shear folds in an orthotropic material (ice), which can be done with the 'director' parameter in 'systems.Stokes' (see code block). Apparently some kind of mesh locking(?) occurs, which falsifies the output completely. 

Do you have an solution for cases like this implemented - or a suggestion?

To illustrate I attached screenshots of the experiment setup and the outcome. 

The material is orthotropic, with a vertical 'director' everywhere. I'm using here fixed boundaries in Z, free slip at the top, no-slip at the bottom. In X the system is periodic. Power law viscosity, which results in a low viscosity close to the bottom and large viscosity at the top.

I assume that this problem is somehow related to FE models trying to model thinplate shearing.

```python
stokes = uw.systems.Stokes(  
	velocityField  = velocityField, 
	pressureField  = pressureField,
	voronoi_swarm  = swarm,
	conditions     = velocityBCs,
	fn_viscosity   = firstViscosityFn,
	fn_viscosity2 = secondViscosityFn,
	fn_director   = c_axis_orientation,
	fn_bodyforce   = buoyancyFn 
	)
```

Setup: shear by moving front boundary (black arrows)
![](https://user-images.githubusercontent.com/15956510/57460188-f2652b00-7274-11e9-9320-838ebdf4a329.png)

Result: one 'fold' per element in a horizontal section close to the model bottom 
![](https://user-images.githubusercontent.com/15956510/57460255-0b6ddc00-7275-11e9-844a-1122e6a86292.png)

**Comment by jmansour** [comment]
Can you explain further what your result viz is showing?

**Comment by cgoise** [comment]
Actually this hasn't been the best image to illustrate my problem. I hope the following image makes it a little clearer. Shown is an initially horizontal plane - represented by a tracer swarm - which has the job to visualize the folding process. In the image below I show timestep 0 and timestep 15. Setup basically as above, but the phenomenon is even more obvious in this simulation (I _think_ I put a certain gaussian noise on the swarm particles in the simulation shown in the previous post, which masked the effect a bit).

The number of folds is 20 (10) in the Z (X) direction, which is just the mesh resolution. What would be expected are buckle folds with long hinges, oriented obliquely to the shear direction (a bit like folds in a wrinked tablecloth - sorry, I cannot find a decent image to post). 

![Simulatonn at timestep 0 / timestep 15](https://user-images.githubusercontent.com/15956510/57488072-535f2400-72b2-11e9-9e83-72e5cf095dda.png)

I hope this explains the situation a bit better.

**Comment by julesghub** [comment]
From a debugging point of view - does firstViscosityFn generate reasonable results? If so, you could gradually increase the orthotropic effects to help identify when the "locking" occurs.

**Comment by lmoresi** [comment]
Also check the definition of the 2nd viscosity. A value of zero means “no effect”.

I haven’t really seen mesh locking resulting from this rheology even when the 2nd viscosity leads to a very weak material. That’s actually why we like using this for plasticity as it has much better convergence properties.

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 10 May 2019, 9:24 AM +1000, Julian Giordani <notifications@github.com>, wrote:

From a debugging point of view - does firstViscosityFn generate reasonable results? If so, you could gradually increase the orthotropic effects to help identify when the "locking" occurs.

**Comment by cgoise** [comment]
Hm, the anisotropy is indeed quite large. viscosityIce2  = 0.99 * viscosityIce (ice is very anisotropic). Plus, there is a forced 'quasi'-anisotropy by the power-law viscosity, which generates a far smaller viscosity at the bottom compared to the top (up to 3 orders of magnitude). 

In a few new simulations I reduced the amount of anisotropy to 50%. Resulting folds are much smaller now, but the mesh dependence is still large, although somewhat smaller (colours indicate relative elevation, otherwise settings as before):

![Screenshot_20190510_113423](https://user-images.githubusercontent.com/15956510/57517657-9ef7e900-7317-11e9-98a4-a11d8dc657af.png)

**Comment by jmansour** [comment]
Which elements are you using?  If you haven't already, perhaps try the "q2/dq1" elements and see if it helps the situation.

**Comment by cgoise** [comment]
Thank you for your response. I tested this with all possible element types that underworld permits.It's getting worse with higher order elements.. which, from my understanding (might be wrong), means that it is not mesh locking which causes this.

**Comment by jmansour** [comment]
Did you make any progress here @cgoise ?

**Comment by cgoise** [comment]
Hi and sorry for the late answer! 

I played with the different element types and also with gaussian noise. But to no avail - the problem persists. 

From what I read about shear locking it seems to be important to use at least quadratic pressure elements to get rid of the problem. 

For the moment I'm busy doing 2D simulations on other problems, but on the long run it would be great to have this type of element in underworld2. 

Is there any chance this will be implemented in the future?
