### ISSUE TITLE
Stokes solver Convergence issue with prescribed velocity BCs

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#378]
Hi all,

I am having a stokes solver convergence issue when trying to investigate the influence of the prescribed upwelling and downwellings on mantle convection. Periodic BC are used for side boundaries. The horizontal velocity of the bottom boundary is fixed to zero while the vertical velocity is as below:
![image](https://user-images.githubusercontent.com/26615840/57500270-6f47e180-7315-11e9-8d74-a7db3e430f75.png)
The stokes solver does not converge after the maximum pressure iteration of 10000:
![image](https://user-images.githubusercontent.com/26615840/57500457-12006000-7316-11e9-9647-89bdb408ab93.png)

But it converges very fast when the bottom vertical velocity is set as zero:
![image](https://user-images.githubusercontent.com/26615840/57500479-26dcf380-7316-11e9-9bc3-16d8586be481.png)

Any suggestions?
The input parameter and log files are attached below.

Best regards,
Ting

[input5A.log](https://github.com/underworldcode/underworld2/files/3164780/input5A.log)
[input5A.py.txt](https://github.com/underworldcode/underworld2/files/3164781/input5A.py.txt)

**Comment by jmansour** [comment]
My guess is you are violating volume conservation.  What is your top BC?  From your graph, it looks like are trying to have equal volume in and out, which is good, except that this BC will only be represented approximately so it probably won't work this way. 

You have a few options:
1.  Add a compressible layer somewhere to take up the slack. 
2.  Use an identical BC at the top.
3.  Be very careful to ensure flux in = flux out at the bottom.  
4.  Set an _open_ BC at the top which will allow outflow as necessary. 

You can create a surface integral across the bottom to calculate your total flux through the boundary.

**Comment by tingyang2004** [comment]
Thanks, John.
Top BC is free slip.
You mean approximation due to mesh discretization? Do you have any suggestions on how to make in- and out- flows equal to each other exactly.
Right now, the relative error of the bottom velocity BC is:
int(x,vz)/int(x,abs(vz))=-0.00475
where int(x,vz) is the integration of vertical velocity along the bottom boundary.

**Comment by jmansour** [comment]
Yep approximate due to discretisation. To ensure an exact in/out flow, you could create a symmetric BC along the bottom so any discretisation errors are reflected exactly in the opposite sense.  I guess it depends on how critical the form of your inflow/outflow are to your modelling. There are other things you could try to _tune_ the condition, but don't really feel it's the way forward as they probably will not prove sufficiently robust.  Perhaps you could even have part of your lower BC fixed and another part _open_.  Say, Dirichlet for the inflow, and then for a subsection Neumann to allow it to automatically find the required outflow. 

I'd suggest the first thing to try is to add the compressible layer to see if this immediately remedies your solve issues.

**Comment by tingyang2004** [comment]
That's true. I have just tested a model with cosine bottom boundary vertical velocity values and the stokes solver converged rapidly. So the discretization error was the key. I guess the Neumann boundary condition may also cause problems? since the exact vertical integration of the density also have numerical errors?

**Comment by jmansour** [comment]
They Neumann condition shouldn't cause issues on account of volume conservation, but it may create other difficulties (if you have gravity, you'll need to set it to provide the required support). Perhaps you could even set a single node to Neumann to provide some _breathing room_, and constrain the rest.

**Comment by tingyang2004** [comment]
I am still using the Direchlet BC but have removed the average of the velocity field, the stokes solver now converges. As you can see, the original vertical velocity and the corrected velocity at the bottom boundary are quite close, but this difference has made the convergence issue.
![image](https://user-images.githubusercontent.com/26615840/57508238-8f869900-7333-11e9-995e-c7aeab5bda69.png)

**Comment by jmansour** [comment]
Actually that's a great idea Ting. I didn't think of that. You could easily
automate this too. After you set your initial velocity, do the surface
integral, then add correction.

**Comment by tingyang2004** [comment]
OK, I will close this ticket since John has kindly helped me solved it out.
