### ISSUE TITLE
Restart a simulation

### ISSUE THREAD

**Issue by huilin0302** [underworldcode/underworld2#38]
To restart a simulation, does Swarm file need to be saved and loaded (like the other checkpotinted fields: temperature, velocity, pressure)? And how to do that?

**Comment by jmansour** [comment]
Generally, yes.  However the functionality to save the swarm is not currently available, but will be coming very soon (within the next week or so). 

If you are not working in parallel, a possible work around is to use numpy.save to save the critical data (particle positions, swarm variables).  You can then re-create the particles using the 'add_particles_with_coordinates' method (after you have reloaded the particle positions into a new numpy array).  Then after you have re-created any swarmvariables, you can reloading them using numpy.load.

**Comment by huilin0302** [comment]
Thanks! Looking forward to the new swarm function.

**Comment by huilin0302** [comment]
I'm wondering whether the save and load swarm function is available in UW2 now ?!

**Comment by julesghub** [comment]
No it is not. We have plans to release it by next week. Stay tuned!

(If you're keen to test the prototype code, it exists on the branch
'newLogging' in our git repo. We are merging it into the main code this
week.)

**Comment by julesghub** [comment]
@huilin0302 - this swarm functionality has been added. (Sorry I forgot to tell you directly)
see the file https://github.com/underworldcode/underworld2/blob/development/docs/user_guide/07_Utilities.ipynb for an example of saving and reloading the swarm & swarm variables.
I'll close the ticket for now, feel free to reopen if you experience difficulties with the swarm save/load.
