### ISSUE TITLE
how to set constant velocity for swarm

### ISSUE THREAD

**Issue by jerryjohn42** [underworldcode/underworld2#381]
Hi all, 
I built a simple slab subduction model and have set the initial velocity for slab and mantle. The velocity of slab would change during loops while I want to keep that velocity constant for several steps, then change the velocity value to another constant number. Any step I should follow to achieve these two functions?

**Comment by lmoresi** [comment]
I think you need to describe the science case a bit better here. The mantle and slab velocity are outputs of the model in general except where they are prescribed as boundary conditions. What are you trying to constrain and how ?

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 15 May 2019, 7:28 PM +1000, jerryjohn42 <notifications@github.com>, wrote:

Hi all,
I built a simple slab subduction model and have set the initial velocity for slab and mantle. The velocity of slab would change during loops while I want to keep that velocity constant for several steps, then change the velocity value to another constant number. Any step I should follow to achieve these two functions?

**Comment by jerryjohn42** [comment]
Hi Louis. Thanks for reply. This simple subduction model I built is meant to restrict slab velocity for another more complex subduction model.

Here I want to simulate the process that the ocean plate subduct beneath the continent plate with a constant speed. The model is composed with three main material: ocean plate, continent plate and mantle. The control systems in underworld2 are SwarmAdvector, Stokes and AdvectionDiffusion. 
Compared with history plate move situation, I want to use historical plate velocity to restrict the ocean plate velocity in the model. The histroical plate velocity value is 10cm/year during 190Ma to 150Ma and decrease to 5cm/year during 150Ma to 120Ma. With conversion equation I am able to calculate the ocean plate velocity in simple model and time for velocity change. During the simulate subduction process, the subducting speed should be constrained by historical plate speed, which is constant for a period and change to the other constant speed value for next period. These are what I plan to do.
 
Here I only know how to set initial different velocity field for ocean plate and mantle. But ocean plate velocity will change due to control equations. According to your reply should I set the slab speed as a boundary condition? At speed change time point, I can save the other simulation results, decrease the slab speed and continue simulation. It's a stupied way but may be useful.
If there is any suggestion please connect with me.

Jerry

**Comment by jmansour** [comment]
The difficulty here is that your boundary conditions will be set on the mesh, not the swarm.  And while you can set internal boundary conditions, you will be limited in the geometry you can apply. 

Another option is to create a special force which acts on the slab alone, but you'd need to iterate to get the velocity you want.   

Neither option is particularly great.

**Comment by julesghub** [comment]
@jerryjohn42 I'm closing the ticket due to inaction. Feel free to reopen the discussion if you like.
