### ISSUE TITLE
Image inserted in markdown cells are not rendered by Jupyter

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#388]
I noticed that the images we have in the markdown cells are not rendered by jupyter...

**Comment by rbeucher** [comment]
It only affects dev

**Comment by jmansour** [comment]
I can't reproduce this @rbeucher.  I've fired up a new dev image, and the images are displayed fine.  @julesghub ?

Perhaps you need to recompile your Arch Linux kernel? 😆
