### ISSUE TITLE
swig 1.3.40 produces broken bindings

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#39]
For some reason this version (and probably others) has issues producing bindings (for SwarmViewer.h).  It doesn't seem to understand our function pointers in this instance, but elsewhere has no issue.  

The best solution is to use a more modern version of swig.  1.3.4 is quiet old in any case.

**Comment by jmansour** [comment]
Note that this issue was encountered on raijin.

**Comment by linkpond** [comment]
hello ~

../build/include/Underworld/Function/FunctionIO.hpp:46: Warning 512: Overloaded method FunctionIO::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:45: Warning 512: using non-const method FunctionIO::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< bool,char >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< bool,char >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< bool,char >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< bool,char >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< bool,char >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< bool,char >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< bool,char >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< bool,char >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< char,char >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< char,char >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< char,char >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< char,char >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< char,char >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< char,char >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< char,char >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< char,char >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< short,short >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< short,short >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< short,short >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< short,short >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< short,short >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< short,short >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< short,short >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< short,short >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< unsigned int,unsigned int >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< unsigned int,unsigned int >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< unsigned int,unsigned int >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< unsigned int,unsigned int >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< unsigned int,unsigned int >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< int,int >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< int,int >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< int,int >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< int,int >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< int,int >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< int,int >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< int,int >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< int,int >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< float,float >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< float,float >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< float,float >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< float,float >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< float,float >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< float,float >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< float,float >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< float,float >::dataRaw() instead.
../build/include/Underworld/Function/FunctionIO.hpp:91: Warning 512: Overloaded method FunctionIOTyped< double,double >::data() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:90: Warning 512: using non-const method FunctionIOTyped< double,double >::data() instead.
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: Overloaded method FunctionIOTyped< double,double >::at() const effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: as it is shadowed by FunctionIOTyped< double,double >::at().
../build/include/Underworld/Function/FunctionIO.hpp:99: Warning 509: Overloaded method FunctionIOTyped< double,double >::at(std::size_t) effectively ignored,
../build/include/Underworld/Function/FunctionIO.hpp:107: Warning 509: as it is shadowed by FunctionIOTyped< double,double >::at(std::size_t) const.
../build/include/Underworld/Function/FunctionIO.hpp:112: Warning 512: Overloaded method FunctionIOTyped< double,double >::dataRaw() const ignored,
../build/include/Underworld/Function/FunctionIO.hpp:111: Warning 512: using non-const method FunctionIOTyped< double,double >::dataRaw() instead.

Traceback (most recent call last):
File "./swigall.py", line 40, in 
raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.

I use swig-3.0.10 but i got this error help me please~
(I use python-2.7.11 and icc (ICC) 15.0.3 20150407 and RHEL 6.5)
