### ISSUE TITLE
Cannot compile getting no PETsc  error

### ISSUE THREAD

**Issue by whositwhatnow** [underworldcode/underworld2#390]
Trying to compile the app and i do have PETsc installed versions 3.9.2.  

When i try to compile i get 

./configure.py --prefix=/cm/shared/apps/underworld2/2.7.1
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... no
Checking for package Python... yes
Checking for package PETSc... no

****  ERROR ****
Failed to locate required package PETSc.
Details in 'config.log'

***************************************
If you require help, send the files:
	config.log
	config.cfg (if it exists)
to: development@underworldproject.org
************************************
in the config.log it says it cannot find petsc.h.  I've tried the --petsc-dir option and it still fails...

**Comment by jmansour** [comment]
Can you post your `config.log` file?  Note also that the `--prefix` option does not work for the current stable release, but is fix in the forthcoming release.  You will need to build in place instead.

**Comment by whositwhatnow** [comment]
here is the last part that errors out

mpicc -o .sconf_temp/conftest_99.o -c -Wall -DHAVE_LIBM -DHAVE_LIBXML2 -DHAVE_MPI -DHAVE_PYTHON -I/usr/include/libxml2 -I/usr/include/python2.7 .sconf_temp/conftest_99.c
cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
        -H|--help               this usage info
        -V|--version            modules version & configuration options
        -f|--force              force active dependency resolution
        -t|--terse              terse    format avail and list format
        -l|--long               long     format avail and list format
        -h|--human              readable format avail and list format
        -v|--verbose            enable  verbose messages
        -s|--silent             disable verbose messages
        -c|--create             create caches for avail and apropos
        -i|--icase              case insensitive
        -u|--userlvl <lvl>      set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
        + add|load              modulefile [modulefile ...]
        + rm|unload             modulefile [modulefile ...]
        + switch|swap           [modulefile1] modulefile2
        + display|show          modulefile [modulefile ...]
        + avail                 [modulefile [modulefile ...]]
        + use [-a|--append]     dir [dir ...]
        + unuse                 dir [dir ...]
        + update
        + refresh
        + purge
        + list
        + clear
        + help                  [modulefile [modulefile ...]]
        + whatis                [modulefile [modulefile ...]]
        + apropos|keyword       string
        + initadd               modulefile [modulefile ...]
        + initprepend           modulefile [modulefile ...]
        + initrm                modulefile [modulefile ...]
        + initswitch            modulefile1 modulefile2
        + initlist
        + initclear

.sconf_temp/conftest_99.c:4:10: fatal error: petsc.h: No such file or directory
 #include "petsc.h"
          ^~~~~~~~~
compilation terminated.
scons: Configure: no

**Comment by jmansour** [comment]
Is it the same error when you specify `--petsc-dir`?  Also, you might like to try pointing directly to the library and headers using `--petsc-lib-dir` and `--petsc-inc-dir` respectively.

**Comment by whositwhatnow** [comment]
same error:

[root@calculon libUnderworld]# python2.7 ./configure.py --prefix=/cm/shared/apps/underworld2/2.7.1 --petsc-dir=/cm/shared/apps/petsc/3.11.2 --petsc-lib-dir=/cm/shared/apps/petsc/3.11.2/lib --petsc-inc-dir=/cm/shared/apps/petsc/3.11.2/include --with-debugging=0
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... no
Checking for package Python... yes
Checking for package PETSc... no

****  ERROR ****
Failed to locate required package PETSc.
Details in 'config.log'


***************************************
If you require help, send the files:
	config.log
	config.cfg (if it exists)
to: development@underworldproject.org
************************************
mpicc -o .sconf_temp/conftest_36.o -c -Wall -DHAVE_LIBM -DHAVE_LIBXML2 -DHAVE_MPI -DHAVE_PYTHON -I/usr/include/libxml2 -I/usr/include/python2.7 .sconf_temp/conftest_36.c
cmdModule.c(166):ERROR:11: Usage is 'module command  [arguments ...] '

  Modules Release 3.2.10 2012-12-21 (Copyright GNU GPL v2 1991):

  Usage: module [ switches ] [ subcommand ] [subcommand-args ]

Switches:
        -H|--help               this usage info
        -V|--version            modules version & configuration options
        -f|--force              force active dependency resolution
        -t|--terse              terse    format avail and list format
        -l|--long               long     format avail and list format
        -h|--human              readable format avail and list format
        -v|--verbose            enable  verbose messages
        -s|--silent             disable verbose messages
        -c|--create             create caches for avail and apropos
        -i|--icase              case insensitive
        -u|--userlvl <lvl>      set user level to (nov[ice],exp[ert],adv[anced])
  Available SubCommands and Args:
        + add|load              modulefile [modulefile ...]
        + rm|unload             modulefile [modulefile ...]
        + switch|swap           [modulefile1] modulefile2
        + display|show          modulefile [modulefile ...]
        + avail                 [modulefile [modulefile ...]]
        + use [-a|--append]     dir [dir ...]
        + unuse                 dir [dir ...]
        + update
        + refresh
        + purge
        + list
        + clear
        + help                  [modulefile [modulefile ...]]
        + whatis                [modulefile [modulefile ...]]
        + apropos|keyword       string
        + initadd               modulefile [modulefile ...]
        + initprepend           modulefile [modulefile ...]
        + initrm                modulefile [modulefile ...]
        + initswitch            modulefile1 modulefile2
        + initlist
        + initclear

.sconf_temp/conftest_36.c:4:10: fatal error: petsc.h: No such file or directory
 #include "petsc.h"
          ^~~~~~~~~
compilation terminated.
scons: Configure: no

**Comment by jmansour** [comment]
Perhaps try this:

```bash
/configure.py --petsc-lib-dir=/cm/shared/apps/petsc/3.11.2/lib --petsc-inc-dir=/cm/shared/apps/petsc/3.11.2/include --with-debugging=0
```
Also, it'd be best if you can attach or email me the entire `config.log`.

**Comment by whositwhatnow** [comment]
sending entire log shortly

**Comment by whositwhatnow** [comment]
just tried above command as well got new error:

.sconf_temp/conftest_9.c:9:10: fatal error: private/kspimpl.h: No such file or directory
 #include "private/kspimpl.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: Configure: no

**Comment by jmansour** [comment]
Thanks @whositwhatnow, received. 

@julesghub, is the stable branch `petsc-3.11.2` compatible?

**Comment by jmansour** [comment]
Did you get further with this @whositwhatnow ?

**Comment by whositwhatnow** [comment]
@jmansour unfortunately I did not I tried multiple recent versions of petsc with no success.

**Comment by jmansour** [comment]
Did you by chance try pointing to these earlier versions using `--petsc-dir` instead of `--petsc-inc-dir`/`--petsc-lib-dir`?  If not, can you give that a shot?   So something like this
```bash
./configure.py --petsc-dir=/cm/shared/apps/petsc/3.11.1
```

**Comment by jmansour** [comment]
Actually, I don't think that will make a difference.  The issue appears to be here:

```bash
/bin/ld: /cm/shared/apps/petsc/3.11.2/lib/libpetsc.a(dlimpl.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/lib64/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
scons: Configure: no
```

Have shared petsc libraries also been created?  

If you're able to organise a temporary account on the machine, I'm happy to login and have a closer look.

**Comment by whositwhatnow** [comment]
finally got it to work and compiled.

**Comment by jmansour** [comment]
Excellent! What was the issue in the end?

**Comment by whositwhatnow** [comment]
For some reason the petsc libraries weren't installing the shared libraries correctly.  I am installing this on a cluster using slurm scheduler.
Now the fun part trying to get underworld imported into python.  That is another issue....

**Comment by jmansour** [comment]
What is the error you are encountering?  Have the bindings been built?  You will need to have swig installed to generate the bindings.

**Comment by whositwhatnow** [comment]
here is the config.log

[config.log](https://github.com/underworldcode/underworld2/files/3461949/config.log)

**Comment by whositwhatnow** [comment]
still having an issue with this unfortunately.. :(

**Comment by jmansour** [comment]
Did you resolve this?
