### ISSUE TITLE
Fatal X server error with gLucifer

### ISSUE THREAD

**Issue by rsbyrne** [underworldcode/underworld2#395]
Hullo,

I'm encountering an occasional gLucifer error which seems to crop up randomly during very long runtimes of very large series of Underworld models when they are being run simultaneously:

```
XIO:  fatal IO error 2 (No such file or directory) on X server ":1013"
      after 467 requests (28 known processed) with 0 events remaining.
```

I've been working around it by just not saving figures from my models, which means I have to generate them in post - very annoying.

Because it appears seemingly randomly, I've had a hard time getting a good diagnostic of it. I will continue to sniff around, but in case this error message means something to someone, I thought I'd put it up and potentially save some time!

Cheers,
Rohan

**Comment by jmansour** [comment]
No, can't really think of any obvious causes. So you're running a number of jobs on the same machine simultaneously. @OKaluza, and thoughts?  

We'll really need an example to reproduce if possible.

**Comment by OKaluza** [comment]
:1013 is a very high X11 display number, is this using Xvfb? Are old Xvfb processes being killed? You're probably running into the limit on open file descriptors (1024) if there are really over 1000 running. You only  actually need one as it can be shared.

**Comment by rsbyrne** [comment]
Yep, there should be one file descriptor per job, and not more than three
hundred jobs in total, so unless each proc is getting its own file
descriptor, I should be under, right?

I may have some garbage collection problems due to the (now rather complex)
object-oriented approach I've taken to these models. But I don't see how
the file descriptors for the X server could be proliferating. All I'm doing
is making one glucifer figure per model at initialisation, then saving it
once for each checkpoint file.

**Comment by OKaluza** [comment]
The display number :1013 indicates to me you are using Xvfb, but starting a new display on each run and they are never killed, each X display needs a file descriptor. Perhaps Underworld is automatically launching it. @jmansour how does underworld manage Xvfb processes?
If it can be disabled I suggest doing so and running Xvfb yourself once to create a single display for all jobs.

**Comment by jmansour** [comment]
Well, ideally it creates one at the start of a job, and tears it down at the end.  In practice, there's issues with the teardown, so I'm pretty sure you're correct and there's probably 1024 `xvfb` processes hanging about.  

@rsbyrne, can you run `ps -e` on the machine and see if there's stray `xvfb` processes?

**Comment by jmansour** [comment]
@OKaluza, this has always been problematic.  Is it difficult to have UW check if there's an `xvfb` in existence?

**Comment by OKaluza** [comment]
Looking at `glucifer/__init__.py` it has to be enabled by setting `GLUCIFER_USE_XVFB` anyway so you must have it switched on. 
Poking around, it seems this is done in the Dockerfile, but in docker it makes much more sense to run Xvfb in the entrypoint, see https://github.com/OKaluza/LavaVu/blob/master/Dockerfile

I never thought it was our business to launch Xvfb within UW as it's super simple to start if you need it but causes problems like this if we try to manage it... I understand having the feature for the sake of making things easier though.

On a personal machine (or a docker image), using a single fixed display number when running Xvfb works (eg: `Xvfb :99`), as if it is launched subsequent times it just fails as the display is already running and continues merrily.
But, on a shared multi-user system, anyone using Underworld will get locked out of display :99 by the first user who opens it. In this case though, it's probably more acceptable to require users to start their own Xvfb and set their $DISPLAY.

Alternatively we could manage it further by creating a display for every LavaVu call and then killing it in a context manager... it's inefficient, but it would work. Would be OK I guess if only enabled with `GLUCIFER_USE_XVFB`

**Comment by jmansour** [comment]
We originally fired up xvfb from an `ENTRYPOINT`:

https://github.com/underworldcode/underworld2/blob/v2.4.0b/docs/development/docker/base/Dockerfile

In honesty I can't remember why we switched out for the current method. Perhaps we should switch back? I am also wondering if there are concerns for containerised HPC jobs (singularity/shifter), as we might end up with many instances of xvfb on each node, but I'm really not 100% sure how entrypoints are handled for these use cases. 

@julesghub thoughts? Should be try and sort this for the release?

**Comment by OKaluza** [comment]
bc273e69e4e614568f5522fe8b5d00b42f4a11ca
hmm there must have been a reason? Don't want to cause a regression.
Multiple Xvfb instances on a node shouldn't be an issue as long as they use different display numbers.
Maybe the context manager path is the way to go for underworld.

I'm still struggling to understand how so many instances of Xvfb have started in a docker container though @rsbyrne I'm assuming you're running in docker, how many underworld processes are you running during one of these jobs for a single container instance? (sequentially and in parallel)

**Comment by julesghub** [comment]
Getting this sorted for the release sounds good. I recall we have seen rogue xvfb procs in containers and this is likely why. Cleaning this would be great!

I'm happy if we switch it back. I recall @jmansour and I chatted about it and thought it was an equivalent with `GLUCIFER_USE_XVFB` - apparently that's NOT the case.

**Comment by rsbyrne** [comment]
Hi all,

Looks like I accidentally started something here! Sorry for potentially
derailing everyone's day.

I'm not at uni right now so I can't speak to some of these points. As I've
said, reproducing the situation is tricky because it occurs after a good
day or so of running and I need those cycles right now for science reasons.

But in general, the situation is:
- 1 docker container (using the standard underworld cylindrical image)
- 16 jobs running simultaneously in the container (i.e. completely
independent jobs, not mpi jobs)
- Each job consists of seven or eight models run one after another
- Each model going through a dozen or so checkpoints, some more, some fewer.
- Each model has one glucifer figure, which gets created at initialisation
- Each figure is told to fig.save() once for each checkpoint

All up, it's only 160ish figures, not the 1000+ numbers we're tossing
around. Perhaps that suggests something is wrong with the fig.save()
method. This would explain why the error crops up about 3/4 of the way
through the job and not earlier. The back of my envelope says ~10 jobs *
~10 models * ~10 checkpoints gets us in the right ballpark for the 1024 x
display limit.

Seems like this should be pretty easy to build a test case for. Can't do it
myself today though I'm afraid.

Thanks for all the attention to my (admittedly *very* niche) issue. The
all-star team is on the case!

Cheers,
Rohan

**Comment by OKaluza** [comment]
I didn't implement the GLUCIFER_USE_XVFB feature and only just looked at the pyvirtualdisplay code that runs the Xvfb instance so I don't know how/if it cleans up, it seems to require you to call .stop(), it looks like it would run xvfb every time glucifer is imported in a new python interpreter instance.

This would be no problem in the usual case of the container only running one job, but for multiple jobs in multiple processes it's obviously causing issues.

I think going back to the entrypoint method is the way to go for docker as it ensures Xvfb is only run once. If we really need to control launching xvfb ourselves, I can set it up to run it in a context manager in the _glucifer.py code for each render produced.

For the future, I've started work on getting things rendering with EGL which can be used without an X server.

**Comment by jmansour** [comment]
It should call `stop()` at teardown (either via `atexit` as in master, and `__del__` as in development), but it often doesn't, or fails trying. 

I'll look at putting it back in the entrypoint.

**Comment by jmansour** [comment]
Ok, i've pushed up the changes:
2659d7d8c1f77b9ec019c2b55e6bedff9ce44c88

Will test once image (v2.8_release) is created.

**Comment by OKaluza** [comment]
Cool. I've had big problems getting things to shut down reliably in python, __del__ doesn't get called in many situations, primarily if there are any circular references. For the render and server threads in lavavu I use __del__ and atexit, and I think I got it to work finally by cleaning up some necessarily evil circular references to use weakref, but worst case scenario it's a thread so it still dies, just not cleanly.

**Comment by jmansour** [comment]
Yep, I know! It's really a pain to get a clean shutdown. Must say, I really don't understand it.  For instance, with xvfb, it fails because when we call `stop()` from `__del__()`, the `logging` module used by `stop()` has already been destroyed. If we keep a reference to an object, shouldn't everything needed to use that object remain active until the object itself is destroyed? Perhaps it's also a circular reference issue.

**Comment by julesghub** [comment]
circular reference checker: https://github.com/bndr/pycycle maybe worth a try. I have no experience with it, just googled it a while back.

**Comment by rsbyrne** [comment]
Hi all,

Did a solution to this go through and has it been tested? I still seem to
be running into the bug.

Rohan.

**Comment by julesghub** [comment]
The change got made to the v2.8_release branch. Only if you're running from that docker image will you notice a difference.

**Comment by rsbyrne** [comment]
So it wouldn't be reflected on the uw2cylindrical:cylindrical branch?

**Comment by julesghub** [comment]
nope not yet. If you want I can move it over this arvo. 
We are still testing the release on the clusters and I can't give a solid date when the release should be ready.

**Comment by rsbyrne** [comment]
If it's not too much trouble, that would be super useful for me! After all,
I'm the only one having this problem, and I only use the cylindrical branch
(because I need the annulus).

I don't rely on clusters - I have a bunch of Nectar VMs I use now - so the
fact it's not tested yet doesn't worry me.

**Comment by julesghub** [comment]
rebuilding now - I'll let you know when it's ready

**Comment by julesghub** [comment]
@rsbyrne it's ready. Try it and report back please.

**Comment by julesghub** [comment]
Closing for now due to inactivity. @rsbyrne feel free to reopen if it's still an issue.
