### ISSUE TITLE
glucifer on raijin

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#396]
@OKaluza 
i'm doing some testing on raijin. I found some glucifer/lavavu errors cropping.
Whenever `show()` is called something like this appears:
```
X11 Error: 179 -> GLXBadFBConfig
In func createWindow: Could not create GLX rendering context.
No context!

LavaVu Run error: No context!
```

and at the end of execution something like this appears:
```
X11 Error: 8 -> BadMatch (invalid parameter attributes)
X11 Error: 8 -> BadMatch (invalid parameter attributes)
X11 Error: 179 -> GLXBadFBConfig
In func createWindow: Could not create GLX rendering context.
No context!

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/python3/3.6.7/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/python3/3.6.7/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/565/jug565/.local/lib/python3.6/site-packages/lavavu/lavavu.py", line 2174, in _thread_run
    viewer.app._thread_run()
  File "/home/565/jug565/.local/lib/python3.6/site-packages/lavavu/lavavu.py", line 2016, in _thread_run
    self._returned = method(*args, **kwargs)
RuntimeError: No context!
```

I have tried with and without `GLUCIFER_USE_XFVB=1`

any suggestions on this?

**Comment by OKaluza** [comment]
Is LavaVu linked with a working Mesa llvmpipe libGL.so? You can't just use the system libGL on raijin, it's ancient.
eg, for my mesa build: 
```
export OPENGL_LIB=/home/565/olk565/mesa-17.1.5/build/linux-x86_64/gallium/targets/libgl-xlib/
export OPENGL_INC=/home/565/olk565/mesa-17.1.5/include/GL
```
I used to have a shared mesa build but I seemed to lose access to the uw project dir, so yeah not anymore.

I remember having lots of problems with Xvfb on raijin, I think I gave up and used turbovnc at one point: https://github.com/OKaluza/LavaVu/wiki/NCI-Raijin-Build

**Comment by julesghub** [comment]
Sweet, thanks for the info. I'll give it a try and report back.

**Comment by OKaluza** [comment]
If you can add me back to the underworld project I'm happy to make a new shared mesa build for this.

**Comment by julesghub** [comment]
yep good thinking - @lmoresi can you make that happen?

**Comment by lmoresi** [comment]
Owen is a member … I don’t remember uninviting him but perhaps something needs to be different about the membership of particular teams.

Happy to fix whatever is needed.


Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 28 Jun 2019, 3:43 PM +1000, Julian Giordani <notifications@github.com>, wrote:

yep good thinking - @lmoresi<https://github.com/lmoresi> can you make that happen?

**Comment by lmoresi** [comment]
Also, Julian, you are an owner so …

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 28 Jun 2019, 3:43 PM +1000, Julian Giordani <notifications@github.com>, wrote:

yep good thinking - @lmoresi<https://github.com/lmoresi> can you make that happen?

**Comment by OKaluza** [comment]
Ah, not sure what's missing but I'm in these groups, I think p67 is the old project? Anyway I have no access to /projects/Underworld (/short/m18/projects) do I need to join m18?
```
bash-4.1$ groups
p67 Monash underworld
bash-4.1$ ls -l /projects/Underworld/
ls: cannot access /projects/Underworld/: Permission denied
bash-4.1$ ls -l /projects
total 12
lrwxrwxrwx   1 root   root           19 Feb  5  2018 UQ_Hypersonics -> /short/n23/projects
lrwxrwxrwx   1 root   root           19 Feb  8  2018 Underworld -> /short/m18/projects
drwxrwxr-x+ 29 ccc561 wrf          4096 Nov 16  2018 WRF
drwxrwsr-x+ 38 access access.admin 4096 Apr  3 09:59 access
drwxr-xr-x   5 root   root         4096 Feb  9  2018 data
lrwxrwxrwx   1 root   root           19 Jan 25  2018 u46 -> /short/u46/projects
lrwxrwxrwx   1 root   root           19 Jan 25  2018 v10 -> /short/v10/projects
lrwxrwxrwx   1 root   root           19 Feb  7  2018 v45 -> /short/v45/projects
```

**Comment by OKaluza** [comment]
Although now that I think about it, I guess I can just put the build on /short/p67 and set the group access to "underworld"... I'll give it a try

**Comment by lmoresi** [comment]
Oh - that underworld project !

I am not sure. Request access to all the relevant projects via Mancini

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 29 Jun 2019, 12:20 +1000, Owen Kaluza <notifications@github.com>, wrote:

Although now that I think about it, I guess I can just put the build on /short/p67 and set the group access to "underworld"... I'll give it a try

**Comment by julesghub** [comment]
Closing this issue. raijin's OSMesa is now running with the 2.8 rc.

**Comment by ZhiqYu** [comment]
@julesghub 
Hello, now I have the same problem when RUNNING underworld code on HPC. Have you solved this problem? I want to continue to ask you for specific solutions.

**Comment by julesghub** [comment]
@ZhiqYu what exactly is the problems you're having with Underowrld on HPC. Do you have an error log? 
Which machine are you running on?

This ticket is quite old - gLucifer has changed significantly and the HPC "raijin" is no longer operational. Can you open a new ticket with more information and the error log. Thanks.
