### ISSUE TITLE
Projecting a mesh variable to a swarm particles

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#397]
Hi All,

I want to project a mesh variable(temperatureField) to the swarm and then deform the swarm by moving the particles manually. After deforming the swarm, I need to project the temperature field back to the mesh and go to next time step for Stokes and Temperature solvers. I can deform the swarm by changing the particle coordinates, but the particles did not carry the temperature data obviously. I am not sure how to project the temperature field between mesh and swarm. Could you please suggest a method to do this?

Thanks
Pras

**Comment by jmansour** [comment]
Hi @Prasanna2989 

This should be relatively straightforward. 

1. Evaluate the mesh variable at the swarm locations, and write to a swarm variable. 
2. Advect your particles as necessary. 
3. Project the swarm variable back to a mesh variable. 

Note that for first step, we don't really think of it as a projection, as we simply perform an evaluation at each required location (the particle coords). For the third step, a projection is required and here a weighted average of the surrounding particles is used to determine the values at all nodes.

```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian()
temp_mesh = mesh.add_variable(1)
swarm = uw.swarm.Swarm(mesh)
swarm.populate_using_layout(uw.swarm.layouts.PerCellSpaceFillerLayout(swarm,20))
temp_swarm = swarm.add_variable("double",1)

# 1.
temp_swarm.data[:] = temp_mesh.evaluate(swarm.data)

# 2. 
# do your advection and/or deform

# 3. 
projector = uw.utils.MeshVariable_Projection(temp_mesh,temp_swarm)  # you only need to create this once
projector.solve()   # do this every time you need to project back to mesh again. 
```

**Comment by Prasanna2989** [comment]
Thanks jmansour. Is there a limitations for number of swarm variables that I can use? If I increase the number of swarm variables how will that impact run time and efficiency other than taking more space?

**Comment by jmansour** [comment]
There are no limitations, but they are heavy objects, so only create what
you need.  Each swarm variable will consume an amount of memory
(particleCount x sizeof(type)), and in parallel these chunks of memory will
need to be communicated across difference processes.  So it can make a
difference, but you probably shouldn't be concerned about it as it
shouldn't be significant.

How many variables do you need?

**Comment by Prasanna2989** [comment]
For the moment, I am using 8 swarm variables for test. I will be able get rid of 2 of them later on by having functions. 

What is the difference between evaluation and projection? Is it weighing in a different way?

Ex:
`
temp_swarm.data[:] = temp_mesh.evaluate(swarm.data)

projector = uw.utils.MeshVariable_Projection(temp_mesh,temp_swarm)
projector.solve() `

**Comment by jmansour** [comment]
An evaluation will simply do a direct evaluation on the underlying objects.
So for a MeshVariable, it will use the element shape functions to form an
interpolation at the required location. An evaluation can be performed at
single locations or globally (it doesn't distinguish).

https://underworld2.readthedocs.io/en/latest/user_guide/04_Functions.html#the-evaluate-method

The projection seeks to project the provided function (in your case, the
SwarmVariable) onto the provided mesh variable.  So it will determine a
representation at *all* mesh nodes.  You don't want to be calling `solve()`
more than you need to, as it is a global operation.

https://underworld2.readthedocs.io/en/latest/underworld.utils.html#underworld.utils.MeshVariable_Projection

**Comment by Prasanna2989** [comment]
Thanks jmansour. It was very helpfull.

**Comment by Prasanna2989** [comment]
Resolved the issue.

**Comment by Prasanna2989** [comment]
Hi All,

I have noticed an issue when I was going through the steps above for the temperature Field projection between mesh and swarm. I have produced the error as per the attachment. 

Here, I take a mantle convection model and evaluate the temperature in the swarm coordinates. I want to deform the swarm, however I have tested this scenario without deforming the swarm to indicate the issue. When I project the swarm temperature in to mesh with the method that you mentioned above, the system diffuse the (heat)temperature faster than it should be. I was wandering this may be an issue with the projection routine. The resolution of the model is 16x16. 


Thanks
Pras

(I need this mechanism to change the temperature of magma intrusion in my model. I can see this method work fine in I2elvis and StagYY codes). Could you please give me some help with this.
<img width="753" alt="MeshTemp_NoTempProjection" src="https://user-images.githubusercontent.com/25965506/64656215-18dce200-d472-11e9-976d-df7577e90842.png">
<img width="737" alt="MeshTemp_WithTempProjection" src="https://user-images.githubusercontent.com/25965506/64656230-285c2b00-d472-11e9-9892-43a4ea48cc47.png">
<img width="780" alt="SwarmTemp_NoTempProjection" src="https://user-images.githubusercontent.com/25965506/64656256-3f9b1880-d472-11e9-997b-a971b6b05dc6.png">
<img width="732" alt="SwarmTemp_WithTempProjection" src="https://user-images.githubusercontent.com/25965506/64656300-58a3c980-d472-11e9-839b-4295e0347309.png">
