### ISSUE TITLE
Error while deforming the swarm and adding new particles while model run continues

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#398]
Hi All,

I was producing the mantle melt in a rectangular convection model with a swarm and was trying to transport the melt particles instantaneously to the surface. In this case, I have selected the melt particles by constraining temperature field (comparing with the solidus) and applied an index for these particles to represent the mantle melt. 

Then, I checked their coordinates(xmelt, ymelt) and transfer them directly to a new coordinate at the surface of the model (xmelt, 0.99). This is a rectangular model and model height is 1. Then, I added a new particle in the previous location of the melt marker to represent the residue of the melt. The model was running fine for few steps and gave me the attached error message. I have included the last figure of material indexes for your reference. I was wandering whether I can get some help to identify this error and to know how to avoid it. (This is not a proper melt generation model at the Earth surface. However, it simulate a prototype model by comparing temperature with some solidus like function)

Thank you
Pras

![Screen Shot 2019-07-04 at 4 50 01 pm](https://user-images.githubusercontent.com/25965506/60645356-cda7c100-9e7b-11e9-9698-c9636467f7c3.png)
<img width="714" alt="Screen Shot 2019-07-04 at 5 00 13 pm" src="https://user-images.githubusercontent.com/25965506/60645889-3fccd580-9e7d-11e9-9e1a-98652b69ba25.png">

**Comment by julesghub** [comment]
Hi Pras,

A swarm variable numpy array (let's call it SVNA) is most likely stale because it was created before the increase in the number of particles. SVNAs that are created before the addition of extra particle don't know about the addition, hence the SVNA is still the original size (bad!) and the array is invalid.

Underworld checks for these invalid SVNAs. If found, a RuntimeError is generated as you received. 

As the message explains you can fix this by `del` the SVNA.

Consider this code snippet below 

```
import numpy as np
import underworld as uw

# build mesh and swarm
mesh  = uw.mesh.FeMesh_Cartesian()
swarm = uw.swarm.Swarm(mesh)
v1    = swarm.add_variable(dataType='int', count=1)

pos = np.random.rand(4,2)
swarm.add_particles_with_coordinates(pos)
v1.data[:,0] = -3
# create a numpy array view
view = v1.data

### UNCOMMENT FOR SUCCESS ###
# copy = np.copy(v1.data)
# del view

pos2 = np.random.rand(4,2)

# if swarm adds these particles then the `view` numpy array is stale.
swarm.add_particles_with_coordinates(pos2)
```

Hope this helps.

**Comment by Prasanna2989** [comment]
Thanks Jule. Do we need to remove 'v1' swarm variable and define a new swarm variable 'v1' again after addition of new particles to the swarm? I removed the numpy arrays (like 'view'), but still the issue exists.

**Comment by Prasanna2989** [comment]
Thanks Jule. Do I need to del all the swarm variables and redefine them in each time step. I tried to remove only np.arrays, but it seems not working. Following shows the part of the code that I am dealing with this issue. k1 and k2 are two arrays that I remove using del now. Attached the error message as well.

`#Parameter values
meltIndex = 1
residueIndex = 2

meltmax = 0.0
meltmin = 0.0

#Swarm variables
materialVariable   = swarm.add_variable( dataType="int", count=1 )
Mext = swarm.add_variable('double', 1)
Mextc = swarm.add_variable('double', 1)
Mextc.data[:] = 0.

def melt_update():
    Mext.data[:] = 0.
    
    Mext.data[:] = XFn.evaluate(swarm)-Mextc.data[:]#XFn is a function
    k1 = Mext.data > 0.
    Mext.data[~k1] = 0.
        
    k2 = Mext.data > meltmax
    Mext.data[k2] = Mext.data[k2]-meltmin
         
    Mextc.data[k2] = Mextc.data[k2]+Mext.data[k2]
        
    del k1
    del k2
        
    #deform the marker locations while saving the coords    
    swarmCoords = [] # To record the previous locations of deformed markers
    for index, coord in enumerate(swarm.particleCoordinates.data):
        x = coord[0]
        z = coord[1]
            
        if Mext.data[index] > 0.0 and coord[1] > boxHeight*0.1:
            materialVariable.data[index] = meltIndex#1
            with swarm.deform_swarm():
                swarm.particleCoordinates.data[index] = (x,0.99) #Moved the particles to the surface
                            
            swarmCoords.append([x,z])#Find the previous marker location 
                
                
    swarmCoords1 = np.array(swarmCoords) #Array of previous locations of deformed markers
    
    #Apply new markers
    if (np.size(swarmCoords1)>0):
        newParticles = swarm.add_particles_with_coordinates(swarmCoords1)
            
        materialVariable.data[newParticles] = residueIndex
        Mextc.data[newParticles] = 1.
        Mext.data[newParticles] = 1.
            `
[error.docx](https://github.com/underworldcode/underworld2/files/3364474/error.docx)
