### ISSUE TITLE
numpy/uw/blas threaded operation

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#400]
Consider.

**Comment by julesghub** [comment]
From my script
# maybe this helps the mpi setup
import mpi4py.rc
mpi4py.rc.threaded = False
mpi4py.rc.thread_level = "single"

**Comment by jmansour** [comment]
`numpy` will by default use all procs available to it for certain routines (such as `np.dot()`).   Try running this within your docker image to see:
```python
import numpy as np
a1 = np.random.rand(10000, 10000)
a2 = np.random.rand(10000, 10000)
np.dot(a1, a2)
```
now try setting `OPENBLAS_NUM_THREADS=1` and re-running.

**Comment by jmansour** [comment]
Discussion of exactly this issue here:

https://github.com/numpy/numpy/issues/11826

**Comment by jmansour** [comment]
I think I'd rather not touch this for the forthcoming release. I originally plugged this into the top level `__init__.py`:
```python
# Disable multithreaded numpy operation for mpi.size>1. 
# Where running in parallel, we don't want multiple threads per process. 
# Do this for all possible backends.
from mpi4py import MPI as _MPI
if _MPI.COMM_WORLD.size > 1:
    import os
    os.environ[       "OMP_NUM_THREADS"] = "1"
    os.environ[  "OPENBLAS_NUM_THREADS"] = "1"
    os.environ[       "MKL_NUM_THREADS"] = "1"
    os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
    os.environ[   "NUMEXPR_NUM_THREADS"] = "1"
```
and it worked but I'm not really comfortable with it.  In particular, this forces us to rely on `mpi4py` to call `MPI_Init()`, which I think we'd rather not do due to the fragile nature of the UW shutdown process (which currently prefers UW call `MPI_Init()`).

Perhaps we should plug it into `dev` and keep an eye on it.

**Comment by jmansour** [comment]
Also, my testing suggests that these environment variables only work if set *before* `numpy` is imported. But this possibly also depends on the BLAS backend being used (check numpy issue above).
