### ISSUE TITLE
Impact of adding particles to a swarm

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#402]
Hi all,

I was wondering whether addition of particles to a swarm in each time step will impact the density ( mass conservation) of the model in the UW2 implementation. Basically will that change the density term of the Stokes equation?

 As per my understanding the density and viscosity functions are evaluated in the coordinates of the swarm. Therefore, addition of particles to an existing swarm should not change the density. If I am correct they are just passive integration points that can be advected. Could you please confirm whether I am right about that?

Thank you
Pras

**Comment by jmansour** [comment]
Yes you are correct @Prasanna2989, adding particles will not affect the density.  It is as you suggest.

**Comment by Prasanna2989** [comment]
Awesome. Thank you.
