### ISSUE TITLE
Swarm interpolation location outside local domain with outflow BC

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#403]
Hi all,

Another issue I met recently is that for models that have inflow and outflow boundary conditions, swarm interpolation usually has an issue reporting the particle outside the domain. This usually occurs after a few hundred steps. The mesh is uneven, but static. One example is as below:

```
An uncaught exception was encountered on processor 5.
Traceback (most recent call last):
  File "input6.py", line 1532, in <module>
    dtStep,time,step,MeshOutput = update(MeshOutput)
  File "input6.py", line 1401, in update
    NewOCGen()
  File "input6.py", line 569, in NewOCGen
    NewOC_ID = np.where(np.logical_and((conditional_NewOC.evaluate(swarm) < 0.0), (materialVariable.data[:] == MantleIndex)))[0]
  File "/BIGDATA1/unimelb_tang_1/UW/y2019/Jan10/underworld2-2.5.1b/underworld/function/_function.py", line 797, in evaluate
    return _cfn.Query(self._fncself).query(inputData._get_iterator())
ValueError: FeVariable interpolation at location (1.71259, -3.50786e-10) does not appear to be valid.
Location is probably outside local domain.
application called MPI_Abort(comm=0x84000002, 1) - process 5
slurmd[cn8179]: *** STEP 1885591.0 KILLED AT 2019-07-12T16:56:00 WITH SIGNAL 9 ***
yhrun: Job step aborted: Waiting up to 2 seconds for job step to finish.
slurmd[cn8179]: *** STEP 1885591.0 KILLED AT 2019-07-12T16:56:00 WITH SIGNAL 9 ***
yhrun: error: cn8179: tasks 0-23: Killed

```
Y-Axis location -3.50786e-10 is slightly below the model bottom boundary, which is 0.0.

I did not see a bug in NewOCGen function, but in case I was wrong, the NewOCGen function is as below. Thanks a lot.
```
def NewOCGen():
    # You might need some modification for models with sticky-air
    d = zw-fn.input()[1]
    conditional_NewOC = fn.branching.conditional( ( (temperatureField < HalfSpaceCoolingFn(5.,Tm,d,tao), 99999999.), (fn.input()[1] < zw-lowerPlateCrustThk, 99999999.), (True, -1.) ) )
    NewOC_ID = np.where(np.logical_and((conditional_NewOC.evaluate(swarm) < 0.0), (materialVariable.data[:] == MantleIndex)))[0]
    if len(NewOC_ID)>0:
        materialVariable.data[NewOC_ID] = lowerPlateCrustIndex
    return
```

**Comment by tingyang2004** [comment]
I guess this has been solved after I switched the location of (temperatureField < HalfSpaceCoolingFn(5.,Tm,d,tao), 99999999.) and (fn.input()[1] < zw-lowerPlateCrustThk, 99999999.) in the NewOCGen function.
At least for the new case I ran, the FeVariable interpolation at a point outside of domain issue did not occur any more.
So it seems that particle location is slightly outside of the defined domain in one step and that has caused the problem when mapping temperature from mesh to swarms.
Will let you know if further experiments rebut the above speculations.

**Comment by jmansour** [comment]
Sorry @tingyang2004, what have you changed? 

I believe that the particle that is straddling the boundary is deemed to be inside earlier (during advection), but then deemed to be outside when you attempted your evaluation.  This is possible, as there's an iterative step involved internally in the calculation, and a particle so close to the boundary might fall inside or out. 

What you probably should do is simply filter the particles first manually.  Something like this:
```python
with swarm.deform_swarm():
    particles_outside = np.where( swarm.data[:,1] < 0 )
    swarm.data[particles_outside,1] = -9999999  # send them outside (further!) to delete them
```
It's possible this might even work,
```python
with swarm.deform_swarm():
    pass
```
as it might take up the slack of the earlier algorithms, but I'm not 100% sure.  Go with the first option to be safe.

**Comment by tingyang2004** [comment]
The three more tests I had made do not have the "FeVariable interpolation at point outside of domain" issue till now.
Since the issue occurs to points close to the bottom boundary and I only concern about points near the top boundary, so using (fn.input()[1] < zw-lowerPlateCrustThk, 99999999.) to filter swarms before the FeVariable interpolation is enough to solve my issue (at least until now).

**Comment by jmansour** [comment]
Ah right, I missed that change you made.  Ok, i'll close the ticket.  Reopen as necessary.
