### ISSUE TITLE
rt_timed.py high resolution reports solve time floating point problems. 

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#404]
Using the timing scripts:

https://github.com/jmansour/scaling_scripts

for runs of resolution >=512 we get a report of floating point issues at solve time. Interestingly, running with limited mg levels  (6 instead of the 10 automatically determined for 512) does not yield the warning.  

Issue persists on Magnus and Raijin, Shifter and bare metal (both platforms).  Model is isoviscous and only has _easy numbers_.   

Solve results appear consistent regardless of warning.

**Comment by drcoopa** [comment]
I'm seeing this issue on Stampede2 (using a bare metal) build for 3D isoviscous convection.  It seems to be # of processors dependent as well as size dependent.  I lowered the resolution and size (down to a 1x1x1 box) and the warnings went away.  I then increased the size of the model (to 2x2x1) and slowly increased the resolution.  If I run the hi-res job (256x256x128) for a 2x2x1 box on 64 procs, no warning; same run with 128 procs, no warning. But if I run it on 256 procs, then I run into the warning.  

Will try for 2D, hi-res next week and report back.

**Comment by drcoopa** [comment]
Bad news...the error appears for a 2D run of isoviscous convection of a 1x1 box with 128x128 resolution running on 64 procs (doesn't happen when running on 8 procs or 1 proc).  Again, this is running on Stampede2 (using a bare metal build).  This is very worrisome b/c I don't feel comfortable running anything using this build of UW2 while getting this error.  It's producing reasonable temperature values, but error is disconcerting.  It also seems tied to the number of processors used rather than strictly the size of the job.

**Comment by jmansour** [comment]
Unfortunately we haven't had a chance to have a closer look at this yet.  A few things:

1. 128x128 across 64 processors is almost certainly over overly decomposed and it'd probably be faster using less processors. That said, we'd hope in either case the numerical results would be unchanged. 
2. Can you try disable MG and see if you still encounter that message? 
```python
solver.set_inner_method("nomg") 
```
3. Can you also try the `mumps` solver?  It's probably a good option for medium sized jobs in any case, but I'd also be interested to know if that message is still triggered. 
```python
solver.set_inner_method("mumps")
```
I'll try and have a bit of closer look at this some stage this week hopefully.

**Comment by drcoopa** [comment]
1.  Yep, I realized that this would be the case.  I was just testing to see when/if the error appeared again.  I would hope that it's not triggered by overly decomposed setups as that sometimes has to happen for timings, etc.

2. Did this - no error

3.  Got the error with mumps...plus this warning "** PETSc DEPRECATION WARNING ** : the option -pc_factor_mat_solver_package is deprecated as of version 3.9 and will be removed in a future release. Please use the option -pc_factor_mat_solver_type instead. (Silence this warning with -options_suppress_deprecated_warnings)
  Setting schur_pc to "uw" ""

**Comment by jmansour** [comment]
Ok, thanks for doing these tests.  

For the time being, I can only suggest you run with `nomg` or `mumps`.

**Comment by drcoopa** [comment]
I'll give it a go with nomg, but mumps also produced the error...

**Comment by jmansour** [comment]
Is that an error, or just a warning about deprecations?

**Comment by drcoopa** [comment]
it had the same error AND the deprecation warning

**Comment by jmansour** [comment]
Ok, missed that.   So `nomg` it is, or you can experiment with limiting the mg levels as per the top post.

**Comment by julesghub** [comment]
Re: the deprecation error. We sorted this out #326. For uw2.8 and beyond the warning shouldn't occur.

**Comment by drcoopa** [comment]
should I do a rebuild and then it'll go?

**Comment by julesghub** [comment]
Yes that should be the case. Build instructions here https://github.com/underworldcode/underworld2/tree/v2.8.1b/docs/install_guides

**Comment by jmansour** [comment]
But note @drcoopa that this will only fix the deprecation warning, **not** the floating point warning.  So it won't really change anything.

**Comment by drcoopa** [comment]
Right.  But I’m guessing that at some point I’ll need to rebuild to avoid depreciation problems?

**Comment by julesghub** [comment]
That is the case if you compile your current version of underworld with a petsc version greater than petsc-3.9.
