### ISSUE TITLE
How to evaluate velocity magnitude using fn.input()?

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#405]
Hi,
I am trying incorporate velocity depend yield stress for particles in the crust. It seems underworld doesn't have option to evaluate velocity using fn.input(). The valid inputs for Function evaluate are mesh, swarm and array or tuple of floating points. How to overcome this hurdle?
Equations and code I am using
![equation](http://bit.ly/2Z2DJVv)
Let's say
![equation](http://bit.ly/2Gm0sok)
Where _v_ is the velocity magnitude.

```python
coord = fn.input()
v_fn_mag = fn.math.sqrt(fn.math.dot(vc,vc))
v_mag = v_fn_mag.evaluate(coord)
mu_eff = 0.6*(1/v_mag)
rho_g = 80.0*1
tao_Y_slab = cohesion_slab  + mu_eff*rho_g *(1. - fn.math.sqrt(coord[0]**2. + coord[1]**2.))
```
Thanks.

**Comment by rbeucher** [comment]
Hi @gthyagi

The 'fn.input' function is basically f(x)=x
When evaluated the function return the mesh coordinates if you use the mesh or the swarm coordinates if you use a swarm....

If you use your v_fn_mag function to define your viscosity function the value returned by the mu_eff function will be the viscosity at the nodes (using the velocity at those same nodes) 

Is it what you are after?

**Comment by rbeucher** [comment]
The code that you have posted will not work because after you have evaluated the v_fn_mag function v_mag is a numpy array and it can't be used to define a new Underworld function.

If for some reason you need to evaluate the velocity before hand I suggest you use a meshvariable to record the output of v_fn_mag

**Comment by gthyagi** [comment]
> Hi @gthyagi
> 
> The `fn.input` function is basically `f(x)=x` It's an identity function.
> When evaluated the function return the mesh coordinates if you use the mesh or the swarm coordinates if you use a swarm....
> 
> If you use your `v_fn_mag` function to define your viscosity function the value returned by the `mu_eff` function will be the viscosity at the nodes (using the velocity at those same nodes)
> 
> Is it what you are after?

@rbeucher Yes, I am calculating viscosity of a particle using velocity at that particle in the crust. I can see your point on evaluate operation.

**Comment by gthyagi** [comment]
> The code that you have posted will not work because after you have evaluated the `v_fn_mag` function `v_mag` is a numpy array and it can't be used to define a new Underworld function.
> 
> If for some reason you need to evaluate the velocity beforehand I suggest you use a meshvariable to record the output of `v_fn_mag`

Even after creating new mesh variable to store velocity magnitude, I have to use evaluate operation on the new mesh variable. But evaluate operation doesn't accept underworld function (fn.input()) as a valid input. Is it possible to find velocity at a particle coordinate in the model domain without using evaluate operation ?

**Comment by rbeucher** [comment]
You don't need to evaluate...
```
coord = fn.input()
v_fn_mag = fn.math.sqrt(fn.math.dot(vc,vc))
# v_mag = v_fn_mag.evaluate(coord) # Any reason you need this?
mu_eff = 0.6*(1/v_fn_mag)
rho_g = 80.0*1
tao_Y_slab = cohesion_slab  + mu_eff*rho_g *(1. - fn.math.sqrt(coord[0]**2. + coord[1]**2.))

tao_Y_slab.evaluate(your_particle_coordinates)
```

**Comment by gthyagi** [comment]
Thanks @rbeucher, now I realised the mistake in my code. The usage of evaluate operation destroys the underworld function property for v_fn_mag.
