### ISSUE TITLE
How to create a xdmf file with multiple field data sets?

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#406]
Hi, 
I am trying to creating to a xdmf files with multiple field data sets. This is the code I am using 
```python
    def checkpoint():
    matVarFieldHnd = ...
    matVarField.xdmf(outputPath+'AllField.'+str(step).zfill(5)+'.xdmf',
                       matVarFieldHnd,"matVarField",meshHnd,"mesh",modeltime=time)
    velocityHnd = ...
    vc.xdmf( outputPath+'AllField.'+str(step).zfill(5)+'.xdmf',
                       velocityHnd, "velocity", meshHnd, "mesh",modeltime=time)
    strainRateInvFieldHnd = ...
    strainRateInvField.xdmf(outputPath+'AllField.'+str(step).zfill(5)+'.xdmf',
                       strainRateInvFieldHnd, "strainRateInv",meshHnd, "mesh",modeltime=time)
```
But this code overwrites the previously generated xdmf file instead of appending. How to append multiple field data sets to same xdmf file at same timestep? I found hard way of manually copy and pasting attributes from each xdmf file to create xdmf files with multiple field data. I am looking for few lines of code to avoid manually work flow.

Thanks.

**Comment by julesghub** [comment]
That functionality doesn't exist at this point in underworld. The xdmf() function doesn't append. In fact the xdmf/hdf5 code is in need of a refactor (contributions/PR welcome ;) ). UWGeo has the required workflow you describe and I would look there for inspiration. 

I'll close this but feel free to continue the discussion.
