### ISSUE TITLE
Open mpi error when using regionalMesh branch in Raijin

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#407]
Hi @julesghub  @jmansour ,
Yesterday, I installed the regionalMesh branch on Raijin without any error. But I am getting the following error when a job is submitted.

```--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[16956,1],59] (PID 2093)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------

[r2797:03850] [[16956,0],0] ORTE_ERROR_LOG: Data unpack would read past end of buffer in file ../../../../orte/util/show_help.c at line 501
Traceback (most recent call last):
  File "/home/565/tg7098/res_test_annulus/2891_spherical/323216_sum_spherical.py", line 10, in <module>
    import underworld as uw
  File "/short/n69/tg7098/Underworld/underworld2_reg_sph_debug/underworld/__init__.py", line 68, in <module>
    raise RuntimeError("Unable to find required libraries.\n"
RuntimeError: Unable to find required libraries.
Note that your PYTHONPATH must now also indicate the directory containing the required compiled libraries. For example, `your_uw_directory/libUnderworld/build/lib`."
```

Note: 
1. Dependencies version number  'python3/3.6.7 openmpi/3.1.2 gcc/5.2.0 hdf5/1.10.2p petsc/3.9.4 swig/3.0.12 scons/3.0.1'.
2. Previous version of the regionalMesh branch works properly with above mentioned dependencies on raijin. Having problems with the latest updates to the branch.

Thanks.

**Comment by julesghub** [comment]
I see #408 - is this issue still valid?

**Comment by gthyagi** [comment]
Yes. Results in #408 are generated using three months old regionalMesh branch not the latest one. #407 occurred when the latest one was used.

**Comment by julesghub** [comment]
ok, thanks for clarifying. 

I have not folded the uw2.8 base into the regionalMesh branch and tested yet. So there might be and issue there.
In any case what is your PYTHONPATH?

**Comment by gthyagi** [comment]
PYTHONPATH=:/short/n69/tg7098/Underworld/underworld2_reg_sph_debug:/short/n69/tg7098/Underworld/underworld2_reg_sph_debug/libUnderworld/build/lib:/short/n69/tg7098/Underworld/underworld2_reg_sph_debug/glucifer::

**Comment by julesghub** [comment]
It appears your missing quite a few thing like h5py, mpi4py.
Please follow the install script [here](https://github.com/underworldcode/underworld2/blob/v2.8.0b/docs/install_guides/nci_raijin.sh), remember you must copy the final output of the script into you pbs file

**Comment by gthyagi** [comment]
@julesghub ok, I will reinstall and update soon.

**Comment by gthyagi** [comment]
> It appears you're missing quite a few thing like h5py, mpi4py.
> Please follow the install script [here](https://github.com/underworldcode/underworld2/blob/v2.8.0b/docs/install_guides/nci_raijin.sh), remember you must copy the final output of the script into your pbs file

I successfully installed regionalMesh branch with latest updates and jobs are running without error. I am closing this issue.
