### ISSUE TITLE
Configure is lying

### ISSUE THREAD

**Issue by mirkovelic** [underworldcode/underworld2#41]
Checking for package X11... yes
Checking for package SDL... no
Checking for package Glut... no
Checking for package OpenGL... yes
****  WARNING ****
Need a windowing system for gLucifer Viewer, either
X11, SDL, Glut or AGL. None of these could be found.
The viewer will not be compiled.

**Comment by mirkovelic** [comment]
Checking for package X11... yes
Checking for package SDL... no
Checking for package Glut... no
Checking for package OpenGL... yes
****  WARNING ****
Need a windowing system for gLucifer Viewer, either
X11, SDL, Glut or AGL. None of these could be found.
The viewer will not be compiled.

**Comment by OKaluza** [comment]
John and I fixed this, may not have been committed yet though

**Comment by jmansour** [comment]
committed now
