### ISSUE TITLE
Docker and output to image files

### ISSUE THREAD

**Issue by cgoise** [underworldcode/underworld2#411]
Hi underworld-team,

not sure if this is really an underworld-issue or a general docker-restriction or maybe just me having no experience with docker.  

If I use the newest docker-image of underworld to start a python-script I receive the following error message (I have to make a few more comments on the way I handle the docker-images below):

	FBO failed INCOMPLETE_ATTACHMENT
	frame 2 depth 2 dims 20000 , 4800
	FBO creation failed, can't continue
	LavaVu Run error: FBO creation failed, can't continue

This happens when I try to save a figure from within the script with

	SomeFigure.save_image("some_fig.png")

Please note that I used to have a lot of lavavu errors like that in previous versions, too. Till now I was able to resolve them if I converted the docker image to a singularity image, and then installed a few missing graphics libraries in the singularity image:
	apt-get install mesa-utils mesa-utils-extra xterm libosmesa6

Xterm is installed in order to pull in the Xorg dependencies, the other things is used for software rendering. I don't know which libs precisely within underworld need these dependencies for image creation, but has to be something glucifer related I would assume. 

After these steps I was able to run local python-scripts through the singularity image and this setup created output png-files without error.

Is there a trick to do this using the docker-image directly? Am I missing some locally installed libs? Any pointer to a solution would be appreciated.

**Comment by jmansour** [comment]
Running the following works fine for me:
```bash
docker run -v $PWD:/workspace -w /workspace --rm -it underworldcode/underworld2:2.8.0b python test.py
```
where `test.py` is:
```python
import underworld as uw
mesh = uw.mesh.FeMesh_Cartesian()
import glucifer
fig = glucifer.Figure()
fig.append(glucifer.objects.Mesh(mesh))
fig.save_image("test.png")
```

What is the platform you're running on?  Are you using docker directly, or have you only tested with singularity?   What kernel version is running on your platform (`uname -a`)

**Comment by cgoise** [comment]
Ok, I figured out what triggers this error: the figsize was not accepted by the recent version of underworld / lavavu. Reducing the figsize-parameter to smaller dimensions (eg to figsize = (2000,1000)) eliminated the error.

The failing code looked like this (abbreviated):

    figTemp = glucifer.Figure( figsize=(5000,1200), boundingBox=((1.5 * minX, 0.0, 0.0), (1.5 * maxX, 1.0 * maxY, 0.0)) )
    figTemp.append( glucifer.objects.Points(swarm, particleTemperature, pointSize=3.0, fn_mask=materialVariable) )
    figTemp.save_image("test.png")

The platform is Linux (Arch..).

**Comment by cgoise** [comment]
Since I don't know if this is expected behaviour I don't close the issue. But feel free to do so yourself.

**Comment by arijitlaik** [comment]
I had the same issue, its because the X framebuffer size is smaller than the large dimentions of the figure, modifying the dockerfile 
```@bash
RUN printf "#\041/bin/sh \n rm -f /tmp/.X99-lock && xvfb-run -s '-screen 0 1600x1200x16' \$@" >> /usr/local/bin/xvfbrun.sh && \
 ```
to something higher e.g. 3200x2400x24 (sufficies for now)

**Comment by jmansour** [comment]
Thanks for info @cgoise.  I'll ping our @OKaluza our viz guy to have a look. 

I guess the image buffer is too larger, but perhaps catching this before it occurs would be useful.  Note also that by default oversampling is used to improve the render quality. This can be disabled by setting the `Figure` constructor parameter `quality=1`.  Docs here:

https://underworld2.readthedocs.io/en/latest/build/glucifer.html#glucifer.Figure

**Comment by jmansour** [comment]
Thanks @arijitlaik.  Good point on the ENTRYPOINT tweak. 

I think we could probably rearrange things so that this can be set via an environment variable.

**Comment by arijitlaik** [comment]
welcome @jmansour , it would be great to have that as an environment variable, especially for post-processing runs and or "production quality" figures.

**Comment by jmansour** [comment]
Note you could also write a new dockerfile to achieve @arijitlaik's tweak:
```Dockerfile
FROM underworldcode/underworld2:2.8.0b

RUN printf "#\041/bin/sh \n rm -f /tmp/.X99-lock && xvfb-run -s '-screen 0 3200x2400x24' \$@" >> /usr/local/bin/xvfbrun.sh && \
chmod +x /usr/local/bin/xvfbrun.sh
```
This is effectively a free operation.

**Comment by OKaluza** [comment]
This is very familiar with a bug I thought was fixed when we did the most recent Raijin build, so looking into it

Do these docker images use a fixed version of lavavu? ie: Is the lavavu pip install fixed at the time when the master image is built and uploaded then any user images just use this cached version or will the version running always be the current pip version? (as looking in the Dockerfile it does not specify a lavavu version, giving me the power to break your images at will)

LavaVu version can be found by: 
```
import lavavu
print(lavavu.__version__)
```

A few other points:
- As surmised, the error message is because the image it is trying to create is larger than the framebuffer object size limitations of the OpenGL driver in use.
- As mentioned by @jmansour this problem can be magnified by the quality setting, if quality=3 (the default) the image will be rendered 3x larger in both dimensions.
- The requested X size is 5000 but the error is because of 20000, even at quality=3 this should be only 15000 so something else is going on and it sounds like the same bug I fixed last month.
- This should not be impacted at all by the X framebuffer size used by xvfb-run, as the framebuffer objects used do not use the main framebuffer, I'll test this though as am surprised to hear it worked for you @arijitlaik 
- The recommended way to do rendering without a GPU has come full circle back to OSMesa, since it supports llvmpipe rendering with multiple cores now and is up to date enough to work nicely with lavavu. I can try to fix the docker image to do a build of Mesa+OSMesa and we can get rid of Xvfb and all that stuff

**Comment by jmansour** [comment]
Thanks @OKaluza.  The latest image is using Lavavu 1.4.3 btw. 

I think getting rid of xvfb would be awesome, but let's aim for next release as I'd rather not tinker with current release image too much.  So if you start working on it, just do it on the dev branch.

**Comment by OKaluza** [comment]
OK I'm glad to say it wasn't the bug I remembered, it's just too big an image.
Default quality=3 actually doubles the image size twice, so 20000 is correct, and the limit is 16Kx16K

I suggest setting `quality=2` for an image that large, if you are already rendering such high resolution you don't need as much anti-aliasing. At `quality=3` the maximum you can render with this OpenGL driver (Mesa) is 4000x4000, at `quality=2` you can go up to 8000x8000.

Changing the xvfb screen size will make no difference, it is a driver limitation.
Implementing tiled rendering to remove all limits is on my todo list as I'd like to be able to render any size but that will probably not happen really soon.

**Comment by arijitlaik** [comment]
i have had the 'FBO failed INCOMPLETE_ATTACHMENT' while running on an xvnc server, with a compiled version of LavaVu and UW, which i used about 8-9 months ago, not with a docker image, with lower resolution and bit depth(640x480x16), but changing the display server resolution worked for me, back then, I was working with images that the resolution near to 3000x2600 .

**Comment by OKaluza** [comment]
> Thanks @OKaluza. The latest image is using Lavavu 1.4.3 btw.
> 
> I think getting rid of xvfb would be awesome, but let's aim for next release as I'd rather not tinker with current release image too much. So if you start working on it, just do it on the dev branch.

@jmansour If we want to include a mesa build and get rid of xvfb, this is how it's done for the LavaVu docker:
https://github.com/lavavu/LavaVu/commit/b50653991529b1e0b2ad83150d28c0c3d13de8cc#diff-3254677a7917c6c01f55212f86c57fbf

**Comment by OKaluza** [comment]
> Ok, awesome. I think we'll should add this to our base image.
I'll have a go and check it in to development if it works.

**Comment by jmansour** [comment]
I'm not sure if you've checked out the new docker multi-stage build feature, but this would probably be a good use case for it actually, and should help avoid duplication across the lavavu & uw images.

**Comment by lmoresi** [comment]
John, that might be helpful for the cloud stuff which just adds a few files and then exits. It would be good to have a workflow for that.

L

Prof Louis Moresi

louis.moresi@unimelb.edu.au<mailto:louis.moresi@unimelb.edu.au>

(w) +61 3 8344 1217

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>


On 26 Sep 2019, 01:11 -0700, John Mansour <notifications@github.com>, wrote:

I'm not sure if you've checked out the new docker multi-stage build feature, but this would probably be a good use case for it actually, and should help avoid duplication across the lavavu & uw images.

**Comment by jmansour** [comment]
@OKaluza I've followed your `Dockerfile` and have osmesa & lavavu built and running.  However, I'm encountering:
```
Failed to open X display

LavaVu Run error: Failed to open X display
```
Note that I'm just `pip` installing lavavu, so perhaps the pypy version is too old?

**Comment by OKaluza** [comment]
It's still trying to use the system libGL and X11, which are the defaults, so you'll need to tell it where to find it Mesa and tell it to use OSMesa when compiling, eg:
```
export LV_OSMESA=1
export LV_LIB_DIRS=${HOME}/mesa-19.1.7/build/install/lib/x86_64-linux-gnu
export LV_INC_DIRS=${HOME}/mesa-19.1.7/build/install/include
pip install lavavu
```
The main difference to my example Dockerfile is setting LV_OSMESA=1, which has the same effect as passing OSMESA=1 to the make command.

**Comment by jmansour** [comment]
Yeah I had those other envs but I’ll add LV_OSMESA and try again!

**Comment by rbeucher** [comment]
@OKaluza  any update on this?

**Comment by OKaluza** [comment]
@rbeucher no update from my end, LV_OSMESA=1 should have sorted it out, @jmansour will know
