### ISSUE TITLE
number of Swarm particles 

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#412]
Hi All,

2-D model
ParticlesPerCell = 20
res_x = 16
res_y = 64

boxHeight = 1.
boxLength = 4.

When I generate a swarm with above values, I assumed it should give the total number of particles = ParticlesPerCell x (res_x) x (res_y)

however, when I checked the size of the swarm, it indicates 2xParticlesPerCell x (res_x) x (res_y)
for (np.size(swarm.data)). 

Is this a way of implementation of the swarm? Which value I should consider as total number of particles.

Thanks
Pras

**Comment by rbeucher** [comment]
Hi @Prasanna2989 

swarm.data contains the coordinates of the points which is a vector of size 2 in 2D.

Romain

**Comment by Prasanna2989** [comment]
Thanks rbeucher. What is the best way to get the number of particles of the swarm without doing ParticlesPerCell x (res_x) x (res_y) because I am adding particles to my model when it runs for a  while?

**Comment by rbeucher** [comment]
You can do:

```swarm.data.shape[0]``` to get the number of particles
```swarm.data.shape[1]``` gives you the number of dimensions which should be 2 in your case.

**Comment by jmansour** [comment]
```python
import underworld as uw  
mesh = uw.mesh.FeMesh_Cartesian(elementRes=(4,4))  
swarm = uw.swarm.Swarm(mesh)    
swarm.populate_using_layout(uw.swarm.layouts.PerCellSpaceFillerLayout(swarm,10))      
print(len(swarm.data))    
# prints 160
```

**Comment by Prasanna2989** [comment]
Great. Thanks All.
