### ISSUE TITLE
docs fix for release

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#413]
hot fix for release

* live documentation is broken
* advectiondiffusion needs updates
* uw.mpi attribs not rendering correct 
* update to mention pip on dev
* possible do tidy up as well, but perhaps that's better for next release.

**Comment by julesghub** [comment]
+1 for a patch of a few thing. So 2.8 -> 2.8.1

**Comment by jmansour** [comment]
what else is there?

**Comment by julesghub** [comment]
Changes I made in the slcn Vs supg test.
Perhaps more on dev.
On 29 Aug 2019, at 17:15, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:

what else is there?
