### ISSUE TITLE
import underworld on Raijin

### ISSUE THREAD

**Issue by btokay** [underworldcode/underworld2#415]
Hi @jmansour ,

I re-installed Underworld with setting PYTHONPATH to UW_DIR (top level directory of underworld files downloaded by git) as you suggested in [#209](https://github.com/underworldcode/underworld2/issues/209) . But, I got another error:

`$ python3 -c "import underworld"
`
> [raijin1:02667] shmem: posix: file name search - max attempts exceeded.cannot continue with posix.
> [raijin1:02670] shmem: posix: file name search - max attempts exceeded.cannot continue with posix.
> 
> A process has executed an operation involving a call to the
> "fork()" system call to create a child process.  Open MPI is currently
> operating in a condition that could result in memory corruption or
> other system errors; your job may hang, crash, or produce silent
> data corruption.  The use of fork() (or system() or other calls that
> create child processes) is strongly discouraged.
> 
> The process that invoked fork was:
> 
>   Local host:          [[12987,1],0] (PID 2667)
> 
> If you are *absolutely sure* that your application will successfully
> and correctly survive a call to fork(), you may disable this warning
> by setting the mpi_warn_on_fork MCA parameter to 0.
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/short/n69/bt1752/Underworld/underworld/__init__.py", line 84, in <module>
>     raise RuntimeError("Unable to find required libraries.\n"
> RuntimeError: Unable to find required libraries.
> Note that your PYTHONPATH must now also indicate the directory containing the required compiled libraries. For example, `your_uw_directory/libUnderworld/build/lib`.

Then, adding path UW_DIR/libUnderworld/bin/lib to $PYTHONPATH, I run `python3 -c "import underworld"` again. New problem is at this time:

> [raijin6:22474] shmem: posix: file name search - max attempts exceeded.cannot continue with posix.
> [raijin6:22477] shmem: posix: file name search - max attempts exceeded.cannot continue with posix.
> 
> A process has executed an operation involving a call to the
> "fork()" system call to create a child process.  Open MPI is currently
> operating in a condition that could result in memory corruption or
> other system errors; your job may hang, crash, or produce silent
> data corruption.  The use of fork() (or system() or other calls that
> create child processes) is strongly discouraged.
> 
> The process that invoked fork was:
> 
>   Local host:          [[14230,1],0] (PID 22474)
> 
> If you are *absolutely sure* that your application will successfully
> and correctly survive a call to fork(), you may disable this warning
> by setting the mpi_warn_on_fork MCA parameter to 0.
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/short/n69/bt1752/Underworld/underworld/__init__.py", line 91, in <module>
>     import libUnderworld
> ImportError: /apps/openmpi/3.1.2/lib/Intel/libmpi_mpifh.so.40: undefined symbol: ompi_mpi_state

Modules `gcc/5.2.0 hdf5/1.10.2p petsc/3.8.4 swig/3.0.12 python3/3.6.2 openmpi/3.1.2 scons` were loaded as guided in the documentation of HPC Installation, but I cannot detect what I might miss for this step.
Do you have any idea?

Best,

Bülent

**Comment by julesghub** [comment]
@btokay 
Please review the final parts of this script. 

https://github.com/underworldcode/underworld2/blob/ea248261c19de26ab64cd1b548843737addcbb3a/docs/install_guides/nci_raijin.sh#L42

Setting the  LD_PRELOAD environment variable is critical for raijin and overcomes the `ImportError` you're experiencing.

**Comment by btokay** [comment]
Hi @jmansour ,
Yes, it works. No error!
Thank you very much :)
Bülent
