### ISSUE TITLE
how do I configure underworld2 code with python3 / scons check

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/underworld2#416]
when I type command

> python ./configure.py --python-dir=/apps/python3/3.6.2 --with-debugging=0

the screen shows

> unknown option --config=force

> usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...

> Try `python -h' for more information.

how do I modify the command?

**Comment by jmansour** [comment]
Where are you trying to build underworld? 

Perhaps try using :
```bash
python3 ./configure.py --python-dir=/apps/python3/3.6.2 --with-debugging=0
```
where we've used `python3` instead of `python`.

**Comment by cgw0814** [comment]
I typed the command like

> python3 ./configure.py --python-dir=/usr/bin/python3.6 --with-debugging=0

or

> python3 ./configure.py --python-dir=/usr/bin/python3 --with-debugging=0

the results is as same before
![螢幕快照 2019-09-03 下午9 51 12](https://user-images.githubusercontent.com/38973778/64179066-19371500-ce95-11e9-93e6-d95817b80000.png)
![螢幕快照 2019-09-03 下午9 51 56](https://user-images.githubusercontent.com/38973778/64179082-1f2cf600-ce95-11e9-9b91-7b3747753a8a.png)

**Comment by jmansour** [comment]
Do you have `scons` installed?  If not, run `pip3 install scons`.

**Comment by cgw0814** [comment]
thanks @jmansour it's work!!!

**Comment by jmansour** [comment]
Ok, great!  Leave this ticket open for now, as i'll add a check somewhere to flag this to users so it's more obvious.

**Comment by cgw0814** [comment]
Now, there is a new problem is , even I have installed the python3 which root is /user/bin/python3 or /user/bin/python3.6. the ./configure.py can not detect python.

**Comment by jmansour** [comment]
What platform are you running on? Do you have the Python development files installed?

**Comment by cgw0814** [comment]
I 'm running on Ubuntu18.04 . 

I tried 
> sudo apt-get install python3.7-dev

and change the python path into 

> export PATH="$PATH:/usr/bin/python3.7" in ~/.bashrc

restart the terminal, but no use.

however, I delete the 

> --python-dir=/usr/bin/python3.7

and typed

> python3 ./configure.py 

it's work.

Anyway, I conclude the install process

> python3 ./configure.py 

> sudo apt-get install python3.7-dev

> sudo apt-get install python3-pip3
> pip3 install scons
> pip3 install numpy
> pip3 install mpi4py.

however

> pip3 install h5py 
is not work

/configure.py can not detect the h5py
![h5py-fail](https://user-images.githubusercontent.com/38973778/64226727-1975f580-cf13-11e9-9086-8006ad52c423.JPG)

even tired 

> conda install -c conda-forge h5py

the result is the same.

**Comment by jmansour** [comment]
So is `h5py` installed?  What does `python3 -c "import h5py"` report?

**Comment by cgw0814** [comment]
I make it. The reason is I have installed h5py in the python2.7 in underworld2 before I switch to python3.  

So, I delete the h5py I installed before 

and re-executed 

> pip3 install h5py

the command

> python3 -c "import h5py"

executes smoothly.

and I also checked with jupyter notebook

thanks @jmansour

**Comment by cgw0814** [comment]
I compile the underworld code

when I import the underworld module

the screen shows

>mpiexec: Error: unknown option "-pmi_args"
Type 'mpiexec --help' for usage.

and It's difficult to shout down the program or jupyter

but I configure successfully.

so I confuse.

**Comment by cgw0814** [comment]
when I type

> python3 -c 'import underworld'

the screen shows

![import failed](https://user-images.githubusercontent.com/38973778/64306915-f1e06500-cfc6-11e9-8462-4ffa55521764.JPG)

**Comment by jmansour** [comment]
Do you have `swig` installed?

**Comment by cgw0814** [comment]
yeah~ I have installed already before I compiled

**Comment by jmansour** [comment]
I think your bindings haven't been generated for some reason.  Can you re-run `compile.py` and report the output here?

**Comment by cgw0814** [comment]
Hi @jmansour  I know where is the problem. The wrong expression of the PYTHONPATH. Now I can import underworld, h5py, numpy, mpi4py, glucifer and lavavu smoothly.
Finally, I write a installation guild for myself.

`https://www.evernote.com/shard/s243/sh/8da5c1ea-0e59-489b-b24f-0ff4835a5f51/f8e57b13664689a9c14f2475846840a5`

![install-su](https://user-images.githubusercontent.com/38973778/64311916-87d0bb80-cfd8-11e9-9352-971dd26629df.JPG)

**Comment by jmansour** [comment]
Ok, great!  Thanks for sharing your build notes too.
