### ISSUE TITLE
Parallel problem with Pressure smoothing

### ISSUE THREAD

**Issue by Yidali26** [underworldcode/underworld2#417]
Hi there,
I encountered a problem when I tried to do the pressure smoothing with multiple processors.
The example:

```python
import underworld as uw
from underworld import function as fn
import glucifer
import numpy as np
import math




elementType = "Q1/dQ0"
res = 50

mesh = uw.mesh.FeMesh_Cartesian( elementType = (elementType), 
                                 elementRes  = (res, res), 
                                 minCoord    = (0., 0.), 
                                 maxCoord    = (1., 1.),
                                 periodic    = [False, False]  ) 

velocityField    = mesh.add_variable(         nodeDofCount=mesh.dim )
temperatureField    = mesh.add_variable(         nodeDofCount=1 )
pressureField    = mesh.subMesh.add_variable( nodeDofCount=1 )

velocityField.data[:] = [0.,0.]
pressureField.data[:] = 0.
temperatureField.data[:] = 0.


pressureFn = pressureField+fn.misc.constant(0.)
pressureFn.evaluate(mesh)
```

which work correctly with single processor, but run into problem with multiple processor. The error message is like:
FeVariable interpolation at location (0.48, 0.48) does not appear to be valid.
Location is probably outside local domain.

The issue seems only appear when I try to evaluate from subMesh variables to Mesh variables, but not exist in the mesh to subMesh cases, like
```python
temperatureFn = temperatureField+fn.misc.constant(0.)
temperatureFn.evaluate(mesh.subMesh)
```
will work.

**Comment by jmansour** [comment]
Hi @Yidali26 

This does appear to be a _bug_.  Basically, when you're doing `evaluate(mesh)` in parallel, it's evaluating at all nodes **including** the shadow space nodes (the nodes a process has copies of but are owned by a neighbouring process), but it should only be evaluating at local nodes (those _owned_ by a given process). 

A workaround is to use the following:
```python
pressureFn.evaluate(mesh.data[0:mesh.nodesLocal])
```
which forces the evaluation at **only** the local nodes. 

@julesghub, the docstring for `FeMesh.data` handle states that the handle only grabs the local nodes, but actually it grabs (local+shadow) nodes.  Do you know if this has always been the case (and the docstring has been wrong), or is it a regression?

**Comment by julesghub** [comment]
> @julesghub, the docstring for FeMesh.data handle states that the handle only grabs the local nodes, but actually it grabs (local+shadow) nodes. Do you know if this has always been the case (and the docstring has been wrong), or is it a regression?

unsure if this was a regression. If we implement the context manager ideas this could be reworked significantly

**Comment by julesghub** [comment]
Post 2.11 release we consider a change based on this ticket - to only return local data at the python level.
The idea is:
1) StgVariable has no idea of array size (local+shadow = domain)
2) In function `StgVariable_getAsNumpyArray` we can only ask for the `local` information.
