### ISSUE TITLE
The swig binding

### ISSUE THREAD

**Issue by cgw0814** [underworldcode/underworld2#420]
When I installed uw2-code in other machine

The erros about swig binding showed in screen
![Screenshot from 2019-09-26 23-17-57](https://user-images.githubusercontent.com/38973778/65746510-e65af800-e0b3-11e9-950c-0ab54a73f2be.png)

and following the config.log
[config.log](https://github.com/underworldcode/underworld2/files/3661124/config.log)

**Comment by jmansour** [comment]
It looks like there was a compilation error before you even made it to the binding generation (via swig). 

What is the output of `./scons.py` ?

**Comment by cgw0814** [comment]
`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> PICellerator/MaterialPoints/src/GeneralSwarm.cpp
PICellerator/MaterialPoints/src/GeneralSwarm.cpp:15:10: fatal error: mpi.h: No such file or directory
 #include <mpi.h>
          ^~~~~~~
compilation terminated.
scons: *** [build/PICellerator/MaterialPoints/src/GeneralSwarm.os] Error 1
scons: building terminated because of errors.
`

**Comment by cgw0814** [comment]
I think the problem is about the no mpi.h in mpi root

**Comment by jmansour** [comment]
It looks like MPI is missing.  So did it configure correctly?  

Is this for a desktop machine? If it is, docker is usually our recommendation. Also, if you are happy to use the dev branch, you might like to try using `pip install`.  We've updated the installation info here:
https://underworld2.readthedocs.io/en/development/Installation.html
Perhaps review that document, and see if there's anything you've missed.

**Comment by cgw0814** [comment]
In fact, we tried to connect one more machines, so need to local install, but recently, I tried to run container in HPC cloud or supercomputer with singularity which function like switch in my country. So. I think we just run docker in desktop machine if run container in supercomputer successfully.

**Comment by cgw0814** [comment]
I close it!!!!

**Comment by jmansour** [comment]
Yes, definitely if your HPC facility can run containers via Singularity or Shifter, that is 100% the way forward. And likewise for desktop machines, we generally prefer container usage (via Docker typically).
