### ISSUE TITLE
Having a heck of a time getting this installed/recognized in python

### ISSUE THREAD

**Issue by whositwhatnow** [underworldcode/underworld2#422]
So,  

I am still running into issues getting this installed our local cluster by doing the native install.

I am using python 3.7.3.

- Download source
- cd libUnderworld
- ./configure.py --prefix=/cm/shared/apps/underworld2/2.8.1 --python-dir=/cm/shared/apps/python/3.7.3b --petsc-lib-dir=/cm/shared/apps/petsc/3.11.2/lib --petsc-inc-dir=/cm/shared/apps/petsc/3.11.2/include --with-debugging=0 
- configures correctly
- do ./compile.py goes and compiles adds libraries only to my set dir in --prefix
- install UWGeodynamics via pip - pip3.7 install UWGeodynamics
- installs no errors
- do python3 -c 'import underworld' get error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'underworld'

**Comment by jmansour** [comment]
Have you updated your `PYTHONPATH`?
```
export PYTHONPATH=$PYTHONPATH:/cm/shared/apps/underworld2/2.8.1 
```

**Comment by whositwhatnow** [comment]
I have and get the following error still it cant find module.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'underworld'


________________________________

**Comment by julesghub** [comment]
It sounds like the underworld python module isn't there.

After `compile.py` you must run `./scons.py install` see https://underworld2.readthedocs.io/en/development/Installation.html#build-system

Does that help?

**Comment by whositwhatnow** [comment]
I get the following error

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> PICellerator/MaterialPoints/src/CoincidentMapper.c
In file included from /cm/shared/apps/petsc/3.11.2/include/petscsys.h:14:0,
                 from /cm/shared/apps/petsc/3.11.2/include/petscbag.h:4,
                 from /cm/shared/apps/petsc/3.11.2/include/petsc.h:5,
                 from build/include/StgDomain/Utils/PETScCompatibility.h:13,
                 from build/include/StgDomain/Utils/Utils.h:21,
                 from build/include/StgDomain/StgDomain.h:17,
                 from PICellerator/MaterialPoints/src/CoincidentMapper.c:12:
/cm/shared/apps/petsc/3.11.2/include/petscconf.h:81:36: error: expected ‘,’ or ‘}’ before ‘__attribute’
 #define PETSC_DEPRECATED_ENUM(why) __attribute((deprecated))
                                    ^
/cm/shared/apps/petsc/3.11.2/include/petscksp.h:430:76: note: in expansion of macro ‘PETSC_DEPRECATED_ENUM’
 #define KSP_DIVERGED_PCSETUP_FAILED_DEPRECATED KSP_DIVERGED_PCSETUP_FAILED PETSC_DEPRECATED_ENUM("Use KSP_DIVERGED_PC_FAILED (since v3.11)")
                                                                            ^
/cm/shared/apps/petsc/3.11.2/include/petscksp.h:452:15: note: in expansion of macro ‘KSP_DIVERGED_PCSETUP_FAILED_DEPRECATED’
               KSP_DIVERGED_PCSETUP_FAILED_DEPRECATED  = -11,
               ^
scons: *** [build/PICellerator/MaterialPoints/src/CoincidentMapper.os] Error 1
scons: building terminated because of errors.


________________________________

**Comment by whositwhatnow** [comment]
So i went to redo the install again.  This time using python 3.6.2.  Here are the steps I did:

- git clone https://github.com/underworldcode/underworld2.git
- cd underworld2
- cd libUnderworld/
- ./configure.py --prefix=/cm/shared/apps/underworld2/2.8.1b --python-dir=/cm/shared/apps/python/3.6.2 --petsc-lib-dir=/cm/shared/apps/petsc/3.11.2/lib --petsc-inc-dir=/cm/shared/apps/petsc/3.11.2/include --with-debugging=0
- ./compile.py - COMPILES SUCCESSFULLY NO ERRORS CREATES BUILD DIR IN UNDERWORLD/LIBUNDERWORLD DIR
- ./scons.py install - COMPILES SUCCESSFULLY NO ERRORS 

- export PYTHONPATH=$PYTHONPATH:/cm/shared/apps/underworld2/2.8.1b - DIRECTORY I INDICATED IN --PREFIX
- python3 -c 'import underworld'
- get error:  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'underworld'

**Comment by jmansour** [comment]
What are the contents of `/cm/shared/apps/underworld2/2.8.1b`?

**Comment by jmansour** [comment]
Ok, no idea why the Python files are not being installed.  

Can you repeat the configure/compile/install steps capturing the standard output & error, and upload it here?

**Comment by whositwhatnow** [comment]
Closing this as rebuild worked
