### ISSUE TITLE
Container Security Hardening

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#427]
In light of the recent security incident (#424), it's important that we review our container security practises.  Measures we should consider include:

1. Jupyter token authentication. Currently we've disabled this, in particular because for Kitematic users it is not obvious how to obtain the required token. However, docker by default will allow connections from all incoming ip addresses.  Generally a properly configured firewall will prevent external connections, but within a local area network connections may be less restrictive.  Therefore, anyone on the same LAN might scan for the open port, and then connect to the Jupyter instance, from which point they can launch anything they desire within the container (but not on the host).  This is possibly the mechanism by which cryptomining binaries were executed in #424.  Enabling the token will mean that only the person who launched the Jupyter instance will have the required credentials (the token) to access Jupyter.  Potentially, as a middle ground, we may like to introduce a baked in token, while recommending users set their own. The former, while providing convenience, would also be a vulnerability if somebody was aware of the container runtime which generated the Jupyter environment (as they could then determine the token).
2. Recommend users only allow connection from localhost.  This will explicitly prevent external connections, but relies on users being careful. So:
```bash
# this
docker run -p 127.0.0.1:8888:8888 --rm underworldcode/underworld2
# not this
docker run -p 8888:8888 --rm underworldcode/underworld2
```
3. Jupyter port obfuscation. Potentially switching to a non-standard port will help hide the connection possibility from malicious players.  Similarly we can let docker decide by using the following
```bash
docker run -p :8888 --rm underworldcode/underworld2
```
4. Container package minimisation.  We should remove all unnecessary tools (wget,curl,etc) to minimise potential container vulnerabilities.  Similarly, switching to multi-stage builds will help us minimise unnecessary packages.  This will also help keep image size down.
5. Scan for vulnerabilities. As part of our release process, we should scan final images to check for and asses any vulnerabilities. Tools like [anchore](https://anchore.com/) or [clair](https://github.com/coreos/clair) can be used.  
6. Update previous images. We should provide regular updates for previous UW versions. Perhaps for the last 3 major releases. This may prove difficult if some of the underlying libraries updates introduce breaking API changes. Updated images should replace previous images (tag wise), but previous images should be retagged for easy access. 
7. Write a blog post to keep our users abreast of security considerations (updating their docker, updating images, being aware of running processes, etc), and inform them of any changes we're making. 
8. Docker Content Trust. Investigate using DCT, which gives us measures to provides users with image integrity assurance.

**Comment by rbeucher** [comment]
A combination of 2 and 3 is also possible:

`docker run -p 127.0.0.1::8888 --rn underworldcode/underworld2` 

Problem with that is you need to figure out what the port is by doing a `docker ps`... 
The message we get from jupyter saying that the notebook is running at 127.0.0.1:8888 might confuse people.

**Comment by rbeucher** [comment]
I believe that's done @jmansour ?
