### ISSUE TITLE
Authors for joss paper

### ISSUE THREAD

**Issue by gassmoeller** [underworldcode/underworld2#428]
This might have been resolved internally, but just to be sure: In https://github.com/underworldcode/underworld2/blob/joss/docs/joss/paper.md you have the following comment:

```
<!--
TODO:
* add Mirko to authors
-->
```

Has this been resolved, i.e. is the author list of the paper up-to-date?

Related to openjournals/joss-reviews/issues/1797

**Comment by jmansour** [comment]
I've just waiting on Mirko to generate an ORCID, which hopefully should happen shortly. Thanks.

**Comment by jmansour** [comment]
Authorship finalised. 

openjournals/joss-reviews/issues/1797

Thanks @gassmoeller.
