### ISSUE TITLE
Function improvements

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#44]
- cache results for faster evaluation #11 
- clean up c++ interface where possible.. hopefully remove these double assignments https://github.com/underworldcode/underworld2/blob/development/libUnderworld/Underworld/Rheology/src/ConstitutiveMatrixCartesian.cpp#L268
  (possible set a 'parentFunctionIO' on the ParticleInCellCoordinate, which then gets 'index' from it's parent IO object).
- get rid of smart pointers for base function evaluations
- do evaluations in batch

**Comment by jmansour** [comment]
also #73.  Would like to leverage eigen3 for linear algebra.  Possibly it could also be useful for the batch evaluation.

**Comment by lmoresi** [comment]
Why not petsc or one of its dependencies for linear algebra ?  Or is eigen3 already there because of petsc ?

**Comment by jmansour** [comment]
We're really talking about small arrays & vectors. Eigen3 provides a very high level interface which should allow us to outsource the difficulty of constructing arbitrary functions (scalar*scalar, scalar*vec, vec*vec, vec*mat, mat*mat, etc).  Ie, these operations should be largely identical from our coding perspective.  This would not be the case with petsc.   Also, eigen3 is trivial to bundle with our code, as it is only a set of header files and does not required compilation itself. 

http://eigen.tuxfamily.org/dox/group__TutorialMatrixArithmetic.html

Anyhow, more investigation is required.

**Comment by jmansour** [comment]
Closing this as not relevant for uw3.
