### ISSUE TITLE
Question regarding fn.branching.conditional

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#441]
Hi All,

Is it possible to use fn.branching.conditional for set of conditions such as,

if:
elif:
elif:
else

total_rheology = fn.branching.conditional([((temperatureField <= T_LAB) & (fn.input()[1] > some_value), viscoelasticity),
(True, viscous_rheology)])

if so can you post an example?

Thank you
Pras

**Comment by lmoresi** [comment]
You might find it helpful to think of this more like a switch statement - though without the C style drop-through.

Prof Louis Moresi

louis.moresi@anu.edu.au

(m) +61 4 0333 1413

(us) +1 505 349 4425

www.moresi.info<http://www.moresi.info/>

www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

@LouisMoresi<https://twitter.com/LouisMoresi>

On 22 Nov 2019, 18:11 +1100, Prasanna2989 <notifications@github.com>, wrote:

Hi All,

Is it possible to use fn.branching.conditional for set of conditions such as,

if:
elif:
elif:
else

total_rheology = fn.branching.conditional([((temperatureField <= T_LAB) & (fn.input()[1] > some_value), viscoelasticity),
(True, viscous_rheology)])

if so can you post an example?

Thank you
Pras

**Comment by Prasanna2989** [comment]
Thank you.

Pras
