### ISSUE TITLE
Pressure noise on the boundary

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#443]
Hi, Underworld developers:
I am a new user of underworld, and recently I am trying to run a model of continent collision. Velocity boundary conditions are applied on the left and right walls from the bottom of the sticky air layer down to the top of the asthenosphere. Neumann boundary is set at the base of the model to keep isostatically balance. Top boundary is free.
Here is part of my codes of boundary conditions:
![1575900675(1)](https://user-images.githubusercontent.com/50648269/70442245-e5d9d700-1ad0-11ea-923a-173b94a1280d.png)
But after solving it for only one time, there is pressure noise at the bottom of the air layer along the vertical walls. When setting uniform viscosity and density on different layers, the pressure field sill goes wrong. I wonder what causes the pressure noise and how to solve it. 
Thanks a lot.

**Comment by alexstruc** [comment]
Here is the solved pressure field figure:
![image](https://user-images.githubusercontent.com/50648269/70443862-e3c54780-1ad3-11ea-96ae-5e71ee920b69.png)

**Comment by alexstruc** [comment]
After running for several steps, the pressure field goes right.

**Comment by jmansour** [comment]
Ok, thanks for reporting back.  Let us know if you encounter further issues.
