### ISSUE TITLE
How to make a convergence file?

### ISSUE THREAD

**Issue by lulu2019uw2** [underworldcode/underworld2#444]
Hi UW2 team,
        I use Underworld2 via Docker on my personal computer. I know the convergence process of solving equations is  usually printed on  the Kitematic monitor. 
        Because I would like to check how the residual changes at every timestep, I am wondering if you could please provide any idea about how to make/save a convergence file. 
        Thank for your help.
Best,
lulu

**Comment by jmansour** [comment]
Hi @lulu2019uw2 

We don't currently capture any information about the solver residuals in the Python interface unfortunately.  You might like to look at  `solver.get_stats()` and `solver.print_stats()` however which return information about iteration counts and solve times.  Here's an example of usage:

https://github.com/underworldcode/underworld2/blob/master/docs/test/solver_1.py

**Comment by lulu2019uw2** [comment]
Thanks for your reply. @jmansour
