### ISSUE TITLE
How to apply a weaker rheolgy for swarm particles based on particle Index and and particle location?

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#447]
Hi All,

I have a struggling point while implementing a weaker rheology for particles above melting locations. I will explain it here as much clearly as I can and please feel free to ask for further details.

I have a swarm variable 'Mext' and I am extracting the particular coordinates of the swarm in each time step to an array (meltCoords) based on the value of the Mext. The meltcoords array is updated in each time step.

```
b1 = (Mext.data > 0.0)
meltIndex = np.where(b1)[0]
meltCoords = swarm.particleCoordinates.data[swarmIndex]
```

Now, I want identify all the swarm particles above the meltCoords in a columnwise as shown in the figure of the the attachment and want to apply a weak viscosity value in those particles. I am trying to use a mechanism like follows for this implementation.

```
meltCoords = np.array([ [1.0,0.5], [2.0,0.4],[3.0,0.6]])
dx = 0.2

coord = fn.input()
#condition  = fn.coord()[0]>meltcord(x) & fn.coord()[1]> (meltcord(y)-dy) & fn.coord()[1]< (meltcord(y)+dy)
condition1 = ((coord[1]>swarmCoords[:,1][0]) & (coord[0]> (swarmCoords[:,0][0]-dx)) & (coord[0]<(swarmCoords[:,0][0]+dx)))
condition2 = ((coord[1]>swarmCoords[:,1][1]) & (coord[0]> (swarmCoords[:,0][1]-dx)) & (coord[0]<(swarmCoords[:,0][1]+dx)))
condition3 = ((coord[1]>swarmCoords[:,1][2]) & (coord[0]> (swarmCoords[:,0][2]-dx)) & (coord[0]<(swarmCoords[:,0][2]+dx)))

condition_Weak  = condition1 | condition2 | condition3
fn_conditional = fn.branching.conditional( [ (condition_Weak, tauY_ductile_Weaken_melt), (True, tauY_ductile ) ])
```
When I have 5 cordinates in meltcoords array, there will be 5 conditions. 
On the other-hand, I have a materialIndex swarm variable seperately where I am mapping my viscosity values. So, I need to check my material type and then whether the particle is in the blue column to assign the viscosity. 

```
viscosity_Y_M = fn_conditional/(2.*(strainRate_2ndInvariant+1.0e-18))
creep_Arr = fn.exception.SafeMaths( fn.misc.min(viscosity_Y_M, creep_Arr) )
viscosityMap = { MantleIndex : creep_Arr,  
                 wetbasaltIndex : creep_Arr,  
                 drybasaltIndex : creep_Arr}

viscosityFn = fn.branching.map( fn_key = materialVariable, mapping = viscosityMap )

```

For the above code segment this model works fine. But, I need to update meltCoords and conditions in each time step. Will you be able to give some help on this. Please find the attachment for more details and please feel free to ask for further clarifications.

Thanks in advance
Pras

[Required_implementation_details.pptx](https://github.com/underworldcode/underworld2/files/3992009/Required_implementation_details.pptx)

**Comment by jmansour** [comment]
Hi @Prasanna2989.  

It's prob best if we sit together and work through what you need here.  Shoot me an email and we can work out a time at Monash.

**Comment by Prasanna2989** [comment]
Thanks John. I will send an email.

Pras

**Comment by julesghub** [comment]
I believe this is resolved, feel free to reopen if needed or send an email to @jmansour
