### ISSUE TITLE
use xshell from windows to log in docker uw on a Ubuntu machine

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#449]
Hi all,

Not sure if it is appropriate to post this here.
Often, it is convenient for me if I can use my windows laptop to open the docker underworld on my Ubuntu desktop.
I know this is possible for Jupyter installed on Ubuntu, as described in the link,
https://janakiev.com/blog/jupyter-notebook-server/
But not sure if you have any way to extend this to the docker image of UW?
Thanks a lot.

**Comment by jmansour** [comment]
So, perhaps, you want to run docker on your Ubuntu machine, but access the Jupyter instance via your Windows machine?  

If the required ports are open, can you not just log into the Ubuntu machine to start the container, and then point your browser to your Ubuntu machine IP:PORT? 

If there is difficulties with having the required ports open, perhaps you can use an SSH tunnelling approach.

**Comment by tingyang2004** [comment]
Thanks John! That is smart.

**Comment by jmansour** [comment]
Ok, great!  I'll close this, but reopen if necessary.
