### ISSUE TITLE
Underworld no longer exits cleanly after MPI_Finalize

### ISSUE THREAD

**Issue by OKaluza** [underworldcode/underworld2#45]
Whenever I run a job it aborts at the end with the message below, not causing any real issue but should probably be cleaned up

*** The MPI_Comm_create_keyval() function was called after MPI_FINALIZE was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.

**Comment by RebeccaFarrington** [comment]
Hey @OKaluza , can you send through an example to test?

**Comment by OKaluza** [comment]
It's not really important as everything works but this happens right at the end of the job (on Linux, Kubuntu 15.10 here) whenever I run a model, eg:
cd underworld2/doc/test
python image_tests.py

**Comment by julesghub** [comment]
@OKaluza i can't reproduce this behaviour on ubuntu 15.04 or os x el capitan.
Is it still an issue for you?

**Comment by lmoresi** [comment]
I saw this on raijin !

Sent from my iPhone

On 28 Apr 2016, at 18:39, julesghub <notifications@github.com<mailto:notifications@github.com>> wrote:


@OKaluza<https://github.com/OKaluza> i can't reproduce this behaviour on ubuntu 15.04 or os x el capitan.
Is it still an issue for you?

**Comment by julesghub** [comment]
for which model, the image_test.py?

**Comment by OKaluza** [comment]
@julesghub I am now running Kubuntu 16.04 and the problem has gone away here.

**Comment by jmansour** [comment]
Nobody has noticed this in a while, so we'll close it for now.  Feel free to reopen if still an issue.
