### ISSUE TITLE
Implementing the dislocation creep viscosity for mantle convection.

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#452]
Hi All,

Can someone point me to a dislocation creep rheology implementation example in Underworld2 or suggest a method to implement it. I have diffusion creep implementation which goes like eta0*exp((E/(T+1))-(E/2) being E = 23.03. I need a similar format for dislocation creep. Any suggestion will be much appreciated.

cheers
Pras

**Comment by jmansour** [comment]
Hi @Prasanna2989 

What is the difficulty here?  Is there a particular form of the dislocation creep rheology you wish to model?

**Comment by lmoresi** [comment]
I presume it’s the non-linearity that is making things confusing but 1) underworld will detect that non linearity and flag the need to select non-linear options and 2) there are examples of non-linear rheology available … over to you JM
On 14 Mar 2020, 6:40 AM +1100, John Mansour <notifications@github.com>, wrote:

Hi @Prasanna2989<https://github.com/Prasanna2989>

What is the difficulty here? Is there a particular form of the dislocation creep rheology you wish to model?

**Comment by julesghub** [comment]
Closing this ticket. Feel free to reopen if needed.
