### ISSUE TITLE
LavaVu Run error: Failed to open X display

### ISSUE THREAD

**Issue by sunningzh** [underworldcode/underworld2#454]
Hi All,

I installed uw2.8.2b on a remote server (Ubuntu 18.04) successfully. Then I run the jupyter notebook on the remote server and link it to my personal computer.

```
import glucifer
fig = glucifer.Figure(figsize=(800,400))
fig.append( glucifer.objects.Surface(mesh, temperatureField, colours="blue white red") )
fig.append( glucifer.objects.Mesh(mesh) )
fig.show()
```

But the figure can't be displayed in the jupyter notebook and a error appears:
`LavaVu Run error: Failed to open X display`

I also try to save the figure:
`fig.save()`

but the error still appears.

I think it's because that my remote server has no GUI-desktop. However, I want to know if there is a way to run the uw2.8.2b on a remote server and display the figure in the jupyter notebook on my personal computer.

Thank you!

**Comment by jmansour** [comment]
Hi @sunningzh

I think the way to do this is to use `xvfb`.  You will need to ensure `xvfb` and `pyvirtualdisplay` are installed.  You will also need to set the `GLUCIFER_USE_XVFB` environment variable (note that for versions 2.9+, you should instead use `UW_USE_XVFB`).  You can set the variable directly from Python but it must be set before import `glucifer`. 

```python
import os
os.environ["GLUCIFER_USE_XVFB"]="1"
import glucifer
```

**Comment by sunningzh** [comment]
It works! Thanks for your response. 
I'll close the issue.

**Comment by jmansour** [comment]
Ok, glad to hear!  Thanks for reporting back.
