### ISSUE TITLE
infinite velocity (?) for a simple thermochemical convection

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#457]
Hi all,

I met the following RuntimeError issue after 100 step in my simple thermochemical convection model.
The model has two materials with different viscosity and densities. The viscosity depends only on depth and composition. This issue disappears if I increase or reduce the viscosity contrast between different compositions.

![image](https://user-images.githubusercontent.com/26615840/75524103-344f9f80-5a48-11ea-8b3d-d5be7adbe84b.png)
![image](https://user-images.githubusercontent.com/26615840/75524192-606b2080-5a48-11ea-89e3-e47ad6add127.png)

It seems the stokes solver gave very large velocity? Please give me your suggestions or comments and let me know if you want more information, thanks.

Best regards,
Ting

**Comment by tingyang2004** [comment]
The temperature , velocity, and compositional fields look fine to me just one step before the collapse.
![image](https://user-images.githubusercontent.com/26615840/75525081-226efc00-5a4a-11ea-9473-4fb7fdb4bedd.png)
![image](https://user-images.githubusercontent.com/26615840/75525099-2d299100-5a4a-11ea-8e27-04fe17e312fc.png)

**Comment by jmansour** [comment]
Are there non-linearities?

**Comment by tingyang2004** [comment]
Thanks John, only linear viscosity is used.

**Comment by jmansour** [comment]
And if you restart from the previous (successful) timestep, do you get the
same result?

**Comment by tingyang2004** [comment]
I do not have restart in the script, but I can repeat the result when I rerun the script from zero_th step.

I think this is not related, but in case it helps, I used periodic boundary condition for the side walls. And in each step, I manually remove the horizontal average velocity as below:

velocityField.data[:,0]=velocityField.data[:,0]-int_Momentum.evaluate()[0]/int_density.evaluate()[0]
where 
int_Momentum is the multiply of velocity and density.

**Comment by tingyang2004** [comment]
The .py script is attached below. It takes only several minutes on one cpu to repeat the issue.
[LLSVPsEvolutionCase1.py.txt](https://github.com/underworldcode/underworld2/files/4273574/LLSVPsEvolutionCase1.py.txt)

**Comment by jmansour** [comment]
Hi @tingyang2004 

I'm unable to run your model as it's missing a file.   Can you put it up at the community repos github?  Follow this template:
https://github.com/underworld-community/template-project

**Comment by tingyang2004** [comment]
Hi John,

Thanks a lot. I can log onto the repo template, but have difficulty do much performance. Not sure it's due to the firewall or anything else. But the file needed is attached below (sorry that I forgot to attach the file). Just download it and change the corresponding file path and name in the line T1D=np.loadtxt(ICFilePath+'InitialTemperatureProfile.dat') 
to the uploaded file should work.

[InitialTemperatureProfile.dat.txt](https://github.com/underworldcode/underworld2/files/4332351/InitialTemperatureProfile.dat.txt)

Best regards,
Ting

**Comment by tingyang2004** [comment]
I have solved this issue. It is associated with some specific bcs.
