### ISSUE TITLE
Strong mantle convection when modeling continental subduction.

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#460]
Hi all,
I am simulating the subduction between two continents in a 2-D model which contains 351 * 151 nodes corresponding to the size of  2000 * 680Km. The model configuration is shown in the figure.
![image](https://user-images.githubusercontent.com/50648269/76943118-cbb65d00-6939-11ea-80c4-9f77dc5650cb.png)

I set free slip conditions on all the boundaries and set a constant compressional rate of 2.5 cm/yr inside both continents. Viscoplastic rheology is employed in my model. Viscosity rheology includes both diffusion and dislocation creep. when running the model, I find that the intensity of mantle convection keeps increasing and the mantle speed gradually becomes faster than the initial speed of the continents. Here is the result of viscosity and speed after running for 1300 steps (6.5Myr). 
![image](https://user-images.githubusercontent.com/50648269/76942768-3d41db80-6939-11ea-8404-daa0449b72b5.png)

Such result really makes me confused and  I am not sure whether it is correct because some similar researches always show the result of moderate mantle speed. Please give me your comments and feel free to ask me for more details if you want. Thanks.
Best regards,
Alex

**Comment by jmansour** [comment]
Hi Alex

Free-slip conditions every can be problematic at times, as there can be little to _anchor_ the velocity. 
Can you re-run your model but setting the bottom boundary to be no-slip to see if the results seem more reasonable?

**Comment by alexstruc** [comment]
Thank you. I will try it and show you the result later.

**Comment by alexstruc** [comment]
Hi jmansour,
I followed you suggestion to set a no-slip condition on the bottom boundary. But the result still becomes unreasonable as the steps increase. This is the velocity field of 0.1Myr and 7Myr respectively. In this experiment, I only set the initial velocity inside the left continent.
![image](https://user-images.githubusercontent.com/50648269/77134665-fd970300-6aa2-11ea-9409-34df5d01f902.png)

![image](https://user-images.githubusercontent.com/50648269/77134199-efe07e00-6aa0-11ea-8f26-8c1b9acdf859.png)
It seems that the boundary condition is not the reason for the overly large velocity of the mantle. 
Do you have any other suggestions about the possible reasons of this issue.
Thank you in advance.
Alex

**Comment by RebeccaFarrington** [comment]
Hi,
Have you checked the viscosity/deformation mechanism of the material with large velocity?
Perhaps the strain rate is localising in an unexpected location.
Cheers,

**Comment by jmansour** [comment]
Also, what does your viscosity field look like?

**Comment by alexstruc** [comment]
Thanks for your suggestions. I checked the relevant viscosity field of 7Myr. The result is in the figure.
![image](https://user-images.githubusercontent.com/50648269/77141038-79e71180-6ab6-11ea-8457-1c45a6ec97ea.png)

The area with large mantle velocity has relatively low viscosity. And there is actually a localization of strain rate near the left boundary. 

![image](https://user-images.githubusercontent.com/50648269/77144692-86249c00-6ac1-11ea-99f1-4342467dfab9.png)

Because I set the initial velocity a little away from the left boundary, a passive rift is pulled apart, causing the upwelling of the mantle. But how could in a passive rift the upwelling velocity be much faster than the pulling velocity. That is why I am so confused.

I also check my initial viscosity field which is calculated by setting strain rate as 1e-19. It shows in the following picture and the values of the color bar correspond to1e19 and 1e25.
![image](https://user-images.githubusercontent.com/50648269/77145937-c89ba800-6ac4-11ea-8757-eae28a70390e.png)

Is there any issue of my viscosity field? Hope to receive your further suggestions. If you need more details, let me know.
thanks a lot.

**Comment by bknight1** [comment]
Hi @alexstruc 

I had a similar issue in my models. I imposed a boundary velocity across the lithosphere, with the issue arising by the velocity condition suddenly changing to 0 below the lithosphere, causing the mantle to flow upwards. For my models, I decreased the velocity linearly below the lithosphere toward 0 at a chosen depth. 

The issue was caused by the non-linear viscous rheology. If you wanted to keep the same setup, you could try having the mantle as a newtonian rheology/constant viscosity as then the deformation becomes rate independent, which should stop the strain rate localisation (and high velocities) near the boundary.

**Comment by alexstruc** [comment]
Hi @bknight1 

I really appreciate your suggestion. I will try it . I also get some reasonable results by decreasing the temperature to 1300° at the boundary between lithosphere and asthenosphere. And the bottom condition is set to no-slip.
