### ISSUE TITLE
Mixed boundary condition

### ISSUE THREAD

**Issue by Yidali26** [underworldcode/underworld2#464]
Hi there,
The Underworld code have both Dirichlet and Neuuman boundary conditions. Is it possible to have the mixed boundary condition in the model? I ask so because in some paper people used sort of mixed boundary condition as a so-called permeable boundary, for example ΔL*dVy/dy+Vy=0 at y=0 for a permeable boundary condition at y=0. This kind of boundary condition has been implemented in some finite difference codes, and can I implement similar things in underworld?
Thanks in advance

**Comment by jmansour** [comment]
There is no direct way to do this, but you could treat it like any other non-linearity and iterate about the solution.

We don't observe any potential non-linearities for the BCs (I believe), but you can still manually ask the solve to iterate by setting `nonLinearIterate=True`.  So you'll set the Neumann BC using the required form, and *not* set any Dirichlet BC, and then solve. 

Whether it converges fast enough (or at all), I'm not sure, and you'll have to report back to us.

**Comment by Yidali26** [comment]
> There is no direct way to do this, but you could treat it like any other non-linearity and iterate about the solution.
> 
> We don't observe any potential non-linearities for the BCs (I believe), but you can still manually ask the solve to iterate by setting `nonLinearIterate=True`. So you'll set the Neumann BC using the required form, and _not_ set any Dirichlet BC, and then solve.
> 
> Whether it converges fast enough (or at all), I'm not sure, and you'll have to report back to us.

Thanks, I'll try this way, but presumably it's not easy to converge.

**Comment by Yidali26** [comment]
Hi @jmansour,
I tried the method you recommended with a very simple 2D case:
A descending ball in the center of box. Top and side are free slip boundaries and bottom is "permeable" boundary, like below.
![swarm](https://user-images.githubusercontent.com/48190414/78112023-7440d400-73b2-11ea-86aa-06fc6729e58b.png)
The way I configure permeable boundary is to set it as the Dirichlet boundary, and force Vv=-ΔL*d(Vy)/dy. Here ΔL=0.2. However the nonLinearIterate=True doesn't work, so I manually update the function at the boundary and run the solver. I'm not sure if there are some sophisticate algorithm for non-Linear iteration between each individual linear loop, but here I just repeatedly call   the solver function manually to test the stability and convergence. Here is the result:
![1](https://user-images.githubusercontent.com/48190414/78112861-aef73c00-73b3-11ea-9570-a0e18d5586fe.png)
![3](https://user-images.githubusercontent.com/48190414/78112871-b28ac300-73b3-11ea-9eb0-1f884fb2c4c4.png)
![5](https://user-images.githubusercontent.com/48190414/78112877-b4ed1d00-73b3-11ea-8dbb-84b22c660a31.png)
As the iteration goes on, the velocity at bottom boundary tends to blow up. It seems this method cannot guarantee a convergence.

**Comment by Yidali26** [comment]
In addition to the Dirichlet boundary, an alternative way might be the Neumann boundary, but the Neumann boundary require an explicit expression of Vv=-ΔL*d(Vy)/dy in terms of traction (or stress). However it seems like we cannot find an equivalent expression using the stress. Actually I got some result looks weird that this boundary condition requires the Vy at the boundary to be a sin function.
![image](https://user-images.githubusercontent.com/48190414/78113713-fa5e1a00-73b4-11ea-8e4d-172f038c332c.png)
In the final result, the Vy is a function of three unknown A, φ and C, which seem to be dependent on the whole system and thereby cannot be expressed independently, and σyy=2ηdVy/dy-P is a function of Vy is unable to be write down before calculating the whole system as well.

**Comment by Yidali26** [comment]
The reason why we what such kind of configuration is because some folks using the finite difference codes used such a boundary as the bottom boundary condition in some subduction studies. Sometimes the finite element codes cannot reproduce some important results(like spontaneous subduction initiation), and we suspect it is because of such a boundary condition which cannot be configured in finite element code.

**Comment by jmansour** [comment]
I think you can construct this using the Neumann term instead.  You'll be setting the normal stress along the bottom boundary (vector n=(0,-1), and therefore a lot of terms will drop out.  In the end, you'll set something like h_y= -(2/ΔL)V_y -P, but I'd suggest you work through this and confirm. 

The `nonLinearIterate=True` parameter should work in this instance, but there's no guarantee of improved convergence behaviour.

**Comment by Yidali26** [comment]
Hi @jmansour ,
I followed your instruction to use the Neumann boundary condition. Here the sigma_11=-2eta/deltaL*Vy-P and traction is -sigma_11. The code see below:
import underworld as uw
from underworld import function as fn
import glucifer
import numpy as np
import math
import os
uw.matplotlib_inline()
import matplotlib
from scipy.optimize import fsolve
import matplotlib.pyplot as plt
from time import time as timer

reference_length = 700000.

elementType = "Q1/dQ0"
resX = 128
resZ = 64
maxX = 3.
maxZ = 1.

mesh = uw.mesh.FeMesh_Cartesian( elementType = (elementType), 
                                 elementRes  = (resX, resZ), 
                                 minCoord    = (0., 0.), 
                                 maxCoord    = (maxX, maxZ),
                                 periodic    = [False, False]  ) 

velocityField    = mesh.add_variable(         nodeDofCount=mesh.dim )
pressureField    = mesh.subMesh.add_variable( nodeDofCount=1 )
velocityField.data[:] = [0., 0.]
pressureField.data[:] = 0.

gravity = 10. #m*s^-2
reference_conductivity = 3.0
reference_thermal_capacivity = 1200.
reference_density = 3300.
reference_expansivity = 3e-5
reference_diffusivity = reference_conductivity/(reference_thermal_capacivity*reference_density)
reference_viscosity = 1e18

rho_mantle = 1.
rho_air = 0.

Rb = (reference_density*gravity*pow(reference_length,3))/(reference_diffusivity*reference_viscosity)

swarm         = uw.swarm.Swarm(mesh, particleEscape=True)
swarmLayout   = uw.swarm.layouts.PerCellSpaceFillerLayout( swarm=swarm,particlesPerCell=36 )
pop_control = uw.swarm.PopulationControl(swarm, aggressive=True, particlesPerCell=36)
swarm.populate_using_layout( layout=swarmLayout )
materialIndex  = swarm.add_variable( dataType="int",    count=1 )

previousStress         = swarm.add_variable( dataType="double", count=3 )
previousStress.data[:] = [0., 0., 0.]
dStress         = swarm.add_variable( dataType="double", count=3 )
dStress.data[:] = [0., 0., 0.]

advector        = uw.systems.SwarmAdvector( swarm=swarm,            velocityField=velocityField, order=2 )


mantle = 0
plume = 1
for index in range( len(materialIndex.data)):
    if (swarm.particleCoordinates.data[index][1]-0.5*maxZ)**2+(swarm.particleCoordinates.data[index][0]-0.5*maxX)**2<0.01:
        materialIndex.data[index] = plume
    else:
        materialIndex.data[index] = mantle

densityMap  = {mantle:rho_mantle, plume:1.1*rho_mantle}
densityFn   = fn.branching.map( fn_key= materialIndex, mapping = densityMap)

viscMap  = {mantle:1e3, plume:1e3}
viscFn   = fn.branching.map( fn_key= materialIndex, mapping = viscMap)

strainRate = fn.tensor.symmetric( velocityField.fn_gradient )

iWalls = mesh.specialSets["MinI_VertexSet"] + mesh.specialSets["MaxI_VertexSet"]
jWalls = mesh.specialSets["MinJ_VertexSet"] + mesh.specialSets["MaxJ_VertexSet"]
botWall = mesh.specialSets["MinJ_VertexSet"]
topWall = mesh.specialSets["MaxJ_VertexSet"]


v1_grad=-2e3*(velocityField[1]+fn.misc.constant(0.))/(0.2*maxZ)-pressureField
appliedTractionField = uw.mesh.MeshVariable( mesh=mesh,    nodeDofCount=2 )
appliedTractionField = (0.0,-v1_grad)
Neu_BC = uw.conditions.NeumannCondition( fn_flux=appliedTractionField, 
                                      variable=velocityField,
                                      indexSetsPerDof=(None, botWall) )
Dir_BC = uw.conditions.DirichletCondition( variable      = velocityField, 
                                          indexSetsPerDof = (iWalls, topWall) )
'''

bot_vfn = -(strainRate[1]+fn.misc.constant(0.))*0.2*maxZ
velocityField.data[mesh.specialSets["MinJ_VertexSet"],1] = bot_vfn.evaluate(mesh)[mesh.specialSets["MinJ_VertexSet"],0]
Dir_BC = uw.conditions.DirichletCondition( variable      = velocityField, 
                                          indexSetsPerDof = (iWalls, jWalls) )
'''
z_hat = ( 0.0, 1.0 )

# Create buoyancy force vector
buoyancyFn = - Rb*densityFn * z_hat

stokes = uw.systems.Stokes( velocityField = velocityField, 
                               pressureField = pressureField,
                               voronoi_swarm = swarm, 
                               conditions    = [Dir_BC,Neu_BC],
                               fn_viscosity  = viscFn,
                               fn_bodyforce  = buoyancyFn
                          )

solver = uw.systems.Solver( stokes )

solver.set_inner_method(solve_type='lu')
solver.solve(nonLinearIterate=True)

**Comment by Yidali26** [comment]
But it seems that the nonLinear solver haven't been activated in here, also I checked that at the bottom boundary the dV_y/dy+Vy/deltaL is not zero. I repeated manually run the solver.solve(nonLinearIterate=True)
and report the residual=||dV_y/dy+Vy/deltaL||, and the residual become larger and larger.

**Comment by NengLu** [comment]
> But it seems that the nonLinear solver haven't been activated in here, also I checked that at the bottom boundary the dV_y/dy+Vy/deltaL is not zero. I manually repeated running the solver.solve(nonLinearIterate=True)
> and report the residual=||dV_y/dy+Vy/deltaL||, and the residual become larger and larger.

Hi Yida,
Have you made some progress on this problem? Recently I run into the same problems as trying to use similar boundary conditions (the infinity-like bc) in the model.

**Comment by Yidali26** [comment]
> > But it seems that the nonLinear solver haven't been activated in here, also I checked that at the bottom boundary the dV_y/dy+Vy/deltaL is not zero. I manually repeated running the solver.solve(nonLinearIterate=True)
> > and report the residual=||dV_y/dy+Vy/deltaL||, and the residual become larger and larger.
> 
> Hi Yida,
> Have you made some progress on this problem? Recently I run into the same problems as trying to use similar boundary conditions (the infinity-like bc) in the model.

Hi Neng,
I don't have any update on this issue, but I'd like to keep an eye on it. 
Could you please keep me updated if any progress?
Thanks

**Comment by NengLu** [comment]
> > > But it seems that the nonLinear solver haven't been activated in here, also I checked that at the bottom boundary the dV_y/dy+Vy/deltaL is not zero. I manually repeated running the solver.solve(nonLinearIterate=True)
> > > and report the residual=||dV_y/dy+Vy/deltaL||, and the residual become larger and larger.
> > 
> > 
> > Hi Yida,
> > Have you made some progress on this problem? Recently I run into the same problems as trying to use similar boundary conditions (the infinity-like bc) in the model.
> 
> Hi Neng,
> I don't have any update on this issue, but I'd like to keep an eye on it.
> Could you please keep me updated if any progress?
> Thanks

Sure, thank you for your reply.

**Comment by jmansour** [comment]
I'll close this ticket due to inactivity. Feel free to reopen.

**Comment by tingyang2004** [comment]
> 

Nice deduction, but there seems to have some flaws in it.
1. the multiplier to delta_ui should be eta instead of 2*eta in the momentum equations.
2. boundary condition 5 is different from shear stress-free condition, but this is fine is you or Taras have the implicit assumption that dvy/dvx << dvx_dvy.
3. boundary condition 5 does not give d2vy/dy2 = 0.

I guess since dL is usually large, the boundary condition (dvy/dy = -vy/dL) should be well approximated by dvy/dy = 0, i.e., the vertical traction is sigma_yy = -P, especially considering the discretization error in calculating velocity gradient and stress.
