### ISSUE TITLE
"Segmentation fault" Error 

### ISSUE THREAD

**Issue by btokay** [underworldcode/underworld2#465]
Hi All,

After I completed all steps of the installation of underworld on Gadi, no problem was seen at the end of build and install. But when I wanted to check if underworld works, I got an error attached: [error_gadi.txt](https://github.com/underworldcode/underworld2/files/4384077/error_gadi.txt)
Do you have any idea about the probable reason of this error? 

Cheers,

Bülent

**Comment by julesghub** [comment]
Closing this issue for now, I believe it's resolved now. Feel free to reopen if needed.
