### ISSUE TITLE
Stampede2 Singularity image & instructions update

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#466]
* Usage instructions could be improved in parts, especially reminding users to reload singularity module after purge. 
* Update for latest singularity on stampede2, and confirm where `sif` files are now written to. 
* Create a new psm2 image.

**Comment by rbeucher** [comment]
Any chance this would work on gadi?

**Comment by jmansour** [comment]
I won't action this as we don't seem to have any users on Stampede2 at this stage.
