### ISSUE TITLE
It is showing 'underworld' has no attribute 'mesh

### ISSUE THREAD

**Issue by PULAK1998** [underworldcode/underworld2#471]
I don't know whether underworld package has installed properly or not. I tried to install it using pip3. In order to check it I tried to run  A quick demo code given in the underworld documentation where it showed after run that: 

>  Traceback (most recent call last):
>      File "plk.py", line 4, in <module>
>      mesh = uw.mesh.FeMesh_Cartesian( elementRes  = (8, 8),
>  AttributeError: module 'underworld' has no attribute 'mesh'

**Comment by jmansour** [comment]
Hi Pulak

It certainly looks like something is missing.  

Can you uninstall underworld, and then reinstall using `pip install -vvv underworld`, and report the output here?

**Comment by PULAK1998** [comment]
Thank for your response @jmansour.
I tried `pip install -vvv underworld` and it runs properly. But at the end it showed 

> InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-RBbiHU/underworld/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cjncsd-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-RBbiHU/underworld/

Also `python3 -c 'import underworld'` shows error now i.e.,`ModuleNotFoundError: No module named 'underworld'
`

**Comment by PULAK1998** [comment]
Thank you @jmansour.
I had some missing files, after installing those files `pip3 install -vvv underworld` has worked very properly.

**Comment by jmansour** [comment]
Ok, glad to hear you've progressed.  I'll close this ticket.
