### ISSUE TITLE
Value overflow issue

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#472]
Hi, all

I met an issue of value overflow after running my model, which simply simulated the process of continental subduction, for around 16Myr. 

![image](https://user-images.githubusercontent.com/50648269/78968744-e98d7100-7b37-11ea-841e-e805d9957fbb.png)

After checking all the results, I found the issue seemed to be caused by the unreasonable temperature field. At the last step before the issue, everything including temperature went well.  However, at the issue step, there was a sharp change of the temperature field whose lowest value dropped to -380℃ from 25℃, although I had set 25℃ as the smallest temperature value by (fn.misc.max(temperatureField, 25/dT)).  It is obvious that all wrong temperature values concentrate in a small point near the subduction zone in the picture of temperature field. 

![image](https://user-images.githubusercontent.com/50648269/78970931-07110980-7b3d-11ea-9a86-3e55cf3b54c8.png)

I do not know about the reason for the wrong temperature calculation, and I hope to find a solution.  Please let me know if you need any further clarification about the question. Thanks for your comments  if  you know anything about it.

Best regards.
Alex

**Comment by jmansour** [comment]
Hi Alex

I'd suggest trying a smaller timestep to see if it helps resolve your
issue.  Also, perhaps provide us with some further info:

* Which UW version?
* Which advection diffusion solver?
* Which elements?
* Is your mesh deformed?
* What does your velocity field look like, especially near the anomalous
temperature?

**Comment by alexstruc** [comment]
Hi jmansour

Thanks for your suggestions. In fact, the timestep of my model is 3000 years  and I think it is small enough, so I guess the issue might not be caused by the timestep.

 As for the further information, I'll list them following your questions' order.

1. I established my model based on UW2.

2. After creating the advection diffusion system, I utilized (advDiff.get_max_dt()) to restrict the timestep, then I used (advDiff.integrate(dt)) to integrate the advection diffusion system through time. In addition, a Dirichlet temperature BC was set on the top boundary, but the bottom was open without any restriction. I am not sure whether this is your wanted answer. If it is not, we can have a further discussion.

3. The element type of my model was ('Q1/dQ0').

4. In my model, I created a fixed mesh which had a resolution of [150,80] corresponding to 1200km*320Km. 

5. I checked the velocity field at the step of the issue, and I think it looks good. Here is the picture of the velocity and temperature fields.
![image](https://user-images.githubusercontent.com/50648269/79039932-588dc700-7c17-11ea-9702-f1e2bd89db44.png)

If you have any other suggestions or need further information, please let me know. Thanks in advance.

Alex

**Comment by jmansour** [comment]
As a starting point I'd suggest trying a smaller timestep.  Perhaps `0.5*advDiff.get_max_dt()` or even `0.25*advDiff.get_max_dt()` and see if it makes a difference.  

You are encountering a divide by zero, do you know exactly where this is coming from?  You can wrap your other functions (`yieldingViscosityFn`/`backgroundViscosityFn`/`meltModifierFn()`) in `SafeMaths` to get a better idea. 

You can also define a `fn.exception.CustomException()` which will halt operation for user defined conditions, such as requiring that temp>25deg.

**Comment by alexstruc** [comment]
Thanks you, I will give it a try.
