### ISSUE TITLE
update figure title

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#474]
Hi,

I am checking the temperature field evolution at a sequence of steps.
The related script is as follows:
```
figTemp = glucifer.Figure(figsize=(1000,400),quality=2,title='Temperature at %.2f Myr'%(time))
figTemp.append( glucifer.objects.Surface(mesh, temperatureField,colourBar=True,colours='blue green red') )
figTemp.show()
```

It seems that the title always keeps as it was initially plotted although the variable time changes at each step. I tried to use figTemp.update, but did not get any luck. Any suggestions on how to update the figure title for each step to reflect the increasing time? Thanks a lot.

![image](https://user-images.githubusercontent.com/26615840/79418626-b0497b00-7fe7-11ea-862a-aec60e3043bd.png)

**Comment by RebeccaFarrington** [comment]
Hello,
Should ‘title’ (or time) be a function to be updated each time step?
Cheers,

**Comment by tingyang2004** [comment]
Thanks Rebecca,

Can you explain that more clearly? Not sure if this is what you meant.
I set 
fn_time=fn.misc.constant(1.0)*time
figTemp = glucifer.Figure(figsize=(1000,400),quality=2,title='Temperature at %.2f Myr'%(fn_time.evaluate()))

still it still give the same result.

**Comment by RebeccaFarrington** [comment]
Hi Ting,
I dropped this!
Is it still an issue?

**Comment by tingyang2004** [comment]
Yes, it is.
I have put plotting the figure into an function, so the title can be updated each time by invoking the function. Just wonder if there is any more convinient way.

**Comment by OKaluza** [comment]
If you want to change a figure title just use:

`figure["title"] = 'New title'`

**Comment by tingyang2004** [comment]
Thanks, Owen. 
It works very well.
I'll close the ticket now.
