### ISSUE TITLE
UWGeodynamics problem - Jupyter

### ISSUE THREAD

**Issue by totaibi01** [underworldcode/underworld2#476]
Hello,

When I import UWGeodynamics in jupiter note book I get the following error:

FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/jovyan']

While if I import underworld, it works fine!

Any ideas?

Thamer

**Comment by julesghub** [comment]
Hi Thamer,
How did you attain the code via docker or via pip install?
Which version of the codes are you using?

docker is the easiest way and shouldn't have these permission errors.

**Comment by totaibi01** [comment]
Hi Julian,

I installed it via docker. But it was working very well until two days ago, when I started seeing this error!

**Comment by julesghub** [comment]
It sounds like you've run out of memory in the docker container. Have you been running lots of models? If you clear some results does that help?

Run `docker stats` to see all docker container resource usage.

You can modify docker's resource usage limits. Check this stackoverflow about it. https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container#44533437
The official documentation is https://docs.docker.com/config/containers/resource_constraints/

What version is the docker image, i.e. underworldcode/underworld:2.x.x?

**Comment by totaibi01** [comment]
Hi Julian,

Thanks for your help and support and apologize for delay.

It appears that the file system on the cluster for the Docker container images and overlay filesystems had become full and corrupted. Once the container cleaned, Docker started working correctly again.

Thanks again for help

Thamer

**Comment by julesghub** [comment]
Good to know. I recommend keeping an eye on docker's resource usage periodically to avoid errors like this.

I'll close the ticket for now.
