### ISSUE TITLE
ERROR: Failed building wheel for underworld

### ISSUE THREAD

**Issue by Pulak-Biswas** [underworldcode/underworld2#477]
My system is Ubuntu 20.04. I tried to install underworld as`pip3 install -vvv underworld`
but it did not install.
Screenshots of terminal screen are attached.
Can you help me out this.
![1](https://user-images.githubusercontent.com/50713287/80703939-54abe100-8b01-11ea-8f8d-dafd80b1b21d.png)
![2](https://user-images.githubusercontent.com/50713287/80703943-570e3b00-8b01-11ea-9485-826252d6695e.png)
![3](https://user-images.githubusercontent.com/50713287/80703947-58d7fe80-8b01-11ea-869e-29ef28f4026f.png)
![4](https://user-images.githubusercontent.com/50713287/80703950-59709500-8b01-11ea-88b0-debf2daa36c6.png)

Thanks in advance.

**Comment by arijitlaik** [comment]
Glad you brought this issue up, uw as of now is compataible with python 3.7.x not 3.8, with ubuntu 20.04 and other derivatives 3.8 is the default version, I have tried tweaking the setup dependencies, but they fail work for a bit with compiling certain files and then stop at a certain set of compilation step.

**Comment by rbeucher** [comment]
Yes. It's a python 3.8 pb I believe. Will have to look into that. I have the same issue on Arch.

**Comment by arijitlaik** [comment]
@rbeucher  thanks. Looking forward to it

**Comment by rbeucher** [comment]
What did you do for your petsc install?

**Comment by rbeucher** [comment]
@arijitlaik did you manage to install all the dependencies on Ubuntu 20.20?
swig? petsc?

**Comment by arijitlaik** [comment]
ya all the dependencies were installed, even started compiling, ill attach the logs in a while, petsc,swig mpi and other deps were was installed from the disto package, possibly 3.12, 
[but i had issuess with installing petsc natively on py3.8 with clear linux previously.]

**Comment by arijitlaik** [comment]
underworld2/underworld/libUnderworld/config/packages/Python.py
```python
from config import Package
import os

class Python(Package):

    def gen_locations(self):
        yield ('/usr/local', ['/usr/local/include'], ['/usr/local/lib'])
        yield ('/opt/local', ['/opt/local/include'], ['/opt/local/lib'])

    def gen_envs(self, loc):
        for env in Package.gen_envs(self, loc):
            self.headers = ['Python.h']
            if self.find_libraries(loc[2], 'python'):
                env.PrependUnique(LIBS=['python'])
                yield env
            if self.find_libraries(loc[2], 'python3.5m'):
                env.AppendUnique(CPPPATH=[os.path.join(self.location[1][0],'python3.5m')])
                env.PrependUnique(LIBS=['python3.5m'])
                yield env
            if self.find_libraries(loc[2], 'python3.6m'):
                env.AppendUnique(CPPPATH=[os.path.join(self.location[1][0],'python3.6m')])
                env.PrependUnique(LIBS=['python3.6m'])
                yield env
            if self.find_libraries(loc[2], 'python3.7m'):
                env.AppendUnique(CPPPATH=[os.path.join(self.location[1][0],'python3.7m')])
                env.PrependUnique(LIBS=['python3.7m'])
                yield env
            if self.find_libraries(loc[2], 'python3.8'):
                env.AppendUnique(CPPPATH=[os.path.join(self.location[1][0],'python3.8')])
                env.PrependUnique(LIBS=['python3.8'])
                yield env
```
[config.log](https://github.com/underworldcode/underworld2/files/4563364/config.log)
[ConfigureAndcompileLog.log](https://github.com/underworldcode/underworld2/files/4563366/ConfigureAndcompileLog.log)

**Comment by rbeucher** [comment]
What version of SWIG are you using @arijitlaik ?

**Comment by arijitlaik** [comment]
ah thanks, it was 4.0.1 the default with the distro, i will try with swig3

**Comment by arijitlaik** [comment]
fails at generating bindings for function.i
note: i  modified the swigall.py form swig to swig3.0  
swigcommandbase = 'swig3.0 -v -Wextra -python -py3 -ignoremissing -O -c++ -DSWIG_DO_NOT_WRAP'

**Comment by rbeucher** [comment]
@jmansour any idea?

**Comment by rbeucher** [comment]
@jmansour  20.04 is fairly new but it is a LTS so we should get it to work..

**Comment by jmansour** [comment]
No idea, but we should sort this `swig4` issue out while we're looking into it. 

I'll fire up a VM and have a look later today.

**Comment by jmansour** [comment]
I've made some changes for ubuntu 20.04 and swig4 
d0d9c67f378b1d8374095a060ebb104c2be091f0
2f1cb91f8c6e129e3a14731faa1487218f2dbba4

Try and build again and report back.  You will need to install from the dev branch.  I think this should do the trick:
```shell
pip install git+https://github.com/underworldcode/underworld2@development.
```

**Comment by rbeucher** [comment]
I have just tried on Arch in a python 3.8 virtual env and swig 4.0.
swigall.py fails:

```    Traceback (most recent call last):
      File "./swigall.py", line 40, in <module>
        raise RuntimeError("Error generating swig bindings.")
    RuntimeError: Error generating swig bindings.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-o7di51rt/setup.py", line 176, in <module>
        setup(name='underworld',
      File "/home/romain/sandbox/underworld_python38/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-o7di51rt/setup.py", line 138, in run
        build(self.dry_run)
      File "/tmp/pip-req-build-o7di51rt/setup.py", line 98, in build
        if status != 0: raise RuntimeError(status)
    RuntimeError: 256
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/romain/sandbox/underworld_python38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-o7di51rt/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-o7di51rt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-amtjp7bc/install-record.txt --single-version-externally-managed --compile --install-headers /home/romain/sandbox/underworld_python38/include/site/python3.8/underworld Check the logs for full command output.
```

**Comment by jmansour** [comment]
can you run the swig command directly and get the actually error message?

**Comment by Pulak-Biswas** [comment]
Thanks @jmansour it worked.

**Comment by rbeucher** [comment]
@jmansour my bad, some issues with petsc 3.13...
I guess @Pulak-Biswas @arijitlaik  are using 3.12?

All good!

**Comment by arijitlaik** [comment]
@rbeucher no issues with the build, thanks @jmansour :)

**Comment by rbeucher** [comment]
What version of petsc?

**Comment by Pulak-Biswas** [comment]
I don't know much about these dependencies but as you guessed @rbeucher the version of petsc is 3.12.

**Comment by arijitlaik** [comment]
petsc 3.12.4 built with openmpi @rbeucher
