### ISSUE TITLE
The Reason of Temperature Convergence Issue?

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#479]
Hi, all.
      I encountered an issue of temperature convergence when running my UW2 model after tens of steps. If I understand it correctly, the calculation and advection of the temperature filed of each step is mainly decided by velocity filed when employing invariant value of fn_diffusivity and fn_sourceTerm in uw.systems.AdvectionDiffusion. I checked the velocity field, but it  seemed to be correct without any convergence problem. It is noticeable that, in all my tested models, the timestep was set to be 0.25*advDiff.get_max_dt(). I wander if there is any other possible reasons for the temperature convergence problem. Is it due to resolution, particle numbers or material properties? why?  Any clues and comments would be appreciated. 
Best regards.
Alex

**Comment by julesghub** [comment]
Hi Alex, it's unclear what you mean by temperature convergence issues. Does the resultant temperature field look incorrect? 

Resolution and material properties will effect the AdvectionDiffusion calculation. Poorly resolved temperature gradients can cause the advection part of the AdvectionDiffusion solve to create numerical errors. If you suspect this is the issue then reduce the temperature gradient over the mesh -  perhaps run a few steps of the AdvectionDiffusion solver with zeroed velocity field to diffuse temperature gradients.

You can use the following models to examine the behaviour of the `uw.systems.AdvectionDiffusion()` with a fixed velocity field
* https://github.com/underworldcode/underworld2/blob/v2.9.4b/docs/test/HeatEq_fluxBC.ipynb
* https://github.com/underworldcode/underworld2/blob/v2.9.4b/docs/test/2DCosineHillAdvection.ipynb

For a thermodynamic model, try this model
* https://github.com/underworldcode/underworld2/blob/v2.9.4b/docs/examples/02_Convection_Example.ipynb

In all the above you can vary mesh resolution or the AdvectionDiffusion parameters and see how the model responds.

**Comment by alexstruc** [comment]
Hi, jule.
    I appreciate your help. You are right, the resultant temperature field looked wrong. Taking one of my models as an example, the results of temperature field worked well at the beginning, the range of temperature value was [25, 1500]. But suddenly that range turned to [-2457, 4837] after tens of steps. I have already checked the possible influences of resolution and timestep as well as viscosity, but the results were similar with incorrect temperature field. I will next give it a try on the temperature gradients following your suggestions. In all, Thanks a lot.
Alex.

**Comment by julesghub** [comment]
Hi Alex, I'll close this ticket for now. Feel free to reopen if you want to continue the conversation.

**Comment by alexstruc** [comment]
Hi, @julesghub.

Sorry for bothering you again. Last time I got some very helpful suggestion from you and the AdvectionDiffusion solver with zeroed velocity field to diffuse temperature gradients made the model work well without temperature field issue.

However, I encountered such issue again in some of my other models even though I applied the same method. For instance, I successfully ran a continental collision model which had a weak zone between two continents to help subduction with normal temperature filed, but something went wrong after only increasing the width of the weak zone from 15Km to 30Km. I set the temperature limits as [0,1680], but it went beyond the prescribed limits to [-3424,3507] after running for 75 steps. I am so confused how could the minor change of the model configuration affect the temperature field. It is so wearied. 

![image](https://user-images.githubusercontent.com/50648269/82287437-caa1ba80-99d2-11ea-9063-7bd53714a272.png)

The above example is just one situation with temperature field problem. Sometimes the minor change of model size or viscosity value also cause such issue. The occurrence of the problem seems random.  If you know anything about the problem, please let me know. I really appreciate your favor. If you need to check my codes, feel free to ask me for it. 

Best regards
Alex

**Comment by julesghub** [comment]
Hi Alex, look like you still have gradients that are too sharp for the numerical method (time and/or space discretisation).
Thanks for the image. The nucleation point appears distant from the weak zone if I understand things right. I'm thinking the area around the nucleation point is the location of sharp temperature gradients. 
Do you have an air layer in the model?

**Comment by alexstruc** [comment]
Thanks for your reply. You are right, I applied an air layer which was 20Km thick and had a density of 1Kg/m3 and a viscosity of  1e19pa*s to model topography.  I set the weak zone in the middle of the whole domain so the nucleation point was indeed distant from the weak zone. In fact, the initial temperature in the air layer was 0℃ and it linearly increased with a temperature gradient of 25℃/Km in the top 10Km depth and then increased with a gradient of  10℃/Km from 10Km depth to Moho interface (35Km depth). The initial temperature profile, which is the result after diffusing temperature gradients for 2Myr, is shown below.

![image](https://user-images.githubusercontent.com/50648269/82299447-1dd23800-99e8-11ea-93d4-7d648ccbcf77.png)


 As for the time space, I dealt with it like that:
![image](https://user-images.githubusercontent.com/50648269/82298757-2c6c1f80-99e7-11ea-8273-471a6de4a105.png)

In addition, the resolution was 5Km✖6.8Km in the model whose domain corresponded to 2000Km✖680Km.

All the parameters mentioned above were nondimensionalized in the model.

**Comment by alexstruc** [comment]
So do you think that the above gradients are still not small enough?

**Comment by julesghub** [comment]
Thanks for the graph. The temperature gradients around the air layer are sharp, even after the diffusion step. As a general idea I suggest you construct/run a few models with the air layer temperature more crust-like than "realistic" air-like. See how that helps?

**Comment by alexstruc** [comment]
Hi, @julesghub 
    Thanks for your kind help. It seems that I find the reason of temperature issue in the above model. In the model, I set the thermal conductivity value of air layer as 0 by mistake. By analyzing the results after running for tens of steps, I noticed that such setting made the temperature of the lower part of air layer keep decreasing to minus value. It eventually caused severe convergence problem in temperature filed calculation. Then I tested a revised model with air thermal conductivity of 20W/m/K, and I find that the sharp temperature gradients around the air layer were eliminated after diffusing for 2Myr. Here is the result, which looks more reasonable compared with the above temperature graph.
![image](https://user-images.githubusercontent.com/50648269/82408420-1f5e3780-9a9e-11ea-9d31-3f7fb3030303.png)
Although I have not got the final results of the revisited model, at least it is still running robustly after running for tens of hundred steps.  I think the issue of the above model is almost solved now.

Besides, I remember that you said that resolution also strongly affected temperature filed evolution. And I indeed encountered such temperature issue when I set the vertical resolution to equal to the thickness of air layer(20Km). Improving the resolution should be helpful, but too high resolution means slower modeling process. Therefore, do you know whether there are any experimental or empirical rules about setting the lowest resolutions which simultaneously keep models robust?

Sorry for asking you for so many questions. I am very interested in this amazing modeling tool, but it is also difficult to use it very well at the beginning. I sincerely appreciate your kind help.

**Comment by julesghub** [comment]
A robust resolution depends on your model and what you want to model. If the resolution is 50km but you have 20km feature (gradient) length scales then the model won't see them.

An experimental way to find a satisfactory resolution is a resolution test. That is, does doubling resolution alter the result significantly? If so, why? If not then you have a lower limit for the model.

**Comment by alexstruc** [comment]
Great. Experiments are always direct and useful.Thanks again.
