### ISSUE TITLE
Boundary Condition set up stuff

### ISSUE THREAD

**Issue by mirkovelic** [underworldcode/underworld2#48]
e.g.

tempBC = uw.conditions.DirichletCondition( variable      = temperatureField, 
                                           indexSetsPerDof = (jWalls,) )

heatequation = uw.systems.SteadyStateHeat(temperatureField=temperatureField, fn_diffusivity=1.0, conditions=[tempBC,])

It seems to me that having the temperatureField passed into the uw.conditions.DirichletCondition class
is redundant,

**Comment by lmoresi** [comment]
Because the tempBC doesn't need to know the actual variable, just the locations and the number of degrees of freedom in the variable ?
