### ISSUE TITLE
Solver use

### ISSUE THREAD

**Issue by cameriaux** [underworldcode/underworld2#480]
Hi,

I am currently having a solve that really struggles apparently at the pressure solve with many iterations. In 2D, it is workable but in 3D it no longer is. I have tested mg, mumps and superludist but I only succeeded to make it even less efficient. I also tried different penalty without seeing much change. Lately I tried to use the pseudo-compressibility in one layer but I am not very comfortable with that parameter lambda nor do I really understand from where the equation 
 u_k,k +p/lambda =H
comes from.
Blindly I made some tests and could see that the number of iterations was decreasing as I increased lambda up to 10, which could not be a sensible idea.

Could someone tell me me more about this pseudo-compressibility and alternative solver options I could try?
I suspect that my matrix is very sparse.

In advance many thanks for any suggestion. Catherine.

**Comment by jmansour** [comment]
Apologies this went unanswered @cameriaux !  

Pseudo-compressibility introduces some compliance to the system which can be useful for some configurations. The lambda parameter simply modulates the degree of compliance introduced (compliance being inversely proportional to lambda). 

Where are you currently at with this modelling Catherine? We can take this to the emails if you prefer!

**Comment by jmansour** [comment]
Have chatted to @cameriaux and she's currently using https://bitbucket.org/ptatin/ptatin3d, so will close this issue.
