### ISSUE TITLE
RuntimeError: Error in _DVCWeights_Calculate2D

### ISSUE THREAD

**Issue by alexstruc** [underworldcode/underworld2#483]
Hi, all.
    I am encountering a RuntimeError after running my model for 280 steps. 
    This is the error information:
![image](https://user-images.githubusercontent.com/50648269/81630850-387d3d80-9439-11ea-9b8b-bd1d1715b726.png)
    It looks like the reason of the error is that the particle amount is not ample. I added the equal particle amount of 20 in each cell at the beginning. Then I changed the particle amount of each cell into 30 in another tested model. But the error appeared again. Does anyone know the true reason of this error and relevant solutions? Any comments would be appreciated.
Thanks in advance.
Alex

**Comment by alexstruc** [comment]
Hi, guys. Sorry for bothering you. I think I find the key reason of the above problem. It is because that swarm advection can make particles move outside of particular cell domain, reducing the particle amount in the cell to cause calculation error if there are not ample particles repopulated. Therefore, I think it is necessary to repopulate the particles after swarm advection in every step. 

The relevant codes are like that:
![image](https://user-images.githubusercontent.com/50648269/82281985-557bb880-99c5-11ea-8b1f-8092589b7d9b.png)
![image](https://user-images.githubusercontent.com/50648269/82282017-69bfb580-99c5-11ea-90da-527ee4690bf9.png)

Now that the issue is solved, I will close it.

**Comment by jmansour** [comment]
Ok, thanks for reporting back.  Yes, the repopulate might be required, depending on your model config.  I believe the `update_particle_owners()` shouldn't be necessary however.
