### ISSUE TITLE
docker run -v option not working: can't bind mount host files

### ISSUE THREAD

**Issue by ejhgeo** [underworldcode/underworld2#484]
From the Docker and Underworld documentation, it is my understanding that the command
```
docker run -p 8888:8888 -v "$(pwd):/workspace underworldcode/underworld2
```
should be used to bind-mount local files and directories on our host system to the container so that we can run our own scripts and use our own datafiles in Underworld. I have tried this and yet none of my files actually show up in the workspace folder when I run the Jupyter Notebook. I have tried trouble shooting this by writing it in different ways via the Docker documentation, checking the file sharing options on Docker Desktop, and searching for others solutions to any similar problems, and I have not been able to get it to work, which means that I can't actually create or use my own files with Underworld. I realize this might be a docker issue, but I need some help. I am new to both docker and Underworld. I am using Mac OS Catalina (10.15.2) and running Docker Desktop version 2.3.0.2. 

I am able to access the jupyter notebook with all the examples without any problems using:
```
docker run -p 8888:8888 underworldcode/underworld2
```
In order to link my personal Underworld directory where I will keep all my Underworld stuff with the container, I used the following command:
```
docker run -p 8888:8888 --name UW_test -v "$(pwd)"/Underworld:/workspace underworldcode/underworld2
```
where pwd is `/Users/ehightower/Documents/Research/SISIE` and ran it from within the SISIE directory. Theoretically, when I do this, I should then see my personal files in my Underworld folder show up in the workspace folder in the jupyter notebook, but nothing is there. There is no docker error and as far as I can tell from the file sharing on Docker Desktop, the path to this folder is set up to share. When I run `docker container inspect`, docker shows my Underworld directory is in fact a mount with the destination `/workspace`:
```
"Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/ehightower/Documents/Research/SISIE/Underworld",
                "Destination": "/workspace",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "6613226f9a070ddba4ad9df93a56df7d2ea35283e62f661f40bb527b62d9e2f0",
                "Source": "/var/lib/docker/volumes/6613226f9a070ddba4ad9df93a56df7d2ea35283e62f661f40bb527b62d9e2f0/_data",
                "Destination": "/home/jovyan/workspace",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
```
But still nothing shows up in the workspace folder on the jupyter notebook! I think perhaps the `rprivate` propagation setting has something to do with this, but I cannot seem to change this setting to shared, rshared, or otherwise in any of the sources I have found. Is this a permission issue with Underworld?

Any guidance on how exactly to resolve this issue and link and run our own files in Underworld is much appreciated. I am a beginner so details are very helpful. Thank you.

**Comment by julesghub** [comment]
This should be the command you want
`docker run -p 8888:8888 -v "$(pwd)":/home/jovyan/workspace underworldcode/underworld2`

Previous versions of the code (<2.5.0b) used `/workspace` as the argument to the right of `:`. It was updated to `/home/jovyan/workspace` because we chose to run the docker container as a non root user (a.k.a jovyan).

**Comment by ejhgeo** [comment]
Update: the -v option works fine when using other images, like r-base for example, and my chosen directory shows up in the container as expected. So, I do not think this is a mac issue or an issue with rprivate. It seems to be an issue with Underworld permissions. If I run the underworld docker container in bash and try to bind my desktop folder for example:
 ```
docker run -it -v ~/Desktop:/workspace underworldcode/underworld2 bash
```
the prompt I get is `jovyan@293e6fc117fd:~$` as opposed to something like `root@293e6fc117fd:~$`. Should it be root? or my own user name in front? Seems like Underworld won't let me bind mount anything.

**Comment by ejhgeo** [comment]
Simple fix! It worked! Thank you.

**Comment by julesghub** [comment]
The user in the docker container should be `jovyan`. 
Can you please send a link to the Documentation you read that assumes you'd run docker as root, i.e. with `/workspace`. I'll update it.

**Comment by gaowqspace** [comment]
> Simple fix! It worked! Thank you.

Hi, can you share us how did you fix it? 
I am looking forward to your reply!
Thank you!

**Comment by julesghub** [comment]
@gaowqspace I think this was the answer. It depends on the version of Underworld you are trying to use.

> This should be the command you want `docker run -p 8888:8888 -v "$(pwd)":/home/jovyan/workspace underworldcode/underworld2`
> 
> Previous versions of the code (<2.5.0b) used `/workspace` as the argument to the right of `:`. It was updated to `/home/jovyan/workspace` because we chose to run the docker container as a non root user (a.k.a jovyan).
