### ISSUE TITLE
visco-elastic rheology at sharp viscosity boundaries

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#489]
Hi all,

I checked the formula for visco-elastic rheology and it looks that very small observational time is needed if large viscosity contrasts presents. Please correct me if there are any issues in the following analysis.

The formulas below are from the visco-elastic beam tutorial.
![image](https://user-images.githubusercontent.com/26615840/86443718-40bf6e00-bd42-11ea-802a-a75373059334.png)

I guess the last equation (momentum conservation) should be actually as below
![image](https://user-images.githubusercontent.com/26615840/86443929-8e3bdb00-bd42-11ea-96c7-1d8fe83cec22.png)

The last approximate equal is reasonable only when the spatial gradient of eta_eff/(mu*dt) is very small (compared to the stress' spatial gradient). However, very large (many orders of) viscosity contrast may appear at material boundaries or when plastic yielding is present. So the only safe way to make the above approximation reasonable seems to be reducing the observational time to smaller than the Maxwell relaxation time. For a viscosity of 1E19, the relaxation time is around 10 yrs or so.  So I guess the observational time must not exceed 10 yrs when large viscosity contrast exists? Please correct me if I was wrong. Thanks a lot.

Best regards,
Ting

**Comment by lmoresi** [comment]
I think that the effective viscosity is used within the weak form so that the derivative is formed correctly and the approximation is not as described. In other words, the value of effective viscosity is computed at each particle location. Right, Julian ?
On 3 Jul 2020, 6:15 PM +1000, Julian Giordani <notifications@github.com>, wrote:

Assigned #489<https://github.com/underworldcode/underworld2/issues/489> to @lmoresi<https://github.com/lmoresi>.

**Comment by RebeccaFarrington** [comment]
Correct @Louis Moresi<mailto:Louis.Moresi@anu.edu.au>!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tingyang2004** [comment]
OK, so [eta_eff/(mu*dt)*tao],j instead of eta_eff/(mu*dt)*tao,j is used in UW. Thanks both. 
I will close the ticket then.

**Comment by julesghub** [comment]
> I think that the effective viscosity is used within the weak form so that the derivative is formed correctly and the approximation is not as described. In other words, the value of effective viscosity is computed at each particle location. Right, Julian ? 

That's correct @Louis and @tingyang2004.

@RebeccaFarrington let's update the documentation where applicable?

**Comment by tingyang2004** [comment]
Thanks, Julian.

In the case that the effective viscosity is not known a priori for non-linear rheologies (dislocation creep, plastic yielding), I guess the extra force term from the historical stress is updated each iteration in the non-linear solver in uw2?

**Comment by lmoresi** [comment]
I’ll just point out that the stress is known in the case of plastic yielding … even though it is non linear - because reaching a particular value of stress is the target of the non-linearity.
On 7 Jul 2020, 12:51 PM +1000, tingyang2004 <notifications@github.com>, wrote:

Thanks, Julian.

In the case that the effective viscosity is not known a priori for non-linear rheologies (dislocation creep, plastic yielding), I guess the extra force term from the historical stress is updated each iteration in the non-linear solver in uw2?

**Comment by julesghub** [comment]
> In the case that the effective viscosity is not known a priori for non-linear rheologies (dislocation creep, plastic yielding), I guess the extra force term from the historical stress is updated each iteration in the non-linear solver in uw2?

Yes Ting, if effective viscosity is a function of velocity (including strain rate 2nd inv.) or pressure then it is evaluated for each iteration in the non-linear solve. With the power of uw.Functions you can set that up.

**Comment by tingyang2004** [comment]
Thanks, both. So the extra force term coming from the multiply of effective viscosity and the advected historical stress is updated in each iteration.

**Comment by julesghub** [comment]
Yes the multiply is updated each iteration. That said the historical stress part should be unchanged between non-linear iterations as it's not dependent on the current time step. 

Technically speaking the uw.function you give as an argument to `fn_stresshistory` term of `Stokes()` will always be evaluated between non-linear iterations.

**Comment by lmoresi** [comment]
It is dependent on the current timestep in the non-linear case though … at least in the formulation as written.
On 7 Jul 2020, 9:22 PM +1000, Julian Giordani <notifications@github.com>, wrote:

Yes the multiply is updated each iteration. That said the historical stress part should be unchanged between non-linear iterations as it's not dependent on the current time step.

Technically speaking the uw.function you give as an argument to fn_stresshistory term of Stokes() will always be evaluated between non-linear iterations.

**Comment by julesghub** [comment]
Yes I was wrong. In the non-linear case the historic stress will be dependent on the current timestep.

Looking at https://github.com/underworldcode/model_library/blob/master/tutorials/ViscoelasticTutorial/010-Overview.ipynb

check out cell 10
`elasticStressFn       = eta_eff / ( mu * dt_e ) * previousStress`

cell 14:
`previousStress.data[:] = ( phi*stressFn_data[:] + ( 1.-phi )*previousStress.data[:] )`

`previousStress` is based on `stressFn` which is the current stress state.

Sorry for the confusion all.

**Comment by tingyang2004** [comment]
I thought elasticStressFn = eta_eff / ( mu * dt_e ) * previousStress is updated each iteration because eta_eff is updated during each iteration. While previousStress keeps unchanged until the next time step?

**Comment by julesghub** [comment]
@lmoresi can you please put up a link to the formulation / equation for discussion?
