### ISSUE TITLE
The default integration scheme?

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#49]
We should flag a warning for this, as PIC is generally not a great option with quad mesh.

**Comment by lmoresi** [comment]
But what alternative is there if you want to use particles ?


On 5 February 2016 at 4:43:19 PM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

We should flag a warning for this, as PIC is generally not a great option with quad mesh.

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/49>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
There's gauss integration, which simply uses nearest neighbour with
particles.

The way this is setup in the `systems` should be reorganised.  Currently if
you provide the particle swarm to the system, it will be use the voronoi
integration. We probably should be more explicit, and ask that users state
which integration they wish to use. But not sure if we should default to
Gauss or PIC.

**Comment by lmoresi** [comment]
I don’t understand why this is not also called PIC ??

Something seems misleading in our nomenclature.

L


On 5 February 2016 at 4:53:26 PM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

There's gauss integration, which simply uses nearest neighbour with
particles.

The way this is setup in the `systems` should be reorganised. Currently if
you provide the particle swarm to the system, it will be use the voronoi
integration. We probably should be more explicit, and ask that users state
which integration they wish to use. But not sure if we should default to
Gauss or PIC.
---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.underworldcode.org
<http://www.underworldcode.org>

**Comment by jmansour** [comment]
Yep, sure.  I guess we're really talking about Voronoi vs Gauss
integration.

**Comment by lmoresi** [comment]
The Voronoi is not great for Q2 so should not even be available. The Voronoi is pretty good for Q1 though. You may well have to have Voronoi default for Q1 and Nearest-Gauss for everything else.

**Comment by jmansour** [comment]
I'm thinking we should do nearest neighbour as default for consistency across element types.  Then allow users to select Voronoi if they wish, but then should also flag a warning for the Voronoi/Q2 combination.

**Comment by jmansour** [comment]
default is currently 3^dim gauss points per element, which samples more particles (via nearest neighbour).   

* check if this is controllable 
* add warning for folks using voronoi and q2

**Comment by jmansour** [comment]
I've added the warning for Q2/voronoi here 3a2e06a799d72cba5a5a9f7f094841c4d9b15007

The default is currently NN by virtue of the voronoi_swarm being an optional parameter to the systems.  However, most our example model files do provide a voronoi_swarm.  So we're effectively recommending voronoi.  I think we should leave it like this for the current release, but then for the next release (ie, once we've done more rigorous science testing) we should switch to NN (or other) as the recommended.
