### ISSUE TITLE
The installation problem of underworld2-2.9.4b 

### ISSUE THREAD

**Issue by ningningwu** [underworldcode/underworld2#491]
Dear Sir/Madam;
I install underworld2-2.9.4b whit the flow issue. How can I fill it?

PS:I use petsc/3.13.2-gcc-5.4.0 and hdf5/1.12.0-gcc-5.4.0.
python3 configure.py --cc=mpicc --cxx=mpic++ --with-debugging=1 --libxml2-dir=/WORK/app//libxml/2.7.8 --python-dir=/WORK/app/Python/3.6.3 --petsc-dir=/WORK/app/petsc/3.13.2 --petsc-arch=arch-linux2-c-opt --hdf5-dir=/WORK/app/hdf5/1.12.0-gcc-5.4.0

Compiling ==> Solvers/KSPSolvers/src/BSSCR/list_operations.c
Solvers/KSPSolvers/src/BSSCR/list_operations.c: In function ‘BSSCR_MatListOperations’:
Solvers/KSPSolvers/src/BSSCR/list_operations.c:204:22: error: ‘struct _MatOps’ has no member named ‘matmult’
  BSSCR_report_op( ops->matmult, v,         i++, "MatMatMult" );
                      ^
Solvers/KSPSolvers/src/BSSCR/list_operations.c:44:7: note: in definition of macro ‘BSSCR_report_op’
   if((op)) { PetscViewerASCIIPrintf((v), "[%.2d] %s: valid operation \n", i, func_name ); } \
       ^
Solvers/KSPSolvers/src/BSSCR/list_operations.c:207:22: error: ‘struct _MatOps’ has no member named ‘ptap’
  BSSCR_report_op( ops->ptap, v,            i++, "MatPtAP" );
                      ^
Solvers/KSPSolvers/src/BSSCR/list_operations.c:44:7: note: in definition of macro ‘BSSCR_report_op’
   if((op)) { PetscViewerASCIIPrintf((v), "[%.2d] %s: valid operation \n", i, func_name ); } \
       ^
Solvers/KSPSolvers/src/BSSCR/list_operations.c: In function ‘BSSCR_VecListOperations’:
Solvers/KSPSolvers/src/BSSCR/list_operations.c:248:11: warning: unused variable ‘i’ [-Wunused-variable]
  PetscInt i;
           ^
Solvers/KSPSolvers/src/BSSCR/list_operations.c:246:9: warning: unused variable ‘ops’ [-Wunused-variable]
  VecOps ops = x->ops;
         ^
scons: *** [build/Solvers/KSPSolvers/src/BSSCR/list_operations.os] Error 1
scons: building terminated because of errors.

**Comment by julesghub** [comment]
Hi @ningningwu, 
Underworld2-2.9.4b isn't compatible with petsc-3.13, but it is compatible with petsc-3.12. Can you use petsc-3.12 instead?

We are working on a new release of Underworld2, called 2.10.0b, it will be compatible with petsc-3.13 and should be release in 2 weeks. Stay tuned.

**Comment by ningningwu** [comment]
Hi julesghub,
Thank you for your help. I  use petsc-3.12 to install Underworld2-2.9.4b, but have the follow issue.
The command is "python3 configure.py --cc=mpicc --cxx=mpic++ --with-debugging=1 --with-viewer=0 --libxml2-dir=/WORK/app//libxml/2.7.8 --python-dir=/WORK/app/Python/3.6.3 --petsc-dir=/WORK/app/petsc/3.12.5-gcc-5.4.0 --hdf5-dir=/WORK/app/hdf5/1.10.6-gcc-5.4.0" .

Compiling ==> libUnderworldPy/Function_wrap.cxx
libUnderworldPy/Function_wrap.cxx: In function ‘swig_module_info* SWIG_Python_GetModule()’:
libUnderworldPy/Function_wrap.cxx:2452:51: error: ‘PyCObject_Import’ was not declared in this scope
         (char*)"type_pointer" SWIG_TYPE_TABLE_NAME);
                                                   ^
libUnderworldPy/Function_wrap.cxx: In function ‘void SWIG_Python_SetModule(swig_module_info*)’:
libUnderworldPy/Function_wrap.cxx:2521:92: error: ‘PyCObject_FromVoidPtr’ was not declared in this scope
   PyObject *pointer = PyCObject_FromVoidPtr((void *) swig_module, SWIG_Python_DestroyModule);
                                                                                            ^
libUnderworldPy/Function_wrap.cxx:2512:22: warning: unused variable ‘swig_empty_runtime_method_table’ [-Wunused-variable]
   static PyMethodDef swig_empty_runtime_method_table[] = { {NULL, NULL, 0, NULL} };/* Sentinel */
                      ^
libUnderworldPy/Function_wrap.cxx: In function ‘swig_type_info* SWIG_Python_TypeQuery(const char*)’:
libUnderworldPy/Function_wrap.cxx:2544:60: error: ‘PyCObject_AsVoidPtr’ was not declared in this scope
     descriptor = (swig_type_info *) PyCObject_AsVoidPtr(obj);
                                                            ^
libUnderworldPy/Function_wrap.cxx:2549:51: error: ‘PyCObject_FromVoidPtr’ was not declared in this scope
       obj = PyCObject_FromVoidPtr(descriptor, NULL);
                                                   ^
libUnderworldPy/Function_wrap.cxx: In function ‘const char* pytype_string(PyObject*)’:
libUnderworldPy/Function_wrap.cxx:3681:32: error: ‘PyString_Check’ was not declared in this scope
     if (PyString_Check(  py_obj)) return "string"      ;
                                ^
scons: *** [build/libUnderworldPy/Function_wrap.os] Error 1
scons: building terminated because of errors.

**Comment by julesghub** [comment]
What version of swig are you using? We use swig 3. 
Also we recommend python 3.7, I notice you're using python 3.6.3

Is this installation for a desktop machine? If it is, then docker is our recommendation. Docker is much easier to get started with the code. The instructions for docker can be found here  https://underworld2.readthedocs.io/en/latest/Installation.html

**Comment by ningningwu** [comment]
I use swig3.0.12 and python3.7.0.But I have the follow issue. I install underworld in HPC.
Can you give me any suggestion?
ng "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
StGermain/Base/Context/src/Init.c: In function ‘BaseContext_Init’:
StGermain/Base/Context/src/Init.c:38:4: error: incompatible types when returning type ‘void *’ but ‘Bool {aka enum Bool}’ was expected
    import_array();
    ^
StGermain/Base/Context/src/Init.c:36:12: warning: unused variable ‘typedStream’ [-Wunused-variable]
    Stream* typedStream;
            ^
scons: *** [build/StGermain/Base/Context/src/Init.os] Error 1
scons: building terminated because of errors.

executing command:
swig -v -Wextra -python -py3 -ignoremissing -O -c++ -DSWIG_DO_NOT_WRAP -I../build/include -I../build/include/StGermain -I../build/include/StgDomain -I../build/include/StgFEM -I../build/include/Solvers -I../build/include/PICellerator -I../build/include/Underworld -I../build/include/gLucifer -I../build/include/petsc -I../ctools c_arrays.i

swig: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.

**Comment by jmansour** [comment]
Hi @ningningwu 

I believe this is related to some recent changes in `numpy`.  Can you try switching to the `v2.10_release` branch where we have a fix?  If you are using `pip`, you can run:

```shell
pip3 install git+https://github.com/underworldcode/underworld2@v2.10_release
```

**Comment by ningningwu** [comment]
> 
> 
> Hi @ningningwu
> 
> I believe this is related to some recent changes in `numpy`. Can you try switching to the `v2.10_release` branch where we have a fix? If you are using `pip`, you can run:
> 
> ```shell
> pip3 install git+https://github.com/underworldcode/underworld2@v2.10_release
> ```

Very appreciated for your supports! I have install v2.10_release successful.But I have some issues when use it.
![图片](https://user-images.githubusercontent.com/37057955/88026433-71880b80-cb68-11ea-9f66-c15d6e33648d.png)
![图片](https://user-images.githubusercontent.com/37057955/88026564-a4320400-cb68-11ea-8c08-4981eb27b37a.png)

**Comment by ningningwu** [comment]
completed
