### ISSUE TITLE
Strain rate dependent viscosity plus elasticity

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#494]
Hi all,

I met an issue adding elasticity to a dislocation creep flow (strain rate dependent viscosity). 
When both dislocation creep and elasticity are considered, the dislocation creep viscosity depends on the second invariant of the viscous creep strain rate:

`viscositydis = fn.math.pow((strainRateVisc_2ndInvField+SRMin)/RefStrainRate,(1.0-ns)/ns)*viscositydif `          (1)

where ns is the stress exponential index, viscositydif is (linear) diffusion creep viscosity.

The viscous creep strain rate and its second invariant can be calculated from the total strainRate as:
```
strainRateViscFn = viscosityFn/viscosity_pureVisc*(strainRateFn+tauHistoryFn/(2.*mu0*dt_e))                          (2)
strainRateVisc_2ndInvFn = fn.tensor.second_invariant( strainRateViscFn )
projectorSR_Visc = uw.utils.MeshVariable_Projection( strainRateVisc_2ndInvField, strainRateVisc_2ndInvFn,type=0)
```

I assume the above dislocation-plus-elasticity creep flow issue can be solved with the following strategy:

First, I give an initial viscous strain rate to get the dislocation creep viscosity and the corresponded effective (numerical) viscosity:
```
relaxation_time   = viscositydis / mu0                         # viscoelastic relaxation time
eta_eff = ( viscositydis * dt_e ) / (relaxation_time + dt_e)  # effective viscosity                                                 (3)

```
Then, let the stokes solver be solved to get the viscosity and total strain rate.

Last, I use the callback_post_solve option to update the viscous strain rate, assuming the nonlinear stokes solver would continue with updated viscous strain rate 
```
solver.solve(nonLinearIterate=True,nonLinearMaxIterations=200,nonLinearTolerance=0.003, callback_post_solve=RecalibratePressure)
def RecalibratePressure():
    #The pressure field is smoothed as in Citcom: from subMesh->Nodes->subMesh 
    # First, subMesh->Nodes
    PresCell2Nodes.solve()
    # Second, Nodes->subMesh
    PresNodes2Cell.solve()

    #fix the horizontal average of the pressure field as zero
    (area,) = surfaceArea.evaluate()
    (p0,) = surfacePressureIntegral.evaluate()
    pressureField.data[:] -= p0 / area

    projectorSR_Visc.solve()
    return
```

However, the above nonLinear stokes solver is automatically transformed to a linear stokes solver when I use the above set up.
Please give me some suggestions and comments on (1) why linear stokes solver is used although I set nonLinearIterate=True; and (2) how to change the above setup to solve the dislocation-elasticity creep flow problems. Thanks a lot.

Best regards,
Ting

**Comment by tingyang2004** [comment]
BTW, when plasticity is also considered, the stokes solver always keeps as nonlinear.

**Comment by dansand** [comment]
This doesn't answer your question @tingyang2004, but another thing you need to be aware of here is that for a power law VE material it's not consistent to use the full strain rate tensor in the viscosity relationship, as the full strain rate includes the elastic strain (rate) components. This could blow up badly when using very short elastic timesteps. The solution would be to try to decouple the elastic and viscous strain rate component. I know that @RebeccaFarrington thesis has all of this stuff written up very clearly. Anyway, just thought I'd throw this in ...

**Comment by tingyang2004** [comment]
Thanks @dansand .

I was aware of the difference between viscous and full strain rate. I tackled this by defining a viscous strain rate explicitly. And this gives the 'non-linear to linear' issue as mentioned above. I bypassed this issue by mannually defining a non-linear stokes solver function. However, it is still helpful if the above issue is solved.

**Comment by dansand** [comment]
Nice work, I didn't read your code snippet closely enough!

**Comment by tingyang2004** [comment]
I used strainRate_2ndInv to represent the strain rate in the dislocation creep initially, that may have caused misunderstandings. I have changed that to strainRateVisc_2ndInvField now.

**Comment by julesghub** [comment]
@tingyang2004 is this still an issue. Happy to investigate more if it is, otherwise please close the ticket?

**Comment by tingyang2004** [comment]
Issue solved.
