### ISSUE TITLE
 advDiff.integrate()

### ISSUE THREAD

**Issue by hl-2000** [underworldcode/underworld2#495]
Hi Underworld group

I got an error when I run "02_Convection_Example". I'm using docker on my laptop.  Do you have any ideas to solve this? Thanks in advance!
The error message is :

<img width="704" alt="image" src="https://user-images.githubusercontent.com/68275670/87411061-befcf980-c5f9-11ea-8023-7045fdce435e.png">

**Comment by jmansour** [comment]
I'm guessing you've run out of memory. What platform are you using (Linux/Mac/Windows)?   

If Mac or Windows, you should be able to increase the amount of your systems memory available to Docker.  

https://docs.docker.com/docker-for-windows/#resources
https://docs.docker.com/docker-for-mac/#resources

If Linux, Docker should have access to all your machine's memory, in which case you've hit a hard limit and you'll need to reorganise your models or machine.

**Comment by lindsay-2020** [comment]
Hi 
Thanks for your reply!  i've already increase the memory to Docker on Mac. But the same error still shows up.  

![image](https://user-images.githubusercontent.com/68275670/88012251-00d2f600-cb4c-11ea-9b87-1b60913e6e01.png)

**Comment by jmansour** [comment]
Well yes, that should be sufficient. 

Which docker image are you using?

**Comment by lindsay-2020** [comment]
Hi, I'm using uw2.9.4.  I tried older versions of underworld image, but sill have the same problem

**Comment by julesghub** [comment]
Hi @lindsay-2020. There is a new version of the docker out
`docker pull underworldcode/underworld2:2.10.1b`
Can you clean out the old docker you have and try the new version. 
The example problem runs well in our latest tests.

**Comment by julesghub** [comment]
Closing ticket, feel free to reopen if you're still having issues.
