### ISSUE TITLE
ipynb pre-commit output clearing / management

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#5]
our previous hg hooks are currently disabled as they don't work with git.  

have to gittify they, or think of a new strategy.

**Comment by lmoresi** [comment]
Git doesn't make it particularly easy to manage these hooks - I think we'd need to install them at compile time. I would also point out that we have to think about the best way to have the notebooks be browsable. In this case, the output might actually be an important part of the notebook.

An in-between solution might be to have target outputs cached and included in the explanatory text of the notebooks (e.g. you should see this: ... )

**Comment by jmansour** [comment]
Setting all 'published' notebooks to read-only possibly solves all these issues.  Am I missing anything?

**Comment by julesghub** [comment]
is still an issue - the readonly permission via git doesn't seem to be working as expected.

**Comment by julesghub** [comment]
No longer valid. As currently we want to retain the output cells
