### ISSUE TITLE
What is the difference between uw.function.misc.constant()and a constant value?

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#502]
Hi there,

I have a question about uw.function.misc.constant(). What is the difference using following two methods in UW2? Will that impact for the output when we run a model using UW2?

example:
x = 1.5
x = uw.function.misc.constant(1.5)

Thanks
Pras

**Comment by julesghub** [comment]
Simply put `uw.function.misc.constant(1.5)` returns a `Function` type object that is compatible with Underworld's Function workflow. i.e. 1) integration with Underworld's c api/data structures and 2) 'lazy' evaluation. See this [user guide](https://underworld2.readthedocs.io/en/latest/build/user_guide/04_Functions.html) for more details.
A `constant` Function can change it's values via the `.value` attribute on the object. 

The `x = 1.5` just makes x a python `float` type. Evaluated and returned immediately.

**Comment by julesghub** [comment]
Closing ticket, feel free to reopen if it's still an issue.
