### ISSUE TITLE
Searching for Example UW2 code "Internal heat only mantle convection"?

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#507]
Hi there,

I have seen an example of internal heat only mantle convection simulation in a previous version of UW2. Now, I need to get this example, but could not find it anywhere in recent releases. Can someone post the particular example or point me to a location. I think this Example is based on Solomatov and Moresi 2020 publication.

Cheers

**Comment by jmansour** [comment]
Hi Pras

In UW2.7 we removed a bunch of examples from the `docs` directory as the list was getting a bit to long to maintain. The idea is that we'd maintain a smaller set of models alongside the codes (ie, those currently found in `docs`), and all other models will be migrated to the `underworld-community` github community:

https://github.com/underworld-community

I'll note that some of the models are yet to be migrated, but have a browse at the above link (@julesghub we should do some house cleaning at the `underworld-community` org), and also you can browse the older version of UW for the model you require:

https://github.com/underworldcode/underworld2/tree/v2.6.1b/docs

Note that both cases (community models, or old repo models), the script might need to be updated to run correctly against the latest version of UW. 

Let me know which model you were after.

**Comment by julesghub** [comment]
@jmansour, happy to do a cleaning day next week. Wednesday?

**Comment by adambeall** [comment]
Hi Pras,

If you saw the notebook a couple of years ago, you may be thinking of this:

https://github.com/underworldcode/underworld2/blob/0e094159c27bab937260f3f21e1946e8dc9d2a6c/docs/examples/1_12_Internally_Heated_Convection.ipynb

It would need to be updated to work on the latest version of Underworld,
but I would be happy to help if you need it.
I can also add it to the underworld-community github if that would be
useful.

Cheers,
Adam

**Comment by Prasanna2989** [comment]
Hi Adam,

Thank you so much for getting back to me regarding this issue. This is the exact example I was looking for. I enjoyed reading your article in GSA (Beall et al., 2018) and it would extremely helpful  for the  underworld community, if you can share the particular code in github. I think it will be a great example for internal heating only convection mode. I was using a mantle convection model with only upper mantle depth(660 km) under basal heating mode. I would like to shift to internal heat only convection mode and having some troubles with the implementation. Specially the Rayleigh number, scaling of temperature as well as scaling of radiogenic heat production. Any type of support will be much appreciated.

cheers
Pras

**Comment by adambeall** [comment]
Hi Pras,

I'm glad it's helpful. I can certainly look at updating the notebook and uploading it somewhere, after talking to the team about how the underworld community repository works.

In the mean time, I think we can close this issue?

Thanks,
Adam

**Comment by Prasanna2989** [comment]
Thanks for all the support.

Pras
