### ISSUE TITLE
disabling viewer not working

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#51]
currently cannot compile with --view-viewer=0.    things needed:

* modify SConscript in libUnderworldPy to only compile LavaVu bindings when requried
* modify libUnderworldPy/__init__.py to conditionally import LavaVu bindings
* update glucifer module accordingly.. in particular, still want to be able to generate db.

**Comment by OKaluza** [comment]
Fixed in 834812b2764fe727f4e31e9eaf800b77b1d3d36e
Switch to disable changed to --with-graphics=0

**Comment by julesghub** [comment]
Closing for now as this works for me. 

Only two test do fail under this setup:
['../docs/test/image_tests.py', '../docs/user_guide/08_Visualisation.ipynb']
I assume this is expected @OKaluza?

**Comment by OKaluza** [comment]
@julesghub yes, any tests that expect image output will fail with this configuration
