### ISSUE TITLE
Mesh refinement in radial direction in parallel on multiple nodes

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#517]
Hi UW team,

I am trying to change the resolution of the mesh in the radial direction i.e., High resolution in UM and Low Resolution in LM. To do this, I have written a snippet of code and it works on single core and multiple cores of a node. However, it does not work on multiple nodes. It seems mesh has different indexing when I am using multiple nodes. To change the resolution of the mesh in radial direction, first I store the indices of "MaxI_VertexSet" and then add '-1' to the set to get all indices of layer below it and change the radial coordinate. Any suggestions how to achieve mesh refinement on multiple nodes? I am attaching python file and error file on the current method. 

Thanks.

``` python3
def remesh_r_direction(_mesh, _outer, _total_nodes=9, _refine_nodes=4, _refine_rad=700):
    """
    Changes the resolution of the mesh in radial direction
    Inputs: mesh, total no.of nodes, no.of nodes to refine, refine radius, outer layer indices
    """
    high_res_depth = np.linspace(0, _refine_rad, _refine_nodes, endpoint=True)
    low_res_depth = np.linspace(_refine_rad, 2891, (_total_nodes-_refine_nodes)+1, endpoint=True)
    refine_depth = np.unique(np.hstack((high_res_depth, low_res_depth)))
    for i in range(1,_total_nodes-1):
        if uw.mpi.rank == 0:
            print(refine_depth[i])
        with _mesh.deform_mesh():
            if uw.mpi.rank == 0:
                print((6371.0 - refine_depth[i])/6371.0)
            new_radius = (6371.0 - refine_depth[i])/6371.0
            deformed_coords = np.zeros((len(_outer.data), 3))
            deformed_coords[:,0] = sphxyz2sphlonlatr(_mesh.data[_outer.data-i])[:,0]
            deformed_coords[:,1] = sphxyz2sphlonlatr(_mesh.data[_outer.data-i])[:,1]
            deformed_coords[:,2] = new_radius
            _mesh.data[_outer.data-i] = sphlonlatr2sphxyz(deformed_coords)     
    return
```
<img width="1000" alt="Screen Shot 2020-12-02 at 2 29 49 pm" src="https://user-images.githubusercontent.com/44185316/100829984-c47ab380-34b6-11eb-8760-b40667658e44.png">

[128512768_create_swarm_sph_dmesh_js_e13980781.txt](https://github.com/underworldcode/underworld2/files/5627050/128512768_create_swarm_sph_dmesh_js_e13980781.txt)
[128512768_create_swarm_sph_dmesh.txt](https://github.com/underworldcode/underworld2/files/5627053/128512768_create_swarm_sph_dmesh.txt)

**Comment by arijitlaik** [comment]
Hi @gthyagi, for me something like this works in parallel. 

# xO = original mesh coordX array
# yO = original mesh coordY array

# refinement code here

# xR = refined mesh coordX array
# yR = refined mesh coordY array

with mesh.deform_mesh():
        if refineHoriz:
            mesh.data[:, 0] = np.interp(mesh.data[:, 0], xO, xR)
        if refineVert:
            mesh.data[:, 1] = np.interp(mesh.data[:, 1], yO, yR)

**Comment by jmansour** [comment]
Something like what @arijitlaik is the correct way to do this. You should not rely on the indexing. As you've discovered, it is not consistent across different parallel partitions. 

The key here is to define a _point-wise_ function, which takes only a coordinate as input (the vertex old location), and produces only a coordinate as output (the vertex new location).  This way you are not dependent on the indexing.

**Comment by gthyagi** [comment]
Thanks @arijitlaik @jmansour. That is what I was going to do. I ditched the indices of the "MaxI_VertexSet" and then used to mesh data to collect the indices of the layers. It worked!
