### ISSUE TITLE
Failed Build on Raijin

### ISSUE THREAD

**Issue by mirkovelic** [underworldcode/underworld2#52]
Code will not build on raijin. Fails at the h5py stage.
If h5py is removed then the build fails elsewhere.

**Comment by jmansour** [comment]
didn't we have it built previously on raijin?  what's changed?

**Comment by mirkovelic** [comment]
h5py as far as I recall.

**Comment by jmansour** [comment]
i though julian got it working with h5py.  i could be mistaken.

**Comment by mirkovelic** [comment]
I am not sure about that.

**Comment by jmansour** [comment]
on raijin, do you need to submit mpi jobs to the queue, or can they be run on the login node?  h5py needs to do an mpi_init, and this can trip up the configuration if it doesn't work.

**Comment by jmansour** [comment]
Ok, the following got me up to the build stage, but it fails there due to some other issue.  What were your previously working instructions?  I think the issue isn't due to anything new, so perhaps the previous instructions blended in might help.  In particular, the compiler choice.  

```
cd ~
module purge
module load gcc/4.9.0
module load python/2.7.5 
module load mpi4py
module load petsc/3.4.3
module load openmpi/1.6.3
module load hdf5/1.8.10p
export HDF5_VERSION=1.8.10

wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
tar zxf six-1.10.0.tar.gz
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0

cd underworld2/libUnderworld
./configure.py --python-dir=$PYTHON_ROOT
```

**Comment by mirkovelic** [comment]
How did you come up that combo?
It's like guessing a combination lock.

Does it work with a newer version of petsc?

**Comment by mirkovelic** [comment]
I suppose the version of mpi should determine several of these.

**Comment by jmansour** [comment]
for mpi i chose the version linked against mpi4py.

gcc i only added after the config so prob just ignore it. perhaps we used
icc last time?

i tried petsc 3.5 but it didnt work immediately so i reverted to the
earlier.

**Comment by mirkovelic** [comment]
Yeah....I might have had the wrong mpi linked to the petsc I was trying to
use.

**Comment by jmansour** [comment]
this builds:
```
cd ~
git clone git clone https://github.com/underworldcode/underworld2

module purge
module load gcc/4.7.3
module load python/2.7.5 
module load mpi4py
module load openmpi/1.6.3
module load hdf5/1.8.10p

export HDF5_VERSION=1.8.10
export PETSC_DIR=/projects/Underworld/petsc-3.6.1

wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
tar zxf six-1.10.0.tar.gz
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0

cd underworld2/libUnderworld
./configure.py --python-dir=$PYTHON_ROOT
./scons.py 
```
There are some MPI issues flagged at runtime, but not sure if it's critical.

**Comment by mirkovelic** [comment]
What is PYTHON_ROOT for?

I could have sworn I tried this exact build recipe except for the
PYTHON_ROOT and six stuff

**Comment by mirkovelic** [comment]
Actually I rebuilt the petsc in that directory last night.

**Comment by jmansour** [comment]
I think without it, underworld was building against python2.6 headers that were in system directories on raijin, and this was causing issues at runtime.  The PYTHON_ROOT variable points to the actual python the python module provides. 

It's possibly more of an issue when you're building h5py.

**Comment by mirkovelic** [comment]
I managed to build h5py last night and got past that.

When I then built UW I found that I needed to run swig again.

I finally remembered that I needed to run swig on a different machine than
raijin and upload the files.
So now it compiled. I had a different recipe than yours last night I would
guess that my problem
was the swig issue after all.

So how did you manage to compile and run stuff without reswigging offsite?

**Comment by jmansour** [comment]
Can't give away all my secrets Mirki!

Nah, I swigged elsewhere then rsynced.  

So did you need the PYTHON_ROOT business?  Possibly it's not required.

**Comment by mirkovelic** [comment]
Sneaky sneaky sneaky.

I reckon we likely don't need the PYTHON_ROOT stuff.

We should put some clear instructions somewhere for raijin.
Especially the reswigging bit. I had forgotten about that.

**Comment by jmansour** [comment]
We can possibly get rid of the function pointers that cause the issues.  One of them isn't used at all, and the other is only used once (which kinda defeats the purpose of a function pointer).

**Comment by jmansour** [comment]
just ran a test, and the PYTHON_ROOT is required if you want configure to build h5py for you.

**Comment by dansand** [comment]
Hi guys, just trying to follow these instructions. I'm running into problems when ./configure.py tries to build  h5py... 

`Checking for package H5py... Can't find a built version of the h5py module ... building h5py  Building private h5py version at /home/563/dds563/underworld2/h5py`
...
`Failed building h5py `

Did you guys specify a pre-built h5py in your configure flags?

**Comment by lmoresi** [comment]
But I guess the one thing about raijin is that we have the centralised build everyone can use.

So as long as somebody is prepared to maintain it,  even a complicated build is survivable.

Can we just get a path to a working build of the stable and the dev (master) branches ?

L


On 20 February 2016 at 11:48:44 am, Dan Sandiford (notifications@github.com<mailto:notifications@github.com>) wrote:

Hi guys, just trying to follow these instructions. I'm running into problems when ./configure.py tries to build h5py...

Checking for package H5py... Can't find a built version of the h5py module ... building h5py Building private h5py version at /home/563/dds563/underworld2/h5py
...
Failed building h5py

Did you guys specify a pre-built h5py in your configure flags?

—
Reply to this email directly or view it on GitHub<https://github.com/underworldcode/underworld2/issues/52#issuecomment-186470131>.

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>

**Comment by jmansour** [comment]
i'm pretty sure those instructions work for me Dan, but will give it
another shot shortly.  make sure you don't have any other environment
variables set.

We'll setup a community install in /projects/Underworld soon.

**Comment by mirkovelic** [comment]
module purge
module load gcc/4.7.3
module load python/2.7.5
module load mpi4py
module load openmpi/1.6.3
module load hdf5/1.8.10p

export HDF5_VERSION=1.8.10
export PETSC_DIR=/projects/Underworld/petsc-3.6.1

wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
tar zxf six-1.10.0.tar.gz
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0

cd underworld2/libUnderworld
./configure.py --python-dir=$PYTHON_ROOT

Yes ..worked for me too.
i.e. h5py was built by configure.

But you will have to re-swig on a machine with a newer version of swig and
copy the files across and compile.
This is not related to the h5py thing though.

**Comment by mirkovelic** [comment]
There is no 'stable' branch. That is what 'master' is. The default checkout
is 'master'

There is a development branch:
If you want to do development. Then after checking out do:

git checkout development

**Comment by jmansour** [comment]
here's my current build recipe using system petsc

```
module purge
module load gcc/4.9.0
module load python/2.7.5
module load mpi4py
module load petsc/3.6.3
module load openmpi/1.10.2
module load hdf5/1.8.14p

export HDF5_VERSION=1.8.14

wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
tar zxf six-1.10.0.tar.gz
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0

cd underworld2/libUnderworld
./configure.py --python-dir=$PYTHON_ROOT
# YOU STILL NEED TO GENERATE THE SWIG BINDINGS 
# ELSEWHERE AND COPY THEM INTO libUnderworld/libUnderworldPy
./scons.py

```

However at import time I get this message

```
>>> import underworld
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.  

The process that invoked fork was:

  Local host:          raijin2 (PID 25417)
  MPI_COMM_WORLD rank: 0

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
```

I'm not sure what is calling fork.  Possibly this can be safely ignored.  Will keep investigating.

**Comment by lmoresi** [comment]
That's different from my experience - I can write up my recipe. Which uses our petsc build, pip and my own swig.

Sent from my iPhone

On 5 May 2016, at 09:28, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


here's my current build recipe using system petsc

module purge
module load gcc/4.9.0
module load python/2.7.5
module load mpi4py
module load petsc/3.6.3
module load openmpi/1.10.2
module load hdf5/1.8.14p

export HDF5_VERSION=1.8.14

wget https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz
tar zxf six-1.10.0.tar.gz
export PYTHONPATH=$PYTHONPATH:$HOME/six-1.10.0

cd underworld2/libUnderworld
./configure.py --python-dir=$PYTHON_ROOT
# YOU STILL NEED TO GENERATE THE SWIG BINDINGS
# ELSEWHERE AND COPY THEM INTO libUnderworld/libUnderworldPy
./scons.py



However at import time I get this message

>>> import underworld
--------------------------------------------------------------------------
An MPI process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your MPI job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          raijin2 (PID 25417)
  MPI_COMM_WORLD rank: 0

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------


I'm not sure what is calling fork. Possibly this can be safely ignored. Will keep investigating.

**Comment by RebeccaFarrington** [comment]
I’ll be needing to build on raijin this week, so I’m happy to try both …

send it through

**Comment by julesghub** [comment]
obsolete! see installation guides in the docs.
