### ISSUE TITLE
multigrid method for a case with 32x32x2 elements per core

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#521]
Hi all,

Hope you are all doing well recently. I am trying to generate a 3D model that is very narrow (and thus only one element assigned) along one direction. This setup induces the number of elements in two directions much larger than the third one.  I tried to use the default setup for multigrid as below in my code:
```
solver = uw.systems.Solver(stokes)
solver.set_penalty(1.0e2)
solver.set_inner_method("mg")
solver.options.A11.ksp_rtol=2.5e-6
solver.options.scr.ksp_rtol=2.5e-6

```
The standard output file indicates that only one layer of multigrid is applied. 
![image](https://user-images.githubusercontent.com/26615840/105009637-ad4b5180-5a75-11eb-88ed-1fa81d4471c4.png)

I guess this is because the number of mg levels in each direction need to identical by default. Are there any options allowing me to set mg levels separately for each direction? Or maybe mg is not applicable to this case in uw? Please give me your suggestions and comments. Thanks a lot.

Best regards,
Ting

**Comment by jmansour** [comment]
I don't think this will be possible Ting. Perhaps a directly parallel solver such as MUMPS might be a better option here.

**Comment by tingyang2004** [comment]
Thanks, John, MUMPS does work in my case.
