### ISSUE TITLE
Constructing a Stg_ObjectAdaptor where there the data pointer is NULL is illegal

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#524]
Hi all,

Occasionally my slab-subduction scripts stop running and report the following issue information after a few thousand steps. I did not observe this issue in my previous models that usually finished the job in around 1-2 thousand steps. So maybe this issue occurs only when the script has been run for over several thousand steps. Do you have any suggestions on how this issue can be avoided? Please let me know if you want to know more information. Thanks a lot.

Best regards,
Ting

![image](https://user-images.githubusercontent.com/26615840/108176830-6cf6f600-713d-11eb-9ead-4ed3c11da898.png)

![image](https://user-images.githubusercontent.com/26615840/108178518-7bdea800-713f-11eb-9f0d-461e898c8965.png)

**Comment by jmansour** [comment]
That's a strange error..  My guess is that there's a memory leak and you've run out of memory.  I'd suggest monitoring the system memory usage to confirm. 

Also, I know it can be painful to update, but you're using a relatively old version of underworld. I'd suggest also updating and seeing if the issue persists.

**Comment by tingyang2004** [comment]
Thanks a lot, John.  I will see if this issue is because the system memory usage was exhausted. I will update to python3 in the next few months.

Best regards,
Ting

**Comment by tingyang2004** [comment]
Thanks a lot, John.  I will see if this issue is because the system memory usage was exhausted. I will update to python3 in the next few months.

Best regards,
Ting

**Comment by julesghub** [comment]
Closing this ticket. If still an issue please reopen.

**Comment by LemonBoy68** [comment]
Hi, everyone~

The dramatic thing is that the same problem occurred after my model was run for hundreds of steps (I can guarantee that this is not a problem with the script file). A similar "twin" task was executed at the same time as this task, and there was no problem. I don't know why the memory leak occurs and it is accidental. But now I know it shouldn’t be a problem with the uw version.

OS: Linux
Python: 3.9
>>> import underworld
>>> underworld.__version__
'2.14.1b'

An uncaught exception was encountered on processor 42.
Traceback (most recent call last):
  File "/work/nnnh/uwgo/hahaha/model16.py", line 1183, in <module>
    stokes = update_stokes(time, viscosityMapFn)
  File "/work/nnnh/uwgo/hahaha/model16.py", line 892, in update_stokes
    stokes = uw.systems.Stokes(velocityField=velocityField,
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/_stgermain.py", line 112, in __call__
    self = super(_SetupClass, cls).__call__(*args, **kwargs)
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/systems/_stokes.py", line 272, in __init__
    self._forceVecTerm   = sle.VectorAssemblyTerm_NA__Fn(   integrationSwarm=intswarm,
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/_stgermain.py", line 112, in __call__
    self = super(_SetupClass, cls).__call__(*args, **kwargs)
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/_stgermain.py", line 203, in __new__
    self._objpointerDict = StgCreateInstances(fullDictionary)
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/_stgermain.py", line 362, in StgCreateInstances
    SetStgDictionaryFromPyDict( pyUWDict, stgRootDict )
  File "/work/nnnh/anaconda3/envs/uwgo_icc/lib/python3.9/site-packages/underworld/_stgermain.py", line 323, in SetStgDictionaryFromPyDict
    ioHandler = libUnderworld.StGermain.XML_IO_Handler_New()
RuntimeError: Error encountered. Full restart recommended as exception safety not guaranteed. Error message:
Constructing a Stg_ObjectAdaptor where there the data pointer is NULL is illegal.

Abort(1) on node 42 (rank 42 in comm 496): application called MPI_Abort(comm=0x84000002, 1) - process 42

**Comment by julesghub** [comment]
Happy new year @LemonBoy68,
This is a difficult issue to diagnose. I'd say it's related to a slow memory leak, to confirm can you watch the memory consumption as the model runs. I suspect it's going up and then consuming all the RAM.

Could you provide some details of your environment setup. I understand you're running >=42 cpus and using uw2.14 installed via anaconda. Is your mpi implementation also from conda? Also is your model 2D or 3D?

**Comment by LemonBoy68** [comment]
Hi @julesghub ,

Happy New Year to you too!

Thank you for your response. My model is 2D. I manage my Python environment with Anaconda as it's quite convenient. I manually compiled Underworld2 using Intel's MPI implementation. I ran the model again and didn't encounter any issues this time.

**Comment by julesghub** [comment]
Great news! 
Nice work with the quick switch to Intel's MPI implementation.
Unfortunately anaconda can do things behind the scenes that don't produce an efficient installation of Underworld. I assume this was leading to the memory corruption.

For 2D models, in general, look out for over decomposition in parallel. Sometimes lots of cpus can help with the I/O operations but can degrade the numerical methods because of the communication overhead of lots of cpus.

**Comment by LemonBoy68** [comment]
Hi @julesghub,

I've always installed and updated Underworld in this way, whether on a personal bare machine or on a workstation, including uw3. I've always been curious about what potential role Anaconda could play in this.

Regarding the issue of parallel overhead that you mentioned, I think it's a very good suggestion. I usually run tasks on a single node.
