### ISSUE TITLE
Interpolation error on points near element boundaries

### ISSUE THREAD

**Issue by brmather** [underworldcode/underworld2#528]
Hello!

I have found that if I sprinkle arbitrary points atop my deformed surface boundary, I get ValueErrors when attempting to interpolate a field variable to these points. The points are still deemed outside the domain if I cast them as a swarm variable.

Here is a simplified 2D example illustrating the problem.
[Groundwater_interpolation_error.zip](https://github.com/underworldcode/underworld2/files/6058959/Groundwater_interpolation_error.zip)

My current approach is to find which points fall outside the domain and iteratively move them further within the interior of the model boundary. However, this approach is inefficient especially when dealing with a huge number of points.

Cheers,
Ben

**Comment by jmansour** [comment]
![image](https://user-images.githubusercontent.com/1439389/109450424-f512bf00-7a9e-11eb-9048-c91cfc1cebc5.png)

**Comment by jmansour** [comment]
So I think this is your problem.  When you're distorting your mesh, the start/finish points for the sloped section do not coincide with element boundaries, and hence the first/last elements in this section are actually at different gradients which do not align with your evaluation points.

**Comment by brmather** [comment]
Hmm... interesting.

I was able to evaluate all points for the above example by constructing a 1D interpolant from the top wall of the mesh,

```python
from scipy.interpolate import interp1d
topWall = mesh.specialSets["MaxJ_VertexSet"]

interp_surface = interp1d(mesh.data[topWall,0], mesh.data[topWall,1])
```

But the 2D interpolation classes in scipy seem not to adequately capture the topology of the top boundary wall. Is there an inbuilt uw function that will paste my points onto the mesh?

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1614578138/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/1954b94b7b53e2d4a6e53045f83a141b/9efab2399c7c560b34de477b9aa0a465/newton.gif]
What’s wrong with stripy in 2D ?

Prof Louis Moresi
louis.moresi@anu.edu.au
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Mon, Mar 1, 2021 at 4:51 PM, Ben Mather <notifications@github.com> wrote:

Hmm... interesting.

I was able to evaluate all points for the above example by constructing a 1D interpolant from the top wall of the mesh,

from scipy.interpolate import interp1d
topWall = mesh.specialSets["MaxJ_VertexSet"]

interp_surface = interp1d(mesh.data[topWall,0], mesh.data[topWall,1])

But the 2D interpolation classes in scipy seem not to adequately capture the topology of the top boundary wall. Is there an inbuilt uw function that will paste my points onto the mesh?

**Comment by brmather** [comment]
It keeps crashing my kernel!

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1614579546/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/499ed56cb6a4384b6ba77ee982c6941c/9efab2399c7c560b34de477b9aa0a465/newton.gif]
Sorry - better contact the developers about that.

Louis

On Mon, Mar 1, 2021 at 5:16 PM, Ben Mather <notifications@github.com> wrote:

It keeps crashing my kernel!

**Comment by brmather** [comment]
Here is my current implementation:

```python
def sprinkle_observations(obs_xyz, dz=10.0):
    """
    Place observations on top boundary wall of the mesh - or pretty close to... (parallel safe)
    """
    inside_particles_g = np.zeros(obs_xyz.shape[0], dtype=np.int32)

    while not inside_particles_g.all():
        swarm_well = uw.swarm.Swarm(mesh=mesh, particleEscape=False)
        particle_index = swarm_well.add_particles_with_coordinates(obs_xyz)

        inside_particles_l = (particle_index >= 0).astype(np.int32)
        inside_particles_g.fill(0)

        comm.Allreduce([inside_particles_l, MPI.INT], [inside_particles_g, MPI.INT], op=MPI.SUM)

        # print(comm.rank, np.count_nonzero(inside_particles_g == 0))
        obs_xyz[inside_particles_g == 0, 2] -= dz
    
    return obs_xyz
```

You start by placing the observations above the mesh, and iteratively lower them by `dz` until it breaches an element. Not at all elegant, but it does the job!

**Comment by jmansour** [comment]
Some other possibilities:

1. Shuffle elements in the x direction to force alignment with your required topology. This could get ugly for complex topologies, but if it's piecewise linear it should be okay, although may still be fiddly when accounting for parallel operation. 
2. Keep mesh unchanged in x-direction and instead shuffle required topology end points to align with closest element boundaries.  This will be easier I suspect. 
3. Create a _height_ variable which you can then use to _paste_ the evaluation points onto the mesh surface... actually this could get difficult in parallel.
4. Use a mass-sink along the line where you require particles, then drops some particles nearby, solve Stokes and advect them towards the line.
