### ISSUE TITLE
Solver bug on latest comitt

### ISSUE THREAD

**Issue by dansand** [underworldcode/underworld2#53]
Just tried a fresh install on ubuntu, importing underworld gave this error:

ImportError: /home/ubuntu/underworlds/underworld2/libUnderworld/build/lib/libSolvers.so: undefined symbol: KSPGetTotalIterations

**Comment by jmansour** [comment]
was it a completely fresh checkout?  if it wasn't, did you re-run swig?

**Comment by mirkovelic** [comment]
Oops....looks like that might only be in petsc 3.6+

**Comment by mirkovelic** [comment]
Sent a fix through...
