### ISSUE TITLE
PNG files not writing with glucifer

### ISSUE THREAD

**Issue by tlczech** [underworldcode/underworld2#530]
Hello, I am using an older version of Underworld2 because I am using a singularity on Kamiak at WSU. Recently I updated from using version 2.6 to 2.8 and now my png files are not writing anymore. Do you know how I can fix this? I tried using the new vis but the module could not be found. I have attached my py file below. 
[ra8_m4_c3_20.pdf](https://github.com/underworldcode/underworld2/files/6120457/ra8_m4_c3_20.pdf)

Thanks! 
Tessa C

**Comment by lmoresi** [comment]
Hi Tessa ... if you would like to paste your script into the issue tracker here, use the syntax. 

    ```python
    # Simple Craton Case with Weakzones
    # First, let's tell Python what it needs:
    # In[24]:
    import underworld as uw
    ``` 
as it is going to be a lot easier for us to read (and for anybody else to search if they have similar issues). The pdf is hard to disentangle other than a couple of lines at a time !

**Comment by jmansour** [comment]
Hi Tessa

For UW2.8, we renamed and moved `glucifer` to `underworld.visualisation`.  So where previously you would do something like this:

```python
import glucifer
figure = glucifer.Figure()
```

now you would do this

```python
import underworld.visualisation as vis
figure = vis.Figure()
```

Here's an example of usage

https://github.com/underworldcode/underworld2/blob/master/docs/examples/01_Steady_State_Heat.ipynb

**Comment by tlczech** [comment]
Ah sorry, first time Git user here! 

```python
    if step % writestep == 0. and writefigures:
        figtemp.save_image(outputPath + 'temperatureplot_%i' %step)
        figEta.save_image(outputPath + 'viscosityplot_%i' %step)
        figMaterialMesh.save_image(outputPath + 'materialsplot_%i' %step)
```

We did try the visualisation but it the module was not found when we tried running it

**Comment by jmansour** [comment]
HI @tlczech. A few questions:

1. Does the model continue quietly as if the images are being created, but no image file is generated?
2. Are there any other outputs or error messages?
3. Are you able to generate any files from within your Python scripts? 

Possibly there's been some changes to the Singularity config on the system and the volume mapping is working differently (or not at all.  You can try writing a file within your script using:

```python
with open("test_output.txt", "w") as text_file:
    text_file.write("This is a test file to see if files are being generated as expected. :-)" )
```

**Comment by tlczech** [comment]
Hi @jmansour 
Yes, the model continues to run and other .h5 and output files are written but it it ends by timing out not when it reaches the last step (not sure if this is related). The error file does say "Failed to open X display". I am not seeing anything strange in the other output files. The test_output.txt did write correctly to the output directory. 
Thanks,
Tessa

**Comment by jmansour** [comment]
@OKaluza any thoughts on this?  They're using Singularity, but (if I recall correctly) the admins are building a custom image for use on their system.

**Comment by OKaluza** [comment]
The "failed to open X display" suggests it is built to use X11 and Xvfb is
not running in the container, so either: build with OSMesa instead or fix
Xvfb and ensure $DISPLAY is set, that's all I've got. I've gone bush so
can't really check anything out until next week.

**Comment by jmansour** [comment]
Underworld support from deep in the Australian outback! 🙂

@tlczech, can you add this to the **very top** of your script (specifically, before you import `underworld` or `glucifer`) and try again:

```python
import os
os.environ["GLUCIFER_USE_XVFB"]="1"
```

**Comment by tlczech** [comment]
Thank you @OKaluza and @jmansour, that worked!!! I now have the png files!

**Comment by jmansour** [comment]
Okay, excellent!  

That environment variable is normally automatically set for container images, but perhaps when the image was rebuilt it wasn't included for some reason. 

You can modify your scripts as per my instructions above, or you _should_ be able to simply set the environment variable from your shell or launch script (from bash `export GLUCIFER_USE_XVFB=1` for example), but how your environment variables are ingested will depend on the system setup.

I'll close this issue for now, but feel free to reopen if necessary.
