### ISSUE TITLE
User warning message will be useful with the following projection error or looks like a bug

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#531]
Hi UW team,

I am trying to project information from the swarm to submesh and then use the submesh continuous field to find the field value at mesh coordinates. Doing this entire process to minimize the projection error while projecting information from particles to mesh. 
```python
stressField_sMesh = mesh.subMesh.add_variable(nodeDofCount=6) 
# saving stress variable (swarm) and field (submesh)
stressVariable.data[:] = stressFn.evaluate(swarm)[:]
stressVariableHnd = stressVariable.save(outputPath+'stressVariable.'+ str(step).zfill(5) +'.h5')
stress_proj = uw.utils.MeshVariable_Projection(stressField_sMesh, stressVariable, voronoi_swarm=swarm, type=0)
stress_proj.solve()
stressDField.data[:] = stressField_sMesh.evaluate(mesh)[:,0:3]
stressNDField.data[:] = stressField_sMesh.evaluate(mesh)[:,3:6]
```

This process works fine in serial. However, in parallel it throws following error. This error makes sense that mesh coordinates are always above the submesh coordinates. It seems different interpolation method or parallel communication causes this error. While constructing model in jupyter notebook, some sort of warning to the users will be useful regarding this issue.

```python
Error message:
FeVariable interpolation at location (3.00781, 0.179688, 0.242188) does not appear to be valid.
Location is probably outside local domain.
An uncaught exception was encountered on processor 717.
Traceback (most recent call last):
  File "/home/565/tg7098/uwgeo_models/subduction_3d_var_slab_dep_uw.py", line 827, in <module>
    checkpoint()
  File "/home/565/tg7098/uwgeo_models/subduction_3d_var_slab_dep_uw.py", line 788, in checkpoint
    stressDField.data[:]        = stressField_sMesh.evaluate(mesh)[:,0:3]
  File "/home/565/tg7098/uw_tools/jules_uwgeo_env/UWRegionalMesh/lib/python3.7/site-packages/underworld/function/_function.py", line 912, in evaluate
    return _cfn.Query(self._fncself).query(inputData._get_iterator())
ValueError: Issue utilising function of class 'MeshVariable'

For full func debug info on all processes, set the UW_WORLD_FUNC_MESSAGES environment variable.
```

**Comment by gthyagi** [comment]
Note: Above way of evaluating field values on mesh coordinates using submesh field works in 3D spherical mesh models. The error occurred for 3D cartesian model of resolution 512*512*128. It seems like a bug.

**Comment by gthyagi** [comment]
Models Details: 
```python
resX = 512
resY = 512
resZ = 128
mesh          = uw.mesh.FeMesh_Cartesian( elementRes  = (resX, resY, resZ),
                                          minCoord    = (0., 0., 0.),
                                          maxCoord    = (4., 4., 1.) )
```

**Comment by jmansour** [comment]
Does this error always occur in parallel?  How many procs?  Perhaps set `UW_WORLD_FUNC_MESSAGES=1 ` and try running under the smallest mesh/proc size configuration that reproduces the issue.

**Comment by gthyagi** [comment]
Yes, it only occurs in parallel for cartesian models. For the recent job, I requested 1058 cpus. I will submit the same job by changing the resolution and halving requested cpus.

**Comment by gthyagi** [comment]
@jmansour , I have submitted a job with smaller resolution and ncpus. Still encountering the same issue. I am attaching error file and script for your reference.
[subduction_3d_var_slab_dep_uw_js.e19204950.txt](https://github.com/underworldcode/underworld2/files/6153958/subduction_3d_var_slab_dep_uw_js.e19204950.txt)
[subduction_3d_var_slab_dep_uw_js.o19204950.txt](https://github.com/underworldcode/underworld2/files/6153959/subduction_3d_var_slab_dep_uw_js.o19204950.txt)
[subduction_3d_var_slab_dep_uw.py.txt](https://github.com/underworldcode/underworld2/files/6153960/subduction_3d_var_slab_dep_uw.py.txt)

**Comment by jmansour** [comment]
@julesghub should the submesh have a shadow space?

**Comment by jmansour** [comment]
@gthyagi, what if as an alternative you simply project back to the constant mesh?

**Comment by gthyagi** [comment]
Projection of information from swarm to mesh and submesh works without any issue. The only problem currently having is to use the submesh field to evaluate at mesh coordinates.

**Comment by jmansour** [comment]
Yep, I'm suggesting that once you projected mesh->submesh, you then project submesh->mesh.

**Comment by jmansour** [comment]
Did you find a satisfactory solution @gthyagi ?

**Comment by gthyagi** [comment]
@jmansour I found that projection errors are always significant (due to combination of viscous and visco-plastic rheologies) either I save them of mesh or submesh. Then I decided to save the stress values on particles and use nearest neighbour algorithm in post-processing step to find the particles close to the interfaces. This generate better results compared to mesh data.

**Comment by jmansour** [comment]
I'll close this ticket for now, but feel free to reopen as required.
