### ISSUE TITLE
Failed to install underworld2 on MacOS

### ISSUE THREAD

**Issue by lxrat** [underworldcode/underworld2#532]
Hi, UW friends,
I am trying to install UW2 on my Macbook (MacOS). However, there is an error in my first installing step, does anyone knows how to repair this error?  Thanks in advance.
Xianrui

The error is in the following:

lxr@LideMacBook-Pro libUnderworld % ./configure.py --prefix=/underworld/install/directory
scons: Reading SConscript files ...
Checking whether the C compiler works... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package Python... no
****  ERROR ****
Failed to locate required package Python.
Details in 'config.log'

——————————I checked the  'config.log' file, and post some information of it as below——————

file /Users/lixianrui/underworld2/underworld/libUnderworld/config/config.py,line 108:
	Configure(confdir = .sconf_temp)

Configuring using:
  /Users/lixianrui/opt/anaconda3/bin/scons --config=force -f SConfigure --prefix=/usr/local/underworld2

file /Users/lixianrui/underworld2/underworld/libUnderworld/config/cc.py,line 10:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking whether the C compiler works... 
.sconf_temp/conftest_737c003a897167642b70f8cdde8a0eaf_0.c <-
  |
  |int main(void)
  |{
  |    return 0;
  |}
  |
gcc -o .sconf_temp/conftest_737c003a897167642b70f8cdde8a0eaf_0_542f5130c3a8edefa8483dd27706e49d.o -c -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 .sconf_temp/conftest_737c003a897167642b70f8cdde8a0eaf_0.c
scons: Configure: yes
......
......
......

file /Users/lixianrui/underworld2/underworld/libUnderworld/config/Package.py,line 153:
	Configure(confdir = .sconf_temp)
scons: Configure: Checking for C library None... 
.sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_0.c <-
  |
  |
  |#include "Python.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
mpicc -o .sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_0.o -c -Wall -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DHAVE_LIBM -DU_SHOW_CPLUSPLUS_API=0 -DHAVE_LIBXML2 -DHAVE_MPI .sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_0.c
.sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_0.c:3:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^~~~~~~~~~
1 error generated.
scons: Configure: no

scons: Configure: Checking for C++ library None... 
.sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_1.cpp <-
  |
  |
  |#include "Python.h"
  |
  |int
  |main() {
  |  
  |return 0;
  |}
  |
mpicxx -o .sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_1.o -c -std=c++11 -Wall -D__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES=0 -DHAVE_LIBM -DU_SHOW_CPLUSPLUS_API=0 -DHAVE_LIBXML2 -DHAVE_MPI .sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_1.cpp
.sconf_temp/conftest_4dd9ef574ee65f2634afaebc38b73108_1.cpp:3:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^~~~~~~~~~
1 error generated.
scons: Configure: no

  Failed to find static or shared libraries for 'Python'.
  Static missing: ['python3.5m']
  Shared missing: ['python3.5m']
  Looked in: ['/usr/lib']
  Failed to find static or shared libraries for 'Python'.
  Static missing: ['python3.6m']
  Shared missing: ['python3.6m']
  Looked in: ['/usr/lib']
  Failed to find static or shared libraries for 'Python'.
  Static missing: ['python3.7m']
  Shared missing: ['python3.7m']
  Looked in: ['/usr/lib']
  Failed to find static or shared libraries for 'Python'.
  Static missing: ['python3.8']
  Shared missing: ['python3.8']
 ......
 ......
 ......

**Comment by jmansour** [comment]
I'd suggest you try installing via pip:

```shell
pip3 install underworld
```

It's usually a good idea to setup a Python-virtualenv first, and then install `underworld` within the virtualenv.  Otherwise, you may need to install using `sudo`. 

Alternatively you might consider using Docker.  There's some further info on our documentation page, but feel free to ask questions here if you're having difficulty. 

https://underworld2.readthedocs.io/en/latest/Installation.html

@julesghub, @rbeucher, we should update the installation page for the next release as it's somewhat out of date.

**Comment by lxrat** [comment]
Hi, jmansour. Thank you for your suggestions. I did as you said,  using the "pip3 install underworld".  But it doesn't work and still has some error information, finally, it is failed to install the UW2 on my macOS. Since I am not skilled in programming, I decide to use Docker instead of native installing. 

Good to hear that the installation page would be updated for the upcoming release, hope it could be more detailed. Then I will try again.

**Comment by jmansour** [comment]
Okay, glad you had success via Docker. 

I'll close this ticket, but reopen if necessary.
