### ISSUE TITLE
Change HDF5 write mode "a"

### ISSUE THREAD

**Issue by brmather** [underworldcode/underworld2#533]
Using the "append" mode to save mesh or swarm information can result in exceptionally large files where only a small chunk of a given dataset is actually being used. To replicate:

1. Run any model at high resolution and save the field variables
2. Run the same model at lower resolution and save the field variables

The filesize remains the same from 1 to 2. Instead, the "w" write mode overwrites any existing files of the same file name.

**Comment by brmather** [comment]
I discovered this issue after transferring nearly 1TB of mostly redundant HDF5 files from Gadi over my dodgy NBN connection!

**Comment by jmansour** [comment]
Yep, I can reproduce this.  Good find!  Surprised it hasn't been noticed sooner.  

Will fix for next release.

**Comment by jmansour** [comment]
Fix is in release queue.  Will close this issue, but feel free to reopen as necessary.
