### ISSUE TITLE
Adding a plane of passive tracers in 3D

### ISSUE THREAD

**Issue by tmar227** [underworldcode/underworld2#534]
Hello,

I am trying to add passive tracers that will monitor flow into/out of a slab gap in a subducting slab in 3D without using the UWGeodynamics package, just uw2. My goal was to add in a diagonal (~45 degree) plane of passive tracer particles at depth that cover the size of the hole at model inititation. It would be a grid of passive tracers of sorts if this is possible such that the particles would go from some minimum X value to a maximum X value, while also changing in the Y (vertical dimension) at the same time, and the plane of tracers would also extend from some minimum Z value to maximum Z. Additionally, to have the tracer locations be viewable in Paraview at each output step via .XDMF is ideal, similar to the way it is accomplished with the Model object and Add_passive_tracers in UWGeodynamics.

The coordinates for my hole, for example, are:
holex1 = nd(2250. * u.kilometer)
holex2 = nd(2375. * u.kilometer)
holey1 = nd(-150. * u.kilometer)
holey2 = nd(-350. * u.kilometer)
holez1 = nd(1350. * u.kilometer)
holez2 = nd(1650. * u.kilometer)

Because it is a 2D plane projected in 3D it would not have a thickness but would still change in the X and Y directions at the same time because it is a tilted/diagonal plane. I have linked a conceptual image of the problem below.

I have ran into a good bit of errors attempting to solve this so far so was hoping to try my luck here! I will try and keep looking for an example that utilizes this type of problem in the meantime.

Thank you!

![tracerPlaneConcept](https://user-images.githubusercontent.com/66849152/114213583-2352ac80-9931-11eb-9c2b-835f66ef0e3f.jpg)

**Comment by jmansour** [comment]
Hi @tmar227 

Have you looked at Numpy's `meshgrid` method? 

https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html

Seems to me you should be able to use this to generate the required coordinate array, and you'll then use that to populate the swarm. 

https://underworld2.readthedocs.io/en/latest/build/user_guide/03_Swarms.html

There are some details on XDMF generation here, but if it doesn't cover what you're wanting to do let us know:

https://underworld2.readthedocs.io/en/latest/build/user_guide/06_Utilities.html

**Comment by tmar227** [comment]
Hello @jmansour ,

Thank you for your response! So far using meshgrid I have the following:

xFlow = np.linspace(nd(2800. * u.km), nd(3300. * u.km), num=500)
yFlow = np.linspace(nd(-300. * u.km), nd(-100. * u.km), num=500)
zFlow = np.linspace(nd(1400. * u.km), nd(1600. * u.km), num=500)

xG, yG, zG = np.meshgrid(xFlow,yFlow,zFlow)

swarmFlow = uw.swarm.Swarm(mesh=mesh)
swarmFlow_coords = (xG,yG,zG)
result = swarmFlow.add_particles_with_coordinates(swarmFlow_coords)

This produces the error:         'coordinateArray' must be provided as a numpy array.

There may be a small error in here that I haven't noticed as I am still learning python, but thank you again for your help!

**Comment by jmansour** [comment]
Actually, perhaps it's better to skip `numpy.meshgrid()` and just generate the required array manually. Note that `Swarm.add_particles_with_coordinates()` expects a _list_ of particles.  

Something like this perhaps:
```python
nx = 10
ny = 10
nz = 10
xFlow = np.linspace(nd(2800. * u.km), nd(3300. * u.km), num=nx)
yFlow = np.linspace(nd(-300. * u.km), nd(-100. * u.km), num=ny)
zFlow = np.linspace(nd(1400. * u.km), nd(1600. * u.km), num=nz)

swarmFlow_coords = np.zeros( (nx*ny*nz,3) )

index = 0
for xcoord in xFlow:
    for ycoord in yFlow:
        for zcoord in zFlow:
            swarmFlow_coords[ index, : ] = (xcoord,ycoord,zcoord)
            index+=1

swarmFlow = uw.swarm.Swarm(mesh=mesh)
result = swarmFlow.add_particles_with_coordinates(swarmFlow_coords)
```
I haven't tested the above so it might need some adjustments. It won't be the most efficient option, but it's probably fine.

**Comment by gthyagi** [comment]
Hi @tmar227 ,

Here is my solution to create plane coordinates. I have pasted below the two functions I used to create random planes in 3D. Mathematically, planes extend infinity long in space. You need to try different values of _x_start, _x_end and _y_start, _y_end to get plane coordinates in the desired range. And _x_num and _y_num controls the resolution of the plane coordinates. Note, however, creating planes parallel to x, y, z axis are tricky. In your cases, planes have some angle so no issue. Then use those coordinates to create passive tracers as @jmansour mentioned. For reference I am attaching two images.

```python3
def get_plane_pts_grid(_point, _normal, _x_start='', _x_end='', _x_num=7):
    """
    Input: Given a point in plane and its normal
    Output: Plane points in grid format
    """
    point  = np.array(_point)
    normal = np.array(_normal)

    # a plane is a*x+b*y+c*z+d=0
    # [a,b,c] is the normal. Thus, we have to calculate
    # d and we're set
    d = -point.dot(normal)

    # create x,y
    xx, yy = np.meshgrid(np.linspace(_x_start, _x_end, _x_num, endpoint=True), 
                         np.linspace(0, 4.0, 513, endpoint=True)) # here _y_start, _y_end

    # calculate corresponding z
    z = (-normal[0] * xx - normal[1] * yy - d) * 1. /normal[2]
    return (xx, yy, z)

def ravel_meshgrid(_meshgrid):
    """
    Ravels mesh grid formated data to numpy array
    """
    # positions = np.stack(map(np.ravel, west_plane2_pts), axis=1) # another way of ravel
    return np.stack((_meshgrid[0].ravel(), _meshgrid[1].ravel(), _meshgrid[2].ravel()), axis=1)
```
Plane coordinates in 2D view
![Screen Shot 2021-04-29 at 12 46 19 pm](https://user-images.githubusercontent.com/44185316/116497070-da679580-a8e9-11eb-95ba-e391428aa32f.png)

Planes in 3D
![Uploading inf_vel.png…]()

**Comment by tmar227** [comment]
Thank you both for your helpful responses! This should be more than enough to fix my problem.

**Comment by julesghub** [comment]
Closing ticket. If this is still and issue feel free to reopen.
