### ISSUE TITLE
import error when compile uw2 from source

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#536]
**Hi, everyone
There have some import problems here when I compile underworld successfully rom the underworld dev source.**
`>>> import underworld
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gpu/miniconda3/envs/geodynamic/lib/python3.8/site-packages/underworld/__init__.py", line 77, in <module>
    from . import libUnderworld as _libUnderworld
  File "/home/gpu/miniconda3/envs/geodynamic/lib/python3.8/site-packages/underworld/libUnderworld/__init__.py", line 62, in <module>
    from ._version import __version__
ModuleNotFoundError: No module named 'underworld.libUnderworld._version'
`

**There also have a compile error when I also try compile master branch of uw2.** 

`
Search paths:
   ./
   ../build/include/
   ../build/include/StGermain/
   ../build/include/StgDomain/
   ../build/include/StgFEM/
   ../build/include/Solvers/
   ../build/include/PICellerator/
   ../build/include/Underworld/
   ../build/include/gLucifer/
   ../build/include/petsc/
   ../ctools/
   ./swig_lib/python/
   /home/gpu/miniconda3/envs/underworld2/share/swig/4.0.2/python/
   ./swig_lib/
   /home/gpu/miniconda3/envs/underworld2/share/swig/4.0.2/
"compile.log" 488L, 17912C                                 144,1         28%
Function.i:158: Error: Undefined scope 'Fn'
Function.i:158: Error: Template 'Fn::MathRelational' undefined.
Function.i:159: Error: Undefined scope 'Fn'
Function.i:159: Error: Template 'Fn::MathRelational' undefined.
Function.i:162: Error: Undefined scope 'Fn'
Function.i:162: Error: Template 'Fn::MathRelational' undefined.
Function.i:163: Error: Undefined scope 'Fn'
Function.i:163: Error: Template 'Fn::MathRelational' undefined.
Function.i:164: Error: Undefined scope 'Fn'
Function.i:164: Error: Template 'Fn::MathRelational' undefined.
Function.i:165: Error: Undefined scope 'Fn'
Function.i:165: Error: Template 'Fn::MathRelational' undefined.
Function.i:166: Error: Undefined scope 'Fn'
Function.i:166: Error: Template 'Fn::MathRelational' undefined.
StGermain.i:107: Warning 303: %extend defined for an undeclared class IndexSet.
PICellerator.i:66: Warning 303: %extend defined for an undeclared class GeneralSwarm.
Traceback (most recent call last):
  File "./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.`

**Comment by jmansour** [comment]
Hi @tyszwh 

Can you share more information?  

How are you trying build `underworld`?  Are you using `pip`? 

What operating system are you using? 

@rbeucher, does `pip install` work on top of a `conda` environment?

**Comment by rbeucher** [comment]
Hi @tyszwh ,

If you use conda, there is an underworld package available through the geo-down-under channel. 
You can try pip in a conda environment but you need to make sure that you have all the compilers and libraries installed.

Romain

**Comment by tyszwh** [comment]
Hi @jmansour 
I build underworld on ubuntu 20.4, and All dependent packages required by underworld are installed from conda package.
Here is my code list. Maybe there have some environmental problems within it.
[Uploading conda.log…]()


@rbeucher 
I can install it through conda install underworld2. But H5py was not set parallelly.

**Comment by tyszwh** [comment]
The Dev branch works fine (I'm still not very sure whether it is a environmental problem finally).
