### ISSUE TITLE
a minor issue in 06_Utilities.ipynb

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#537]
I happened to spot this little flaw this morning, the volume integration should lie within the square instead of outside it. It is the second cell in 06_Utilities.ipynb. It should be easily seen when you recheck it.

Best regards,
Ting

![image](https://user-images.githubusercontent.com/26615840/115334750-81ec1600-a1ce-11eb-9097-a7339ea07d8e.png)

**Comment by julesghub** [comment]
Thanks @tingyang2004, you're right about this. I'll change it for the upcoming release.

**Comment by julesghub** [comment]
Done - 37810a836e08da84abee145ebad87d4f140c3b37
