### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Dnepropetrovst** [underworldcode/underworld2#539]
When configuring Underworld2 in federal, it keeps telling me that "Failed to locate required package Python". But i already installed python. 

Checking for package Python... no
****  ERROR ****
Failed to locate required package Python.
Details in 'config.log'

**Comment by jmansour** [comment]
You'll also need the Python development files.  On Ubuntu this is the `python3-dev` package. 

What operating system are you using?  I'm not familiar with federal.

**Comment by longgangfan** [comment]
> When configuring Underworld2 in federal, it keeps telling me that "Failed to locate required package Python". But i already installed python.
> 
> Checking for package Python... no
> **** ERROR ****
> Failed to locate required package Python.
> Details in 'config.log'

Tips: 
Please run the commands below in your python,
` import sysconfig`
` sysconfig.get_config_vars('Py_ENABLE_SHARED')`

If the result is not '[1]', you can try to reinstall your python with the option "--enable-shared" while configure.
