### ISSUE TITLE
equation numbering store on fevariable is dangerous

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#54]
Currently when we create a system, the equation number is created and stored on the fevariable.  This will cause issues if the same fevariable is used in an alternate system (which may have different BCs).  

Should store eq numbering to somewhere more appropriate, like the system.

**Comment by julesghub** [comment]
See commit 9fedda8ae7696aecd02e7312d5760bfed3a498b3 + the few commits before it.
EqNums are now created by the SLE system python object and are passed to SolutionVectors, ForceVectors.
