### ISSUE TITLE
Apple Silicon native compilation

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#540]
There have been some queries about this, so here's an issue for people to keep track. 

As far as I can tell, our biggest dependencies,  OpenMPI & PETSc, are supported via Homebrew already:

https://formulae.brew.sh/formula/open-mpi
https://formulae.brew.sh/formula/petsc

So there probably isn't a huge leap to have Underworld natively compiled.

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1619663531/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/b45bbb908fcabee2357216856aa2fcc0/9efab2399c7c560b34de477b9aa0a465/newton.gif]
That would be cool. Conda forge also supports building on apple silicon but petsc has not been rebuilt.

Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Thu, Apr 29, 2021 at 12:21 PM, John Mansour ***@***.***> wrote:

There have been some queries about this, so here's an issue for people to keep track of this.

As far as I can tell, our biggest dependencies, OpenMPI & PETSc, are supported via Homebrew already:

https://formulae.brew.sh/formula/open-mpi
https://formulae.brew.sh/formula/petsc

So there probably isn't a huge leap to have Underworld natively compiled.

**Comment by jmansour** [comment]
https://www.underworldcode.org/articles/how-to-install-underworld-on-mac-osx-big-sur-apple-silicon-m1/

**Comment by rbeucher** [comment]
Still need to get the conda build on M1.
