### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by Dnepropetrovst** [underworldcode/underworld2#541]
Hello everyone,
When done `configure.py`, I meet some problem running `compile.py`. My operation system is Ubuntu 18.04.1.
The output errors are as follows:
```shell
`Starting language-specific parse...
../build/include/StGermain/Base/Container/types.h:112: Warning 314: 'self' is a python keyword, renaming to '_self'
../build/include/StGermain/Base/Automation/Stg_ComponentRegister.h:126: Warning 322: Redundant redeclaration of 'Stg_ComponentRegister_AssertGet',
../build/include/StGermain/Base/Automation/Stg_ComponentRegister.h:115: Warning 322: previous declaration of 'Stg_ComponentRegister_AssertGet'.
../build/include/PICellerator/MaterialPoints/GeneralSwarm.h:106: Warning 313: Unrecognized extern type "C++".
Function.i:115: Error: Template 'FunctionIOTyped' undefined.
Function.i:116: Error: Template 'FunctionIOTyped' undefined.
Function.i:117: Error: Template 'FunctionIOTyped' undefined.
Function.i:118: Error: Template 'FunctionIOTyped' undefined.
Function.i:119: Error: Template 'FunctionIOTyped' undefined.
Function.i:120: Error: Template 'FunctionIOTyped' undefined.
Function.i:121: Error: Template 'FunctionIOTyped' undefined.
Function.i:123: Error: Undefined scope 'Fn'
Function.i:123: Error: Template 'Fn::MathUnary' undefined.
Function.i:124: Error: Undefined scope 'Fn'
Function.i:124: Error: Template 'Fn::MathUnary' undefined.
Function.i:125: Error: Undefined scope 'Fn'
Function.i:125: Error: Template 'Fn::MathUnary' undefined.
Function.i:126: Error: Undefined scope 'Fn'
Function.i:126: Error: Template 'Fn::MathUnary' undefined.
Function.i:127: Error: Undefined scope 'Fn'
Function.i:127: Error: Template 'Fn::MathUnary' undefined.
Function.i:128: Error: Undefined scope 'Fn'
Function.i:128: Error: Template 'Fn::MathUnary' undefined.
Function.i:129: Error: Undefined scope 'Fn'
Function.i:129: Error: Template 'Fn::MathUnary' undefined.
Function.i:130: Error: Undefined scope 'Fn'
Function.i:130: Error: Template 'Fn::MathUnary' undefined.
Function.i:131: Error: Undefined scope 'Fn'
Function.i:131: Error: Template 'Fn::MathUnary' undefined.
Function.i:132: Error: Undefined scope 'Fn'
Function.i:132: Error: Template 'Fn::MathUnary' undefined.
Function.i:133: Error: Undefined scope 'Fn'
Function.i:133: Error: Template 'Fn::MathUnary' undefined.
Function.i:134: Error: Undefined scope 'Fn'
Function.i:134: Error: Template 'Fn::MathUnary' undefined.
Function.i:135: Error: Undefined scope 'Fn'
Function.i:135: Error: Template 'Fn::MathUnary' undefined.
Function.i:136: Error: Undefined scope 'Fn'
Function.i:136: Error: Template 'Fn::MathUnary' undefined.
Function.i:137: Error: Undefined scope 'Fn'
Function.i:137: Error: Template 'Fn::MathUnary' undefined.
Function.i:138: Error: Undefined scope 'Fn'
Function.i:138: Error: Template 'Fn::MathUnary' undefined.
Function.i:139: Error: Undefined scope 'Fn'
Function.i:139: Error: Template 'Fn::MathUnary' undefined.
Function.i:140: Error: Undefined scope 'Fn'
Function.i:140: Error: Template 'Fn::MathUnary' undefined.
Function.i:141: Error: Undefined scope 'Fn'
Function.i:141: Error: Template 'Fn::MathUnary' undefined.
Function.i:142: Error: Undefined scope 'Fn'
Function.i:142: Error: Template 'Fn::MathUnary' undefined.
Function.i:144: Error: Undefined scope 'Fn'
Function.i:144: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:145: Error: Undefined scope 'Fn'
Function.i:145: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:146: Error: Undefined scope 'Fn'
Function.i:146: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:147: Error: Undefined scope 'Fn'
Function.i:147: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:148: Error: Undefined scope 'Fn'
Function.i:148: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:149: Error: Undefined scope 'Fn'
Function.i:149: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:150: Error: Undefined scope 'Fn'
Function.i:150: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:151: Error: Undefined scope 'Fn'
Function.i:151: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:152: Error: Undefined scope 'Fn'
Function.i:152: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:153: Error: Undefined scope 'Fn'
Function.i:153: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:154: Error: Undefined scope 'Fn'
Function.i:154: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:155: Error: Undefined scope 'Fn'
Function.i:155: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:156: Error: Undefined scope 'Fn'
Function.i:156: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:158: Error: Undefined scope 'Fn'
Function.i:158: Error: Template 'Fn::MathRelational' undefined.
Function.i:159: Error: Undefined scope 'Fn'
Function.i:159: Error: Template 'Fn::MathRelational' undefined.
Function.i:162: Error: Undefined scope 'Fn'
Function.i:162: Error: Template 'Fn::MathRelational' undefined.
Function.i:163: Error: Undefined scope 'Fn'
Function.i:163: Error: Template 'Fn::MathRelational' undefined.
Function.i:164: Error: Undefined scope 'Fn'
Function.i:164: Error: Template 'Fn::MathRelational' undefined.
Function.i:165: Error: Undefined scope 'Fn'
Function.i:165: Error: Template 'Fn::MathRelational' undefined.
Function.i:166: Error: Undefined scope 'Fn'
Function.i:166: Error: Template 'Fn::MathRelational' undefined.
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
Traceback (most recent call last):
  File "./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.`
```
I would be appreciate if anyone could tell me how to solve this problem. 
Many thanks in advance.

**Comment by lsli0116** [comment]
I have the same problem!

**Comment by jmansour** [comment]
Hi @Dnepropetrovst 

Can you try the solution posted in #543 ?

**Comment by Dnepropetrovst** [comment]
> Hi @Dnepropetrovst
> 
> Can you try the solution posted in #543 ?

Hi @jmansour 
I tried the v2.11_release, but the same errors came out when i ran `compile.py`.

`Starting language-specific parse...
../build/include/StGermain/Base/Container/types.h:112: Warning 314: 'self' is a python keyword, renaming to '_self'
../build/include/StGermain/Base/Automation/Stg_ComponentRegister.h:126: Warning 322: Redundant redeclaration of 'Stg_ComponentRegister_AssertGet',
../build/include/StGermain/Base/Automation/Stg_ComponentRegister.h:115: Warning 322: previous declaration of 'Stg_ComponentRegister_AssertGet'.
Function.i:117: Error: Template 'FunctionIOTyped' undefined.
Function.i:118: Error: Template 'FunctionIOTyped' undefined.
Function.i:119: Error: Template 'FunctionIOTyped' undefined.
Function.i:120: Error: Template 'FunctionIOTyped' undefined.
Function.i:121: Error: Template 'FunctionIOTyped' undefined.
Function.i:122: Error: Template 'FunctionIOTyped' undefined.
Function.i:123: Error: Template 'FunctionIOTyped' undefined.
Function.i:125: Error: Undefined scope 'Fn'
Function.i:125: Error: Template 'Fn::MathUnary' undefined.
Function.i:126: Error: Undefined scope 'Fn'
Function.i:126: Error: Template 'Fn::MathUnary' undefined.
Function.i:127: Error: Undefined scope 'Fn'
Function.i:127: Error: Template 'Fn::MathUnary' undefined.
Function.i:128: Error: Undefined scope 'Fn'
Function.i:128: Error: Template 'Fn::MathUnary' undefined.
Function.i:129: Error: Undefined scope 'Fn'
Function.i:129: Error: Template 'Fn::MathUnary' undefined.
Function.i:130: Error: Undefined scope 'Fn'
Function.i:130: Error: Template 'Fn::MathUnary' undefined.
Function.i:131: Error: Undefined scope 'Fn'
Function.i:131: Error: Template 'Fn::MathUnary' undefined.
Function.i:132: Error: Undefined scope 'Fn'
Function.i:132: Error: Template 'Fn::MathUnary' undefined.
Function.i:133: Error: Undefined scope 'Fn'
Function.i:133: Error: Template 'Fn::MathUnary' undefined.
Function.i:134: Error: Undefined scope 'Fn'
Function.i:134: Error: Template 'Fn::MathUnary' undefined.
Function.i:135: Error: Undefined scope 'Fn'
Function.i:135: Error: Template 'Fn::MathUnary' undefined.
Function.i:136: Error: Undefined scope 'Fn'
Function.i:136: Error: Template 'Fn::MathUnary' undefined.
Function.i:137: Error: Undefined scope 'Fn'
Function.i:137: Error: Template 'Fn::MathUnary' undefined.
Function.i:138: Error: Undefined scope 'Fn'
Function.i:138: Error: Template 'Fn::MathUnary' undefined.
Function.i:139: Error: Undefined scope 'Fn'
Function.i:139: Error: Template 'Fn::MathUnary' undefined.
Function.i:140: Error: Undefined scope 'Fn'
Function.i:140: Error: Template 'Fn::MathUnary' undefined.
Function.i:141: Error: Undefined scope 'Fn'
Function.i:141: Error: Template 'Fn::MathUnary' undefined.
Function.i:142: Error: Undefined scope 'Fn'
Function.i:142: Error: Template 'Fn::MathUnary' undefined.
Function.i:143: Error: Undefined scope 'Fn'
Function.i:143: Error: Template 'Fn::MathUnary' undefined.
Function.i:144: Error: Undefined scope 'Fn'
Function.i:144: Error: Template 'Fn::MathUnary' undefined.
Function.i:146: Error: Undefined scope 'Fn'
Function.i:146: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:147: Error: Undefined scope 'Fn'
Function.i:147: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:148: Error: Undefined scope 'Fn'
Function.i:148: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:149: Error: Undefined scope 'Fn'
Function.i:149: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:150: Error: Undefined scope 'Fn'
Function.i:150: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:151: Error: Undefined scope 'Fn'
Function.i:151: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:152: Error: Undefined scope 'Fn'
Function.i:152: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:153: Error: Undefined scope 'Fn'
Function.i:153: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:154: Error: Undefined scope 'Fn'
Function.i:154: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:155: Error: Undefined scope 'Fn'
Function.i:155: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:156: Error: Undefined scope 'Fn'
Function.i:156: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:157: Error: Undefined scope 'Fn'
Function.i:157: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:158: Error: Undefined scope 'Fn'
Function.i:158: Error: Template 'Fn::AnalyticCRTP' undefined.
Function.i:160: Error: Undefined scope 'Fn'
Function.i:160: Error: Template 'Fn::MathRelational' undefined.
Function.i:161: Error: Undefined scope 'Fn'
Function.i:161: Error: Template 'Fn::MathRelational' undefined.
Function.i:164: Error: Undefined scope 'Fn'
Function.i:164: Error: Template 'Fn::MathRelational' undefined.
Function.i:165: Error: Undefined scope 'Fn'
Function.i:165: Error: Template 'Fn::MathRelational' undefined.
Function.i:166: Error: Undefined scope 'Fn'
Function.i:166: Error: Template 'Fn::MathRelational' undefined.
Function.i:167: Error: Undefined scope 'Fn'
Function.i:167: Error: Template 'Fn::MathRelational' undefined.
Function.i:168: Error: Undefined scope 'Fn'
Function.i:168: Error: Template 'Fn::MathRelational' undefined.
PICellerator.i:66: Warning 303: %extend defined for an undeclared class GeneralSwarm.
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
Traceback (most recent call last):
  File "./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig `bindings.`

**Comment by jmansour** [comment]
Hi @Dnepropetrovst 

Can you run `./scons.py` instead of `./compile.py` and report the output?

**Comment by julesghub** [comment]
`./scons &> scons.txt`

**Comment by jmansour** [comment]
Well close this due to inactivity. Feel free to reopen as required.
