### ISSUE TITLE
consider adiabatic compression in the advection-diffusion equation

### ISSUE THREAD

**Issue by tingyang2004** [underworldcode/underworld2#542]
Hi all,

I am wondering if we can consider adiabatic compression influences (TαDp/Dt in the formula below, and can be simplified to -Tα*g*uz, where g is gravity and uz is vertical velocity) on the temperature fields in uw2? This will bring different temperature gradients for cold and hot regions.
![image](https://user-images.githubusercontent.com/26615840/117386642-d5be6500-af19-11eb-80c4-22241919c231.png)

**Comment by lmoresi** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1620355806/e0463a85314d353cd65b915287a67da9/5/56e0546f227d5dd9cd487b5bee1a3fe2/248a8e7a2f1d37422bcc2114e186b9b2/9efab2399c7c560b34de477b9aa0a465/newton.gif]
@julesghub

Did you not implement various things like extended Boussinesq that would address this issue. If the relevant operators are available, but not properly documented, then can we update the documentation for the next release and let people know to go out and do some tests ?

L

Prof Louis Moresi
***@***.***
(m) +61 4 0333 1413
(us) +1 505 349 4425
www.moresi.info<http://www.moresi.info/>
geo-down-under.geoscience.education<https://geo-down-under.geoscience.education/>
@LouisMoresi<https://twitter.com/LouisMoresi>

On Fri, May 7, 2021 at 11:56 AM, tingyang2004 ***@***.***> wrote:

Hi all,

I am wondering if we can consider adiabatic compression influences (TαDp/Dt in the formula below, and can be simplified to -Tαguz, where g is gravity and uz is vertical velocity) on the temperature fields in uw2? This will bring different temperature gradients for cold and hot regions.
[image]<https://user-images.githubusercontent.com/26615840/117386642-d5be6500-af19-11eb-80c4-22241919c231.png>

**Comment by julesghub** [comment]
Hey Ting, 
https://github.com/underworldcode/underworld2/blob/v2.11_release/docs/test/14_Convection_EBA.ipynb

Is a new model on the upcoming 2.11 branch (not released yet). It contains an EBA formulation. Take a look and feel free to reopen this ticket to discuss more.
