### ISSUE TITLE
ImportError when using visualisation on hpc

### ISSUE THREAD

**Issue by lsli0116** [underworldcode/underworld2#545]
Hi everyone. I install the underworld2 on hpc of Centos 7.9 system. All the module except the visualisation module of underworld works fine. And everytime `import underworld.visualisation as vis`, the following message will occur: 

`/fsa/home/wxl_lsli/software/anaconda3/envs/underworld2/lib/python3.7/site-packages/lavavu/_LavaVuPython.cpython-37m-x86_64-linux-gnu.so: undefined symbol: png_create_info_struct : module not found! disabling inline visualisation`

And I noted the problem may happen in the lavavu package, so I `import lavavu`, and ImportError occurred:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-e67ffacf111d> in <module>
----> 1 import lavavu

~/software/anaconda3/envs/underworld2/lib/python3.7/site-packages/lavavu/__init__.py in <module>
      8 sys.path.append(os.path.dirname(__file__))
      9 
---> 10 from .lavavu import *
     11 
     12 from vutils import is_ipython, is_notebook

~/software/anaconda3/envs/underworld2/lib/python3.7/site-packages/lavavu/lavavu.py in <module>
     75 
     76 #import swig module
---> 77 import LavaVuPython
     78 version = LavaVuPython.version
     79 server_ports = []

~/software/anaconda3/envs/underworld2/lib/python3.7/site-packages/lavavu/LavaVuPython.py in <module>
     13     from . import _LavaVuPython
     14 else:
---> 15     import _LavaVuPython
     16 
     17 try:

ImportError: /fsa/home/wxl_lsli/software/anaconda3/envs/underworld2/lib/python3.7/site-packages/lavavu/_LavaVuPython.cpython-37m-x86_64-linux-gnu.so: undefined symbol: png_create_info_struct
```
I have reinstall the lavavu with pip, but it doesn't work.

**Comment by OKaluza** [comment]
Looks like an issue with an old or missing libpng installation. 
See https://github.com/lavavu/LavaVu/issues/95 where I have suggested using the lavavu-osmesa pip package instead, this is generally the way to go on HPC unless a GPU is available.

**Comment by lsli0116** [comment]
Thanks for your suggestions. It works fine now :)
