### ISSUE TITLE
Non-linear convergence test

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#546]
Question from a user:

Dear John,

I need to perform manual non-linear iterations, something like that:

```python
stokes = uw.systems.Stokes(velocityField        = velocityField,
                           pressureField        = pressureField,
                           conditions           = velocityBC,
                           fn_viscosity         = viscosityFn,
                           fn_bodyforce         = buoyancyFn)
solver = uw.systems.Solver(stokes)
solver.set_inner_method("superlu")
init_pseudovisc()
k = 0
while True:
    solver.solve(nonLinearIterate = False)
    res = update_pseudovisc()
    if (tolerance < 0.02 and res == 0):
        break
    k += 1
    print('Step %d ; Iteration %d',step,k)
```

The problem is that I don't know how to easily calculate the relative tolerance on the velocity field. Is there any underworld API for this purpose?

**Comment by jmansour** [comment]
I think the best option here is to use the `underworld.utils.Integral` class to generate a integral which performs an RMS type difference of an old and a new velocity field. This approach is good because it handles all parallel considerations, and also if your mesh is deformed, the velocity values are scaled according to their basis domain weighting.

Here's an example:

```python
import underworld as uw
from underworld import function as fn
import math

dim = 2
res = 32
mesh  = uw.mesh.FeMesh_Cartesian(elementRes=(res,)*dim,minCoord=(0.,)*dim,maxCoord=(1.,)*dim)
vel   = uw.mesh.MeshVariable(mesh,dim)
press = uw.mesh.MeshVariable(mesh.subMesh, 1)
vel.data[:]   = (0.,)*dim
press.data[:] = 0.

soln = fn.analytic.SolNL()
bcs = soln.get_bcs(vel)
# setup and do linear solve first
stokes = uw.systems.Stokes(vel,press,1.,fn_bodyforce=soln.fn_bodyforce, conditions=[bcs,])
solver = uw.systems.Solver(stokes)
solver.solve()
# now set the NL viscosity
stokes.fn_viscosity = soln.get_viscosity_nl(vel,press)

# add variable to record old velocity
vel_old = uw.mesh.MeshVariable(mesh,dim)

# create integral for rms change
diff_int = uw.utils.Integral(fn.math.dot(vel-vel_old,vel-vel_old), mesh)

# iterate for our numerical solution
n = 0
delta=10000
delta_converged = 1.e-4
while delta>delta_converged :
    vel_old.data[:] = vel.data[:]
    solver.solve(nonLinearIterate=False)
    delta = math.sqrt(diff_int.evaluate())
    n+=1
    print(n, delta)
    if n>50:
        break
```

**Comment by jmansour** [comment]
Note that it may be advisable to also consider the pressure solution to ensure our iterations deliver a convergent pressure solution too.

**Comment by antonio-schettino** [comment]
Thank you John. It seems that you suggest an absolute tolerance criterion. Below please find an alternative code that uses relative tolerance. Could it work? Furthermore, what is the purpose of the initial constructor uw.systems.Stokes() with a fixed viscosity? Should I set stokes.fn_viscosity at each subsequent step? However, I am trying the following code, which does not seem to converge quickly. I assumed a tolerance of 0.02 for Vx and 0.02*aspect ratio fo Vy. The function update_pseudovisc() has only the objective to reduce pseudoviscosities that exceed a yield failure criterion. The code should be completed with a test on pressure too:

stokes = uw.systems.Stokes(velocityField        = velocityField,
                           pressureField        = pressureField,
                           conditions           = velocityBC,
                           fn_viscosity         = eta_min,
                           fn_bodyforce         = buoyancyFn)
solver = uw.systems.Solver(stokes)
solver.set_inner_method("superlu")
solver.solve(nonLinearIterate = False)
stokes.fn_viscosity = viscosityFn
init_pseudovisc()
k = 0
while True:
    vx_old = velocityField[0].evaluate(mesh)
    vy_old = velocityField[1].evaluate(mesh)
    solver.solve(nonLinearIterate = False)
    vx_new = velocityField[0].evaluate(mesh)
    vy_new = velocityField[1].evaluate(mesh)
    tx = np.divide(vx_new - vx_old,vx_old,out = np.zeros_like(vx_new - vx_old),where = vx_old != 0.0)
    ty = np.divide(vy_new - vy_old,vy_old,out = np.zeros_like(vy_new - vy_old),where = vy_old != 0.0)
    dVx = np.fabs(tx)
    dVy = np.fabs(ty)
    rmsx = np.sqrt(np.mean(dVx ** 2))
    rmsy = np.sqrt(np.mean(dVy ** 2))
    res = update_pseudovisc()
    if (rmsx <= 0.02 and rmsy <= 0.02 * Ar and res == 0):
        break
    k += 1
    print('Step: ',step,'k: ',k,'Max dVx = ',np.nanmax(dVx),'Max dVy = ',np.nanmax(dVy),'rms dVx/Vx = ',rmsx,'rms dVy/Vy = ',rmsy)
...
step = 0
while step < steps_end:
   ...
    k = 0
    while True:
        vx_old = velocityField[0].evaluate(mesh)
        vy_old = velocityField[1].evaluate(mesh)
        solver.solve(nonLinearIterate = False)
        vx_new = velocityField[0].evaluate(mesh)
        vy_new = velocityField[1].evaluate(mesh)
        tx = np.divide(vx_new - vx_old,vx_old,out = np.zeros_like(vx_new - vx_old),where = vx_old != 0.0)
        ty = np.divide(vy_new - vy_old,vy_old,out = np.zeros_like(vy_new - vy_old),where = vy_old != 0.0)
        dVx = np.fabs(tx)
        dVy = np.fabs(ty)
        rmsx = np.sqrt(np.mean(dVx ** 2))
        rmsy = np.sqrt(np.mean(dVy ** 2))
        res = update_pseudovisc()
        if (rmsx <= 0.02 and rmsy <= 0.02 * Ar and res == 0):
            break
        k += 1
        print('Step: ',step,'k: ',k,'Max dVx = ',np.nanmax(dVx),'Max dVy = ',np.nanmax(dVy),'rms dVx/Vx = ',rmsx,'rms dVy/Vy = ',rmsy)
    step += 1

**Comment by jmansour** [comment]
Yes relative tolerance is fine. The specifics of the convergence test are up to you. To do an relative convergence using the integrals, you'd simply construct something along these lines:
```python
diff_int = uw.utils.Integral(fn.math.dot(vel-vel_old,vel-vel_old)/fn.math.dot(vel_old,vel_old), mesh)
```
Although you'll need to be careful for divide by zeros. 

What you have constructed seems reasonable. Note that there's no guarantee of convergence, so you might consider reducing your non-linearity strength and seeing if you find convergence. Also note that relying on Numpy arrays won't work for parallel execution, whereas using `underworld.utils.Integral` will. 

The initial Stokes construct with `viscosity=1.` is simply to get a good initial guess for the non-linear solver. In particular, for this model, the initial velocity condition `v=(0.,0.)` results in a zero non-linear viscosity, which the solver certainly won't like, and therefore constructing a reasonable initial guess is necessary.  You might also like to check that this isn't an issue for your models.

After the initial setup, we would always use the non-linear viscosity for future solves (although it only needs to be set once).

**Comment by antonio-schettino** [comment]
It works fine with velocities, but there is no convergence for pressure. I used the following code, from which I removed a potential source of slow convergence (the pseudoviscosity update).:

v_norm = uw.utils.Integral(fn.math.dot(velocityField - v_old,velocityField - v_old) / fn.math.dot(v_old,v_old),mesh)
p_norm = uw.utils.Integral(fn.math.pow(pressureField - p_old,2.0) / fn.math.pow(p_old,2.0),mesh)
init_pseudovisc()
k = 0
while (k < 100):
    v_old.data[:] = velocityField.data[:]
    p_old.data[:] = pressureField.data[:]
    solver.solve(nonLinearIterate = False)
    delta_v = math.sqrt(v_norm.evaluate())
    delta_p = math.sqrt(p_norm.evaluate())
#    res = update_pseudovisc()
    if (delta_v <= 0.02 and delta_p <= 0.05 and res == 0):
        break
    k += 1
    print('Step: ',step,'k: ',k,'dV/V = ',delta_v,'dp/p = ',delta_p,'eta_star_s updates = ',res)

The following listing shows that velocity quickly converges to a relative tolerance of less than 2% in 7 iterations, while pressure does not. A previous experiment based on the automatic nonlinear solver (solver.solve(nonLinearIterate = True)) also converged in 7 iterations.

Step:  0 k:  1 dV/V =  2.0535232863488795 dp/p =  3584.2693268381
Step:  0 k:  2 dV/V =  0.8640854963441276 dp/p =  251.09723788381453
Step:  0 k:  3 dV/V =  0.28639383482533987 dp/p =  4.177230786859758
Step:  0 k:  4 dV/V =  0.12838664133632247 dp/p =  114.95301547224584
Step:  0 k:  5 dV/V =  0.0860993006039989 dp/p =  2.543456387414513
Step:  0 k:  6 dV/V =  0.03702703385928948 dp/p =  97.38650068092971
Step:  0 k:  7 dV/V =  0.018603744756462485 dp/p =  4.7966401133915175
Step:  0 k:  8 dV/V =  0.01410969094450475 dp/p =  7.255516041230514
Step:  0 k:  9 dV/V =  0.01698743683917393 dp/p =  45.83380337775896
Step:  0 k:  10 dV/V =  0.05214976557231065 dp/p =  20.633654541520993
Step:  0 k:  11 dV/V =  0.023455616093158528 dp/p =  98.60153995092372
Step:  0 k:  12 dV/V =  0.03762944666013536 dp/p =  246.35298123265827
Step:  0 k:  13 dV/V =  0.011444063671350365 dp/p =  16.245530803153805
Step:  0 k:  14 dV/V =  0.010629383239113508 dp/p =  14.819473467418186
Step:  0 k:  15 dV/V =  0.0021383464524366226 dp/p =  3397.405430873926
Step:  0 k:  16 dV/V =  0.001801972063301643 dp/p =  54.58642651950089
Step:  0 k:  17 dV/V =  0.0016803940962522564 dp/p =  63.23371636698611
Step:  0 k:  18 dV/V =  0.005920560286625577 dp/p =  66.75820898625173
Step:  0 k:  19 dV/V =  0.028928710932345232 dp/p =  26.321944848698205
Step:  0 k:  20 dV/V =  0.03257367139648325 dp/p =  23.704742530397635
Step:  0 k:  21 dV/V =  0.0027605597564522564 dp/p =  33.40763381526084
Step:  0 k:  22 dV/V =  0.028476056654585708 dp/p =  48.99083917831572
Step:  0 k:  23 dV/V =  0.03377331652215253 dp/p =  28.903246645956383
Step:  0 k:  24 dV/V =  0.026649452868847165 dp/p =  46.556648407823936
Step:  0 k:  25 dV/V =  0.03359862878099472 dp/p =  17.82089203847093
Step:  0 k:  26 dV/V =  0.004784112311814151 dp/p =  37.5443644176598
Step:  0 k:  27 dV/V =  0.007266912642936384 dp/p =  37.349714202669674
Step:  0 k:  28 dV/V =  0.0025650341891329757 dp/p =  74.17335700761392
Step:  0 k:  29 dV/V =  0.0015366913445601824 dp/p =  66.30701873351583
Step:  0 k:  30 dV/V =  0.0029842807020690858 dp/p =  40.347022784805304
Step:  0 k:  31 dV/V =  0.0025873520469744623 dp/p =  100.51683013637663
Step:  0 k:  32 dV/V =  0.02892766331152145 dp/p =  31.690745703713556
Step:  0 k:  33 dV/V =  0.03136689618422241 dp/p =  34.48836347624016
Step:  0 k:  34 dV/V =  0.0020923249271293993 dp/p =  468.750304136037
Step:  0 k:  35 dV/V =  0.03076561696332582 dp/p =  26.894954731250706
Step:  0 k:  36 dV/V =  0.03393148425094873 dp/p =  12.844101950793071
Step:  0 k:  37 dV/V =  0.02753356751492918 dp/p =  16.270760694299828
Step:  0 k:  38 dV/V =  0.03640938414554928 dp/p =  30.757794122173195
Step:  0 k:  39 dV/V =  0.005958138422108076 dp/p =  54.1140813305089
Step:  0 k:  40 dV/V =  0.006566604116337451 dp/p =  398.463919538532

**Comment by jmansour** [comment]
Hi Antonio

Firstly, I suggested a point-wise relative error earlier:

```python
rel_diff_int = uw.utils.Integral(fn.math.dot(vel-vel_old,vel-vel_old)/fn.math.dot(vel_old,vel_old), mesh)
```

which is not unreasonable, but it's possibly better to use a global relative error:

```python
diff_int = uw.utils.Integral(fn.math.dot(vel-vel_old,vel-vel_old), mesh)
rms_int = uw.utils.Integral(fn.math.dot(vel_old,vel_old), mesh)
delta_v = math.sqrt(diff_int.evaluate() /rms_int.evaluate() )
```

as this is less likely to encounter divide by zero issues.  

Now, for your pressure iteration, note that pressure solutions are only guaranteed up to an arbitrary constant, as unlike the velocities the pressure isn't tethered to a boundary condition. You can if you like set a pressure node condition somewhere in your domain, but what we usually do is simply normalise the pressure solution after it has been obtained. There are a few options for normalisation, such as shifting by the average pressure value:

```python
press_sum = uw.utils.Integral(pressureField, mesh)
volume = uw.utils.Integral(1., mesh).evaluate()

### somewhere in your solve loop
while(....):
    solver.solve()
    # normalise
    pressureField.data[:] -= press_sum.evaluate()/volume
    #.... 
```

Note also that pressure normalisation/calibration becomes important if you have a pressure dependent rheology. In that case, you'd want a more physically based normalisation. One option is to obtain the average pressure across the top of the domain, and normalise by that. This will give you an on average zero pressure at the top of the domain:

```python
press_sum_top = uw.utils.Integral(pressureField, integrationType='Surface', surfaceIndexSet=mesh.specialSets["Top_VertexSet"])
top_length = uw.utils.Integral(1., integrationType='Surface', surfaceIndexSet=mesh.specialSets["Top_VertexSet"]).evaluate()

### somewhere in your solve loop
while(....):
    solver.solve()
    # normalise
    pressureField.data[:] -= press_sum_top.evaluate()/top_length
    #.... 
```

**Comment by antonio-schettino** [comment]
That's great! I thank you again John. In fact, I am using pressure in viscosity calculations. Unfortunately, underworld2 does not allow to normalize pressure along the topographic surface that separates the skicky air layer from the crust, because the following error is generated:

ValueError: Your surfaceIndexSet appears to contain node(s) which do not belong to the mesh boundary. Surface integration across internal nodes is not currently supported.

Therefore, I guess that the zero-mean normalization in the domain through a volume integral is the most appropriate choice.

**Comment by jmansour** [comment]
No problems!  I'll close this issue, but feel free to reopen (or start a new one) if necessary.
