### ISSUE TITLE
windows install problem 

### ISSUE THREAD

**Issue by weihy01** [underworldcode/underworld2#548]
hi, all

I have some problems when I try to install underworld2 on windows. When I execute the command (python setup.py install), it always prompts that the installation fails, and I don’t see the dependent packages. 

Is there a way to solve this?  how to install it on windows?  ( python3.6)

thanks a lot! 
hang

![WechatIMG654](https://user-images.githubusercontent.com/86364709/123440135-5f112000-d5ca-11eb-985f-c9893747b8d3.png)

**Comment by julesghub** [comment]
Hi Hang,
Underworld is run on windows using Docker - not directly installing Underworld on windows.

Please see the details below for running the underworld docker.
https://underworld2.readthedocs.io/en/latest/Installation.html

If you have any questions, please reopen this ticket.
