### ISSUE TITLE
Changing boundary conditions

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#55]
Hello,

Does uw2 support changing boundary conditions on the stokes solver? I'm modifying the velocityField between each solve() via the numpy interface, but it looks like the boundary conditions set when the solver was instantiated are still being applied after each solve.

Cheers,
Luke

**Comment by jmansour** [comment]
You can

**Comment by jmansour** [comment]
... certainly modify the bc values by directly modifying them on the
meshvariable (the same as you set them).

if you wish to change which nodes/dofs are flagged as dirichlet BCs, you
will need to recreate the system. this incurs some cost, but it's probably
not a huge drama.

**Comment by OlympusMonds** [comment]
Ah, it looks like this notation doesn't work:
`velocityField.data[left_wall.data][:,0] = 1`
inside the solver loop, anyway.
Using the notation from the user guide 06_systems works!
