### ISSUE TITLE
Problem with XDMF exports

### ISSUE THREAD

**Issue by agreen15** [underworldcode/underworld2#556]
Hello,

I have been trying to output model results as dynamic xdmf files in order to construct animations of lithospheric delamination.  To do this, I mostly based the code in my model on the example script provided (Rayleigh-Taylor). When I run that example script, the output XDMF files are openable and readable in paraview.  However, when I generate the XDMF files in my script, Paraview produces this error when I try to open them:

```
ERROR: In C:\glr\builds\paraview\paraview-ci\build\superbuild\paraview\src\VTK\IO\Xdmf2\vtkXdmfReader.cxx, line 478
vtkXdmfReader (00000207F6E79700): Failed to read data.

ERROR: In C:\glr\builds\paraview\paraview-ci\build\superbuild\paraview\src\VTK\Common\ExecutionModel\vtkExecutive.cxx, line 753
vtkPVCompositeDataPipeline (00000207F6D8A6D0): Algorithm vtkFileSeriesReader(00000207F97D0D30) returned failure for request: vtkInformation (00000207F9B102D0)
  Debug: Off
  Modified Time: 394085
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA
  FORWARD_DIRECTION: 0
  ALGORITHM_AFTER_FORWARD: 1
  FROM_OUTPUT_PORT: 0
```
Here is the relevant section of the notebook:

```
if rank==0:
        if step % step_out == 0:
            temperatureField.save(outputPath+'IceSag_T.out')
            temperatureDotField.save(outputPath+'IceSag_TDot.out')
            velocityField.save(outputPath+'IceSag_v.out')
            pressureField.save(outputPath+'IceSag_P.out')
        
            velocityFile = outputPath+"/velocityField"+str(Trial)+"."+str(step)
            vFH      = velocityField.save(velocityFile+".h5")
            velocityField.xdmf( velocityFile, vFH, "velocity", meshFileHandle, "TheMesh", time )
        
            pressureFile = outputPath+"/pressureField"+str(Trial)+"."+str(step)
            pFH      = pressureField.save(pressureFile+".h5")
            pressureField.xdmf(pressureFile, pFH, "pressure", meshFileHandle, "TheMesh", time )
        
            temperatureFile = outputPath+"/temperatureField"+str(Trial)+"."+str(step)
            TFH      = temperatureField.save(temperatureFile+".h5")
            temperatureField.xdmf(temperatureFile, TFH, "temperature", meshFileHandle, "TheMesh", time )
        
            particleFile = outputPath+"/MVar"+str(Trial)+"."+str(step) 
            MVFH      = materialVariable.save(particleFile+".h5")
            materialVariable.xdmf(particleFile, MVFH, "materialVariable", swarmFileHandle, "TheSwarm", time )

```
I have not been able to find a meaningful difference between this code and the example code provided, other than the identifying information relevant to my model setup.  Is there something I'm missing? 

Let me know if you need more information.

**Comment by jmansour** [comment]
Have you saved the mesh?

**Comment by jmansour** [comment]
Actually, I'd image you have if you have the `meshFileHandle` object.

Do the file sizes and timestamps look correct? 

Perhaps post a minimal set of xdmf & h5 (low-resolution!) here and we'll take a look.

**Comment by agreen15** [comment]
[h5xdmf.zip](https://github.com/underworldcode/underworld2/files/6793129/h5xdmf.zip)

Here is a sample of some small h5 and xdmf files generated by the script.

**Comment by jmansour** [comment]
I'll need the corresponding mesh `h5` file too.

**Comment by agreen15** [comment]
Here's a freshly run folder with the mesh file included.
[h5xdmf2.zip](https://github.com/underworldcode/underworld2/files/6812709/h5xdmf2.zip)

**Comment by jmansour** [comment]
I can open these in Paraview. 

Paraview presents me with 3 options, and I select "XDMF Reader" from those (not "Xdmf3ReaderS" or "Xdmf3ReaderT").  I'm using Paraview 5.9.1.

**Comment by agreen15** [comment]
So do I need the mesh or swarm h5 file in the same directory for paraview to read them?

**Comment by jmansour** [comment]
All your `h5` and `xdmf` files should be saved in the same directory, and to view `MeshVariable` H5 objects Paraview will need the corresponding `Mesh` H5 object (and similarly for SwarmVariable/Swarm H5 objects).

**Comment by agreen15** [comment]
I think I got it then---I had all of my h5 and xdmf files (from both scripts) in the same "paraview test" directory. So it was getting confused about which mesh and swarm h5 files corresponded to which xdmf.  Thanks for the help!

**Comment by jmansour** [comment]
Okay great, I suspected something along those lines was at play.
