### ISSUE TITLE
02_TheMesh.ipynb  unable to save mesh

### ISSUE THREAD

**Issue by rmoucha** [underworldcode/underworld2#56]
As far as I can tell, all compiled without issues on El Capitan, but when I run the 02_TheMesh.ipynb in the user guide I get the following error:

IOError                                   Traceback (most recent call last)
<ipython-input-10-170796f0f421> in <module>()
----> 1 mesh.save('deformedMesh.h5')

/Users/rmoucha/Research/Geodynamics/Underworld2/underworld/mesh/_mesh.pyc in save(self, filename)
    415             raise TypeError("'filename', must be of type 'str'")
    416 
--> 417         h5f = h5py.File(name=filename, mode="w", driver='mpio', comm=MPI.COMM_WORLD)
    418 
    419         # save attributes and simple data - MUST be parallel as driver is mpio

/Users/rmoucha/Research/Geodynamics/Underworld2/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/Users/rmoucha/Research/Geodynamics/Underworld2/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
     96         fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
     97     elif mode == 'w':
---> 98         fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
     99     elif mode == 'a':
    100         # Open in append mode (read/write).

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/rmoucha/Research/Geodynamics/Underworld2/libUnderworld/h5py_ext/h5py/_objects.c:2918)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/Users/rmoucha/Research/Geodynamics/Underworld2/libUnderworld/h5py_ext/h5py/_objects.c:2877)()

h5py/h5f.pyx in h5py.h5f.create (/Users/rmoucha/Research/Geodynamics/Underworld2/libUnderworld/h5py_ext/h5py/h5f.c:2333)()

IOError: Unable to create file (Mpi_err_access: invalid access mode)

**Comment by jmansour** [comment]
Hi there

Sorry for the delay in response.  It's hard to tell what is causing your issue.  Guessing you do, but make sure you have write access to that directory.  

This could be an issue with the h5py installation.  Have you installed it via pip?  If so, perhaps uninstall it (then reconfigure/recompile Underworld), as Underworld will compile its own parallel compatible version. 

Alternatively, using a docker installation will allow you to avoid all these difficulties:
http://www.underworldcode.org/posts/Underworld-and-Dockers2

**Comment by RebeccaFarrington** [comment]
If this is still an issue please re open
