### ISSUE TITLE
How to download the regionalMesh branch of Underworld2

### ISSUE THREAD

**Issue by royarnab18** [underworldcode/underworld2#560]
I am using the docker container for installing and using Underworld2 in my system. However, by default the master branch of the code is downloaded through the following command: 

sudo docker run -p 8888:8888 -v "$PWD:/home/jovyan/workspace" underworldcode/underworld2

I need to download the regionalMesh branch of Underworld2. Can someone please tell whether it is possible to download the regionalMesh branch through docker and what is the procedure for that?

**Comment by jmansour** [comment]
@julesghub is there an up to date image for the `regionalMesh` branch of UW?

**Comment by julesghub** [comment]
There isn't a recent version of the `regionalMesh` branch. We have a 2 year old version docker images of it called `underworldcode/uw2cylindrical`. 
The majority of that functionality was ported into the branch  `jgiordani/curvi-bits` and it's much more recent. 

What exactly to you need @royarnab18?

Probably the best thing to do is build a recent docker of `curvi-bits`.

**Comment by royarnab18** [comment]
Thank you for the information. Basically I need the functionality of the annulus mesh.

**Comment by julesghub** [comment]
Hi @royarnab18 I have made a docker for the curve-bits. It is based off the latest 2.11 release that came out today and includes the extra bits for the annulus mesh.
To use it get the docker image use something like this.
`docker run -p 8888:8888 -v "$PWD:/home/jovyan/workspace" underworldcode/underworld2:curvi-bits`

The annulus mesh example is located in `docs/examples/curvi_examples`

I'll close the ticket now, feel free to reopen if you have issues downloading the new image.
