### ISSUE TITLE
Particle Swarm XDMF files not recording particle advection

### ISSUE THREAD

**Issue by agreen15** [underworldcode/underworld2#561]
Hello,

I am trying to use Paraview to animate lithospheric drips via UW2's XDMF generator.  You may recall my previous thread on these issues.  

This time, I am having issues with swarm-based XDMF files.  The mesh-based XDMF files turn out fine and animate well, but I have had two simultaneous problems with swarm-based XDMFs.

First, I generated some from my university's supercluster, which is currently using the 2.11 prerelease of underworld.  When I opened the XDMF files generated by this UW build, it rendered the initial conditions correctly:

![image](https://user-images.githubusercontent.com/57016679/129082170-802dc45d-20ce-469c-bb4d-1621752dd807.png)

However, later timesteps look like this:

![image](https://user-images.githubusercontent.com/57016679/129082282-7969021e-6ac7-46ec-ab68-5e2d816da4ae.png)

I then ran the same script on my home computer to identify whether the problem was with UW or the supercluster.  I ran it this time through the 2.10 build of UW2, which is the latest release I have on my home PC.  This time, the particle swarm shown by the XDMF files seemed not to advect, giving me this result for the final recorded timestep:

![image](https://user-images.githubusercontent.com/57016679/129082527-e2bc6b46-4d57-40a1-861d-90e09bf7dfd0.png)

I triple-checked my script and the swarm is advecting, as demonstrated by this jupyter-generated figure of the final state of the particle swarm:

![image](https://user-images.githubusercontent.com/57016679/129082627-1f3fdd0e-3e83-4d78-84e2-84fd1ae20042.png)

Are there any common mistakes that would lead to XDMF files behaving this way, but only for swarms? 
Let me know if you need more information.  Thanks!

**Comment by julesghub** [comment]
Hi @agreen15. 
Issue 1 looks like an "incorrect ordering" of the saved particle information and issue 2 i'm unsure about.
When creating xdmf files it's important to ensure the correct state of the swarm is referenced by the xdmf file.
If you could post your example into a github repo or gist - (public or private) I can look into it.

Also please use the docker to test the example and I can look use the same docker image to investigate.

**Comment by julesghub** [comment]
PS: If you'd like to build a gitub repo with a "live" binder button to it then I can invite you to use our template github repository. 
An example: https://github.com/underworld-community/template-project

**Comment by agreen15** [comment]
Hi Jules,

Thanks for your help. I'm relatively inexperienced when it comes to using github, so I hope this repository I've constructed following your template is sufficient:

[https://github.com/agreen15/IceDelamination](url)

Thanks again.

**Comment by agreen15** [comment]
Hello,

Any progress on this issue?

**Comment by agreen15** [comment]
Hi,

Sorry for taking so long to get back on this, but I did try your fix, and now paraview crashes on trying to open the xdmf files through the "XDMF reader". Using the other listed readers does not cause a crash, but it also does not render the particle field.  Any ideas on this?

Austin

**Comment by agreen15** [comment]
Bumping this issue.

**Comment by julesghub** [comment]
What version of the paraview are you using?
I'm on 5.7.0

**Comment by agreen15** [comment]
I use 5.9.1

**Comment by julesghub** [comment]
oh I wasn't specific enough in my previous response.

> in cell 33 move the line
> `swarmFileHandle = swarm.save(outputPath+"Swarm.h5")`
> in the time step (while) loop.

 Not only do you have to move the swarm save to the while loop but you'll also have to name it uniquely. ie, add something like:
 `swarmFileHandle = swarm.save(outputPath+"Swarm."+str(step)+"h5")
 
 This makes sure the correct swarm variable h5 files (eg. materialIndex) are associate with the correct swarm file.

**Comment by agreen15** [comment]
Thanks! This works!
