### ISSUE TITLE
How to extract the particle coordinates of swarm in parellel by providing certain conditions?

### ISSUE THREAD

**Issue by Prasanna2989** [underworldcode/underworld2#562]
Hi there,

This is a question related to running in parallel with 4 to 16 cpus. 

I have a swarm variable named 'materialIndex' as illustrated in the attached ppt. I need to extract the coordinates red color particles in this swarm (that has a materialIndex of 10) and get the maximum and minimum x coordinates of the region. I can do this in a single processor using the code segment given below. In that code, I take all the coordinates into a list named 'cratcrustCoordslist' and select the max and min values. But, when I run this using 4 cpus in NCI, it gives me trouble. Basically, it does not update the particles as it should be. Is there anything that I can do to overcome this issue? Please let me know if you need more clarification about the question. I am exhausted on this test for two days keep trying :-). 

cheers 
Pras

[question.pptx](https://github.com/underworldcode/underworld2/files/6973139/question.pptx)

```python
def FindPreCratonSize(growthRate):
    leftBound = 1.  #initialised to these values
    rightBound = 1.4
    crat1Rightedge = 1.
    crat1Rightedge = 1.4

    cratcrustCoordslist = [] #This where to x coordinates are collected
    
    for i, c in enumerate(swarm.particleCoordinates.data):
        if (materialVariable.data[i]>10-0.01) & (materialVariable.data[i]<10.+0.01): #selecting material index 10 
            cratcrustCoordslist.append(c[0])
            
    #Then I get the min and max values of x coordinates list        
    if (len(cratcrustCoordslist)>0):
        crat1Rightedge = max(cratcrustCoordslist)
        crat1Leftedge = min(cratcrustCoordslist)

     # Next, I increase the width of the region   
    rightBound = crat1Rightedge + growthRate/2.
    leftBound = crat1Leftedge - growthRate/2.
    return rightBound, leftBound  `



#Here I redefine the particles based on above extracted min max values and some other conditions
def Applycraton(rightBound, leftBound ):
    
    FelLithCon = ( (coord[0] > leftBound) & (coord[0] < rightBound) & (coord[1] > (height_N-250.e3)/height_N))
    FelLithConFn = fn.branching.conditional(((FelLithCon, crat_Lith), (True, materialVariable)))
    materialVariable.data[:] = FelLithConFn.evaluate(swarm)
  
    FelcrustCon = ((temp<600.) & (coord[0] > leftBound) & (coord[0] < rightBound) & (coord[1] > (height_N-250.e3)/height_N))
    FelcrustConFn = fn.branching.conditional(((FelcrustCon, crat_crust), (True, materialVariable))) 
    materialVariable.data[:] = FelcrustConFn.evaluate(swarm)`
```

**Comment by rbeucher** [comment]
Hi @Prasanna2989,

Sorry I just saw this.
I think you would be better off using a couple of passive tracers. 

The domain is partitioned in parallel and some processes will have no particles from the swarm you are trying to track.

I am closing this because it is now more than 3 months old. Feel free to get back to me if you need help.
