### ISSUE TITLE
LavaVu Run error: No context!

### ISSUE THREAD

**Issue by ZhiqYu** [underworldcode/underworld2#569]
@julesghub 
Hi!
I  installed underworld code on the Dell HPC at my school according to https://underworld2.readthedocs.io/en/latest/Installation.html
Then I installed UWGeodynamics according to https://uwgeodynamics.readthedocs.io/en/latest/Installation.html#hpc-installation
 I  try running the example 01_Steady_State_Heat_with the Jupyter Notebook
whenever running fig.show() ，
it‘s called something like this appears：
LavaVu Run error: No context!

![i](https://user-images.githubusercontent.com/89136167/130406190-09efa056-6757-4155-8293-10572dbed712.jpg)

Other examples have the same problem.
I don't know what's going on here！

**Comment by julesghub** [comment]
Hi @ZhiqYu 

Have you install LavaVu? 
Try: 
`python -c 'import lavavu;print(lavavu.__version__)'`

LavaVu is only for our visualisation not running the code. So technically all the notebooks should still run despite showing this error on `Fig.show()` calls

**Comment by ZhiqYu** [comment]
Thanks，Julian Giorani




This error has been solved

but there is a new error like this

while I run Model.init_model()





-----原始邮件-----
发件人:"Julian Giordani" ***@***.***>
发送时间:2021-08-25 09:40:35 (星期三)
收件人: underworldcode/underworld2 ***@***.***>
抄送: ZhiqYu ***@***.***>, Mention ***@***.***>
主题: Re: [underworldcode/underworld2] LavaVu Run error: No context! (#569)






Hi @ZhiqYu

Have you install LavaVu?
Try:
python -c 'import lavavu;print(lavavu.__version__)'

LavaVu is only for our visualisation not running the code. So technically all the notebooks should still run despite showing this error on Fig.show() calls

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by julesghub** [comment]
Great news.
Do you have any details about the new error? Either from the notebook or the command line running the jupyter-notebook server?

**Comment by ZhiqYu** [comment]
I used jupyter-book to run the code in UWGeodynamics\docs\examples such as 1_02_Convection_Example, 1_05_StokesSinker,etc.

	I also run the code in UWGeodynamics\docs\tutorials such as Tutorial_2_Melt.ipynb,etc.

	whenever run model._init model()，the following error occurs.

	this is 1_02_Convection_Example
this is 1_05_StokesSinker
and this is Tutorial_2_Melt.ipynb



Attached is the code that might be used 





-----原始邮件-----
发件人:"Julian Giordani" ***@***.***>
发送时间:2021-09-01 15:19:45 (星期三)
收件人: underworldcode/underworld2 ***@***.***>
抄送: ZhiqYu ***@***.***>, Mention ***@***.***>
主题: Re: [underworldcode/underworld2] LavaVu Run error: No context! (#569)






Great news.
Do you have any details about the new error? Either from the notebook or the command line running the jupyter-notebook server?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZhiqYu** [comment]
I used jupyter-book to run the code in UWGeodynamics\docs\examples such as 1_02_Convection_Example, 1_05_StokesSinker,etc.
I also run the code in UWGeodynamics\docs\tutorials such as Tutorial_2_Melt.ipynb,etc.

whenever run model._init model()，the following error occurs.

this is 1_02_Convection_Example
![image](https://user-images.githubusercontent.com/89136167/131678994-9d17b4c0-4dfd-47b2-9e83-a085d6899462.png)

this is 1_05_StokesSinker
![image](https://user-images.githubusercontent.com/89136167/131679103-77c9a256-a1b5-4a95-8def-9cdbd945df08.png)
![image](https://user-images.githubusercontent.com/89136167/131679152-04dbb090-2acc-4a2d-a95b-68b304fd4cc6.png)

and this is Tutorial_2_Melt.ipynb
![image](https://user-images.githubusercontent.com/89136167/131679211-a55f7e3a-e9f2-4f90-b9f1-efa002d8b9ad.png)
![image](https://user-images.githubusercontent.com/89136167/131679226-889bd0c6-a4d3-4192-adf7-19bedb66d511.png)
