### ISSUE TITLE
Weights update after each linear solve

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#57]
I've noticed that UW always runs a weights calculation after every call to solve(). I think this is different to previous UW, where when you ran a nonlinear problem, it would only do the weights after the nonlinear solver had finished.

Should/could this [line](https://github.com/underworldcode/underworld2/blob/master/underworld/systems/_bsscr.py#L351) be gated with a specific function argument? Or would just detecting a non linear problem, with nonLinearIterate=False being passed into the solve() be enough to let it know not to update?

Cheers,
Luke

**Comment by jmansour** [comment]
I'll have a look into this Luke.  Should definitely not be run every non-linear iteration.

**Comment by jmansour** [comment]
I just tested this, and weights are not currently recalculated during non-linear iterations.
