### ISSUE TITLE
Potential pb when building for new Apple M1

### ISSUE THREAD

**Issue by rbeucher** [underworldcode/underworld2#572]
While working on the CMake build for MacOSX I found that Clang was complaining about implicit function declarations that
we have in our C code.
That is something that could cause issues on the new M1 systems. I am opening this issue so that we can keep that in mind.

 Implicit declaration of functions has been prohibited ever since the C99 standard was introduced decades ago, but compilers have allowed it with a warning. The reason it now becomes a problem (in the past year) is that the version of clang included with Xcode 12 and later considers implicit declaration of functions to be an error, not a warning: It defaults to -Werror=implicit-function-declaration. Turning this off by specifying -Wno-error=implicit-function-declaration is strongly discouraged. 
Apple made this the default because they introduced new Mac models based on ARM processors, for which they use the brand name Apple Silicon.  ARM processors use different calling conventions for variadic and non-variadic functions whereas Intel processors  used the same conventions (in most cases) so this was not a problem on Intel.
But for ARM the compiler must know before it writes a function invocation's machine code which type of function it is.
To know this, it must see the function prototype.

**Comment by jmansour** [comment]
Which functions are implicitly declared?

**Comment by rbeucher** [comment]
I'll see if I can make a list

**Comment by julesghub** [comment]
Perhaps a script'o'doom can be used to address it?

**Comment by jmansour** [comment]
Is this sorted now @rbeucher ?

**Comment by rbeucher** [comment]
Yes it is!
