### ISSUE TITLE
How to draw a section of a 3D model

### ISSUE THREAD

**Issue by feiyucugb** [underworldcode/underworld2#582]
I want to draw a profile of density. How can I write the code
![density png0000](https://user-images.githubusercontent.com/49788691/136939886-110b693c-9b59-4f30-af51-a2f8b5e0a59a.png)

**Comment by rbeucher** [comment]
@OKaluza do you have any comment/suggestions on this?

**Comment by OKaluza** [comment]
`glucifer.objects.CrossSection` doesn't actually plot anything as it's a base class for various visualisation objects that defines the cross section parameters and samples the data in a cross section, to tell it how to plot the data you need to use a derived class, in this case: `glucifer.objects.Surface` 
https://underworld2.readthedocs.io/en/v2.3.0b/glucifer.objects.html#glucifer.objects.Surface
So something like (untested)...
```
figVisCross.append(glucifer.objects.Surface(mesh, materialField, crossSection="x=0", onMesh=True)
```
