### ISSUE TITLE
Install: h5py test fails mpi

### ISSUE THREAD

**Issue by VictorEijkhout** [underworldcode/underworld2#585]
```
CONFIGURE H5PY

Checking if h5py is available.MPI startup(): PMI server not found. Please set I_MPI_PMI_LIBRARY
variable if it is not a singleton case.
Error in system call pthread_mutex_destroy: Device or resource busy
    ../../src/mpi/init/init_thread_cs.c:60
Abort(2664079) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(136)........:
MPID_Init(904)...............:
MPIDI_OFI_mpi_init_hook(1421):
MPIDU_bc_table_create(311)...:

h5py does not appear to be available.
```

I suspect the problem lies in how you start up the MPI/hdf5 test program.

Speaking of which: do you want parallel or sequential hdf5?

**Comment by jmansour** [comment]
Okay, glad we've made some progress. 

It's not obvious to me why your prefix is being ignored. Can you provide more info on your config/build/install process?

**Comment by jmansour** [comment]
Hi @VictorEijkhout 

The underworld configuration script is only trying to import `h5py`:

https://github.com/underworldcode/underworld2/blob/master/underworld/libUnderworld/config/packages/H5py.py#L18

In versions previous, it would attempt to build `h5py`, but it no longer does, and that message is old and should be corrected (@julesghub). 

I'm a bit confused however as I thought you'd successfully configured `underworld` (including the `h5py` config phase) and were instead having problems with installing to your specified prefix.  Perhaps attach the complete standard output from your entire process.

**Comment by VictorEijkhout** [comment]
On , 2021Nov3, at 04:04, John Mansour ***@***.******@***.***>> wrote:

I thought you'd successfully configured

I seem to be suffering from Heissenbugs. Any small change makes one error go away and another one appear.

For the moment I seem to have an installation, so I’m waiting for my user to tell me whether it works.

Maybe you can dictate me an ultra-short program that I can run as a sanity check on my installation?

Victor.

**Comment by julesghub** [comment]
> In versions previous, it would attempt to build `h5py`, but it no longer does, and that message is old and should be corrected (@julesghub).

Yeah, this error message is misleading, I'll fix asap.

**Comment by julesghub** [comment]
@VictorEijkhout for a test of h5py and underworld run this script. https://github.com/underworldcode/underworld2/blob/master/docs/test/swarm_aux.py

Most of the `*.py` test scripts under `/doc/tests/` are lightweight and provide good testing coverage for an underworld installation.

**Comment by rbeucher** [comment]
@VictorEijkhout I am closing this ticket. Feel free to reopen or create a new ticket if needed.

R
