### ISSUE TITLE
Install underworld and quagmire together

### ISSUE THREAD

**Issue by NengLu** [underworldcode/underworld2#587]
Hi all,
Here I would like to share a recipe for installing underworld and quagmire together without packages conflict.

1. build conda env 
$ conda create -n Env_Name python=3.7.6  (python > 3.8.0 or <= 3.7.1 may have issues)
$ conda activate Env_Name

2. install dependencies
- [Mpi4py](https://anaconda.org/conda-forge/mpi4py) 
   $ conda install -c conda-forge mpi4py 
- [petsc4py](https://anaconda.org/conda-forge/petsc4py) 
   $ conda install -c conda-forge petsc4py 
- [H5py](https://anaconda.org/conda-forge/h5py) 
   $ conda install -c conda-forge h5py 
- [pint](https://anaconda.org/conda-forge/pint)
   $ conda install -c conda-forge pint 
- swig  
   $ conda install -c conda-forge/label/gcc7 swig  
- [stripy](https://anaconda.org/underworldcode/stripy) 
   $ conda install -c underworldcode stripy 

3. install underworld (from source)
$ git clone –branch v2.11_release https://github.com/underworldcode/underworld2.git
$ cd underworld/underworld/libUnderworld
$ ./configure.py --mpi-dir=anaconda3/envs/Env_Name/ --prefix=anaconda3/envs/Env_Name/lib/python3.7/site-packages/
$ sudo apt-get install build-essential # if have compile issue with gcc+ missing
$ ./compile.py
$ ./scons.py install

4. install quagmire (from source, using conda install may cause the packages conflict, using pip install will install an old version of quagmire)
$ sudo apt-get install gfortran
$ git clone https://github.com/underworldcode/quagmire.git
$ cd quagmire
$ python setup.py build 
$ python setup.py install

5. install UWGeodynamics 
$  pip install UWGeodynamics --target=anaconda3/envs/Env_Name/lib/python3.7/site-packages/ --upgrade 

Cheers,
Neng

**Comment by rbeucher** [comment]
There is a major issue which makes Underworld and Stripy incompatible.
I am closing this because I don't want people to waste time trying to install the codes...
