### ISSUE TITLE
Configuration does not link hdf5

### ISSUE THREAD

**Issue by VictorEijkhout** [underworldcode/underworld2#597]
I configure with 

```
python3 configure.py \
      --prefix=${UNDERWORLD_INSTALLATION} \
      --mpi-dir=${TACC_IMPI_DIR}  \
      --h5py-launcher=ibrun \
      --h5py-notest=1 
```

which results in:

```
mpicc -o .sconf_temp/conftest_3bc360d57f73328069eb20cbf77fe2ad_9_aae0ad77796c680c67caca2c0a92ccfc -Wl,-rpath=/opt/apps/intel19/python3/3.9.2/lib -Wl,-rpath=/home1/apps/intel19/impi19_0/petsc/3.16/lib64 -Wl,-rpath=/home1/apps/intel19/impi19_0/petsc/3.16/clx/lib .sconf_temp/conftest_3bc360d57f73328069eb20cbf77fe2ad_9.o -L/opt/apps/intel19/python3/3.9.2/lib -L/home1/apps/intel19/impi19_0/petsc/3.16/lib64 -L/home1/apps/intel19/impi19_0/petsc/3.16/clx/lib -lpython3.9 -lxml2 -lm -lpetsc
/opt/apps/gcc/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home1/apps/intel19/impi19_0/petsc/3.16/clx/lib/libpetsc.so: undefined reference to `H5Pget_dxpl_mpio'
/opt/apps/gcc/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home1/apps/intel19/impi19_0/petsc/3.16/clx/lib/libpetsc.so: undefined reference to `H5Pset_dxpl_mpio'
/opt/apps/gcc/8.3.0/lib/gcc/x86_64-pc-linux-gnu/8.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /home1/apps/intel19/impi19_0/petsc/3.16/clx/lib/libpetsc.so: undefined reference to `H5Pset_fapl_mpio'
```

As you can see, the link line does not contain the hdf5 libraries. What extra options do I need?

**Comment by jmansour** [comment]
UW doesn't ever call these symbols (directly), so the linking issue is really related to the `petsc` library not having an rpath to **its** required libraries. 
Perhaps adding the missing library locations to the `LD_LIBRARY_PATH` will help. Or maybe you can set `CC=h5pcc` (if available), although that's probably a bit ugly.

**Comment by VictorEijkhout** [comment]
The issue is not the library path: it's that you don't link the necessary libraries. To me it looks like you assume that `libpetsc.{so,a}` contains all necessary symbols. That is not true: if petsc is installed with external packages you'd have to parse the include files to see what extra libraries need to be loaded.

**Comment by julesghub** [comment]
Hi @VictorEijkhout, thanks for the feedback. 
Does jmansour's suggestions work for you?

**Comment by VictorEijkhout** [comment]
1. The `LD-LIBRARY_PATH` tells the linker where to find libraries. That doesn't help if you don't link the right libraries.
2.  Using `h5cc` bombs almost immediately:
```
executing command:
swig -v -Wextra -python -py3 -ignoremissing -O -c++ -DSWIG_DO_NOT_WRAP -I../build/include -I../build/include/StGermain -I../build/include/StgDomain -I../build/include/StgFEM -I../build/include/Solvers -I../build/include/PICellerator -I../build/include/Underworld -I../build/include/gLucifer -I../build/include/petsc -I../ctools Function.i

Traceback (most recent call last):
  File "/admin/build/admin/rpms/frontera/BUILD/underworld-git20220106/underworld/libUnderworld/libUnderworldPy/./swigall.py", line 40, in <module>
    raise RuntimeError("Error generating swig bindings.")
RuntimeError: Error generating swig bindings.
```

**Comment by VictorEijkhout** [comment]
Can you dictate me a three line UW program that tests if hdf5 functionality is properly installed?

**Comment by jmansour** [comment]
Hi @VictorEijkhout.  Note that UW never uses the `hdf5` library directly, and instead only utilises hdf5 via `h5py`.  

For a simple test, perhaps run `UW_DIRECTORY/docs/tests/swarm_aux.py`. 

Also, I was wrong about `LD_LIBRARY_PATH`, as that's for the runtime. Gcc also supports the `LIBRARY_PATH` variable for the compile time link-check, which you might try. As for adding PETSc's libraries directly, we did do this in the past, but it often led to other difficulties due to library link ordering. It shouldn't be necessary for a program/library to know about a library it never directly calls.

Which TACC machine are you building on?  If you support `spack`, I have a spack package that might possibly be useful.

**Comment by VictorEijkhout** [comment]
On , 2022Jan18, at 13:31, John Mansour ***@***.******@***.***>> wrote:


For a simple test, perhaps run UW_DIRECTORY/docs/tests/swarm_aux.py.


***@***.***:underworld> python3 swarm_aux.py
Traceback (most recent call last):
  File "/admin/build/victor/underworld/swarm_aux.py", line 4, in <module>
    import underworld as uw
  File "/home1/apps/intel19/impi19_0/underworld/git20220106/underworld/__init__.py", line 136, in <module>
    import underworld.mesh
  File "/home1/apps/intel19/impi19_0/underworld/git20220106/underworld/mesh/__init__.py", line 15, in <module>
    from ._mesh import FeMesh, FeMesh_Cartesian, FeMesh_IndexSet, _FeMesh_Regional
  File "/home1/apps/intel19/impi19_0/underworld/git20220106/underworld/mesh/_mesh.py", line 24, in <module>
    from underworld.scaling import dimensionalise
  File "/home1/apps/intel19/impi19_0/underworld/git20220106/underworld/scaling/__init__.py", line 14, in <module>
    from ._scaling import non_dimensionalise
  File "/home1/apps/intel19/impi19_0/underworld/git20220106/underworld/scaling/_scaling.py", line 16, in <module>
    from pint import UnitRegistry
ModuleNotFoundError: No module named ‘pint'



Which TACC machine are you building on? If you support spack, I have a spack package that might possibly be useful.

I ought to look into spack. For now I install from source.

Victor.

**Comment by jmansour** [comment]
Okay, you'll need `pint`.  `pip install --user pint` should do the trick.

**Comment by julesghub** [comment]
Hi @VictorEijkhout - is this issue still valid?
