### ISSUE TITLE
Adding processes to non-linear stokes solves (Non-linear viscosity questions)

### ISSUE THREAD

**Issue by OlympusMonds** [underworldcode/underworld2#6]
OK, so I have a viscosity function like this:
```python
sri_Fn = fn.tensor.second_invariant( 
                fn.tensor.deviatoric(
                    fn.tensor.symmetric ( 
                        velocityField.gradientFn )) )

non_newtonian_fn = 0.5 * fn.math.pow( A_Fn, -1. / n_Fn ) * \
                   fn.math.pow( sri_Fn, (1. / n_Fn) - 1.) * \
                   fn.math.pow( d_Fn, p_Fn / n_Fn ) * \
                   fn.math.pow( fH20_Fn, -r_Fn / n_Fn ) * \
                   fn.math.exp( (E_Fn + pressureField * V_Fn) / (n_Fn * R * temperatureField))
```
And down the page a bit, I use this:
```python
stokesPIC.solve(nonLinearIterate=True)
```
And it seems to work OK (I'm assuming the sri_Fn will be updated on every non-linear iteration, because it's dependent on the velocityField?)

My question is about linking other things into the non-linear process. For example, this rheology depends on the lithostatic pressure. In old UW, we had the PressureCalibration plugin to make sure the pressure outputted by stokes was approximately right for this, and it kicked in after every linear stokes solve. Another example is the isostasy plugin, which could be run non-linearly and would run after each linear stokes solve too.

How can I link in processes like this to the non-linear solve?

**Comment by jmansour** [comment]
sri_Fn is somewhat non-linearity agnostic.  It just uses the velocityField in whichever state it is at evaluation time.  (ie, it will do exactly what you want). 

As for integrating other aspects of your model into the nonlinear loop, you can achieve this by manually looping within python. For instance

```
for ii in range(0,n_nonlinear_iterations):
    stokesPIC.solve(nonLinearIterate=True)  # you could also set nonLinearIterate to False here
    pressureCalibrate.recalibrate()  # for example
```
Naturally some sort of convergence criterion would be a better option than just a arbitrary iteration count.  Also note that if you set nonLinearIterate=True, the solve itself will run a non-linear loop about the velocity/pressure solutions, and then you can have an outer non-linear loop with the pressureCalibration included.  

However, you can also set nonLinearIterate=False in which case velocity/pressure/solve non-linearity is ignore, and a regular solve occurs.. Then the non-linearity is exclusively handled by your python loop.

**Comment by OlympusMonds** [comment]
Ah right! I was asking how to expose the nonLinearIterate=True part, because I thought setting it to false  would make it complain. 
Looking at the code now, I see it only complains if you DON'T specify nonLinearIterate at all, and it detects non-linearities. 

So yes, as per your example, I would set it to be false, and handle all the extra processes as needed.

Cheers!

**Comment by jmansour** [comment]
Yep, exactly.  The flag is there to force users to be explicit when there is a non-linearity.
