### ISSUE TITLE
Anisotropic viscosity implementation

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#60]

**Comment by lmoresi** [comment]
This is important for our capacity to model frictional fault segments.  

We have a previous implementation and I would be very happy to see us expose this in a loose fashion that would allow the user to specify a second viscosity function and an orientation vector.  

While this might not be 100% robust, it would open the way to implement a number of things that were the original motivation for the python interface. Lithospheric faults imposed from python shapes etc.

**Comment by jmansour** [comment]
I will investigate if generalised weak form can be constructed at python level.  Otherwise we leverage existing integration terms (ConstitutiveMatrixCartesian etc).

**Comment by jmansour** [comment]
This is committed as hidden options to Stokes.  

Louis have you had a chance to have a play with this yet?

**Comment by julesghub** [comment]
needs documentation, testing, examples

**Comment by jmansour** [comment]
This is stale and won't be fixed for UW2. To reconsider for UW3.
