### ISSUE TITLE
What is the quickest and best way to find the submesh coordinates in deformed mesh (i.e., spherical mesh)?

### ISSUE THREAD

**Issue by gthyagi** [underworldcode/underworld2#601]
Hi,

I am trying to extract dynamic pressure data in different domains of the model. I have noticed pressure is stored on sub mesh and mesh.h5 contains only the following keys <KeysViewHDF5 ['en_map', 'vertices']>. How to find sub mesh coordinates in the deformed mesh?  XML file does computations automatically using mesh['en_map']. How to save this information? 
```
<Attribute Type="Scalar" Center="Cell" Name="pressure">
	<DataItem Format="HDF" NumberType="Float" Precision="8" Dimensions="69632001">pressureField.00001.h5:/data</DataItem>
</Attribute>
```
Thanks.

Cheers
Tyagi

**Comment by julesghub** [comment]
Hi @gthyagi 
It you're using the default mesh layout, with `elementType='Q1/dQ0'` the mesh pressure nodes coordinates will be interpolated using the linear shape functions coordinates of the velocity mesh nodes. 
We don't save this information in the mesh.h5 file as it's derivative information.

To find this information use the original python script and evaluate something like.
```
coords = underworld.function.coord()
pcoords = coords.evaluate(mesh.subMesh)
```
`pcoords` will be a numpy array you can do whatever with.

**Comment by gthyagi** [comment]
Hi @julesghub 
Thanks! It worked and was much better than my method.
