### ISSUE TITLE
About couple underworld model to badlands

### ISSUE THREAD

**Issue by gaowqspace** [underworldcode/underworld2#603]
Hello, Thanks for your job!

From this page: [https://badlands.readthedocs.io/en/latest/use.html#geodynamic-models](url)
I learned uwgeodynamics provides a way to couple an underworld model to badlands.

I want to know how can I get more information about couple underworld model to Badlands?

Thank you again.

**Comment by julesghub** [comment]
Hi @gaowqspace,

What kind of information are you after?

Here is a link with some general info,
https://uwgeodynamics.readthedocs.io/en/latest/UserGuide.html#coupling-with-badlands

An example model with the coupling is available 
https://github.com/underworldcode/UWGeodynamics/blob/master/docs/tutorials/Tutorial_11_Coupling_with_Badlands.ipynb
You can run and explore the model using a recent UWGeodynamics docker images
  `docker pull underworldcode/uwgeodynamics:2.12.4`

**Comment by gaowqspace** [comment]
I am very happy to find your reply and will learn this information.

Thanks again for your kind help.

**Comment by gaowqspace** [comment]
I have successfully run Tutorial11- Coupling with badlands！
But there is a question like this：
I installed underworld2 and UWGeodynamics separately.
underworld2: `docker run -p 8888:8888 underworldcode/underworld2`
UWGeodynamics: `docker pull underworldcode/uwgeodynamics`

They have the same content: _underworld_, _UWGeodynamics_ and _workshop_. 

But I can only run Tutorial_11 in UWGeodynamics. I don't know the reason about it. And can you solve it for other users?

Thanks!

**Comment by julesghub** [comment]
The reason is likely because the versions of UWGeo and uw2 are slightly different in the two dockers.
Currently the UWGeodynamics docker is preferred for running models with badlands.
We are working to bring underworld and UWGeodynamics together in a single docker for a later release.
