### ISSUE TITLE
Temperature BC nodes

### ISSUE THREAD

**Issue by HanyMKhalil** [underworldcode/underworld2#605]
Hi Romain, all,

I am trying to assign the temperature to specific set of nodes in this way:

nodes=list(range(10260,13337))
#nodesb=list(range(1000,15902))
Model.set_temperatureBCs(top=273.15 * u.degK,
                         bottom=1573.15 * u.degK,
                         materials=[(air, 273.15 * u.degK),(asthenosphere, 1573.15 * u.degK)],nodeSets=[(nodes, 1573.15 * u.degK )])

--------------------------------------------------
however I always get this error:

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
An uncaught exception appears to have been raised by all processes. Set the 'UW_ALL_MESSAGES' environment variable to see all messages. Rank 0 message is:
Traceback (most recent call last):
  File "./afar.py", line 217, in <module>
    materials=[(air, 273.15 * u.degK),(asthenosphere, 1573.15 * u.degK)],nodeSets=[(nodes, 1573.15 * u.degK )])
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_model.py", line 633, in set_temperatureBCs
    return self._temperatureBCs.get_conditions()
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_boundary_conditions.py", line 212, in get_conditions
    self._apply_conditions_nodes(condition, nodes)
  File "/usr/local/lib/python3.5/dist-packages/UWGeodynamics/_boundary_conditions.py", line 183, in _apply_conditions_nodes
    self.field.data[nodes.data, dim] = nd(condition[dim])
IndexError: index 10260 is out of bounds for axis 0 with size 4356
application called MPI_Abort(comm=0x84000002, 1) - process 2
application called MPI_Abort(comm=0x84000002, 1) - process 3
application called MPI_Abort(comm=0x84000002, 1) - process 4
application called MPI_Abort(comm=0x84000002, 1) - process 5
application called MPI_Abort(comm=0x84000002, 1) - process 6
application called MPI_Abort(comm=0x84000002, 1) - process 7
application called MPI_Abort(comm=0x84000002, 1) - process 8
application called MPI_Abort(comm=0x84000002, 1) - process 9
application called MPI_Abort(comm=0x84000002, 1) - process 10
application called MPI_Abort(comm=0x84000002, 1) - process 11
application called MPI_Abort(comm=0x84000002, 1) - process 12
application called MPI_Abort(comm=0x84000002, 1) - process 13
application called MPI_Abort(comm=0x84000002, 1) - process 14
application called MPI_Abort(comm=0x84000002, 1) - process 15
application called MPI_Abort(comm=0x84000002, 1) - process 1
application called MPI_Abort(comm=0x84000004, 1) - process 0

**Comment by rbeucher** [comment]
The pb is that you are passing a global index to the function. you can build an indexSet but you should use some logic that will remain valid after the mesh is partitioned. Don't use the node index itself.

Romain

**Comment by HanyMKhalil** [comment]
Hi Romain thanks a-lot, any idea about how i can build that logic an example perhaps?

**Comment by rbeucher** [comment]
Look at the Hot Canon Ball example.

https://github.com/underworldcode/UWGeodynamics/blob/master/docs/examples/1_25_Hot_Canon_Ball.ipynb

**Comment by HanyMKhalil** [comment]
Perfect, Thanks Romain. I think the code is very helpful so I can create a geoshape and assign it the temperature I want.
