### ISSUE TITLE
Under resolved cell

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/underworld2#609]
G'day all,
Running a simple 2D convection model (for teaching) on version 2.11.0-dev-485ad28, I got a under resolved cell issue. The model is relatively simple: viscosity = 1, Tsurf=Tmin=0, Tbase=Tmax=1, diffusivity=1, visc=1, g=1, density=1, expansivity=RayleighNb=1.43e7, free slip everywhere excepted at the surface Vx=0, and the model includes a fixed plate (visc=10000) covering a thrid of the model length. This model stops after a while due to an unresolved cell.  I have played with swarm.particles.per.cell.2D, popcontrol.max.splits, popcontrol.particles.per.cell.2D, and popcontrol.aggressive with no luck.
Inspection of the swarm reveals that indeed the particles get clustered in a strange pattern at a very early stage of the run (see image attached), and quickly cells are depleted of particles. It looks like the re-population doesn't work properly. I have attached an image, does anyone have seen this behavior before?

![Image2](https://user-images.githubusercontent.com/13742565/153704001-d3a19d01-9e86-4481-9eea-b31b0f5c5998.png)

**Comment by julesghub** [comment]
@patrice-rey - is this still an issue? It went quite.

**Comment by patrice-rey** [comment]
Yes, but it isn't worth investing time in it. You can close this issue, thanks Julian and Romain.

**Comment by rbeucher** [comment]
Thanks @patrice-rey
