### ISSUE TITLE
About model_run output

### ISSUE THREAD

**Issue by gaowqspace** [underworldcode/underworld2#617]
Hi, Underworld / UWGeodynamics team! Thanks for your job!

Aruptly, when I run UWGeodynamics examples or tutorials, I found it could creat output folder sometimes, but in most cases, it wouldn't creat this folder. I try to fix it but not in effect.

e.g:
`Model.outputDir=outputs_tutorial6` and `Model.outputDir=1_07_SlabSubduction` and so on. 
They could't creat outputdir.

I am looking forward to your reply!
Thank you!

**Comment by julesghub** [comment]
Hi @gaowqspace, sounds like a disk error (i.e. permissions, disk is full, etc.).
Which version of the code are you using and how did you install it?

**Comment by gaowqspace** [comment]
Hi, thanks for your reply!
I install it on Linux with Docker and the tag is latest. I run it by follow code:
`docker run -it -p 9999:8888 -v /home/manba/workspcae:/home/jovyan/workspace/ underworldcode/uwgeodynamics`

**Comment by julesghub** [comment]
on the docker the default user is `joyvan` and it has 1000 as the `$UID`. 
What's your hostmachine `UID`? i.e `echo $UID`. 
If it's not 1000 that explains it.

**Comment by gaowqspace** [comment]
I checked my hostmachine `UID `and it is 1000. GID is 1000, too.

**Comment by julesghub** [comment]
Interesting, what platform are you running on? I'm using pop_os (linux) and can run the following successfully. Can you.
```
docker run --rm -it -v $PWD:/home/jovyan/workspace underworldcode/uwgeodynamics:latest bash -c 'echo "testing..." >> ~/workspace/foo.dat' ; cat foo.dat
```

Does that work for you?

**Comment by gaowqspace** [comment]
Thanks for your reply again. I run UWG on Ubuntu successfully. And I try run it with your method like this:
`docker run --rm -it -v $PWD:/home/jovyan/workspace underworldcode/uwgeodynamics:latest bash -c 'echo "testing..." >> ~/workspace/foo.dat'`
`>cat foo.dat`
`>testing...`
It looks like succeed.

**Comment by julesghub** [comment]
> Hi, thanks for your reply! I install it on Linux with Docker and the tag is latest. I run it by follow code: `docker run -it -p 9999:8888 -v /home/manba/workspcae:/home/jovyan/workspace/ underworldcode/uwgeodynamics`

Hi @gaowqspace did you manage to fix your error? The test shows you have write permissions so I think it's a missing directory problem. 
In the above response I notice a typo, `workspcae`. Perhaps this was the problem?

**Comment by gaowqspace** [comment]
Hi @julesghub I'm try some another methods. Above `workspace` is my type error in here. 
Thank you again!
