### ISSUE TITLE
Issues loading and saving swarms and swarm variables

### ISSUE THREAD

**Issue by cgoise** [underworldcode/underworld2#618]
**EDIT** we tested this a little further (it is really important to us to properly save and open data on different machines in our current scenario) and it seems that this error does not occur with a freshly restarted kernel. Just if you open and save multiple times. That doesn't really solve it for us, but maybe it is a hint for you. 

When I try to save and re-load swarms and swarm-variables, the values are most often **not identically restored**. Maybe I am doing something wrong, but the restored data seems to be partly random.

Below I demonstrate what I mean in 2 slightly different cases. I tested this with uw2 2.11.2b, 2.12.2b and 2.13.0b, running in both, docker and singularity containers. Would be interesting to know if this happens to other people, too.

## Case 1

If I run the code below:

```python
import underworld.visualisation as vis

import underworld as uw
import numpy as np

mesh = uw.mesh.FeMesh_Cartesian(elementRes=(10, 10),minCoord=(0., 0.),maxCoord=(10., 10.),)

swarm = uw.swarm.Swarm(mesh=mesh, particleEscape=True)
swarmLayout = uw.swarm.layouts.PerCellSpaceFillerLayout( swarm=swarm, particlesPerCell=100)
swarm.populate_using_layout(layout=swarmLayout)

materialVariable = swarm.add_variable(dataType="float", count=1)
materialVariable.data[:] = np.expand_dims(np.random.normal(size=materialVariable.data.size),1)

figMaterial = vis.Figure(figsize=(1800, 500))
figMaterial.append(vis.objects.Points(swarm, materialVariable, pointSize=7.0))
figMaterial.show()

swarm2 = swarm
materialVariable2 = materialVariable
mesh2 = mesh

mesh.save("mesh.h5")
mesh.load("mesh.h5")

swarm.save("swarm.h5")
swarm.load("swarm.h5")

materialVariable.save("material.h5")
materialVariable.load("material.h5")

print(np.allclose(swarm.data, swarm2.data))
print(np.allclose(materialVariable.data, materialVariable2.data))
print(np.allclose(mesh.data, mesh2.data))

figMaterial.show()
```

the results could be that:
![grafik](https://user-images.githubusercontent.com/15956510/180046620-7d2e8abe-976f-4e54-b747-5e7be254a5d2.png)
```sh
True
False
True
```
![grafik](https://user-images.githubusercontent.com/15956510/180046762-c8f5aa46-5fc3-41fd-8f1c-44cecd77944c.png)

I do not know if the problem is solely in the loading of the swarm-variable data, althoug it seems so.

## Case 2

I did also have the following, maybe related, issue. Note that I save and load the `director` swarm variable, but not the swarm itself. Which - to my understanding - should not be necessary, as the data-structure remains what it is, right?

```python

            fnameVelocityField =  outputPath + "velocityField" + str(step).zfill(4)
            xdmf_info_velocityField = velocityField.save(fnameVelocityField + '.h5')

            xdmf_info_swarm    = swarm.save(outputPath + "swarm" + str(step).zfill(4) + '.h5')
            fnameDirector = outputPath + "cAxes-" + str(step).zfill(4)
            xdmf_info_director = director.save(fnameDirector + ".h5")

            # xdmf
            velocityField.xdmf( fnameVelocityField + '.xdmf', xdmf_info_velocityField, "VelocityField", xdmf_info_mesh, "TheMesh", modeltime=time)
            director.xdmf(fnameDirector + '.xdmf', xdmf_info_director, "C-axes", xdmf_info_swarm, "TheSwarm", modeltime=time)

            if rank==0:
                np.save(outputPath + "time" + str(step).zfill(4), step)
                print(f'\n -------  step: {step}  ------- \n')
            comm.Barrier()

            # test
            mesh.load(outputPath + "mesh.h5")
            #swarm.load(outputPath + "swarm" + str(step).zfill(4) + '.h5')

            velocityField.load (outputPath + "velocityField" + str(step).zfill(4) + ".h5" )
            director.load( outputPath + "cAxes-" + str(step).zfill(4) + ".h5" )
```
output:
```sh
RuntimeError                              Traceback (most recent call last)
<ipython-input-39-3edc013dfc47> in <module>
     72 
     73 if __name__ == "__main__":
---> 74     main()

<ipython-input-39-3edc013dfc47> in main()
     44 
     45             velocityField.load (outputPath + "velocityField" + str(step).zfill(4) + ".h5" )
---> 46             director.load( outputPath + "cAxes-" + str(step).zfill(4) + ".h5" )
     47 
     48             #figCAxes.save_image(outputPath + "cAxes-" + str(step).zfill(4) +

/opt/venv/lib/python3.8/site-packages/underworld/swarm/_swarmvariable.py in load(self, filename, collective)
    273 
    274         if self.swarm._checkpointMapsToState != self.swarm.stateId:
--> 275             raise RuntimeError("'Swarm' associate with this 'SwarmVariable' does not appear to be in the correct state.\n" \
    276                                "Please ensure that you have loaded the swarm prior to loading any swarm variables.")
    277         gIds = self.swarm._local2globalMap

RuntimeError: 'Swarm' associate with this 'SwarmVariable' does not appear to be in the correct state.
Please ensure that you have loaded the swarm prior to loading any swarm variables.
```
If I save **and** load the swarm immediately after saving, the error-message is that the size of the swarm has doubled (it has really 80.000 particles). This might have to do with the dimension of the system, which is 2.
```sh
RuntimeError: It appears that the swarm has 160000 particles, but provided h5 file has 80000 data points. Please check that both the Swarm and the SwarmVariable were saved at the same time, and that you have reloaded using the correct files.
```

**Comment by julesghub** [comment]
@cgoise, the general problem is python `=` is a reference, not a new copy of the object.variable/datastructure.

![image](https://user-images.githubusercontent.com/13825704/180345161-d95b9fdf-4fe5-4ce6-9906-58d5a9c6f3e6.png)

Don't make `swarm2 = swarm`, make swarm2 and entirely new `Swarm()`, you should also do this when reloading a model.

**Comment by cgoise** [comment]
Thank you for your answer. 

Maybe I have to play a bit more with that. Create (and purge) swarms anytime I 
need to do any loading / saving. The Python way of 'copying' is nothing for 
the faint-hearted.

But: my original code was the way you suggest. I needed to make it a little 
more github-compatible and shortened it. And what I don't see: why would this 
matter?

The data structure remains exactly the same, doesn't it? A swarm can't be more 
compatible with anything than with itself. Is there something internal to UW2 
preventing this on purpose?

Many greetings,
Till


Am Freitag, 22. Juli 2022, 04:01:07 CEST schrieb Julian Giordani:
> @cgoise, the general problem is python `=` is a reference, not a new copy of
> the object.variable/datastructure.
> 
> ![image](https://user-images.githubusercontent.com/13825704/180345161-d95b9f
> df-4fe5-4ce6-9906-58d5a9c6f3e6.png)
> 
> Don't make `swarm2 = swarm`, make swarm2 and entirely new `Swarm()`, you
> should also do this when reloading a model.

**Comment by julesghub** [comment]
Hi Till,

There's more info on this user guide. There is a section on checkpointing Swarms/SwarmVariables and Mesh/MesVariables.
https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/06_Utilities.ipynb

Note the swarm load is an additive operation. So if you have a swarm with 10 particles and `save()` then `load()` the swarm will then have 20 particles i.e. (original 10 * 2).

Hope this helps.

**Comment by cgoise** [comment]
Hi,

yes, thank you, this helped a lot. I had no idea that this is operation is 
additive, this explains it all.

I will close the issue.

The world makes sense again.

Greetings,
Till

Am Freitag, 22. Juli 2022, 11:48:53 CEST schrieb Julian Giordani:
> Hi Till,
> 
> There's more info on this user guide. There is a section on checkpointing
> Swarms/SwarmVariables and Mesh/MesVariables.
> https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/0
> 6_Utilities.ipynb
> 
> Note the swarm load is an additive operation. So if you have a swarm with 10
> particles and `save()` then `load()` the swarm will then have 20 particles
> i.e. (original 10 * 2).
> 
> Hope this helps.
