### ISSUE TITLE
Sediments are no longer time stamped.

### ISSUE THREAD

**Issue by patrice-rey** [underworldcode/underworld2#619]
G'day, I have noticed that sediments are no longer time stamped through the projTimeField. The outcome is that we no longer can colour code the sediment with their age of deposition, which is essential for any model involving the formation of sedimentary basins. Would it be possible to fix this? Cheers.

**Comment by rbeucher** [comment]
Probably related to the change you made a while back @julesghub ...

**Comment by julesghub** [comment]
Yeah that's what I'm suspecting - I can see the projTimeField has numbers in it. I'll sift though the history.

**Comment by patrice-rey** [comment]
Thanks Julian for fixing this non-issue. It turns out that in the 2 lines of code below, the erosion threshold masks the previous surfaceProcesses (sedimentation). 

Model.surfaceProcesses = GEO.surfaceProcesses.SedimentationThreshold(air=[air], sediment=[sediment], threshold=0. * u.metre)
Model.surfaceProcesses = GEO.surfaceProcesses.ErosionThreshold(air=[air], threshold=4000. * u.metre)

The solution of my problem was simply to comment out the erosion threshold. 

In case when both erosion and sedimentation are needed, better use the ErosionAndSedimentationThreshold.

**Comment by julesghub** [comment]
Glad this fixed the issue.
