### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Soul-Star** [underworldcode/underworld2#637]
I tried to install underworld with pip3 install underworld, but it failed. And I can't find why.
My system is Ubuntu 18.04.  And python version: 3.8.4, swig version: 4.1.0, petsc version: 3.16.4
There are some of contents of terminal screen.

![image](https://user-images.githubusercontent.com/53247253/202424092-0e1e493b-4c0c-4d3f-9b84-eaba0cfcad24.png)
![image](https://user-images.githubusercontent.com/53247253/202424190-85fa5bdf-91cf-4fba-88f2-4c7ceb095231.png)
![image](https://user-images.githubusercontent.com/53247253/202424505-ec90d446-0046-4978-a1c5-55cb2cd6a5e5.png)
![image](https://user-images.githubusercontent.com/53247253/202424634-4b645efb-52fe-4631-abd0-cc4baee105d0.png)
![image](https://user-images.githubusercontent.com/53247253/202424793-ca6a3422-cf40-44c1-b0f6-4f571768fb54.png)
![image](https://user-images.githubusercontent.com/53247253/202424835-2a4a5a92-b316-4792-a40a-88994cab3ae6.png)
![image](https://user-images.githubusercontent.com/53247253/202424908-a300a050-5f42-415e-b8c9-8086aa77c48c.png)
![image](https://user-images.githubusercontent.com/53247253/202425016-4547cd7e-2db4-47f2-8ca0-8bcc0ba585ee.png)
![image](https://user-images.githubusercontent.com/53247253/202425076-45bc610d-accc-45c6-9c6e-8e2b61b47537.png)

Can anyone helpe me?

**Comment by Soul-Star** [comment]
Hi @julesghub , thanks for your response!
I updated my python to 3.10, and enable shared, so I got the libpython3.10.so.
Then I reinstall underworld, it worked! I also tried some examples, it worked well.
Thank you again!

**Comment by julesghub** [comment]
Great stuff. Enjoy the Underworld!
