### ISSUE TITLE
(Geodynamics) Projection/Add swarm_variable for viscous dissipation in Geodynamics

### ISSUE THREAD

**Issue by Peigen-L** [underworldcode/underworld2#638]
Hi underworld team,
I am trying to build an individual field for viscous dissipation field in the example 1_04_SlabSubduction using Geodynamics 2.10.1.
SImple codes is attached here: 
[DissipationToolTest.py.txt](https://github.com/underworldcode/underworld2/files/10038542/DissipationToolTest.py.txt)

I defined the viscous dissipation value by: 
`Dissipation = Model.strainRate_2ndInvariant[0]*Model.projStressTensor[0] + Model.strainRate_2ndInvariant[1]*Model.projStressTensor[1] +Model.strainRate_2ndInvariant[2]*Model.projStressTensor[2]`
(please correct me if this is wrong)
and added a new swarm variable using:
`DissipationField = Model.add_swarm_variable(name='Dissipation', restart_variable=True, count=1)`

But the output Model.dissipation is 0 everywhere after 2 timesteps. I assume need a correct projection on the mesh for viscous dissipation in the Model?

Please help

Kind Regards

Peigen

**Comment by bknight1** [comment]
Hi @Peigen-L,

I've taken a quick look and updated the script for you. Essentially you also needed to update the dissipation swarm variable every time you want to calculate/visualise the viscous dissipation (VD). I have added a function that updates this every loop for you in the script. I've previously calculated the VD a slightly different way and included that in the script too. Also the figure at the end used Model.dissipation, which didn't exist in your script, this should be the swarm variable name, which was 'DissipationField'. I've attached an updated script for you, let me know if you need any more help!

Cheers,
Ben
[DissipationToolTest-BK.py.txt](https://github.com/underworldcode/underworld2/files/10051049/DissipationToolTest-BK.py.txt)

**Comment by Peigen-L** [comment]
Hi Ben, @bknight1 

Thank you for your help! The script works well! I will close this issue.

Cheers,

Peigen
