### ISSUE TITLE
Increase resolution and swarm in parallel 

### ISSUE THREAD

**Issue by jlikermanUPC** [underworldcode/underworld2#643]
Dear UWGeodynamics team,

I have two specific queries:

1) Is it possible increase the resolution at the top of the domain with UWGeodynamics? Is there an example i can check?

2) When I run UW with singularity in parallel, is it okay to have as an output a single swam file (per checkpoint) despite using more than one processor?

Thanks, 

Jeremías

**Comment by julesghub** [comment]
Hi @jlikermanUPC,

Nice to hear from you.

1. UW can only deform a regular mesh, not arbitrarily increase the resolution in a region of the model. So you can gain resolution in one part of the model at the expense of other regions.
See this example 
https://github.com/underworldcode/underworld2/blob/master/docs/UWGeodynamics/examples/1_23_03_FreeSurface_Crameri2012Case1_Relaxation.ipynb 
Note the lines below which deform the y coordinates of the `top_wall` mesh nodes.
```
with Model.mesh.deform_mesh():
     Model.mesh.data[Model.top_wall.data, 1] = perturbationFn.evaluate(Model.top_wall)[:,0] 
``` 
Follow that pattern and you should be able to deform the mesh.

2. Short answer Yes. UW is designed to only generate one checkpoint file for the swarm. It doesn't matter the number of processors. We utilise parallel h5py to handle the I/O operations for that. 
In general the UW design is to provide parallel enabled python objects so the code works exactly the same in serial or parallel.

cheers,
J

**Comment by jlikermanUPC** [comment]
Thanks for the fast reply!

1. Will check and try!
2. Ok. So, to be sure I'm doing right, the py file with the mumps solver is fine, and to run it on the cluster, with the command: 
`srun -n $ntasks singularity exec $PATH python file.py
`
would it be ok?

Thanks again,
J

**Comment by julesghub** [comment]
> srun -n $ntasks singularity exec $PATH python file.py 

That should work, different HPC configurations exist, so it's difficult to say exactly. 
What HPC are you running on?
Any documentation on it?

**Comment by jlikermanUPC** [comment]
[MareNostrum.](https://www.bsc.es/supportkc/docs/MareNostrum4/intro)

Jobs are running fine. But I just want to double check if it's running with all the resources assigned.

This is what i found: https://www.bsc.es/supportkc/blog/mpi-singularity-guide.

Thanks again

**Comment by julesghub** [comment]
To check the model is correctly distributed you should see a output message like this:
```
	Global element size: 1024x128x256
	Local offset of rank 0: 0x0x0
	Local range of rank 0: 32x32x32
```
Note the numbers are only an example.

The `Local range` reflects the per processor chunk of work from the `Global element size`, i.e. the mesh size.

**Comment by julesghub** [comment]
Looking at these: 
https://www.bsc.es/supportkc/blog/mpi-singularity-guide
https://www.bsc.es/supportkc/docs-utilities/singularity/

bsc uses the hybrid singularity approach for MPI execution. So you should use:
`mpirun -np 4 singularity exec image_name.sif ./mpi_app`

Let me know how your model runs go.

For testing singularity configurations I'd use a short/small model to minimise execution response time.

**Comment by jlikermanUPC** [comment]
Thanks @julesghub , it worked!, both, mesh deformation and the jobs running in parallel.
