### ISSUE TITLE
KeyError could be suitable here

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/underworld2#648]
https://github.com/underworldcode/underworld2/blob/b72fc39337db6c36a68b585540262c14cc9fc59e/underworld/swarm/_swarmvariable.py#L344

Hi, I was recently trying to load a swarm variable without units and generated by an older version of underworld, the 'UndefinedUnitError' doesn't catch the exception which in my case threw a 'KeyError', changing this resulted in the loading to work as expected. 
Sorry for not adding a file.

**Comment by julesghub** [comment]
Hi @arijitlaik ,
Thanks for pointing this out! We have a fix for this that I applied to the _meshvariable and _swarm. I missed making this change here. I can apply now.

**Comment by arijitlaik** [comment]
Thanks :)
