### ISSUE TITLE
cannot import name 'StGermain' from partially initialized module 'underworld.libUnderworld.libUnderworldPy'

### ISSUE THREAD

**Issue by blingwang1996** [underworldcode/underworld2#651]
Dear Underworld Team

I encountered some problems in "import underworld"

The ImportError: cannot import name 'StGermain' from partially initialized module 'underworld.libUnderworld.libUnderworldPy' (most likely due to a circular import) (/Volumes/DATA/Underworld2/underworld2/underworld/libUnderworld/libUnderworldPy/__init__.py)
The underworld2 _version is ""2.14.0b""

Please help

Kind Regards

**Comment by julesghub** [comment]
Hi @blingwang1996 ,

The current underworld version is 2.14.1b. I can confirm installing it with `pip install underworld` works for me.
```
$ pip install underworld
...
$ python -c 'import underworld as uw; print(uw.__version__)'
2.14.1b
```
How did you install underworld: using docker, pip or compilation?

cheers,
J

**Comment by blingwang1996** [comment]
Thanks guys so much
