### ISSUE TITLE
Export antisymmetric tensor

### ISSUE THREAD

**Issue by jlikermanUPC** [underworldcode/underworld2#656]
Hi all, 

I am trying to export, from the Model.projStressTensor, the anti-symmetric part of a tensor. I apply the function underworld.function.tensor.antisymmetric(Model.projStressTensor), but then I don't know how get the output for each step.

Could you give me an idea how to do it?

I'm trying to have the 4 components of the stress tensor (2D).

Thank you!

Jeremías

**Comment by lmoresi** [comment]
Most of the constitutive models assume the tensor is symmetric and this is probably assumed in most parts of the code. Perhaps the function you are using is not compatible with being fed a symmetric tensor ?

There is also the issue of which solver setup to choose if the problem does not have the expected symmetry. We may need to discuss this somewhere other than the issue tracker.

**Comment by tingyang2004** [comment]
Due to the equilibrium of momentum, the stress tensor is always symmetric, so its asymmetric part should always be zero. However, the velocity gradient usually incorporates both the symmetric (strain tensor) and asymmetric (rotation) parts.

**Comment by jlikermanUPC** [comment]
Thanks both @lmoresi and @tingyang2004 .  I'll asume that tensor is symmetric.
