### ISSUE TITLE
Tutorial for using LavaVu standalone for visualisation

### ISSUE THREAD

**Issue by OKaluza** [underworldcode/underworld2#66]
Run through a workflow using LavaVu for visualisation:
- Create databases, including multiple timesteps to single file
- Build the standalone viewer
- View visualisations from database files
- Export images and video from database files
- The pros and cons of using this workflow rather than generating images on HPC facilities.

**Comment by arijitlaik** [comment]
@OKaluza could you kindly provide an example for a simple exporting images from database files example??
```python
import glucifer

gluciferDatabase = glucifer.Viewer('databaseFile')

fname=""
for step in gluciferDatabase.steps:
    for name in  gluciferDatabase.figures:
        gluciferDatabase.figure(name)
        gluciferDatabase["quality"] = 1
        #gluciferDatabase.show()
	fname=gluciferDatabase['title']+"-"+str(step).zfill(5)+".png"
        gluciferDatabase.save(fname)


# vis =glucifer.Viewer('Subduction2') 
# vis.interactive()

```
this save a text file
[Velocity-00000.png.txt](https://github.com/underworldcode/underworld2/files/2508529/Velocity-00000.png.txt)

**Comment by OKaluza** [comment]
Using lavavu... (the return object from glucifer.Viewer is now a wrapper for lavavu.Viewer anyway so you can use it the same way):

```
import lavavu
lv = lavavu.Viewer(database=dbfilename)

for step in lv.steps:
    print(step)
    lv.timestep(step)
    lv.display() # Displays inline if in IPython, saves image to disk if not
```

If you want to choose the filename manually or always save to disk from IPython, your example was almost right, but the function is image() rather than save() (save exports a JSON file with all the current vis settings)
```
    fname = str(step).zfill(5) + ".png"
    lv.image(fname)
```

If you have separate figures in the same database you can iterate through lv.figures too in an inner loop but it's not necessary if you have only one.

You can modify any of the visualisation properties, or set the camera etc too before saving images.

Alternatively, simplest way to dump images without breaking out python is just using the executable:
`LVPATH/lavavu/LavaVu -i dbfile.gldb`
If you have installed with the pip package, the script LV should work without needing to know the install path:
`LV -i dbfile.gldb`
