### ISSUE TITLE
Increase resolution in a specific area

### ISSUE THREAD

**Issue by jlikermanUPC** [underworldcode/underworld2#666]
Dear UWGeodynamics team,

Is it possible to increase the resolution of a 2D domain in a specific area of the UWGeodynamics mesh? Is there an example I can check?

Thanks,

Jeremías

**Comment by julesghub** [comment]
Hi Jeremis,

You can deform the mesh (without adding mesh points). This can increase the resolution in specific parts of the domain, whilst also reducing the resolution in other parts.

A simple example you can checkout is the raw Underworld user guide here.
https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/02_TheMesh.ipynb

From the `Model` object in UWGeodynamics you can grab the mesh object and follow the workflow in the user guide.

Hope this helps.

**Comment by jlikermanUPC** [comment]
Thanks!
