### ISSUE TITLE
The influence of mesh resolution

### ISSUE THREAD

**Issue by jlikermanUPC** [underworldcode/underworld2#667]
Dear UW team,

We are doing some tests with a 2D thrust wedge model and we realized that the evolution of the model changes drastically as the resolution increases after a threshold (512 for the x-axis).

We understand that the selection of the resolution is a sensitive issue, but what explanation can be given to obtain such different models? By increasing the resolution of the regular mesh, and therefore the amount of swarm particles, does that make the model subject to small stress perturbations and therefore result in the development of more structures? Additionally, non-rectangular cells can influence this behavior?

Figure 1: 512x128
![Figure1](https://github.com/underworldcode/underworld2/assets/68082760/a64ee3a5-c990-41d6-90a9-f423e2ed3d60)

Figure 2: 1024x128
![Figure2](https://github.com/underworldcode/underworld2/assets/68082760/7339bdc2-2e3c-465c-80ac-785113b8dd1b)

We're using Underworld2.13

Thanks,

Jeremías

**Comment by jlikermanUPC** [comment]
Hi @tingyang2004 , thanks for the reply.

Ok, that makes sense but the difference remains substantial.

The initial weak seed is a velocity discontinuity located in the bottom center of the model. Yes, the dimensional time is the same in both models.

**Comment by tingyang2004** [comment]
Are you saying that the horizontal velocity of the base boundary is imposed as a Dirichlet boundary condition, and that the imposed velocity is discontinuous at the horizontal center? In this case, the physical model of the weak seed setup does not depend on resolution, but maybe the inhomogeneity introduced by your initial weak seed may have effects lower than or comparable to that of the random error (e.g., introduced by the swarm whose initial position is usually randomly assigned). In this case, rerun the model at the same resolution may also make a noticeable difference.

**Comment by julesghub** [comment]
@jlikermanUPC it would be good to see the high res. "regular" results, ie, 1024 x 256, 2048x512, ....
Perhaps the model was initially underesolved in the vertical direction with 128.
Also solver tolerances could impact the results of fine (and finer) shear banding.
Maybe decrease (tighten) the tolerances for high resolution if you still observe different outcomes at difference resolutions.

**Comment by jlikermanUPC** [comment]
@tingyang2004, indeed, the issue we are facing does not seem to originate from the generation of the weakness seed itself, but rather from the overall result of the model. In fact, failure occurs consistently in the seed's location in all runs. On the other hand, we have run several models keeping the resolution (either the same or varying it minimally) and there are not substantial changes.

Thanks @julesghub, we will carry out the suggested tests. Currently, we are running mumps solver with a tolerance of 1e-2. Would you recommend reducing it to 1e-3?

**Comment by bknight1** [comment]
I agree with @tingyang2004 initial comment.

To me, this looks similar to the 'wide' and 'narrow' rift phenomenon, which is dictated by the viscosity at the base of the crust. As your resolution increases it looks like the viscosity at the base of the crust appears to decrease. This is probably due to the higher resolution capturing the change from strong plastic crust to weak viscous crust below the brittle-ductile transition. The weaker the lower crust the more spread out (or wider) the deformation becomes. This may be why you see it after a certain resolution, I assume the models before this critical resolution look like fig 1 and all modes after look like fig 2.

**Comment by jlikermanUPC** [comment]
Thanks to all, we conducted the test and found the best mesh resolution.
