### ISSUE TITLE
How to set an elevation with a height variation in coupling model of uwGeodynamics and badlands

### ISSUE THREAD

**Issue by 42041030** [underworldcode/underworld2#671]
When I used the coupling model of uwGeodynamics and badlands, I found that I couldn't use the imported elevation data (the location of the elevation file was added to the badlands XML file), and could only set the constant horizontal elevation, which is surfElevation=y (seems can't set an array). So I would like to know how to set an elevation with a height variation

**Comment by julesghub** [comment]
Can you please send through your input files and the elevation file used. 
Either setup a private GitHub repo or send the files directly here.
Thanks!

**Comment by Ankke3** [comment]
Thanks,Jules. I test another way to solve this question. I will reopen it if it's not work.

> Can you please send through your input files and the elevation file used. Either setup a private GitHub repo or send the files directly here. Also what version of underworld are you using? Thanks!

**Comment by 42041030** [comment]
Thanks, Jules! I am testing another way to solve this question. And I will reopen it if it's not work.

> Can you please send through your input files and the elevation file used. Either setup a private GitHub repo or send the files directly here. Also what version of underworld are you using? Thanks!

**Comment by 42041030** [comment]
Thanks, Jules! I am testing another way to solve this question. And I will reopen it if it's not work.

> Can you please send through your input files and the elevation file used. Either setup a private GitHub repo or send the files directly here. Also what version of underworld are you using? Thanks!

**Comment by 42041030** [comment]
Thanks, Jules! I am testing another way to solve this question. And I will reopen it if it's not work.

> Can you please send through your input files and the elevation file used. Either setup a private GitHub repo or send the files directly here. Also what version of underworld are you using? Thanks!
