### ISSUE TITLE
Solver / non-linearity & reporting

### ISSUE THREAD

**Issue by lmoresi** [underworldcode/underworld2#68]
``` python
solver.print_stats()
```

Should do the right thing in a non-linear case. At the moment it reports stats on the final linear solve of the picard iteration. It should give a summary of the non-linear solution.

**Comment by jmansour** [comment]
the solver reporting could be improved significantly.  it might even be a good option to solver chugging away async, allowing users to continue interfacing with ipython, and to query the solver status etc.

**Comment by julesghub** [comment]
remember the kspconvergedreason

**Comment by jmansour** [comment]
@lmoresi, you committed some changes recently. Did they address this ticket, or was it something else?

**Comment by lmoresi** [comment]
No, I don’t think I could see how to do that easily. I just tried to ensure that the “timeout" would not be problematic.

L

---
Professor Louis Moresi
louis.moresi@unimelb.edu.au<http://mailto:louis.moresi@unimelb.edu.au/>
   (w) +61 3 8344 1217<tel://8344%201217>
   (m) +61 4 0333 1413<tel://0333%201413>
   (us) +1 505 349 4425<tel://349%204425>
www.moresi.info<http://www.moresi.info/>
www.facebook.com/underworldcode<http://www.facebook.com/underworldcode>


On 4 October 2016 at 12:51:29 PM, jmansour (notifications@github.com<mailto:notifications@github.com>) wrote:

@lmoresi<https://github.com/lmoresi>, you committed some changes recently. Did they address this ticket, or was it something else?

**Comment by julesghub** [comment]
#235

**Comment by julesghub** [comment]
See c1bdcc8bc0cd958fccd05a953aacd9d8e479d952

KSPGetConvergedReason() is used to check the 3 KSPSolves done in auglag-driver-DGTGD.c (outer solve, velocity backsolve and fhat solve)
In  _bsscr.py a check on the 3 reason values is made and if divergence occurs a warning is raised.
This will work in both non-linear and linear cases.

Not the cleanest design for solver reporting but it's a start and the idea can be applied to the other systems we have in UW.

**Comment by jmansour** [comment]
Closing this. Issues still relevant for uw3, but it'll need a rethink for new petsc backend.
