### ISSUE TITLE
A question about strata results from coupled model

### ISSUE THREAD

**Issue by tyszwh** [underworldcode/underworld2#689]
Hi  Dr Julian 
     I have some question about the coupled model, and I'm not sure it's a problem with the code. I was hoping you could give me some advice.
    When I use the coupled uwgeodynamics (2d) and badlands (2.5d) model, the position of the basin sequences formed by the surface process model seems to be out of sync with the position of the basin sediment on the underworld2 model, there is clearly some deviation. How is this caused? Is this prossible to fix this problem? Please refer to the attached figure for details.

Thanks

![Model_Resutls](https://github.com/underworldcode/underworld2/assets/8081772/d105efdb-2e39-4029-8d1a-d8c7f6c3b240)

**Comment by julesghub** [comment]
Hi @tyszwh, how are you visualising these results? 
what version of the code are you running?

The mesh for badlands and the upper surface of Underworld2 are not the same and information is shared between the two meshes using a virtual interface. I believe this is the cause of the deviation you are observing.

**Comment by tyszwh** [comment]
These results were visualised using paraview and zoomed in 5x on the vertical. I have also used python plot strata results and the results are similar.
I am using underworld version 2.16.x and badlands version 2.2.4.
Is the 'np_surface' defined in the code a virtual surface? Any suggestions on how to fix this?

**Comment by tyszwh** [comment]
Hi,@julesghub 
I did some more testing and I found that even though the two models share the same velocity field, they don't seem to deform in the same way in the areas of greater deformation. Is this related to mesh accuracy? Any suggestions on fixing this issue?
Thanks
