### ISSUE TITLE
Pythonize regional spherical 

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#76]

**Comment by jmansour** [comment]
What is required here?  Does this involve rotated BCs?

**Comment by julesghub** [comment]
Yep - i'm going to get started on it soon.

Will try go down the path of building a global rotation matrix and make it
accessibly to the python layer.
This should enable use to expose some of the previously low level
operations that were done in uw1.

**Comment by julesghub** [comment]
In commit 7bd600f93f1a7e3c3c660c05e15a899e2e9b68b7 a spherical section mesh is available. No boundary conditions or rotated coord systems yet.
To use:
uw.mesh._FeMesh_Regional()
