### ISSUE TITLE
Viscoelastic

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#77]
Viscoelastic rheology & analysis with
1. subduction
2. thermal
3. plasticity
4. Jaumann

**Comment by AngelValverdePerez** [comment]
Have some questions about what equations is underworld working with:

I know the uw solves the stokes equation, and uses the byerlee criteria for the viscoplasticity (with the cohesion), but if I want a material only with plasticity behaviour, I have to include the equations and the elasticity parameters such as Young modulus? In addition, If I want to write other criteria or additional criteria to the byerlee, how this could be implemented in uw?

**Comment by RebeccaFarrington** [comment]
Hi Angel,

The first place to look for different rheologies is in the examples directory.  You will see examples using a number of different rheologies. It would be a good idea to review the references listed in http://www.underworldcode.org/  starting with  

_Moresi, L., Quenette, S., Lemiale, V., Mériaux, C., Appelbe, W., Mühlhaus, 2007, Computational approaches to studying non-linear dynamics of the crust and mantle: Phys. Earth Planet. Inter, v. 163, p. 69–82, doi: 10.1016/j.pepi.2007.06.009_

Also note that when modelling plastic behaviour in Underworld, a viscoplastic implementation is used not  purely plastic.

**Comment by julesghub** [comment]
@RebeccaFarrington  should this be moved to post june. Jaumann needs further implmentation

**Comment by RebeccaFarrington** [comment]
Yes, yes it should.  done.

**Comment by jmansour** [comment]
Need some way to handle Jaumann

**Comment by RebeccaFarrington** [comment]
All bar Jaumann. 
I'll have a look asap.
Cheers,

**Comment by jmansour** [comment]
This is stale and won't be fixed for UW2. To reconsider for UW3.
