### ISSUE TITLE
Flux terms

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#79]

**Comment by julesghub** [comment]
A flux condition can now be added to the energy equation and the heat equation. 

See commit  78ff7c8f1b3a6991a1b42fbb1e8f3dfb4484fb14 and the example fluxBC_heat_eq.ipynb

For the momentum equation the flux conditions haven't been tested yet. I'll close this ticket and open another one for finalising momentum flux conditions.
