### ISSUE TITLE
invalid submesh not detected

### ISSUE THREAD

**Issue by jmansour** [underworldcode/underworld2#8]
this probably shouldn't be a valid input
```
elementMesh = uw.mesh.FeMesh_Cartesian( elementType='Q2/3213DPC1', 
                                         elementRes=(1,1), 
                                           minCoord=(0.,0.), 
                                           maxCoord=(0.9142,1.) )
```

**Comment by mirkovelic** [comment]
It's like that by special request.

**Comment by jmansour** [comment]
Nein!

**Comment by mirkovelic** [comment]
Nein Nein!
This is one of those rare cases where the 'bug' is actually a feature!

**Comment by jmansour** [comment]
You sure this wasn't meant to be a feature on the fruity repo?
                                   ___
                                _/`.-'`.
                      _      _/` .  _.'
             ..:::::.(_)   /` _.'_./
           .oooooooooo\ \o/.-'__.'o.
          .ooooooooo`._\_|_.'`oooooob.
        .ooooooooooooooooooooo&&oooooob.
       .oooooooooooooooooooo&@@@@@@oooob.
      .ooooooooooooooooooooooo&&@@@@@ooob.
      doooooooooooooooooooooooooo&@@@@ooob
      doooooooooooooooooooooooooo&@@@oooob
      dooooooooooooooooooooooooo&@@@ooooob
      dooooooooooooooooooooooooo&@@oooooob
      `dooooooooooooooooooooooooo&@ooooob'
       `doooooooooooooooooooooooooooooob'
        `doooooooooooooooooooooooooooob'
         `doooooooooooooooooooooooooob'
          `doooooooooooooooooooooooob'
           `doooooooooooooooooooooob'
      jgs   `dooooooooobodoooooooob'
             `doooooooob dooooooob'
               `"""""""' `""""""'

**Comment by jmansour** [comment]
damn you useless preview!

**Comment by mirkovelic** [comment]
haha.

**Comment by jmansour** [comment]
___
                                _/`.-'`.
                      _      _/` .  _.'
             ..:::::.(_)   /` _.'_./
           .oooooooooo\ \o/.-'__.'o.
          .ooooooooo`._\_|_.'`oooooob.
        .ooooooooooooooooooooo&&oooooob.
       .oooooooooooooooooooo&@@@@@@oooob.
      .ooooooooooooooooooooooo&&@@@@@ooob.
      doooooooooooooooooooooooooo&@@@@ooob
      doooooooooooooooooooooooooo&@@@oooob
      dooooooooooooooooooooooooo&@@@ooooob
      dooooooooooooooooooooooooo&@@oooooob
      `dooooooooooooooooooooooooo&@ooooob'
       `doooooooooooooooooooooooooooooob'
        `doooooooooooooooooooooooooooob'
         `doooooooooooooooooooooooooob'
          `doooooooooooooooooooooooob'
           `doooooooooooooooooooooob'
      jgs   `dooooooooobodoooooooob'
             `doooooooob dooooooob'
               `"""""""' `""""""'

**Comment by mirkovelic** [comment]
looks lovely!!

**Comment by jmansour** [comment]
__
                           /  `~-,
                          /     /
                 ___     {     /
              ,-'   `-.  ;    :
             /         \/    ;'
            !           |   |
          ,-|        ,--+-. \,--.
         /  {       /      \/    \
         |   \     /        ;     )
         |   /`-.__|        |    _!_
         \  (      |        )  ,'   `.
          `-|       \      / )/       \
           _(        `-..-'  !         |
         ,'  \  ___  /,-"""-.|         |
        /     ,'   `./       \\       /
        |    /       \        )`-._,-'
        (    |       |        |    |
         \   \       /        ).  /
         /`-._:-._,-'\       /  \'
        (        ,'   `-._,-'    |
        (       /        \       |
         \     (          )     /
          `+.__|          |__,-';
           |   (          )     |
           \  / \        /      |
            `-|  `-.__,-'      /
              |       |`-.__,-'
              \       /   |
               `-._.-'    )
                 \       /
                  `-._,-' htk

**Comment by mirkovelic** [comment]
Looks very grapy!

**Comment by jmansour** [comment]
Ok, fruitiness aside, how this is a feature?

**Comment by lmoresi** [comment]
The debate we had was q2/dpc1 v q2-dpc1 v q2,dpc1 the idea was that all would be allowable. But there should be some fruity-filtering in my view. There should also be some feedback on invalid combinations.

Mirko chose the permissive parser - any separator is allowed if the start / end strings match. Might be better to split the string on the allowable ones.

Sent from my iPhone

On 1 Oct 2015, at 7:19 AM, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, fruitiness aside, how this is a feature?

**Comment by jmansour** [comment]
Ok, but should this be valid?  

```
uw.mesh.FeMesh_Cartesian( elementType='Q2/Fruity')
```

Ok, I see what's happening, 'Q2' is the primary, '/Fruity' is the separator, and there is no submesh. 

I'm cool with the fruity-filtering, but it should catch out what appears to be an attempt at a primary/sub mesh combo.

**Comment by lmoresi** [comment]
I dont think this is appropriate.

We could have a function call to add a submesh/submeshes

The fact that submeshes are a special case seems worth considering in the way we implement the setup.




Sent from my iPhone

On 1 Oct 2015, at 8:29 AM, jmansour <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, but should this be valid?

uw.mesh.FeMesh_Cartesian( elementType='Q2/Fruity')


Ok, I see what's happening, 'Q2' is the primary, '/Fruity' is the separator, and there is no submesh.

I'm cool with the fruity-filtering, but it should catch out what appears to be an attempt at a primary/sub mesh combo.

**Comment by jmansour** [comment]
c4c6e746a957df923db6e73d8f32959933140053
