### ISSUE TITLE
Gauss as default integration scheme

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#81]
@garethkennedy to investigate & provide analysis

**Comment by lmoresi** [comment]
Be sure to analyse viscoelasticity !

Sent from my iPhone

On 20 Mar 2016, at 23:05, RebeccaFarrington <notifications@github.com<mailto:notifications@github.com>> wrote:


@garethkennedy<https://github.com/garethkennedy> to investigate & provide analysis

**Comment by RebeccaFarrington** [comment]
yes, yes!

**Comment by RebeccaFarrington** [comment]
What about having a look at what Dave May does?  -- LM
 @julesghub @jmansour @garethkennedy

**Comment by jmansour** [comment]
duplicate
#49
