### ISSUE TITLE
Build system review

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#82]
swig vs cython

@jmansour, @julesghub and jerico

**Comment by jmansour** [comment]
* automatically invoke swig
* don't build lavavu bindings when --with-viewer=0 
* h5py should be forced to use the libhdf5 that we have configured against (currently it just uses the first it finds which can be an issue when multiple versions of the library exist)

**Comment by julesghub** [comment]
for the automatically invoking swig with scons
use:
 `compile.py` instead of `scons.py`
see commit eb9798876c5c96c4fe28e195ebb3cd07a2da3691

**Comment by jmansour** [comment]
I think all the critical items here have been addressed.   

the swig vs cython is for later, so reassigned this to post june milestone.
