### ISSUE TITLE
Expose population control

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#83]

**Comment by julesghub** [comment]
done as of changes a6d32c487124159fdcd340ae041fe8a75ff9ca0d & 95990370a32c24bb54d947700d42361a5705cbf2

PICIntegrationSwarm has been renamed to VoronoiIntegrationSwarm

The full set of options (with defaults) are
intSwarm = uw.swarm.VoronoiIntegrationSwarm( 
                 swarm, resx=15,resy=15,resz=15,
                 lowerVolumeThreshold=0.6, upperVolumeThreshold=25,
                 maxDeletions=0, maxSplits=10,
                 centroidPositionRatio=0.01,
                 threshold = 0.8,
                 particlesPerCell = 25,
                 shotgun=False)

explanations below
    lowerVolumeThreshold : 0-100%, default 0.6
        lower % threshold volume for deletion of particles.
        i.e if a particle volume < 0.6% of total then delete it

    upperVolumeThreshold : 0-100%, default 25
        upper % threshold volume for deletion of particles.
        i.e if a particle volume > 25% of total then split it

    maxDeletions : int, defualt 3
        maximum number of particle deletions per cell

    maxSplits : int, default 3
        maximum number of particles splits per cell

    resolutionX, resolutionY, resolutionZ : int, default 15
        The resolution of the mesh used for the discrete voronoi algorithm

    shotgun : bool, default False
        Enable shotgun-style population control, for agressive repopulation.
        Was formerly known as the 'inflow' option.

    threshold : 0.0-1.0, default 0.8
        Threshold for cell population in an inflow problem:
        If a cell has less than 80% of its assigned particles then we re-populate
