### ISSUE TITLE
Newton nonlinear

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#85]

**Comment by lmoresi** [comment]
I'm not sure how to do this but happy to discuss a plan !

Sent from my iPhone

On 20 Mar 2016, at 23:34, RebeccaFarrington <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #85<https://github.com/underworldcode/underworld2/issues/85> to @lmoresi<https://github.com/lmoresi>.

**Comment by RebeccaFarrington** [comment]
Great, we didn't want to exclude you :)

**Comment by jmansour** [comment]
This is stale and won't be done for UW2. UW3 has an alpha Newton implementation ready.
