### ISSUE TITLE
Website & documentation review

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#86]
All hands!  @jmansour @julesghub @garethkennedy

**Comment by jmansour** [comment]
- update top level README.txt file
- get sphinx up and running so that we can generate ReadTheDocs style API documentation
- ensure docstrings & doctests are up to date
- underworldproject.org redirect to underworldcode.org
- review / update user guides
- review / update developer guides

**Comment by RebeccaFarrington** [comment]
I'm going to close this - falls under the release guidelines (/docs/development/release_guidelines.md)
