### ISSUE TITLE
Voxel

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#88]

**Comment by jmansour** [comment]
my solution:
* use numpy array to represent voxel data 
* cast onto which required swarm, in python.

**Comment by jmansour** [comment]
add example

**Comment by RebeccaFarrington** [comment]
create a blog post on this. Showing howto use voxel information easily via scipy or numpy

**Comment by julesghub** [comment]
i just got the ndimage.map_coordinates working. I'm happy to do this documenting on this... fyi: bovine anomaly style!

**Comment by julesghub** [comment]
Solution is for Julian to write a blog post on the cow voxel method

**Comment by jmansour** [comment]
This should still be a blog post! I've created a Jira project and item:
https://underworldcode.atlassian.net/browse/TB-1?atlOrigin=eyJpIjoiNDg0Nzk4ZWFiNWMxNGI3MWFkNTlhZmRiMzdjMTQyOGIiLCJwIjoiaiJ9
