### ISSUE TITLE
Implementation of analytic solutions

### ISSUE THREAD

**Issue by RebeccaFarrington** [underworldcode/underworld2#94]
- in test sys

@garethkennedy  & @jmansour

**Comment by RebeccaFarrington** [comment]
What's the best way to design these analytic solns?  ( c v python, initial MV work v newer updates).
Decide & proceed!

**Comment by jmansour** [comment]
The tests (or at least SolDB2dCheck) do not currently throw an exception if results aren't satisfactory.

**Comment by jmansour** [comment]
Lets review the existing tests, and add the required exceptions.  Also, add documentation from existing pdf files.  Down the track we will consolidate with the analytic solutions publication.

**Comment by RebeccaFarrington** [comment]
include examples of all the analytic solutions.  
It'll be a really good resource for users.

**Comment by jmansour** [comment]
Exceptions for out of tolerance results have been added to the existing analytic solutions, but i'll leave this open as a reminder to add examples and documentation for the rest of the solutions.

**Comment by julesghub** [comment]
Analytic sols, SolCx and SolKx have been implemented.
3d2359ea36ae2a2c82a81b11dea4efcb7f882b53
ab482373bfee5bdfae64a36845a1296548d100e5

SolDB has been moved from the main 'docs/test' directory into the 'docs/development' section as the test script wasn't doing a valid resolution test.

Closing this ticket as it's old.
