### ISSUE TITLE
Trouble building Underworld2 on Ubuntu14.04:h5py

### ISSUE THREAD

**Issue by liuyuly** [underworldcode/underworld2#96]
Hi,
I'm a beginner to learn underworld, and I meet some difficulties when install the software. I need your help. I'm trying to install Underworld V2.02b on Ubuntu14.04 system. The code is download by https://github.com/underworldcode/underworld2/releases. I am tring to install the  Underworld V2.02b according the blog that is how do I install on Ubuntu 14.04, and the web site is http://www.underworldcode.org/posts/Ubuntu14.04-Installation.
when it is configured, the error was happened. However, when the h5py is separate imported, it is no error. Please see the follwing. I don't know where the problem is and how to solve it. I really need your help, thanks a lot.

l@l:~/underworld2/libUnderworld$ ./configure.py
scons: Reading SConscript files ...
Checking whether the C compiler worksyes
Checking for Solvers... yes
Checking for package libm... yes
Checking for package libXML2... yes
Checking for package MPI... yes
Checking for package HDF5... yes
Checking for package Python... yes
Checking for package PETSc... yes
Checking for package Numpy... yes
Checking for package Mpi4py... yes
Checking for package H5py... Can't find a built version of the h5py module ... building h5py  Building private h5py version at /home/l/underworld2/h5py
running configure
Autodetected HDF5 1.8.15
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.8.15'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
running build_ext
Autodetected HDF5 1.8.15
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.8.15'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
Executing cythonize()
running build
running build_py
running build_ext
Autodetected HDF5 1.8.15
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.8.15'
     MPI Enabled: True
Rebuild Required: False

********************************************************************************
Executing cythonize()
RuntimeError: Unable to import h5py module. It was possibly not build successfully.:
  File "/home/l/underworld2/libUnderworld/SConfigure", line 196:
    env.ConfigurePackage(packages.H5py)
  File "/home/l/underworld2/libUnderworld/config/scons/scons-local-1.2.0/SCons/Environment.py", line 217:
    return apply(self.method, nargs, kwargs)
  File "/home/l/underworld2/libUnderworld/config/config.py", line 29:
    pkg(**kw)
  File "/home/l/underworld2/libUnderworld/config/Package.py", line 148:
    for env in self.gen_envs(loc):
  File "/home/l/underworld2/libUnderworld/config/packages/H5py.py", line 71:
    raise RuntimeError("Unable to import h5py module. It was possibly not build successfully.")
l@l:~/underworld2/libUnderworld$ 

the h5py is separate imported

l@l:~$ python
Python 2.7.11 |Anaconda 2.5.0 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import h5py
>>>

**Comment by jmansour** [comment]
Sorry you've been having difficulty liuyuly.  Yep, the h5py part of the compilation process is not as robust as we'd like.  

Is this installation for your personal computer, or for a HPC facility?  If it's your PC, we highly recommend you use the docker installation instead of compiling yourself. It will be in general *much* easier than compilation, and once setup it's trivial to update or change versions. 

http://www.underworldcode.org/posts/Underworld-and-Dockers
http://www.underworldcode.org/posts/Underworld-and-Dockers2

**Comment by liuyuly** [comment]
Hi jmansour.
Thanks for your help.  I install the underworld2 again. It is installation for my personal computer. It seems to have been installed successfully, but I am not sure. Because I am a beginner and haven't had any contact with underworld before. Can you give me a user manual or guider for underworld 2? I don't know how to learn and use it.
 The following shows the Installation result.

(python-default)ly@pc:~/underworld2$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import underworld as uw
>>> help(uw.mesh)

Help on package underworld.mesh in underworld:

NAME
    underworld.mesh - Implementation relating to meshing.

FILE
    /home/ly/underworld2/underworld/mesh/__init__.py

PACKAGE CONTENTS
    _mesh
    _meshvariable
    _specialSets_Cartesian

Then, the internet will show a webpage (http://localhost:8888/tree)
![Uploading 2016-04-02 20:30:53屏幕截图.png…]()
Is that right?

**Comment by jmansour** [comment]
Ok, seems like you have Underworld2 compiled and functioning correctly. :-)

You can find various examples and guides in the 'docs' directory:

https://github.com/underworldcode/underworld2/tree/master/docs/examples
https://github.com/underworldcode/underworld2/tree/master/docs/user_guide

Note that the documentation is in Jupyter Notebook format.  Here's the getting started notebook:

https://github.com/underworldcode/underworld2/blob/master/docs/user_guide/01_GettingStarted.ipynb

**Comment by liuyuly** [comment]
Thanks a lot. There is another question. when I run the "run_tests.py" which is in the '/home/ly/underworld2/utils/run_tests.py', there is a import error. Where is the problem? 
ly@pc:~/underworld2$ cd utils
ly@pc:~/underworld2/utils$ ls
run_tests.py
ly@pc:~/underworld2/utils$ python run_tests.py
Traceback (most recent call last):
  File "run_tests.py", line 21, in <module>
    from runipy.notebook_runner import NotebookRunner, NotebookError
ImportError: No module named runipy.notebook_runner
ly@pc:~/underworld2/utils$

**Comment by jmansour** [comment]
Currently the test script requires `ipython` and also `runipy`.   We will fix this soon. #100

**Comment by jmansour** [comment]
I'll close this issue. If you are having further issues, please create another ticket.  Thanks.

**Comment by liuyuly** [comment]
OK发自网易邮箱大师
            在2016年04月05日 08:58，jmansour 写道:I'll close this issue. If you are having further issues, please create another ticket.  Thanks.
