### ISSUE TITLE
Unified context manager for data modification

### ISSUE THREAD

**Issue by julesghub** [underworldcode/underworld2#99]
Eg, when one changes the mesh geometry, other data structure MUST change and be updated. Like the swarm, mesh algorithms, etc.

Also can the pattern we use for this be applicable to parallel problems - eg, creating a directory need a if uw.rank() == 0:

**Comment by jmansour** [comment]
The context managers are great for forcing safe operations, but rolling them out across all relevant objects would result in very cumbersome and ugly scripts.   And I agree, this pattern might be useful for MPI type operations. 

That said, this ticket is probably too vague to result in any action, so I'm gonna shut it down!
